INSERT INTO syllabus_chunks (id, file_id, file_name, heading, body, tf) VALUES
('chunk_d96060d157781d0d5d','file_9635f055da2d10cf4a','language-and-literature.md','Compare and Contrast — Justify','- **Purpose:** to examine two texts/works, showing similarities and differences, and *justify* a judgement.
- **Structure:** either *block* (all of A, then all of B) or *point-by-point* (theme by theme). Point-by-point is usually stronger.
- **Features:** clear criteria (theme, device, tone, effect); comparative connectives ("similarly," "whereas," "in contrast," "likewise"); evidence from both texts; a justified conclusion (which is more effective and why).
- **Checklist:** Same criteria applied to both? Evidence for each point? Comparative language? A justified verdict?

**Command-term question.** *Compare and contrast* "Caged Bird" and "We Wear the Mask," then *justify* which more powerfully conveys hidden suffering.','{"compare":2,"and":6,"contrast":3,"justify":3,"purpose":1,"examine":1,"two":1,"texts":2,"works":1,"showing":1,"similarities":1,"differences":1,"judgement":1,"structure":1,"either":1,"block":1,"all":2,"then":2,"point":5,"theme":3,"usually":1,"stronger":1,"features":1,"clear":1,"criteria":2,"device":1,"tone":1,"effect":1,"comparative":2,"connectives":1,"similarly":1,"whereas":1,"likewise":1,"evidence":2,"from":1,"both":2,"justified":2,"conclusion":1,"which":2,"more":2,"effective":1,"why":1,"checklist":1,"same":1,"applied":1,"for":1,"each":1,"language":1,"verdict":1,"command":1,"term":1,"question":1,"caged":1,"bird":1,"wear":1,"the":1,"mask":1,"powerfully":1,"conveys":1,"hidden":1,"suffering":1}'::jsonb),
('chunk_2981a118192660ef16','file_9635f055da2d10cf4a','language-and-literature.md','Active and Passive Voice','- **Rule:** *Active* = subject does the action ("Rachel wore the sweater"). *Passive* = subject receives the action ("The sweater was worn by Rachel"). Passive = form of *be* + past participle.
- **When to use:** active for directness and energy; passive when the doer is unknown/unimportant or to shift emphasis ("Mistakes were made").
- **Common error:** overusing the passive, making writing vague and wordy. *Correction:* prefer active in persuasive/narrative writing.
- **Practice:** Make passive — "The teacher accused Rachel." (Answer: Rachel was accused by the teacher.)','{"active":4,"and":3,"passive":6,"voice":1,"rule":1,"subject":2,"does":1,"the":8,"action":2,"rachel":4,"wore":1,"sweater":2,"receives":1,"was":2,"worn":1,"form":1,"past":1,"participle":1,"when":2,"use":1,"for":1,"directness":1,"energy":1,"doer":1,"unknown":1,"unimportant":1,"shift":1,"emphasis":1,"mistakes":1,"were":1,"made":1,"common":1,"error":1,"overusing":1,"making":1,"writing":2,"vague":1,"wordy":1,"correction":1,"prefer":1,"persuasive":1,"narrative":1,"practice":1,"make":1,"teacher":2,"accused":2,"answer":1}'::jsonb),
('chunk_ee2854f68782c03be6','file_9635f055da2d10cf4a','language-and-literature.md','Direct and Indirect (Reported) Speech','- **Rule:** *Direct* = exact words in quotation marks ("It''s mine," said Rachel). *Indirect* = reported without quotes, often shifting tense and pronouns (Rachel said that it was hers).
- **Changes when reporting:** tense usually "back-shifts" (is → was; will → would); pronouns and time words shift (today → that day; here → there).
- **Common error:** keeping quotation marks or present tense in reported speech — "She said that it *is* mine." *Correction:* "She said that it *was* hers."
- **Practice:** Report — Mrs. Price said, "Put it on now." (Answer: Mrs. Price told her to put it on then / right away.)','{"direct":2,"and":3,"indirect":2,"reported":3,"speech":2,"rule":1,"exact":1,"words":2,"quotation":2,"marks":2,"mine":2,"said":5,"rachel":2,"without":1,"quotes":1,"often":1,"shifting":1,"tense":3,"pronouns":2,"that":4,"was":3,"hers":2,"changes":1,"when":1,"reporting":1,"usually":1,"back":1,"shifts":1,"will":1,"would":1,"time":1,"shift":1,"today":1,"day":1,"here":1,"there":1,"common":1,"error":1,"keeping":1,"present":1,"she":2,"correction":1,"practice":1,"report":1,"mrs":2,"price":2,"put":2,"now":1,"answer":1,"told":1,"her":1,"then":1,"right":1,"away":1}'::jsonb),
('chunk_649ba74a72e5880c03','file_9635f055da2d10cf4a','language-and-literature.md','Modals','- **Rule:** modal verbs (*can, could, may, might, must, shall, should, will, would, ought to*) express ability, permission, possibility, obligation or advice. They are followed by the base verb (no *to*): "You *must* try."
- **Common error:** "must to," "can to," or double modals ("might could"). *Correction:* "must try," "can go."
- **Real-world use:** modals control the force of persuasive writing — "we *should*" (advice) vs. "we *must*" (obligation).
- **Practice:** Choose the modal of strong obligation — "Athletes ___ follow the rules." (Answer: must.)','{"modals":3,"rule":1,"modal":2,"verbs":1,"can":3,"could":2,"may":1,"might":2,"must":6,"shall":1,"should":2,"will":1,"would":1,"ought":1,"express":1,"ability":1,"permission":1,"possibility":1,"obligation":3,"advice":2,"they":1,"are":1,"followed":1,"the":4,"base":1,"verb":1,"you":1,"try":2,"common":1,"error":1,"double":1,"correction":1,"real":1,"world":1,"use":1,"control":1,"force":1,"persuasive":1,"writing":1,"practice":1,"choose":1,"strong":1,"athletes":1,"follow":1,"rules":1,"answer":1}'::jsonb),
('chunk_60fce5e36ff3a5fc99','file_9635f055da2d10cf4a','language-and-literature.md','Kinds of Sentences','| Kind | Purpose | Ends with | Example |
|------|---------|-----------|---------|
| Declarative | states | . | Ghost runs fast. |
| Interrogative | asks | ? | Can Ghost win? |
| Imperative | commands/requests | . or ! | Run faster! |
| Exclamatory | strong emotion | ! | What a race that was! |

- **By structure:** simple (one clause), compound (two independent clauses joined by a conjunction), complex (one independent + one dependent), compound-complex.
- **Common error:** run-on sentences and fragments. *Correction:* punctuate or join clauses correctly.
- **Practice:** Identify the kind — "What a brave boy Joby became!" (Answer: exclamatory.)

---','{"kinds":1,"sentences":2,"kind":2,"purpose":1,"ends":1,"with":1,"example":1,"declarative":1,"states":1,"ghost":2,"runs":1,"fast":1,"interrogative":1,"asks":1,"can":1,"win":1,"imperative":1,"commands":1,"requests":1,"run":2,"faster":1,"exclamatory":2,"strong":1,"emotion":1,"what":2,"race":1,"that":1,"was":1,"structure":1,"simple":1,"one":3,"clause":1,"compound":2,"two":1,"independent":2,"clauses":2,"joined":1,"conjunction":1,"complex":2,"dependent":1,"common":1,"error":1,"and":1,"fragments":1,"correction":1,"punctuate":1,"join":1,"correctly":1,"practice":1,"identify":1,"the":1,"brave":1,"boy":1,"joby":1,"became":1,"answer":1}'::jsonb),
('chunk_b3cb5c60bbd23fa3be','file_9635f055da2d10cf4a','language-and-literature.md','Literary devices glossary','| Device | Definition | Example (from our texts) |
|--------|-----------|--------------------------|
| **Metaphor** | direct comparison, one thing *is* another | Ages are "the rings inside a tree trunk" ("Eleven") |
| **Simile** | comparison using *like/as* | crying "like I''m three" ("Eleven") |
| **Symbolism** | an object standing for a larger idea | the painted leaf = hope ("The Last Leaf"); the mask = concealment |
| **Irony** | a gap between expectation and reality | Behrman''s "worthless" life produces a masterpiece (situational irony) |
| **Personification** | giving human qualities to non-human things | the caged bird "sings" of freedom |
| **Imagery** | vivid sensory language | the falling snow and freezing storm ("The Last Leaf") |
| **Tone** | the writer''s attitude to the subject | Dunbar''s tone is quietly anguished |
| **Mood** | the feeling created in the reader | the tense, fearful mood before Shiloh |
| **Alliteration** | repeated initial consonant sounds | "silver shoes" |
| **Hyperbole** | deliberate exaggeration | "a thousand years" of embarrassment |
| **Foreshadowing** | hints of what is to come | the "scream inside" Ghost |
| **Refrain** | a repeated line | "We wear the mask" |
| **Extended metaphor** | a metaphor sustained through a text | the caged/free birds (Angelou) |
| **Allegory** | a story with a second, symbolic meaning | "Caged Bird" as oppression |
| **Enjambment** | a line of poetry running on without pause | frequent in free-verse poems here |
| **Juxtaposition** | placing contrasting ideas side by side | free bird vs. caged bird |
| **Anaphora** | repetition at the start of lines | used in spoken word poetry |','{"literary":1,"devices":1,"glossary":1,"device":1,"definition":1,"example":1,"from":1,"our":1,"texts":1,"metaphor":3,"direct":1,"comparison":2,"one":1,"thing":1,"another":1,"ages":1,"are":1,"the":16,"rings":1,"inside":2,"tree":1,"trunk":1,"eleven":2,"simile":1,"using":1,"like":2,"crying":1,"three":1,"symbolism":1,"object":1,"standing":1,"for":1,"larger":1,"idea":1,"painted":1,"leaf":3,"hope":1,"last":2,"mask":2,"concealment":1,"irony":2,"gap":1,"between":1,"expectation":1,"and":2,"reality":1,"behrman":1,"worthless":1,"life":1,"produces":1,"masterpiece":1,"situational":1,"personification":1,"giving":1,"human":2,"qualities":1,"non":1,"things":1,"caged":4,"bird":4,"sings":1,"freedom":1,"imagery":1,"vivid":1,"sensory":1,"language":1,"falling":1,"snow":1,"freezing":1,"storm":1,"tone":2,"writer":1,"attitude":1,"subject":1,"dunbar":1,"quietly":1,"anguished":1,"mood":2,"feeling":1,"created":1,"reader":1,"tense":1,"fearful":1,"before":1,"shiloh":1,"alliteration":1,"repeated":2,"initial":1,"consonant":1,"sounds":1,"silver":1,"shoes":1,"hyperbole":1,"deliberate":1,"exaggeration":1,"thousand":1,"years":1,"embarrassment":1,"foreshadowing":1,"hints":1,"what":1,"come":1,"scream":1,"ghost":1,"refrain":1,"line":2,"wear":1,"extended":1,"sustained":1,"through":1,"text":1,"free":3,"birds":1,"angelou":1,"allegory":1,"story":1,"with":1,"second":1,"symbolic":1,"meaning":1,"oppression":1,"enjambment":1,"poetry":2,"running":1,"without":1,"pause":1,"frequent":1,"verse":1,"poems":1,"here":1,"juxtaposition":1,"placing":1,"contrasting":1,"ideas":1,"side":2,"anaphora":1,"repetition":1,"start":1,"lines":1,"used":1,"spoken":1,"word":1}'::jsonb),
('chunk_aea16f75ca43dce00a','file_9635f055da2d10cf4a','language-and-literature.md','Common misconceptions master list','1. **"Theme = topic."** No. The topic is *what it''s about* (e.g., freedom); the theme is *what the text says* about it (e.g., freedom must be fought for and never taken for granted).
2. **"The narrator is the author."** No. The narrating "I" (Ghost, Rachel) is a constructed voice, not Jason Reynolds or Sandra Cisneros.
3. **"Historical fiction is all true."** No. It uses real settings/events but invents characters and dialogue to convey emotional truth.
4. **"Passive voice is grammatically wrong."** No — it is a valid choice; it is just often *weaker* for persuasion and narrative.
5. **"An adjective and an adverb are interchangeable."** No — "ran quick" is incorrect; use "ran quickly."
6. **"Use *an* before any word starting with a vowel letter."** Go by *sound*: "a university," "an hour."
7. **"More faster / most fastest is emphatic."** These are double comparatives and are incorrect.
8. **"A comma can join two sentences."** That is a comma splice; use a conjunction or semicolon.
9. **"Symbolism is only in poetry."** Advertisements and films use symbols and visual metaphors too.
10. **"A close-up just shows a face."** Its *purpose* is to force emotional focus — technique creates meaning.','{"common":1,"misconceptions":1,"master":1,"list":1,"theme":2,"topic":2,"the":6,"what":2,"about":2,"freedom":2,"text":1,"says":1,"must":1,"fought":1,"for":3,"and":7,"never":1,"taken":1,"granted":1,"narrator":1,"author":1,"narrating":1,"ghost":1,"rachel":1,"constructed":1,"voice":2,"not":1,"jason":1,"reynolds":1,"sandra":1,"cisneros":1,"historical":1,"fiction":1,"all":1,"true":1,"uses":1,"real":1,"settings":1,"events":1,"but":1,"invents":1,"characters":1,"dialogue":1,"convey":1,"emotional":2,"truth":1,"passive":1,"grammatically":1,"wrong":1,"valid":1,"choice":1,"just":2,"often":1,"weaker":1,"persuasion":1,"narrative":1,"adjective":1,"adverb":1,"are":3,"interchangeable":1,"ran":2,"quick":1,"incorrect":2,"use":4,"quickly":1,"before":1,"any":1,"word":1,"starting":1,"with":1,"vowel":1,"letter":1,"sound":1,"university":1,"hour":1,"more":1,"faster":1,"most":1,"fastest":1,"emphatic":1,"these":1,"double":1,"comparatives":1,"comma":2,"can":1,"join":1,"two":1,"sentences":1,"that":1,"splice":1,"conjunction":1,"semicolon":1,"symbolism":1,"only":1,"poetry":1,"advertisements":1,"films":1,"symbols":1,"visual":1,"metaphors":1,"too":1,"close":1,"shows":1,"face":1,"its":1,"purpose":1,"force":1,"focus":1,"technique":1,"creates":1,"meaning":1}'::jsonb),
('chunk_ff5f109f4713262310','file_9635f055da2d10cf4a','language-and-literature.md','Command-term question bank','1. **Analyse** how Jason Reynolds uses first-person voice to shape our view of Ghost.
2. **Interpret** the symbolism of the painted leaf in "The Last Leaf."
3. **Compare** how "We Wear the Mask" and "Caged Bird" present hidden suffering and resilience.
4. **Evaluate** the effectiveness of the persuasive techniques in a chosen advertisement.
5. **Justify** which camera angle best conveys a character''s powerlessness in a studied film scene.
6. **Analyse** how Sandra Cisneros constructs a believable child''s voice in "Eleven."
7. **Compare and contrast** the way two poems in this course respond to injustice, and **justify** which is more powerful.
8. **Interpret** how setting is used as an instrument of injustice in "The Bracelet."','{"command":1,"term":1,"question":1,"bank":1,"analyse":2,"how":4,"jason":1,"reynolds":1,"uses":1,"first":1,"person":1,"voice":2,"shape":1,"our":1,"view":1,"ghost":1,"interpret":2,"the":8,"symbolism":1,"painted":1,"leaf":2,"last":1,"compare":2,"wear":1,"mask":1,"and":4,"caged":1,"bird":1,"present":1,"hidden":1,"suffering":1,"resilience":1,"evaluate":1,"effectiveness":1,"persuasive":1,"techniques":1,"chosen":1,"advertisement":1,"justify":2,"which":2,"camera":1,"angle":1,"best":1,"conveys":1,"character":1,"powerlessness":1,"studied":1,"film":1,"scene":1,"sandra":1,"cisneros":1,"constructs":1,"believable":1,"child":1,"eleven":1,"contrast":1,"way":1,"two":1,"poems":1,"this":1,"course":1,"respond":1,"injustice":2,"more":1,"powerful":1,"setting":1,"used":1,"instrument":1,"bracelet":1}'::jsonb),
('chunk_15553851a120239b2e','file_9635f055da2d10cf4a','language-and-literature.md','Cross-subject connections','- **History / Individuals & Societies:** historical fiction ("The Bracelet" and Japanese-American internment; "The Drummer Boy of Shiloh" and the American Civil War) links directly to modern and world history. Poems on migration ("The Migrants," "These Are the Times We Live In") connect to human rights, borders and development. Hughes and Angelou connect to the U.S. Civil Rights movement and the Harlem Renaissance.
- **Visual Art:** advertisement analysis (colour, composition, focal point) and film mise-en-scène share the visual-literacy skills of the art room; "The Last Leaf" turns on the meaning of a painting.
- **Theatre / Drama:** speech writing and spoken-word poetry require performance skills — projection, pace, pause, gesture — shared with drama.
- **Music:** rhythm and refrain in poetry and spoken word parallel musical structure; the drumbeat in "The Drummer Boy of Shiloh" is literally about rhythm setting courage.
- **Individuals & Societies (Civics/Ethics):** persuasive writing, media literacy (decoding ads and film) and social-issue poetry all build critical citizenship — recognising bias, injustice and the fair treatment of people.
- **PSHE / Wellbeing:** *Ghost* (trauma, anger management, second chances) and "Eleven" (child psychology, being silenced, gender sensitisation) support social-emotional learning.','{"cross":1,"subject":1,"connections":1,"history":2,"individuals":2,"societies":2,"historical":1,"fiction":1,"the":14,"bracelet":1,"and":14,"japanese":1,"american":2,"internment":1,"drummer":2,"boy":2,"shiloh":2,"civil":2,"war":1,"links":1,"directly":1,"modern":1,"world":1,"poems":1,"migration":1,"migrants":1,"these":1,"are":1,"times":1,"live":1,"connect":2,"human":1,"rights":2,"borders":1,"development":1,"hughes":1,"angelou":1,"movement":1,"harlem":1,"renaissance":1,"visual":2,"art":2,"advertisement":1,"analysis":1,"colour":1,"composition":1,"focal":1,"point":1,"film":2,"mise":1,"share":1,"literacy":2,"skills":2,"room":1,"last":1,"leaf":1,"turns":1,"meaning":1,"painting":1,"theatre":1,"drama":2,"speech":1,"writing":2,"spoken":2,"word":2,"poetry":3,"require":1,"performance":1,"projection":1,"pace":1,"pause":1,"gesture":1,"shared":1,"with":1,"music":1,"rhythm":2,"refrain":1,"parallel":1,"musical":1,"structure":1,"drumbeat":1,"literally":1,"about":1,"setting":1,"courage":1,"civics":1,"ethics":1,"persuasive":1,"media":1,"decoding":1,"ads":1,"social":2,"issue":1,"all":1,"build":1,"critical":1,"citizenship":1,"recognising":1,"bias":1,"injustice":1,"fair":1,"treatment":1,"people":1,"pshe":1,"wellbeing":1,"ghost":1,"trauma":1,"anger":1,"management":1,"second":1,"chances":1,"eleven":1,"child":1,"psychology":1,"being":1,"silenced":1,"gender":1,"sensitisation":1,"support":1,"emotional":1,"learning":1}'::jsonb),
('chunk_40e904ceff7026084e','file_3393b5fbe4e9b31e26','mathematics.md','Subject Overview','**MYP subject group:** Mathematics. In the IB Middle Years Programme, mathematics equips students to recognise structure, reason logically, model real situations, and communicate quantitative thinking with precision. Grade 7 sits in the middle of the MYP continuum: students consolidate number and algebra foundations while beginning to reason abstractly and to justify (not merely compute).

**The four MYP mathematics criteria (each marked out of 8):**

| Criterion | Title | What it assesses |
|-----------|-------|------------------|
| A | Knowing and understanding | Recall of facts/procedures; selecting and applying maths in familiar and unfamiliar situations; solving problems in mathematical and real-life contexts. |
| B | Investigating patterns | Applying mathematical problem-solving techniques to recognise patterns; describing patterns as relationships/general rules; verifying and justifying (proving) those rules. |
| C | Communicating | Using appropriate mathematical language, notation, forms of representation (symbols, diagrams, tables, graphs); moving between representations; coherent, complete, logical lines of reasoning. |
| D | Applying mathematics in real-life contexts | Identifying relevant elements of a real situation; selecting a model/strategy; applying maths to reach a solution; justifying the degree of accuracy and the validity/reasonableness of the solution. |

**Mathematics Related Concepts (drawn on across MYP):** Change, Equivalence, Generalization, Justification, Measurement, Model, Pattern, Quantity, Representation, Simplification, Space, System.

**Key Concepts most used in maths:** Form, Logic, Relationships (with Systems appearing frequently in this course).

**How to read this file:** Content is organised **Unit → Sub-topic (chapter) → concept entries**. Each unit opens with its conceptual framing (Key Concept, Related Concepts, Global Context, Statement of Inquiry, inquiry questions). Each concept gives a definition, a worked example, a real-world use, an analogy, method steps, at least one misconception, and three IB command-term questions. Math is written in plain notation (e.g., `(a+b)^2 = a^2 + 2ab + b^2`).

---','{"subject":2,"overview":1,"myp":4,"group":1,"mathematics":5,"the":7,"middle":2,"years":1,"programme":1,"equips":1,"students":2,"recognise":2,"structure":1,"reason":2,"logically":1,"model":3,"real":5,"situations":2,"and":10,"communicate":1,"quantitative":1,"thinking":1,"with":3,"precision":1,"grade":1,"sits":1,"continuum":1,"consolidate":1,"number":1,"algebra":1,"foundations":1,"while":1,"beginning":1,"abstractly":1,"justify":1,"not":1,"merely":1,"compute":1,"four":1,"criteria":1,"each":3,"marked":1,"out":1,"criterion":1,"title":1,"what":1,"assesses":1,"knowing":1,"understanding":1,"recall":1,"facts":1,"procedures":1,"selecting":2,"applying":4,"maths":3,"familiar":1,"unfamiliar":1,"solving":2,"problems":1,"mathematical":3,"life":2,"contexts":2,"investigating":1,"patterns":3,"problem":1,"techniques":1,"describing":1,"relationships":2,"general":1,"rules":2,"verifying":1,"justifying":2,"proving":1,"those":1,"communicating":1,"using":1,"appropriate":1,"language":1,"notation":2,"forms":1,"representation":2,"symbols":1,"diagrams":1,"tables":1,"graphs":1,"moving":1,"between":1,"representations":1,"coherent":1,"complete":1,"logical":1,"lines":1,"reasoning":1,"identifying":1,"relevant":1,"elements":1,"situation":1,"strategy":1,"reach":1,"solution":2,"degree":1,"accuracy":1,"validity":1,"reasonableness":1,"related":2,"concepts":3,"drawn":1,"across":1,"change":1,"equivalence":1,"generalization":1,"justification":1,"measurement":1,"pattern":1,"quantity":1,"simplification":1,"space":1,"system":1,"key":2,"most":1,"used":1,"form":1,"logic":1,"systems":1,"appearing":1,"frequently":1,"this":2,"course":1,"how":1,"read":1,"file":1,"content":1,"organised":1,"unit":2,"sub":1,"topic":1,"chapter":1,"concept":3,"entries":1,"opens":1,"its":1,"conceptual":1,"framing":1,"global":1,"context":1,"statement":1,"inquiry":2,"questions":2,"gives":1,"definition":1,"worked":1,"example":1,"world":1,"use":1,"analogy":1,"method":1,"steps":1,"least":1,"one":1,"misconception":1,"three":1,"command":1,"term":1,"math":1,"written":1,"plain":1,"2ab":1}'::jsonb),
('chunk_874b5564d4791d2f48','file_3393b5fbe4e9b31e26','mathematics.md','UNIT 1: Numerical Reasoning','**Key Concept:** Form
**Related Concepts:** Quantity, Equivalence, Representation, Simplification
**Global Context:** Globalization and sustainability (how quantities, rates and currencies let us trade, tax, grow and compare across a connected world).
**Statement of Inquiry:** Representing quantities in equivalent forms lets people measure, compare and make fair decisions about resources across a globalized world.

**Inquiry questions**
- *Factual:* How do we convert between fractions, decimals and percentages, and between units and time zones?
- *Conceptual:* Why can the same quantity be written in many equivalent forms without changing its value?
- *Debatable:* Is a percentage always the fairest way to describe a change or a comparison?

---','{"unit":1,"numerical":1,"reasoning":1,"key":1,"concept":1,"form":1,"related":1,"concepts":1,"quantity":2,"equivalence":1,"representation":1,"simplification":1,"global":1,"context":1,"globalization":1,"and":7,"sustainability":1,"how":2,"quantities":2,"rates":1,"currencies":1,"let":1,"trade":1,"tax":1,"grow":1,"compare":2,"across":2,"connected":1,"world":2,"statement":1,"inquiry":2,"representing":1,"equivalent":2,"forms":2,"lets":1,"people":1,"measure":1,"make":1,"fair":1,"decisions":1,"about":1,"resources":1,"globalized":1,"questions":1,"factual":1,"convert":1,"between":2,"fractions":1,"decimals":1,"percentages":1,"units":1,"time":1,"zones":1,"conceptual":1,"why":1,"can":1,"the":2,"same":1,"written":1,"many":1,"without":1,"changing":1,"its":1,"value":1,"debatable":1,"percentage":1,"always":1,"fairest":1,"way":1,"describe":1,"change":1,"comparison":1}'::jsonb),
('chunk_84d91695d6bea2c4aa','file_3393b5fbe4e9b31e26','mathematics.md','Concept: Percentage as a form of a quantity (fractions → decimals → percentages)','**Definition:** A percentage is a fraction out of 100; it is one equivalent form of a proportion. `1/4 = 0.25 = 25%`.
**Worked example:** Convert 3/8. `3 ÷ 8 = 0.375 = 37.5%`. Reverse: `62% = 0.62 = 62/100 = 31/50`.
**Real-world use:** Discounts, exam scores, interest rates are all read as percentages.
**Analogy:** A percentage is like slicing any pizza into exactly 100 pieces so different pizzas can be compared piece-for-piece.
**Method:** fraction → divide top by bottom → decimal → ×100 → %. Reverse: % → ÷100 → decimal → simplify to fraction.
**Misconception:** "To make a decimal a percentage, just remove the decimal point." Students see 0.5 → 5%. Wrong because you must multiply by 100: `0.5 = 50%`. Corrective: `0.5 × 100 = 50%`, and `0.05 = 5%`.
**Questions:** (1) *State* 7/20 as a percentage. (2) *Calculate* the decimal form of 84%. (3) *Explain* why 1/3 gives a recurring decimal but 3/8 does not.','{"100":7,"375":1,"concept":1,"percentage":5,"form":3,"quantity":1,"fractions":1,"decimals":1,"percentages":2,"definition":1,"fraction":3,"out":1,"one":1,"equivalent":1,"proportion":1,"worked":1,"example":1,"convert":1,"reverse":2,"real":1,"world":1,"use":1,"discounts":1,"exam":1,"scores":1,"interest":1,"rates":1,"are":1,"all":1,"read":1,"analogy":1,"like":1,"slicing":1,"any":1,"pizza":1,"into":1,"exactly":1,"pieces":1,"different":1,"pizzas":1,"can":1,"compared":1,"piece":2,"for":1,"method":1,"divide":1,"top":1,"bottom":1,"decimal":6,"simplify":1,"misconception":1,"make":1,"just":1,"remove":1,"the":2,"point":1,"students":1,"see":1,"wrong":1,"because":1,"you":1,"must":1,"multiply":1,"corrective":1,"and":1,"questions":1,"state":1,"calculate":1,"explain":1,"why":1,"gives":1,"recurring":1,"but":1,"does":1,"not":1}'::jsonb),
('chunk_ffa64a1ea778b373c7','file_3393b5fbe4e9b31e26','mathematics.md','Concept: Percentage increase and decrease (finding change and final value)','**Definition:** A percentage change scales a quantity up or down by a stated percent. Final = original × (1 ± rate).
**Worked example:** A €40 jacket rises 15%. Change `= 0.15 × 40 = €6`; final `= 40 × 1.15 = €46`. A €40 jacket falls 15%: final `= 40 × 0.85 = €34`.
**Real-world use:** Sale prices, salary rises, population growth.
**Analogy:** A multiplier is like a photocopier zoom setting — 115% enlarges, 85% shrinks.
**Method:** rate as decimal → multiply original by (1+rate) for increase or (1−rate) for decrease.
**Misconception:** "Add 15% then take 15% off returns the start." Wrong: `40×1.15×0.85 = 39.10`, not 40, because the second percentage acts on a different base.
**Questions:** (1) *Calculate* the final value when 250 increases by 8%. (2) *Find* the change when 90 decreases by 30%. (3) *Analyse* whether a 20% rise followed by a 20% fall returns the original value; justify.','{"115":1,"250":1,"concept":1,"percentage":3,"increase":2,"and":2,"decrease":2,"finding":1,"change":4,"final":5,"value":3,"definition":1,"scales":1,"quantity":1,"down":1,"stated":1,"percent":1,"original":3,"rate":4,"worked":1,"example":1,"jacket":2,"rises":2,"falls":1,"real":1,"world":1,"use":1,"sale":1,"prices":1,"salary":1,"population":1,"growth":1,"analogy":1,"multiplier":1,"like":1,"photocopier":1,"zoom":1,"setting":1,"enlarges":1,"shrinks":1,"method":1,"decimal":1,"multiply":1,"for":2,"misconception":1,"add":1,"then":1,"take":1,"off":1,"returns":2,"the":5,"start":1,"wrong":1,"not":1,"because":1,"second":1,"acts":1,"different":1,"base":1,"questions":1,"calculate":1,"when":2,"increases":1,"find":1,"decreases":1,"analyse":1,"whether":1,"rise":1,"followed":1,"fall":1,"justify":1}'::jsonb),
('chunk_c91c5755d79f9542f0','file_3393b5fbe4e9b31e26','mathematics.md','Concept: Percentage change from original and final values','**Definition:** `Percentage change = (change ÷ original value) × 100`, where change = final − original.
**Worked example:** Price goes from 80 to 100. Change `= 20`; `% change = 20/80 × 100 = 25%` increase. From 100 to 80: `−20/100 × 100 = −20%`.
**Real-world use:** Reporting inflation, comparing this year''s sales to last year''s.
**Analogy:** Judging a change by the *original* is like measuring a growth spurt against a child''s starting height, not the adult''s.
**Method:** subtract to get change → divide by the ORIGINAL → ×100 → state increase/decrease.
**Misconception:** Dividing by the final value. Corrective: 100→80 is 20% decrease (÷100), but 80→100 is 25% increase (÷80) — the two are not equal because the bases differ.
**Questions:** (1) *Calculate* the percentage change from 50 to 65. (2) *Determine* whether a rise from 200 to 250 or a fall from 250 to 200 has the larger percentage size. (3) *Evaluate* the claim "a 50% loss needs a 50% gain to recover."','{"100":10,"200":2,"250":2,"concept":1,"percentage":4,"change":9,"from":6,"original":5,"and":1,"final":3,"values":1,"definition":1,"value":2,"where":1,"worked":1,"example":1,"price":1,"goes":1,"increase":3,"real":1,"world":1,"use":1,"reporting":1,"inflation":1,"comparing":1,"this":1,"year":2,"sales":1,"last":1,"analogy":1,"judging":1,"the":9,"like":1,"measuring":1,"growth":1,"spurt":1,"against":1,"child":1,"starting":1,"height":1,"not":2,"adult":1,"method":1,"subtract":1,"get":1,"divide":1,"state":1,"decrease":2,"misconception":1,"dividing":1,"corrective":1,"but":1,"two":1,"are":1,"equal":1,"because":1,"bases":1,"differ":1,"questions":1,"calculate":1,"determine":1,"whether":1,"rise":1,"fall":1,"has":1,"larger":1,"size":1,"evaluate":1,"claim":1,"loss":1,"needs":1,"gain":1,"recover":1}'::jsonb),
('chunk_56750e51f47537d366','file_3393b5fbe4e9b31e26','mathematics.md','Concept: Reverse percentages (finding original from a percentage change + final)','**Definition:** When the final value already includes a change, divide by the multiplier to recover the original. `Original = final ÷ (1 ± rate)`.
**Worked example:** After a 20% discount, a bag costs €48. Original `= 48 ÷ 0.80 = €60`. After a 5% tax, a bill is €105 → pre-tax `= 105 ÷ 1.05 = €100`.
**Real-world use:** Working out the pre-VAT price, or a salary before a raise.
**Analogy:** Undoing a percentage is like reversing a recipe scaling to find the original portion.
**Method:** identify multiplier (1+rate or 1−rate) → divide the final value by it.
**Misconception:** Taking a percentage of the final price. Students do `48 × 1.20 = 57.60`. Wrong — the 20% was of the *original*. Corrective: `48 ÷ 0.8 = 60`, check `60 × 0.8 = 48`.
**Questions:** (1) *Find* the original price if €66 is the price after a 10% rise. (2) *Calculate* the pre-discount price when €153 follows a 15% reduction. (3) *Justify* why we divide rather than multiply to reverse a percentage.','{"100":1,"105":2,"153":1,"concept":1,"reverse":2,"percentages":1,"finding":1,"original":7,"from":1,"percentage":4,"change":2,"final":5,"definition":1,"when":2,"the":12,"value":2,"already":1,"includes":1,"divide":3,"multiplier":2,"recover":1,"rate":3,"worked":1,"example":1,"after":3,"discount":2,"bag":1,"costs":1,"tax":2,"bill":1,"pre":3,"real":1,"world":1,"use":1,"working":1,"out":1,"vat":1,"price":5,"salary":1,"before":1,"raise":1,"analogy":1,"undoing":1,"like":1,"reversing":1,"recipe":1,"scaling":1,"find":2,"portion":1,"method":1,"identify":1,"misconception":1,"taking":1,"students":1,"wrong":1,"was":1,"corrective":1,"check":1,"questions":1,"rise":1,"calculate":1,"follows":1,"reduction":1,"justify":1,"why":1,"rather":1,"than":1,"multiply":1}'::jsonb),
('chunk_90e0d3ee34a6069ae0','file_3393b5fbe4e9b31e26','mathematics.md','Concept: Applications — tax, commission, profit, loss, discount','**Definition:** Profit/loss and discount are percentage changes on a cost or marked price; tax and commission are percentages added/earned.
**Worked example:** Cost €200, sold €260 → profit `= 60`, `profit% = 60/200 ×100 = 30%`. Salesperson earns 4% commission on €5000 sales `= €200`.
**Real-world use:** Retail, salaries, government revenue.
**Analogy:** Profit percentage is a "score card" measured against what you paid, not what you charged.
**Method:** identify the base (cost price for profit/loss, marked price for discount) → apply percentage.
**Misconception:** Calculating profit% on selling price. Corrective: profit% is always on **cost price** unless stated otherwise.
**Questions:** (1) *Calculate* the selling price for a €150 item marked up 20%. (2) *Determine* the loss percentage if a €90 item sells for €72. (3) *Discuss* whether "30% profit" and "30% discount" on the same number give the same money.','{"100":1,"150":1,"200":3,"260":1,"5000":1,"concept":1,"applications":1,"tax":2,"commission":3,"profit":9,"loss":4,"discount":4,"definition":1,"and":3,"are":2,"percentage":4,"changes":1,"cost":4,"marked":3,"price":6,"percentages":1,"added":1,"earned":1,"worked":1,"example":1,"sold":1,"salesperson":1,"earns":1,"sales":1,"real":1,"world":1,"use":1,"retail":1,"salaries":1,"government":1,"revenue":1,"analogy":1,"score":1,"card":1,"measured":1,"against":1,"what":2,"you":2,"paid":1,"not":1,"charged":1,"method":1,"identify":1,"the":5,"base":1,"for":4,"apply":1,"misconception":1,"calculating":1,"selling":2,"corrective":1,"always":1,"unless":1,"stated":1,"otherwise":1,"questions":1,"calculate":1,"item":2,"determine":1,"sells":1,"discuss":1,"whether":1,"same":2,"number":1,"give":1,"money":1}'::jsonb),
('chunk_bbecf65a0e66afdf52','file_3393b5fbe4e9b31e26','mathematics.md','Concept: Repeated percentage change (growth and decay)','**Definition:** Applying a percentage repeatedly compounds it: `final = original × (1 ± rate)^n`. The overall change is NOT n × the single change.
**Worked example:** €1000 grows 10% per year for 3 years: `1000 × 1.1^3 = €1331` (overall +33.1%, not +30%). A car worth €20000 depreciates 15%/yr for 2 yrs: `20000 × 0.85^2 = €14450`.
**Real-world use:** Compound interest, population growth, radioactive/asset decay.
**Analogy:** Interest on interest is like a snowball rolling downhill — each turn adds to a bigger ball.
**Method:** find multiplier → raise to power n → multiply original.
**Misconception:** "Three years of 10% = 30%." Wrong: compounding gives 33.1%. Corrective: `1.1^3 = 1.331`.
**Questions:** (1) *Calculate* the value of €500 after 2 years at 6% compound growth. (2) *Compare* 3 years of 10% growth with a single 30% rise. (3) *Evaluate* which is better for a saver: 20% once or 10% twice.

---','{"331":1,"500":1,"1000":2,"1331":1,"14450":1,"20000":2,"concept":1,"repeated":1,"percentage":2,"change":3,"growth":4,"and":1,"decay":2,"definition":1,"applying":1,"repeatedly":1,"compounds":1,"final":1,"original":2,"rate":1,"the":3,"overall":2,"not":2,"single":2,"worked":1,"example":1,"grows":1,"per":1,"year":1,"for":3,"years":4,"car":1,"worth":1,"depreciates":1,"yrs":1,"real":1,"world":1,"use":1,"compound":2,"interest":3,"population":1,"radioactive":1,"asset":1,"analogy":1,"like":1,"snowball":1,"rolling":1,"downhill":1,"each":1,"turn":1,"adds":1,"bigger":1,"ball":1,"method":1,"find":1,"multiplier":1,"raise":1,"power":1,"multiply":1,"misconception":1,"three":1,"wrong":1,"compounding":1,"gives":1,"corrective":1,"questions":1,"calculate":1,"value":1,"after":1,"compare":1,"with":1,"rise":1,"evaluate":1,"which":1,"better":1,"saver":1,"once":1,"twice":1}'::jsonb),
('chunk_6d31456b7030de3cb7','file_3393b5fbe4e9b31e26','mathematics.md','Concept: Classification of numbers (natural, whole, integers, rational, real)','**Definition:** Naturals `{1,2,3,...}` ⊂ wholes `{0,1,2,...}` ⊂ integers `{...,−2,−1,0,1,2,...}` ⊂ rationals ⊂ reals. Reals = rationals + irrationals.
**Worked example:** −3 is an integer and rational but not whole; 2/5 is rational not integer; √2 is real, irrational.
**Real-world use:** Choosing a number type — you can have 3 children (natural) but a temperature of −4°C (integer).
**Analogy:** Number sets are nested Russian dolls; every natural sits inside all the larger sets.
**Method:** ask: negative? decimal/fraction? terminating or repeating? non-repeating infinite? → classify.
**Misconception:** "Zero is natural / all decimals are irrational." Corrective: 0 is whole not natural (IB convention); 0.75 is rational.
**Questions:** (1) *Classify* −7, 0, 3/4, √9, √3. (2) *State* the smallest set containing −5. (3) *Explain* why every integer is rational but not every rational is an integer.','{"concept":1,"classification":1,"numbers":1,"natural":5,"whole":3,"integers":2,"rational":6,"real":3,"definition":1,"naturals":1,"wholes":1,"rationals":2,"reals":2,"irrationals":1,"worked":1,"example":1,"integer":5,"and":1,"but":3,"not":4,"irrational":2,"world":1,"use":1,"choosing":1,"number":2,"type":1,"you":1,"can":1,"have":1,"children":1,"temperature":1,"analogy":1,"sets":2,"are":2,"nested":1,"russian":1,"dolls":1,"every":3,"sits":1,"inside":1,"all":2,"the":2,"larger":1,"method":1,"ask":1,"negative":1,"decimal":1,"fraction":1,"terminating":1,"repeating":2,"non":1,"infinite":1,"classify":2,"misconception":1,"zero":1,"decimals":1,"corrective":1,"convention":1,"questions":1,"state":1,"smallest":1,"set":1,"containing":1,"explain":1,"why":1}'::jsonb),
('chunk_0da334e0ca7e7b17eb','file_3393b5fbe4e9b31e26','mathematics.md','Concept: Rational number theory (p/q, q ≠ 0)','**Definition:** A rational number can be written as `p/q` with p, q integers and `q ≠ 0`. Its decimal terminates or recurs.
**Worked example:** `0.6 = 6/10 = 3/5`; `7 = 7/1`; `0.333... = 1/3`.
**Real-world use:** Money and measurements are rationals (2.75 m = 11/4 m).
**Analogy:** A rational is any number you can hit exactly by cutting a whole into equal parts.
**Method:** express as integer over integer; forbid zero denominator.
**Misconception:** "q can be any number." Corrective: `q ≠ 0` — division by zero is undefined.
**Questions:** (1) *Express* 0.45 as p/q in simplest form. (2) *State* why 5 is rational. (3) *Explain* why q cannot be 0.','{"333":1,"concept":1,"rational":4,"number":4,"theory":1,"definition":1,"can":3,"written":1,"with":1,"integers":1,"and":2,"its":1,"decimal":1,"terminates":1,"recurs":1,"worked":1,"example":1,"real":1,"world":1,"use":1,"money":1,"measurements":1,"are":1,"rationals":1,"analogy":1,"any":2,"you":1,"hit":1,"exactly":1,"cutting":1,"whole":1,"into":1,"equal":1,"parts":1,"method":1,"express":2,"integer":2,"over":1,"forbid":1,"zero":2,"denominator":1,"misconception":1,"corrective":1,"division":1,"undefined":1,"questions":1,"simplest":1,"form":1,"state":1,"why":2,"explain":1,"cannot":1}'::jsonb),
('chunk_7ae460da9941d033ff','file_3393b5fbe4e9b31e26','mathematics.md','Concept: Rational vs irrational decimals; surds; and π','**Definition:** Rationals give terminating or recurring decimals; irrationals give infinite non-recurring decimals. A **surd** is an irrational root (e.g. √2, √3) left in root form. **π** (≈3.14159…) is a special irrational (the circle''s circumference:diameter ratio).
**Worked example:** √4 = 2 (rational); √2 = 1.41421356… (irrational, a surd). π has no repeating block.
**Real-world use:** π appears in every circular measurement; surds appear in exact Pythagoras answers (√2 diagonal of a unit square).
**Analogy:** An irrational decimal is like a number that never lets you "land" exactly — it keeps running with no pattern.
**Method:** if a root is not a perfect square/cube it is a surd → irrational; leave exact or round as required.
**Misconception:** "π = 22/7." Corrective: 22/7 is only an approximation; π is irrational, 22/7 is rational.
**Questions:** (1) *Identify* which are surds: √9, √5, √16, √7. (2) *Explain* why √2 is irrational. (3) *Discuss* why π cannot be written exactly as a fraction.

---','{"14159":1,"41421356":1,"concept":1,"rational":3,"irrational":8,"decimals":3,"surds":3,"and":1,"definition":1,"rationals":1,"give":2,"terminating":1,"recurring":2,"irrationals":1,"infinite":1,"non":1,"surd":3,"root":3,"left":1,"form":1,"special":1,"the":1,"circle":1,"circumference":1,"diameter":1,"ratio":1,"worked":1,"example":1,"has":1,"repeating":1,"block":1,"real":1,"world":1,"use":1,"appears":1,"every":1,"circular":1,"measurement":1,"appear":1,"exact":2,"pythagoras":1,"answers":1,"diagonal":1,"unit":1,"square":2,"analogy":1,"decimal":1,"like":1,"number":1,"that":1,"never":1,"lets":1,"you":1,"land":1,"exactly":2,"keeps":1,"running":1,"with":1,"pattern":1,"method":1,"not":1,"perfect":1,"cube":1,"leave":1,"round":1,"required":1,"misconception":1,"corrective":1,"only":1,"approximation":1,"questions":1,"identify":1,"which":1,"are":1,"explain":1,"why":2,"discuss":1,"cannot":1,"written":1,"fraction":1}'::jsonb),
('chunk_2436125941adcad6eb','file_3393b5fbe4e9b31e26','mathematics.md','Concept: Meaning of a ratio; ratio as fraction; ratio vs fraction','**Definition:** A ratio `a : b` compares two quantities part-to-part. As a fraction it is a part-to-whole idea; `a:b` means a is `a/(a+b)` of the total.
**Worked example:** Mixing paint 2:3 (blue:yellow). Blue is `2/5` of the mix, yellow `3/5` — the fraction 2/3 compares blue to yellow, not to the whole.
**Real-world use:** Recipes, map scales, screen aspect ratios (16:9).
**Analogy:** A ratio is a recipe rule that holds no matter how big the batch.
**Method:** read the order of the quantities; convert to fraction of total by summing parts.
**Misconception:** "2:3 means 2/3 of the total is blue." Wrong — 2/3 compares blue to yellow; blue is 2/5 of the total.
**Questions:** (1) *Write* the ratio 4:6 in simplest form. (2) *State* what fraction of a 3:5 mixture is the first part. (3) *Explain* the difference between the ratio 3:4 and the fraction 3/4.','{"concept":1,"meaning":1,"ratio":7,"fraction":7,"definition":1,"compares":3,"two":1,"quantities":2,"part":4,"whole":2,"idea":1,"means":2,"the":14,"total":4,"worked":1,"example":1,"mixing":1,"paint":1,"blue":6,"yellow":4,"mix":1,"not":1,"real":1,"world":1,"use":1,"recipes":1,"map":1,"scales":1,"screen":1,"aspect":1,"ratios":1,"analogy":1,"recipe":1,"rule":1,"that":1,"holds":1,"matter":1,"how":1,"big":1,"batch":1,"method":1,"read":1,"order":1,"convert":1,"summing":1,"parts":1,"misconception":1,"wrong":1,"questions":1,"write":1,"simplest":1,"form":1,"state":1,"what":1,"mixture":1,"first":1,"explain":1,"difference":1,"between":1,"and":1}'::jsonb),
('chunk_fd76619c0ac06a397e','file_3393b5fbe4e9b31e26','mathematics.md','Concept: Simplifying ratios and finding quantities','**Definition:** Simplify by dividing all parts by their common factor; share a total by summing parts and scaling.
**Worked example:** Simplify 12:18 → ÷6 → 2:3. Share €50 in 2:3: parts total 5, one part `= 50/5 = 10`, so `€20 : €30`. Given the first share is €20 in 2:3, the other is `20/2 × 3 = €30`.
**Real-world use:** Splitting bills, dividing profits between partners.
**Analogy:** "Parts" are equal buckets; find one bucket, then fill the rest.
**Method:** sum the ratio parts → total ÷ sum = one part → multiply each part.
**Misconception:** Dividing the total by 2 for a 2:3 split. Corrective: divide by 5 (the number of parts), not 2.
**Questions:** (1) *Simplify* 30:45. (2) *Calculate* the two amounts when €120 is shared 5:3. (3) *Determine* the total when the larger part of a 2:7 share is 63.','{"120":1,"concept":1,"simplifying":1,"ratios":1,"and":2,"finding":1,"quantities":1,"definition":1,"simplify":3,"dividing":3,"all":1,"parts":6,"their":1,"common":1,"factor":1,"share":4,"total":5,"summing":1,"scaling":1,"worked":1,"example":1,"one":3,"part":4,"given":1,"the":9,"first":1,"other":1,"real":1,"world":1,"use":1,"splitting":1,"bills":1,"profits":1,"between":1,"partners":1,"analogy":1,"are":1,"equal":1,"buckets":1,"find":1,"bucket":1,"then":1,"fill":1,"rest":1,"method":1,"sum":2,"ratio":1,"multiply":1,"each":1,"misconception":1,"for":1,"split":1,"corrective":1,"divide":1,"number":1,"not":1,"questions":1,"calculate":1,"two":1,"amounts":1,"when":2,"shared":1,"determine":1,"larger":1}'::jsonb),
('chunk_747beee9120f9ee271','file_3393b5fbe4e9b31e26','mathematics.md','Concept: Proportion as variation','**Definition:** Two quantities are in (direct) proportion when their ratio stays constant: `y = kx`. As one grows, the other grows by the same factor.
**Worked example:** 3 pens cost €4.50, so 1 pen = €1.50 → 7 pens = €10.50. The unit rate k = 1.50 is constant.
**Real-world use:** Scaling recipes, currency conversion, unit pricing.
**Analogy:** Direct proportion is a fixed gear ratio — turn the pedal twice, the wheel turns twice as much.
**Method:** find the unit rate (k) → multiply by the new quantity.
**Misconception:** Adding a constant difference instead of multiplying. Corrective: proportion multiplies (×), it does not add a fixed amount.
**Questions:** (1) *Calculate* the cost of 9 items if 4 cost €10. (2) *Determine* the constant of proportionality when y = 15 at x = 3. (3) *Explain* why "buy 2 get more expensive per unit" is NOT proportional.

---','{"concept":1,"proportion":4,"variation":1,"definition":1,"two":1,"quantities":1,"are":1,"direct":2,"when":2,"their":1,"ratio":2,"stays":1,"constant":4,"one":1,"grows":2,"the":9,"other":1,"same":1,"factor":1,"worked":1,"example":1,"pens":2,"cost":3,"pen":1,"unit":4,"rate":2,"real":1,"world":1,"use":1,"scaling":1,"recipes":1,"currency":1,"conversion":1,"pricing":1,"analogy":1,"fixed":2,"gear":1,"turn":1,"pedal":1,"twice":2,"wheel":1,"turns":1,"much":1,"method":1,"find":1,"multiply":1,"new":1,"quantity":1,"misconception":1,"adding":1,"difference":1,"instead":1,"multiplying":1,"corrective":1,"multiplies":1,"does":1,"not":2,"add":1,"amount":1,"questions":1,"calculate":1,"items":1,"determine":1,"proportionality":1,"explain":1,"why":1,"buy":1,"get":1,"more":1,"expensive":1,"per":1,"proportional":1}'::jsonb),
('chunk_8c4b676656ae627f2b','file_3393b5fbe4e9b31e26','mathematics.md','Concept: Unit conversions (length, area, volume, time)','**Definition:** Convert by multiplying/dividing by the conversion factor. Area factors are squared, volume factors cubed.
**Worked example:** `2.5 km = 2500 m`; `3 m² = 3 × 100² cm² = 30000 cm²`; `1 L = 1000 cm³`; `2 h 15 min = 135 min`.
**Real-world use:** Engineering, cooking, buying flooring by area.
**Analogy:** Converting units is swapping currencies of measurement at a fixed exchange rate.
**Method:** write the factor; length ×10/100/1000, area ×(factor)², volume ×(factor)³.
**Misconception:** "1 m² = 100 cm²." Wrong — it is `100² = 10000 cm²`. Corrective: square the linear factor.
**Questions:** (1) *Convert* 4.2 m to cm. (2) *Calculate* how many cm² in 5 m². (3) *Explain* why area conversions square the factor while length does not.','{"100":4,"135":1,"1000":2,"2500":1,"10000":1,"30000":1,"concept":1,"unit":1,"conversions":2,"length":3,"area":5,"volume":3,"time":1,"definition":1,"convert":2,"multiplying":1,"dividing":1,"the":4,"conversion":1,"factor":6,"factors":2,"are":1,"squared":1,"cubed":1,"worked":1,"example":1,"min":2,"real":1,"world":1,"use":1,"engineering":1,"cooking":1,"buying":1,"flooring":1,"analogy":1,"converting":1,"units":1,"swapping":1,"currencies":1,"measurement":1,"fixed":1,"exchange":1,"rate":1,"method":1,"write":1,"misconception":1,"wrong":1,"corrective":1,"square":2,"linear":1,"questions":1,"calculate":1,"how":1,"many":1,"explain":1,"why":1,"while":1,"does":1,"not":1}'::jsonb),
('chunk_b5f9fde8269f093e29','file_3393b5fbe4e9b31e26','mathematics.md','Concept: 12-hour ↔ 24-hour clock and adding/subtracting time','**Definition:** 24-hour time labels the day 00:00–23:59; pm hours add 12. Time arithmetic carries in base 60.
**Worked example:** 3:45 pm = 15:45. A train leaves 14:50, journey 1 h 35 min → arrives 16:25 (`50+35 = 85 min = 1 h 25`).
**Real-world use:** Timetables, flight schedules, alarms.
**Analogy:** Minutes roll over at 60 like an odometer, not at 100.
**Method:** convert to 24-hour → add hours and minutes separately → carry 60 min = 1 h.
**Misconception:** Treating minutes as base 100 (50 + 35 = 85 "= 1.85 h"). Corrective: 85 min = 1 h 25 min.
**Questions:** (1) *Convert* 9:20 pm to 24-hour time. (2) *Calculate* the arrival time: depart 22:40, travel 2 h 50 min. (3) *Determine* the journey length between 08:15 and 13:05.','{"100":2,"concept":1,"hour":5,"clock":1,"and":3,"adding":1,"subtracting":1,"time":5,"definition":1,"labels":1,"the":3,"day":1,"hours":2,"add":2,"arithmetic":1,"carries":1,"base":2,"worked":1,"example":1,"train":1,"leaves":1,"journey":2,"min":6,"arrives":1,"real":1,"world":1,"use":1,"timetables":1,"flight":1,"schedules":1,"alarms":1,"analogy":1,"minutes":3,"roll":1,"over":1,"like":1,"odometer":1,"not":1,"method":1,"convert":2,"separately":1,"carry":1,"misconception":1,"treating":1,"corrective":1,"questions":1,"calculate":1,"arrival":1,"depart":1,"travel":1,"determine":1,"length":1,"between":1}'::jsonb),
('chunk_8e433f4385c83bcc95','file_3393b5fbe4e9b31e26','mathematics.md','Concept: Rates, unit rates, and converting rates & currencies','**Definition:** A rate compares quantities in different units (km/h, €/kg). A unit rate is "per one". Convert rates by converting each unit.
**Worked example:** 150 km in 2.5 h → `60 km/h`. At £1 = €1.17, £250 = `€292.50`. 72 km/h = `72000 m ÷ 3600 s = 20 m/s`.
**Real-world use:** Speed limits, shopping "best buy", exchanging money for travel.
**Analogy:** A unit rate is the "price tag per single item" that lets you compare unfairly-sized packs.
**Method:** divide to get "per one"; for currency multiply by the exchange rate; keep units in the working.
**Misconception:** Multiplying when you should divide converting to per-unit. Corrective: km/h → m/s multiply by 1000 and divide by 3600.
**Questions:** (1) *Calculate* the speed for 210 km in 3 h. (2) *Convert* €90 to pounds at £1 = €1.20. (3) *Analyse* which is the better buy: 500 g for €2.20 or 750 g for €3.15.','{"150":1,"210":1,"250":1,"292":1,"500":1,"750":1,"1000":1,"3600":2,"72000":1,"concept":1,"rates":4,"unit":5,"and":2,"converting":3,"currencies":1,"definition":1,"rate":4,"compares":1,"quantities":1,"different":1,"units":2,"per":4,"one":2,"convert":2,"each":1,"worked":1,"example":1,"real":1,"world":1,"use":1,"speed":2,"limits":1,"shopping":1,"best":1,"buy":2,"exchanging":1,"money":1,"for":5,"travel":1,"analogy":1,"the":5,"price":1,"tag":1,"single":1,"item":1,"that":1,"lets":1,"you":2,"compare":1,"unfairly":1,"sized":1,"packs":1,"method":1,"divide":3,"get":1,"currency":1,"multiply":2,"exchange":1,"keep":1,"working":1,"misconception":1,"multiplying":1,"when":1,"should":1,"corrective":1,"questions":1,"calculate":1,"pounds":1,"analyse":1,"which":1,"better":1}'::jsonb),
('chunk_07e3b6aca9f430f634','file_3393b5fbe4e9b31e26','mathematics.md','Concept: Work / Time / Distance–Time simple problems','**Definition:** `distance = speed × time`; rearrange for any variable. Work problems use rate × time = amount.
**Worked example:** A cyclist at 24 km/h for 45 min (0.75 h) covers `24 × 0.75 = 18 km`. Time for 60 km at 40 km/h `= 60/40 = 1.5 h`.
**Real-world use:** Trip planning, delivery estimates.
**Analogy:** The D=S×T triangle is a see-saw — cover any corner to find it from the other two.
**Method:** convert time to hours → pick the correct rearrangement → substitute.
**Misconception:** Leaving 45 min as "45" in km/h working. Corrective: use 0.75 h.
**Questions:** (1) *Calculate* the distance at 50 km/h for 2 h. (2) *Find* the time for 30 km at 12 km/h. (3) *Evaluate* whether doubling speed halves the journey time.','{"concept":1,"work":2,"time":8,"distance":3,"simple":1,"problems":2,"definition":1,"speed":2,"rearrange":1,"for":5,"any":2,"variable":1,"use":3,"rate":1,"amount":1,"worked":1,"example":1,"cyclist":1,"min":2,"covers":1,"real":1,"world":1,"trip":1,"planning":1,"delivery":1,"estimates":1,"analogy":1,"the":6,"triangle":1,"see":1,"saw":1,"cover":1,"corner":1,"find":2,"from":1,"other":1,"two":1,"method":1,"convert":1,"hours":1,"pick":1,"correct":1,"rearrangement":1,"substitute":1,"misconception":1,"leaving":1,"working":1,"corrective":1,"questions":1,"calculate":1,"evaluate":1,"whether":1,"doubling":1,"halves":1,"journey":1}'::jsonb),
('chunk_0130b02cbdda0654b9','file_3393b5fbe4e9b31e26','mathematics.md','Concept: Time zones and calculating times across them','**Definition:** The world is divided into time zones offset from UTC; travelling east adds hours, west subtracts. This lets people coordinate globally.
**Worked example:** London (UTC+0) 12:00 → New York (UTC−5) is 07:00; → Tokyo (UTC+9) is 21:00. A 09:00 call in Delhi (UTC+5:30) is 03:30 UTC = 22:30 previous day in New York.
**Real-world use:** Scheduling international meetings, flights, live sport.
**Analogy:** Time zones are like everyone reading the same clock but each standing in a different "hour lane".
**Method:** find each zone''s UTC offset → convert to UTC → add the target offset.
**Misconception:** "Every country is a whole number of hours from UTC." Corrective: India is +5:30, Nepal +5:45.
**Questions:** (1) *State* the time in Tokyo (UTC+9) when it is 10:00 UTC. (2) *Calculate* the New York time (UTC−5) for a 15:00 London meeting. (3) *Discuss* why time zones make global business scheduling difficult.','{"concept":1,"time":6,"zones":4,"and":1,"calculating":1,"times":1,"across":1,"them":1,"definition":1,"the":5,"world":2,"divided":1,"into":1,"offset":3,"from":2,"utc":12,"travelling":1,"east":1,"adds":1,"hours":2,"west":1,"subtracts":1,"this":1,"lets":1,"people":1,"coordinate":1,"globally":1,"worked":1,"example":1,"london":2,"new":3,"york":3,"tokyo":2,"call":1,"delhi":1,"previous":1,"day":1,"real":1,"use":1,"scheduling":2,"international":1,"meetings":1,"flights":1,"live":1,"sport":1,"analogy":1,"are":1,"like":1,"everyone":1,"reading":1,"same":1,"clock":1,"but":1,"each":2,"standing":1,"different":1,"hour":1,"lane":1,"method":1,"find":1,"zone":1,"convert":1,"add":1,"target":1,"misconception":1,"every":1,"country":1,"whole":1,"number":1,"corrective":1,"india":1,"nepal":1,"questions":1,"state":1,"when":1,"calculate":1,"for":1,"meeting":1,"discuss":1,"why":1,"make":1,"global":1,"business":1,"difficult":1}'::jsonb),
('chunk_651ea90e58e86d0726','file_3393b5fbe4e9b31e26','mathematics.md','Concept: Recurring decimals ↔ fractions; conditions for recurring','**Definition:** A recurring decimal has a repeating block; convert using algebra (×10^k, subtract). A fraction recurs when the simplified denominator has a prime factor other than 2 or 5.
**Worked example:** `x = 0.444...`; `10x = 4.444...`; `9x = 4` → `x = 4/9`. `0.272727... = 27/99 = 3/11`. `3/8` terminates (denominator 2³); `1/6` recurs (factor 3).
**Real-world use:** Understanding calculator rounding, exact fraction answers.
**Analogy:** Multiplying by 10 "lines up" the repeating tail so it cancels when subtracted.
**Method:** let x = decimal → multiply by 10^(length of block) → subtract → solve → simplify.
**Misconception:** "0.999... < 1." Corrective: `x=0.999..., 10x=9.999..., 9x=9, x=1` exactly.
**Questions:** (1) *Convert* 0.6 recurring to a fraction. (2) *Determine* whether 7/20 terminates or recurs, and justify. (3) *Explain* why 1/3 recurs but 1/4 terminates.','{"444":2,"999":3,"272727":1,"concept":1,"recurring":4,"decimals":1,"fractions":1,"conditions":1,"for":1,"definition":1,"decimal":2,"has":2,"repeating":2,"block":2,"convert":2,"using":1,"algebra":1,"subtract":2,"fraction":3,"recurs":4,"when":2,"the":2,"simplified":1,"denominator":2,"prime":1,"factor":2,"other":1,"than":1,"worked":1,"example":1,"10x":2,"terminates":3,"real":1,"world":1,"use":1,"understanding":1,"calculator":1,"rounding":1,"exact":1,"answers":1,"analogy":1,"multiplying":1,"lines":1,"tail":1,"cancels":1,"subtracted":1,"method":1,"let":1,"multiply":1,"length":1,"solve":1,"simplify":1,"misconception":1,"corrective":1,"exactly":1,"questions":1,"determine":1,"whether":1,"and":1,"justify":1,"explain":1,"why":1,"but":1}'::jsonb),
('chunk_53cd7e6295d276eec6','file_3393b5fbe4e9b31e26','mathematics.md','Concept: Nearest perfect square via the range method','**Definition:** Estimate a square root by finding the two perfect squares it lies between.
**Worked example:** √50: since `7²=49` and `8²=64`, √50 is between 7 and 8, very close to 7 (7.07…). Nearest perfect square to 50 is 49.
**Real-world use:** Quick mental estimates, checking calculator answers, sizing a square area.
**Analogy:** Placing a number on a ruler between two known marks.
**Method:** list squares around the number → identify the bracketing pair → pick the closer.
**Misconception:** "√50 ≈ 25." Corrective: that halves it; √50 ≈ 7.1 because 7²=49.
**Questions:** (1) *State* the two integers √30 lies between. (2) *Estimate* √85 to one decimal place. (3) *Explain* the range method to a peer.

---','{"concept":1,"nearest":2,"perfect":3,"square":4,"via":1,"the":7,"range":2,"method":3,"definition":1,"estimate":2,"root":1,"finding":1,"two":3,"squares":2,"lies":2,"between":4,"worked":1,"example":1,"since":1,"and":2,"very":1,"close":1,"real":1,"world":1,"use":1,"quick":1,"mental":1,"estimates":1,"checking":1,"calculator":1,"answers":1,"sizing":1,"area":1,"analogy":1,"placing":1,"number":2,"ruler":1,"known":1,"marks":1,"list":1,"around":1,"identify":1,"bracketing":1,"pair":1,"pick":1,"closer":1,"misconception":1,"corrective":1,"that":1,"halves":1,"because":1,"questions":1,"state":1,"integers":1,"one":1,"decimal":1,"place":1,"explain":1,"peer":1}'::jsonb);