INSERT INTO syllabus_chunks (id, file_id, file_name, heading, body, tf) VALUES
('chunk_ea27299fc645759d22','file_3393b5fbe4e9b31e26','mathematics.md','Concept: Identifying patterns and number sequences; stating the rule','**Definition:** A sequence is an ordered list following a rule (term-to-term or position-to-term/nth term).
**Worked example:** 3, 7, 11, 15, … adds 4 (term-to-term); nth term `= 4n − 1`. Check n=1 → 3. For 1, 4, 9, 16 the rule is `n²`.
**Real-world use:** Predicting seating rows, tiling, saving schedules.
**Analogy:** The nth-term rule is a "machine" — input a position, output that term directly.
**Method:** find the common difference d → nth term `= dn + (first term − d)`.
**Misconception:** "The rule is just +4" is enough. For the 100th term you need the nth-term formula, not repeated adding.
**Questions:** (1) *State* the next two terms of 5, 8, 11, 14. (2) *Find* the nth term of 2, 5, 8, 11. (3) *Determine* whether 100 is a term of the sequence 4n − 1; justify.

---','{"100":1,"concept":1,"identifying":1,"patterns":1,"and":1,"number":1,"sequences":1,"stating":1,"the":10,"rule":5,"definition":1,"sequence":2,"ordered":1,"list":1,"following":1,"term":15,"position":2,"nth":6,"worked":1,"example":1,"adds":1,"check":1,"for":2,"real":1,"world":1,"use":1,"predicting":1,"seating":1,"rows":1,"tiling":1,"saving":1,"schedules":1,"analogy":1,"machine":1,"input":1,"output":1,"that":1,"directly":1,"method":1,"find":2,"common":1,"difference":1,"first":1,"misconception":1,"just":1,"enough":1,"100th":1,"you":1,"need":1,"formula":1,"not":1,"repeated":1,"adding":1,"questions":1,"state":1,"next":1,"two":1,"terms":1,"determine":1,"whether":1,"justify":1}'::jsonb),
('chunk_4e1796dfb6d6a0114a','file_3393b5fbe4e9b31e26','mathematics.md','UNIT 2: Abstract Reasoning','**Key Concept:** Logic
**Related Concepts:** Equivalence, Simplification, Generalization, Pattern
**Global Context:** Scientific and technical innovation (algebra as the language that generalises and drives technology).
**Statement of Inquiry:** Logical rules for manipulating symbols let us generalise relationships and simplify complexity into equivalent, solvable forms.

**Inquiry questions**
- *Factual:* What are the laws of indices and the rules for expanding and factorising?
- *Conceptual:* How does keeping an expression equivalent while changing its form help us solve problems?
- *Debatable:* Is factorising or expanding the "more useful" skill in algebra?

---','{"unit":1,"abstract":1,"reasoning":1,"key":1,"concept":1,"logic":1,"related":1,"concepts":1,"equivalence":1,"simplification":1,"generalization":1,"pattern":1,"global":1,"context":1,"scientific":1,"and":5,"technical":1,"innovation":1,"algebra":2,"the":4,"language":1,"that":1,"generalises":1,"drives":1,"technology":1,"statement":1,"inquiry":2,"logical":1,"rules":2,"for":2,"manipulating":1,"symbols":1,"let":1,"generalise":1,"relationships":1,"simplify":1,"complexity":1,"into":1,"equivalent":2,"solvable":1,"forms":1,"questions":1,"factual":1,"what":1,"are":1,"laws":1,"indices":1,"expanding":2,"factorising":2,"conceptual":1,"how":1,"does":1,"keeping":1,"expression":1,"while":1,"changing":1,"its":1,"form":1,"help":1,"solve":1,"problems":1,"debatable":1,"more":1,"useful":1,"skill":1}'::jsonb),
('chunk_d5fc6bcdae4116a974','file_3393b5fbe4e9b31e26','mathematics.md','Concept: Laws of indices','**Definition:** Index (power) laws are rules for combining powers of the same base.

| Law | Rule | Example |
|-----|------|---------|
| Product | `a^m × a^n = a^(m+n)` | `2^3 × 2^4 = 2^7` |
| Quotient | `a^m ÷ a^n = a^(m−n)` | `x^5 ÷ x^2 = x^3` |
| Power of a power | `(a^m)^n = a^(mn)` | `(x^2)^3 = x^6` |
| Distributing | `(ab)^n = a^n b^n` | `(2x)^3 = 8x^3` |
| Zero power | `a^0 = 1 (a≠0)` | `5^0 = 1` |
| Negative power | `a^(−n) = 1/a^n` | `2^(−3) = 1/8` |

**Worked example:** `3x^4 × 2x^3 = 6x^7`; `12x^6 ÷ 4x^2 = 3x^4`; `(2x^2)^3 = 8x^6`.
**Real-world use:** Scientific notation, computing storage (2^10 bytes), growth models.
**Analogy:** Multiplying powers is stacking identical Lego blocks — you just count how many.
**Method:** same base? add (×) or subtract (÷) indices; power of power multiplies.
**Misconception:** "`a^m × a^n = a^(mn)`." Wrong — you ADD indices for a product: `a^2 × a^3 = a^5`, not a^6.
**Questions:** (1) *Simplify* `y^7 × y^2`. (2) *Evaluate* `(3x^2)^2`. (3) *Explain* why `a^0 = 1` using the quotient law.','{"concept":1,"laws":2,"indices":3,"definition":1,"index":1,"power":7,"are":1,"rules":1,"for":2,"combining":1,"powers":2,"the":2,"same":2,"base":2,"law":2,"rule":1,"example":2,"product":2,"quotient":2,"distributing":1,"zero":1,"negative":1,"worked":1,"12x":1,"real":1,"world":1,"use":1,"scientific":1,"notation":1,"computing":1,"storage":1,"bytes":1,"growth":1,"models":1,"analogy":1,"multiplying":1,"stacking":1,"identical":1,"lego":1,"blocks":1,"you":2,"just":1,"count":1,"how":1,"many":1,"method":1,"add":2,"subtract":1,"multiplies":1,"misconception":1,"wrong":1,"not":1,"questions":1,"simplify":1,"evaluate":1,"explain":1,"why":1,"using":1}'::jsonb),
('chunk_3185ad2e1eb7dda3b3','file_3393b5fbe4e9b31e26','mathematics.md','Concept: Fractional indices in radical form','**Definition:** `a^(1/n) = nth root of a`; `a^(m/n) = (nth root of a)^m`. The number under the root is the radicand.
**Worked example:** `9^(1/2) = √9 = 3`; `8^(2/3) = (cube root 8)^2 = 2² = 4`; `x^(1/2) = √x`.
**Real-world use:** Formulas for periods, areas, and scaling laws.
**Analogy:** A fractional index is a "half-power" instruction — square rooting is powering by one-half.
**Method:** denominator = root, numerator = power; take the root first, then the power.
**Misconception:** "`a^(1/2)` means `a ÷ 2`." Corrective: `9^(1/2)=3`, not 4.5.
**Questions:** (1) *Evaluate* `16^(1/2)`. (2) *Write* `x^(3/2)` in radical form. (3) *Explain* why `27^(1/3) = 3`.

---','{"concept":1,"fractional":2,"indices":1,"radical":2,"form":2,"definition":1,"nth":2,"root":6,"the":5,"number":1,"under":1,"radicand":1,"worked":1,"example":1,"cube":1,"real":1,"world":1,"use":1,"formulas":1,"for":1,"periods":1,"areas":1,"and":1,"scaling":1,"laws":1,"analogy":1,"index":1,"half":2,"power":3,"instruction":1,"square":1,"rooting":1,"powering":1,"one":1,"method":1,"denominator":1,"numerator":1,"take":1,"first":1,"then":1,"misconception":1,"means":1,"corrective":1,"not":1,"questions":1,"evaluate":1,"write":1,"explain":1,"why":1}'::jsonb),
('chunk_c3232bb893fc1f89ed','file_3393b5fbe4e9b31e26','mathematics.md','Concept: Binomial × binomial (area of a rectangle model)','**Definition:** Expanding `(x+a)(x+b)` multiplies every term in the first bracket by every term in the second; the rectangle-area model shows the four pieces.
**Worked example:** `(x+3)(x+5) = x² + 5x + 3x + 15 = x² + 8x + 15`.
**Real-world use:** Finding areas of extended plots, algebra behind quadratics.
**Analogy:** Splitting a rectangle of sides (x+3) and (x+5) into four smaller tiles that sum to the area.
**Method:** use FOIL / grid → multiply all pairs → collect like terms.
**Misconception:** Only multiplying "firsts and lasts" (x² + 15). Corrective: include both middle products, 5x + 3x.
**Questions:** (1) *Expand* `(x+2)(x+6)`. (2) *Expand* `(x−4)(x+3)`. (3) *Explain* how the area model shows the middle term.','{"concept":1,"binomial":2,"area":4,"rectangle":3,"model":3,"definition":1,"expanding":1,"multiplies":1,"every":2,"term":3,"the":7,"first":1,"bracket":1,"second":1,"shows":2,"four":2,"pieces":1,"worked":1,"example":1,"real":1,"world":1,"use":2,"finding":1,"areas":1,"extended":1,"plots":1,"algebra":1,"behind":1,"quadratics":1,"analogy":1,"splitting":1,"sides":1,"and":2,"into":1,"smaller":1,"tiles":1,"that":1,"sum":1,"method":1,"foil":1,"grid":1,"multiply":1,"all":1,"pairs":1,"collect":1,"like":1,"terms":1,"misconception":1,"only":1,"multiplying":1,"firsts":1,"lasts":1,"corrective":1,"include":1,"both":1,"middle":2,"products":1,"questions":1,"expand":2,"explain":1,"how":1}'::jsonb),
('chunk_b2c95e34e215bb0f82','file_3393b5fbe4e9b31e26','mathematics.md','Concept: Squaring a binomial and the key identities','**Definition:** `(a+b)^2 = a^2 + 2ab + b^2`; `(a−b)^2 = a^2 − 2ab + b^2`; `(a+b)(a−b) = a^2 − b^2` (difference of squares).
**Worked example:** `(x+4)^2 = x² + 8x + 16`; `(x−3)^2 = x² − 6x + 9`; `(x+5)(x−5) = x² − 25`.
**Real-world use:** Fast mental squaring (e.g., 31² = (30+1)² = 961) and simplifying.
**Analogy:** `(a+b)²` is a big square split into two square tiles (a², b²) plus two identical rectangles (2ab).
**Method:** square first, square last, add twice the product (sign from the middle).
**Misconception:** "`(a+b)^2 = a^2 + b^2`." VERY common. Students distribute the power. Wrong because it drops the `2ab` cross-term. Corrective: `(3+2)² = 25` but `3² + 2² = 13`; the missing `2·3·2 = 12`.
**Questions:** (1) *Expand* `(x+7)^2`. (2) *Expand* `(2x−1)^2`. (3) *Analyse* the error in "`(a+b)^2 = a^2 + b^2`" with a numeric counterexample.

---','{"961":1,"concept":1,"squaring":2,"binomial":1,"and":2,"the":7,"key":1,"identities":1,"definition":1,"2ab":4,"difference":1,"squares":1,"worked":1,"example":1,"real":1,"world":1,"use":1,"fast":1,"mental":1,"simplifying":1,"analogy":1,"big":1,"square":4,"split":1,"into":1,"two":2,"tiles":1,"plus":1,"identical":1,"rectangles":1,"method":1,"first":1,"last":1,"add":1,"twice":1,"product":1,"sign":1,"from":1,"middle":1,"misconception":1,"very":1,"common":1,"students":1,"distribute":1,"power":1,"wrong":1,"because":1,"drops":1,"cross":1,"term":1,"corrective":1,"but":1,"missing":1,"questions":1,"expand":2,"analyse":1,"error":1,"with":1,"numeric":1,"counterexample":1}'::jsonb),
('chunk_845b223c2c63d53bc2','file_3393b5fbe4e9b31e26','mathematics.md','Concept: Common-factor factorising (and negative common factors)','**Definition:** Factorising reverses expansion by pulling out the highest common factor (HCF). Terms decrease; factors increase.
**Worked example:** `ac − bc = c(a − b)`; `6x² + 9x = 3x(2x + 3)`; `−ac − bc = −c(a + b)`; `abc + bcd + bcf = bc(a + d + f)`. With 1: `x² + x = x(x + 1)`.
**Real-world use:** Simplifying formulas before substituting; solving equations.
**Analogy:** Un-distributing is repacking loose items back into a shared box (the common factor).
**Method:** find the HCF of all terms → divide each term by it → write factor(HCF)(remaining).
**Misconception:** Forgetting the invisible 1: `x² + x = x(x)` (dropping the +1). Corrective: `x(x+1)`, check by expanding.
**Questions:** (1) *Factorise* `8x + 12`. (2) *Factorise* `x² − x` fully. (3) *Explain* why factorising increases the number of factors but decreases the terms inside.','{"concept":1,"common":4,"factor":4,"factorising":3,"and":1,"negative":1,"factors":3,"definition":1,"reverses":1,"expansion":1,"pulling":1,"out":1,"the":7,"highest":1,"hcf":3,"terms":3,"decrease":1,"increase":1,"worked":1,"example":1,"abc":1,"bcd":1,"bcf":1,"with":1,"real":1,"world":1,"use":1,"simplifying":1,"formulas":1,"before":1,"substituting":1,"solving":1,"equations":1,"analogy":1,"distributing":1,"repacking":1,"loose":1,"items":1,"back":1,"into":1,"shared":1,"box":1,"method":1,"find":1,"all":1,"divide":1,"each":1,"term":1,"write":1,"remaining":1,"misconception":1,"forgetting":1,"invisible":1,"dropping":1,"corrective":1,"check":1,"expanding":1,"questions":1,"factorise":2,"fully":1,"explain":1,"why":1,"increases":1,"number":1,"but":1,"decreases":1,"inside":1}'::jsonb),
('chunk_98019a9af77af97552','file_3393b5fbe4e9b31e26','mathematics.md','Concept: Factorising by grouping and difference of squares','**Definition:** Grouping pairs terms to expose a common bracket; difference of squares uses `a² − b² = (a+b)(a−b)`.
**Worked example:** `ba + ac − db − dc = a(b+c) − d(b+c) = (b+c)(a−d)`. `x² − 16 = (x+4)(x−4)`.
**Real-world use:** Simplifying algebraic fractions before cancelling.
**Analogy:** Grouping is sorting mixed socks into pairs, then noticing every pair shares a common label.
**Method:** group in pairs → factor each pair → factor the common bracket. For a²−b²: square-root each term.
**Misconception:** "`x² − 16` doesn''t factor because there''s no middle term." Corrective: it is a difference of squares → `(x+4)(x−4)`.
**Questions:** (1) *Factorise* `xy + 2x + 3y + 6`. (2) *Factorise* `x² − 49`. (3) *Determine* whether `x² + 9` is a difference of squares; justify.

---','{"concept":1,"factorising":1,"grouping":3,"and":1,"difference":4,"squares":4,"definition":1,"pairs":3,"terms":1,"expose":1,"common":3,"bracket":2,"uses":1,"worked":1,"example":1,"real":1,"world":1,"use":1,"simplifying":1,"algebraic":1,"fractions":1,"before":1,"cancelling":1,"analogy":1,"sorting":1,"mixed":1,"socks":1,"into":1,"then":1,"noticing":1,"every":1,"pair":2,"shares":1,"label":1,"method":1,"group":1,"factor":3,"each":2,"the":1,"for":1,"square":1,"root":1,"term":2,"misconception":1,"doesn":1,"because":1,"there":1,"middle":1,"corrective":1,"questions":1,"factorise":2,"determine":1,"whether":1,"justify":1}'::jsonb),
('chunk_30b4368f46d87d8673','file_3393b5fbe4e9b31e26','mathematics.md','Concept: Meaning of an algebraic fraction; add/subtract with numeric denominators','**Definition:** An algebraic fraction has an algebraic expression in numerator/denominator. Add/subtract using a common denominator, like numeric fractions.
**Worked example:** `x/2 + x/3 = 3x/6 + 2x/6 = 5x/6`. `(2x)/5 − x/5 = x/5`.
**Real-world use:** Combining rates, proportions in formulas.
**Analogy:** You can only add slices of the same size — first cut both into the same size (common denominator).
**Method:** find the LCM of denominators → rewrite each fraction → add/subtract numerators.
**Misconception:** Adding numerators AND denominators: `x/2 + x/3 = 2x/5`. Wrong. Corrective: common denominator 6 → 5x/6.
**Questions:** (1) *Simplify* `x/4 + x/2`. (2) *Simplify* `(3x)/7 − x/7`. (3) *Explain* why you cannot just add the denominators.','{"concept":1,"meaning":1,"algebraic":3,"fraction":3,"add":5,"subtract":3,"with":1,"numeric":2,"denominators":4,"definition":1,"has":1,"expression":1,"numerator":1,"denominator":4,"using":1,"common":3,"like":1,"fractions":1,"worked":1,"example":1,"real":1,"world":1,"use":1,"combining":1,"rates":1,"proportions":1,"formulas":1,"analogy":1,"you":2,"can":1,"only":1,"slices":1,"the":4,"same":2,"size":2,"first":1,"cut":1,"both":1,"into":1,"method":1,"find":1,"lcm":1,"rewrite":1,"each":1,"numerators":2,"misconception":1,"adding":1,"and":1,"wrong":1,"corrective":1,"questions":1,"simplify":2,"explain":1,"why":1,"cannot":1,"just":1}'::jsonb),
('chunk_c5883577ccb2923153','file_3393b5fbe4e9b31e26','mathematics.md','Concept: Multiplying and dividing algebraic fractions (with factorising)','**Definition:** Multiply straight across; divide by multiplying by the reciprocal; cancel common factors (factorise first if needed).
**Worked example:** `(x/3) × (6/x²) = 6x/(3x²) = 2/x`. `(x/4) ÷ (x/2) = (x/4)(2/x) = 2/4 = 1/2`. Using factors: `(x²−9)/(x+3) = ((x+3)(x−3))/(x+3) = x−3`.
**Real-world use:** Simplifying compound rate and scale expressions.
**Analogy:** Dividing by a fraction is asking "how many of these fit?" — flip and multiply.
**Method:** factorise → cancel common factors → multiply (flip the divisor when dividing).
**Misconception:** Cancelling terms not factors: `(x+3)/3 = x` (cancelling the 3s). Wrong — you may only cancel whole factors, not parts of a sum.
**Questions:** (1) *Simplify* `(x/5) × (10/x)`. (2) *Simplify* `((x+2)(x−1))/(x+2)`. (3) *Analyse* why `(x+3)/3` cannot be simplified to `x+1`.

---','{"concept":1,"multiplying":2,"and":3,"dividing":3,"algebraic":1,"fractions":1,"with":1,"factorising":1,"definition":1,"multiply":3,"straight":1,"across":1,"divide":1,"the":3,"reciprocal":1,"cancel":3,"common":2,"factors":5,"factorise":2,"first":1,"needed":1,"worked":1,"example":1,"using":1,"real":1,"world":1,"use":1,"simplifying":1,"compound":1,"rate":1,"scale":1,"expressions":1,"analogy":1,"fraction":1,"asking":1,"how":1,"many":1,"these":1,"fit":1,"flip":2,"method":1,"divisor":1,"when":1,"misconception":1,"cancelling":2,"terms":1,"not":2,"wrong":1,"you":1,"may":1,"only":1,"whole":1,"parts":1,"sum":1,"questions":1,"simplify":2,"analyse":1,"why":1,"cannot":1,"simplified":1}'::jsonb),
('chunk_6d21f59e648a9d7515','file_3393b5fbe4e9b31e26','mathematics.md','Concept: Expressions vs equations; LCM/HCF of algebraic terms','**Definition:** An expression has no equals sign (it can be simplified); an equation states two expressions are equal (it can be solved). HCF/LCM extend to algebraic terms.
**Worked example:** `3x + 2` is an expression; `3x + 2 = 11` is an equation (x = 3). HCF of `6x²` and `9x` is `3x`; LCM is `18x²`.
**Real-world use:** Knowing when there is something to "solve" versus "simplify".
**Analogy:** An expression is a phrase; an equation is a full sentence making a claim.
**Method:** look for `=`. HCF: lowest powers × number HCF; LCM: highest powers × number LCM.
**Misconception:** "You can solve `3x + 2`." Corrective: with no equals sign there is nothing to solve — only simplify.
**Questions:** (1) *State* whether `5x − 1` is an expression or equation. (2) *Find* the HCF of `8x³` and `12x²`. (3) *Explain* the difference between simplifying and solving.','{"concept":1,"expressions":2,"equations":1,"lcm":5,"hcf":6,"algebraic":2,"terms":2,"definition":1,"expression":4,"has":1,"equals":2,"sign":2,"can":3,"simplified":1,"equation":4,"states":1,"two":1,"are":1,"equal":1,"solved":1,"extend":1,"worked":1,"example":1,"and":3,"18x":1,"real":1,"world":1,"use":1,"knowing":1,"when":1,"there":2,"something":1,"solve":3,"versus":1,"simplify":2,"analogy":1,"phrase":1,"full":1,"sentence":1,"making":1,"claim":1,"method":1,"look":1,"for":1,"lowest":1,"powers":2,"number":2,"highest":1,"misconception":1,"you":1,"corrective":1,"with":1,"nothing":1,"only":1,"questions":1,"state":1,"whether":1,"find":1,"the":2,"12x":1,"explain":1,"difference":1,"between":1,"simplifying":1,"solving":1}'::jsonb),
('chunk_eddd5069f9d5ac54a2','file_3393b5fbe4e9b31e26','mathematics.md','Concept: The balance-scale model and forming equations','**Definition:** An equation is a balance; do the same to both sides to keep it level. Real situations can be modelled as equations.
**Worked example:** `x + 3 = 7` → subtract 3 → `x = 4`. `3x = 9` → ÷3 → `x = 3`. `x/3 = 5` → ×3 → `x = 15`. Model: "5 more than twice a number is 17" → `2x + 5 = 17`.
**Real-world use:** Turning word problems (costs, ages, totals) into solvable equations.
**Analogy:** A pan balance — remove 3 kg from one side, remove 3 kg from the other to stay level.
**Method:** identify the unknown → build the equation from the words → keep both sides balanced.
**Misconception:** Changing only one side. Corrective: whatever you do to one side you must do to the other.
**Questions:** (1) *Solve* `x − 3 = 5`. (2) *Form* an equation for "a number tripled equals 21" and solve. (3) *Explain* why both sides must change together.','{"concept":1,"the":7,"balance":3,"scale":1,"model":2,"and":2,"forming":1,"equations":3,"definition":1,"equation":3,"same":1,"both":3,"sides":3,"keep":2,"level":2,"real":2,"situations":1,"can":1,"modelled":1,"worked":1,"example":1,"subtract":1,"more":1,"than":1,"twice":1,"number":2,"world":1,"use":1,"turning":1,"word":1,"problems":1,"costs":1,"ages":1,"totals":1,"into":1,"solvable":1,"analogy":1,"pan":1,"remove":2,"from":3,"one":3,"side":3,"other":2,"stay":1,"method":1,"identify":1,"unknown":1,"build":1,"words":1,"balanced":1,"misconception":1,"changing":1,"only":1,"corrective":1,"whatever":1,"you":2,"must":2,"questions":1,"solve":2,"form":1,"for":1,"tripled":1,"equals":1,"explain":1,"why":1,"change":1,"together":1}'::jsonb),
('chunk_afe63af6ecc89b7c93','file_3393b5fbe4e9b31e26','mathematics.md','Concept: Solving by transposition (multiple steps, with brackets)','**Definition:** Transposition moves terms across the equals sign, changing their operation to the inverse, to isolate the variable.
**Worked example:** `2(x + 3) = 16` → expand `2x + 6 = 16` → `2x = 10` → `x = 5`. `5x − 4 = 3x + 8` → `2x = 12` → `x = 6`.
**Real-world use:** Rearranging any formula to solve for a needed quantity.
**Analogy:** Moving a term across the "=" is like moving a weight to the other pan — it flips its effect.
**Method:** expand brackets → collect variables one side, numbers the other → divide by the coefficient.
**Misconception:** Not flipping the sign when moving: `2x + 6 = 16 → 2x = 16 + 6`. Corrective: subtract 6 from both sides → `2x = 10`.
**Questions:** (1) *Solve* `3x + 4 = 19`. (2) *Solve* `4(x − 2) = 12`. (3) *Solve and check* `7x − 5 = 2x + 15`.

---','{"concept":1,"solving":1,"transposition":2,"multiple":1,"steps":1,"with":1,"brackets":2,"definition":1,"moves":1,"terms":1,"across":2,"the":8,"equals":1,"sign":2,"changing":1,"their":1,"operation":1,"inverse":1,"isolate":1,"variable":1,"worked":1,"example":1,"expand":2,"real":1,"world":1,"use":1,"rearranging":1,"any":1,"formula":1,"solve":4,"for":1,"needed":1,"quantity":1,"analogy":1,"moving":3,"term":1,"like":1,"weight":1,"other":2,"pan":1,"flips":1,"its":1,"effect":1,"method":1,"collect":1,"variables":1,"one":1,"side":1,"numbers":1,"divide":1,"coefficient":1,"misconception":1,"not":1,"flipping":1,"when":1,"corrective":1,"subtract":1,"from":1,"both":1,"sides":1,"questions":1,"and":1,"check":1}'::jsonb),
('chunk_e90d785c7bdf543786','file_3393b5fbe4e9b31e26','mathematics.md','UNIT 3: Spatial Reasoning','**Key Concept:** Form (with Relationships)
**Related Concepts:** Space, Measurement, Generalization, Justification
**Global Context:** Personal and cultural expression / Orientation in space and time (how shape, angle and measurement describe and organise the physical world).
**Statement of Inquiry:** Understanding the properties and measurements of shapes lets us justify relationships and navigate, design and build in physical space.

**Inquiry questions**
- *Factual:* What are the angle sums and area formulas for polygons and the rule of Pythagoras?
- *Conceptual:* How do the properties of a shape determine what we can prove about it?
- *Debatable:* Is a proof more convincing than measuring many examples?

---','{"unit":1,"spatial":1,"reasoning":1,"key":1,"concept":1,"form":1,"with":1,"relationships":2,"related":1,"concepts":1,"space":3,"measurement":2,"generalization":1,"justification":1,"global":1,"context":1,"personal":1,"and":9,"cultural":1,"expression":1,"orientation":1,"time":1,"how":2,"shape":2,"angle":2,"describe":1,"organise":1,"the":5,"physical":2,"world":1,"statement":1,"inquiry":2,"understanding":1,"properties":2,"measurements":1,"shapes":1,"lets":1,"justify":1,"navigate":1,"design":1,"build":1,"questions":1,"factual":1,"what":2,"are":1,"sums":1,"area":1,"formulas":1,"for":1,"polygons":1,"rule":1,"pythagoras":1,"conceptual":1,"determine":1,"can":1,"prove":1,"about":1,"debatable":1,"proof":1,"more":1,"convincing":1,"than":1,"measuring":1,"many":1,"examples":1}'::jsonb),
('chunk_188bab943ffc0a7353','file_3393b5fbe4e9b31e26','mathematics.md','Concept: Angle sum of a quadrilateral (via two triangles)','**Definition:** Any quadrilateral splits into two triangles by a diagonal; since each triangle''s angles sum to 180°, a quadrilateral''s interior angles sum to `360°`.
**Worked example:** Three angles are 100°, 85°, 95°; the fourth `= 360 − 280 = 80°`.
**Real-world use:** Checking a window frame or tile is a true quadrilateral.
**Analogy:** Cutting a quadrilateral corner-to-corner makes two triangular "pizza slices" of 180° each.
**Method:** sum known angles → subtract from 360.
**Misconception:** "Angles of a quadrilateral sum to 180°." Corrective: 180° is a triangle; a quadrilateral is two triangles = 360°.
**Questions:** (1) *State* the interior angle sum of a quadrilateral. (2) *Find* the missing angle given 70°, 110°, 90°. (3) *Explain*, using triangles, why the sum is 360°.','{"100":1,"110":1,"180":4,"280":1,"360":5,"concept":1,"angle":3,"sum":7,"quadrilateral":8,"via":1,"two":4,"triangles":4,"definition":1,"any":1,"splits":1,"into":1,"diagonal":1,"since":1,"each":2,"triangle":2,"angles":5,"interior":2,"worked":1,"example":1,"three":1,"are":1,"the":4,"fourth":1,"real":1,"world":1,"use":1,"checking":1,"window":1,"frame":1,"tile":1,"true":1,"analogy":1,"cutting":1,"corner":2,"makes":1,"triangular":1,"pizza":1,"slices":1,"method":1,"known":1,"subtract":1,"from":1,"misconception":1,"corrective":1,"questions":1,"state":1,"find":1,"missing":1,"given":1,"explain":1,"using":1,"why":1}'::jsonb),
('chunk_d5bfa3a29c6419db38','file_3393b5fbe4e9b31e26','mathematics.md','Concept: Classifying quadrilaterals and their properties','**Definition:** Squares, rectangles, rhombi, parallelograms, kites and trapezia are classified by sides, angles, parallelism and diagonals.
**Worked example:** A rhombus has 4 equal sides and diagonals that bisect each other at right angles; a kite has two pairs of adjacent equal sides and one diagonal bisecting the other; a trapezium has exactly one pair of parallel sides.
**Real-world use:** Recognising shapes in design, architecture, kites and signs.
**Analogy:** A family tree: a square is a special rectangle which is a special parallelogram.
**Method:** check sides equal? parallel? angles right? diagonals'' behaviour → name it.
**Misconception:** "A square is not a rectangle." Corrective: a square satisfies all rectangle properties, so it IS a special rectangle.
**Questions:** (1) *State* two properties of a rhombus. (2) *Classify* a shape with one pair of parallel sides. (3) *Explain* why every square is also a parallelogram.','{"concept":1,"classifying":1,"quadrilaterals":1,"and":6,"their":1,"properties":3,"definition":1,"squares":1,"rectangles":1,"rhombi":1,"parallelograms":1,"kites":2,"trapezia":1,"are":1,"classified":1,"sides":6,"angles":3,"parallelism":1,"diagonals":3,"worked":1,"example":1,"rhombus":2,"has":3,"equal":3,"that":1,"bisect":1,"each":1,"other":2,"right":2,"kite":1,"two":2,"pairs":1,"adjacent":1,"one":3,"diagonal":1,"bisecting":1,"the":1,"trapezium":1,"exactly":1,"pair":2,"parallel":3,"real":1,"world":1,"use":1,"recognising":1,"shapes":1,"design":1,"architecture":1,"signs":1,"analogy":1,"family":1,"tree":1,"square":4,"special":3,"rectangle":4,"which":1,"parallelogram":2,"method":1,"check":1,"behaviour":1,"name":1,"misconception":1,"not":1,"corrective":1,"satisfies":1,"all":1,"questions":1,"state":1,"classify":1,"shape":1,"with":1,"explain":1,"why":1,"every":1,"also":1}'::jsonb),
('chunk_c70a3dbd7676b944a2','file_3393b5fbe4e9b31e26','mathematics.md','Concept: Congruence and the mid-point theorem','**Definition:** Congruent figures are identical in shape and size (SSS, SAS, ASA, RHS). The **mid-point theorem**: the segment joining midpoints of two sides of a triangle is parallel to the third side and half its length.
**Worked example:** In triangle ABC, D and E are midpoints of AB and AC → `DE ∥ BC` and `DE = ½ BC`; if BC = 12, DE = 6.
**Real-world use:** Proving structures identical (manufacturing), scaling in design.
**Analogy:** Congruent triangles are like two keys cut from the same template — interchangeable.
**Method:** match equal sides/angles to a congruence rule; for midpoints apply DE = ½ (third side).
**Misconception:** "Same angles = congruent." Corrective: equal angles give *similar* (same shape) but not necessarily congruent (same size).
**Questions:** (1) *State* the four triangle congruence conditions. (2) *Calculate* DE if the joined midpoints face a side of length 18. (3) *Justify* whether two triangles with all angles equal must be congruent.

---','{"concept":1,"congruence":3,"and":6,"the":7,"mid":2,"point":2,"theorem":2,"definition":1,"congruent":5,"figures":1,"are":3,"identical":2,"shape":2,"size":2,"sss":1,"sas":1,"asa":1,"rhs":1,"segment":1,"joining":1,"midpoints":4,"two":3,"sides":2,"triangle":3,"parallel":1,"third":2,"side":3,"half":1,"its":1,"length":2,"worked":1,"example":1,"abc":1,"real":1,"world":1,"use":1,"proving":1,"structures":1,"manufacturing":1,"scaling":1,"design":1,"analogy":1,"triangles":2,"like":1,"keys":1,"cut":1,"from":1,"same":4,"template":1,"interchangeable":1,"method":1,"match":1,"equal":3,"angles":4,"rule":1,"for":1,"apply":1,"misconception":1,"corrective":1,"give":1,"similar":1,"but":1,"not":1,"necessarily":1,"questions":1,"state":1,"four":1,"conditions":1,"calculate":1,"joined":1,"face":1,"justify":1,"whether":1,"with":1,"all":1,"must":1}'::jsonb),
('chunk_66602d9d3c433baec0','file_3393b5fbe4e9b31e26','mathematics.md','Concept: Interior and exterior angles of polygons','**Definition:** A polygon of n sides splits into (n−2) triangles, so interior angles sum to `(n−2)×180°`. Exterior angles always sum to `360°`. Regular = all sides/angles equal.
**Worked example:** Hexagon interior sum `= (6−2)×180 = 720°`; each interior angle of a regular hexagon `= 720/6 = 120°`; each exterior `= 360/6 = 60°`. Irregular pentagon missing angle: sum 540°, known 100+120+90+110 = 420 → missing 120°.
**Real-world use:** Tiling, floor patterns, nut/bolt design, football panels.
**Analogy:** Walking around a polygon, the exterior turns always add up to one full 360° spin.
**Method:** interior sum `(n−2)180`; regular interior `= sum/n`; exterior `= 360/n`.
**Misconception:** "Exterior angles sum depends on n." Corrective: exterior sum is always 360°, for every convex polygon.
**Questions:** (1) *Calculate* the interior angle sum of an octagon. (2) *Find* each interior angle of a regular pentagon. (3) *Explain* why exterior angles always sum to 360°.

---','{"100":1,"110":1,"120":3,"180":3,"360":6,"420":1,"540":1,"720":2,"concept":1,"interior":8,"and":1,"exterior":8,"angles":6,"polygons":1,"definition":1,"polygon":3,"sides":2,"splits":1,"into":1,"triangles":1,"sum":10,"always":4,"regular":4,"all":1,"equal":1,"worked":1,"example":1,"hexagon":2,"each":3,"angle":4,"irregular":1,"pentagon":2,"missing":2,"known":1,"real":1,"world":1,"use":1,"tiling":1,"floor":1,"patterns":1,"nut":1,"bolt":1,"design":1,"football":1,"panels":1,"analogy":1,"walking":1,"around":1,"the":2,"turns":1,"add":1,"one":1,"full":1,"spin":1,"method":1,"misconception":1,"depends":1,"corrective":1,"for":1,"every":1,"convex":1,"questions":1,"calculate":1,"octagon":1,"find":1,"explain":1,"why":1}'::jsonb),
('chunk_90d2bcdc4c9f93f614','file_3393b5fbe4e9b31e26','mathematics.md','Concept: Areas of quadrilaterals (parallelogram, rhombus, kite, trapezium)','**Definition:** Area formulas: parallelogram `= base × height`; rhombus/kite `= ½ × d1 × d2` (diagonals); trapezium `= ½(a+b) × h`.
**Worked example:** Parallelogram base 8, height 5 → `40`. Kite diagonals 6 and 10 → `½×6×10 = 30`. Trapezium parallel sides 7 and 11, height 4 → `½(18)(4) = 36`.
**Real-world use:** Land area, flooring, fabric cutting, roof panels.
**Analogy:** A parallelogram is a rectangle with a triangle slid from one end to the other — same area, `base × height`.
**Method:** identify the shape → pick the formula → use PERPENDICULAR height, not the slant side.
**Misconception:** Using the slanted side as the height of a parallelogram. Corrective: height is the perpendicular distance between the parallel sides.
**Questions:** (1) *Calculate* the area of a trapezium with parallel sides 5 and 9, height 6. (2) *Find* a rhombus area with diagonals 8 and 12. (3) *Explain* why a parallelogram uses perpendicular height.','{"concept":1,"areas":1,"quadrilaterals":1,"parallelogram":6,"rhombus":3,"kite":3,"trapezium":4,"definition":1,"area":5,"formulas":1,"base":3,"height":9,"diagonals":3,"worked":1,"example":1,"and":4,"parallel":3,"sides":3,"real":1,"world":1,"use":2,"land":1,"flooring":1,"fabric":1,"cutting":1,"roof":1,"panels":1,"analogy":1,"rectangle":1,"with":3,"triangle":1,"slid":1,"from":1,"one":1,"end":1,"the":9,"other":1,"same":1,"method":1,"identify":1,"shape":1,"pick":1,"formula":1,"perpendicular":3,"not":1,"slant":1,"side":2,"misconception":1,"using":1,"slanted":1,"corrective":1,"distance":1,"between":1,"questions":1,"calculate":1,"find":1,"explain":1,"why":1,"uses":1}'::jsonb),
('chunk_b0033caaa1241bfee9','file_3393b5fbe4e9b31e26','mathematics.md','Concept: Compound shapes and circles (incl. concentric circles)','**Definition:** Compound areas are found by splitting into known shapes and adding, or subtracting a hole. Circle: `area = πr²`, `circumference = 2πr`. Concentric circles share a centre; a ring (annulus) area `= π(R² − r²)`.
**Worked example:** L-shape = big rectangle − missing rectangle. Ring with R=5, r=3: `π(25−9) = 16π ≈ 50.3`.
**Real-world use:** Flooring odd rooms, washers, running tracks, garden paths.
**Analogy:** Compound area is like weighing a sculpture by adding up its simple blocks.
**Method:** decompose → find each area → add or subtract as the picture demands.
**Misconception:** Using diameter for r in `πr²`. Corrective: r is the radius (half the diameter).
**Questions:** (1) *Calculate* the area of a circle radius 7 (use π ≈ 3.14). (2) *Find* an annulus area for R=6, r=4. (3) *Determine* the area of an L-shape you split into rectangles.','{"concept":1,"compound":3,"shapes":2,"and":2,"circles":3,"incl":1,"concentric":2,"definition":1,"areas":1,"are":1,"found":1,"splitting":1,"into":2,"known":1,"adding":2,"subtracting":1,"hole":1,"circle":2,"area":7,"circumference":1,"share":1,"centre":1,"ring":2,"annulus":2,"worked":1,"example":1,"shape":2,"big":1,"rectangle":2,"missing":1,"with":1,"real":1,"world":1,"use":2,"flooring":1,"odd":1,"rooms":1,"washers":1,"running":1,"tracks":1,"garden":1,"paths":1,"analogy":1,"like":1,"weighing":1,"sculpture":1,"its":1,"simple":1,"blocks":1,"method":1,"decompose":1,"find":2,"each":1,"add":1,"subtract":1,"the":5,"picture":1,"demands":1,"misconception":1,"using":1,"diameter":2,"for":2,"corrective":1,"radius":2,"half":1,"questions":1,"calculate":1,"determine":1,"you":1,"split":1,"rectangles":1}'::jsonb),
('chunk_d5d7ff35ef19f6657f','file_3393b5fbe4e9b31e26','mathematics.md','Concept: Constructions (compass and ruler only)','**Definition:** Geometric constructions build triangles, angle bisectors and perpendiculars using only compass and straightedge.
**Worked example:** To bisect an angle: arc from the vertex cutting both arms, then equal arcs from those two points intersect; the vertex-to-intersection line bisects the angle.
**Real-world use:** Technical drawing, engineering, drafting without measuring.
**Analogy:** A compass guarantees equal distances the way a fixed string keeps a goat the same distance from its post.
**Method:** keep the compass width fixed for equal radii; intersecting arcs locate exact points.
**Misconception:** "Just estimate the halfway line." Corrective: construction gives an exact bisector, not an eyeballed one.
**Questions:** (1) *Describe* the steps to bisect an angle. (2) *Construct* a perpendicular bisector of a line segment. (3) *Explain* why equal compass radii guarantee accuracy.

---','{"concept":1,"constructions":2,"compass":5,"and":3,"ruler":1,"only":2,"definition":1,"geometric":1,"build":1,"triangles":1,"angle":4,"bisectors":1,"perpendiculars":1,"using":1,"straightedge":1,"worked":1,"example":1,"bisect":2,"arc":1,"from":3,"the":8,"vertex":2,"cutting":1,"both":1,"arms":1,"then":1,"equal":4,"arcs":2,"those":1,"two":1,"points":2,"intersect":1,"intersection":1,"line":3,"bisects":1,"real":1,"world":1,"use":1,"technical":1,"drawing":1,"engineering":1,"drafting":1,"without":1,"measuring":1,"analogy":1,"guarantees":1,"distances":1,"way":1,"fixed":2,"string":1,"keeps":1,"goat":1,"same":1,"distance":1,"its":1,"post":1,"method":1,"keep":1,"width":1,"for":1,"radii":2,"intersecting":1,"locate":1,"exact":2,"misconception":1,"just":1,"estimate":1,"halfway":1,"corrective":1,"construction":1,"gives":1,"bisector":2,"not":1,"eyeballed":1,"one":1,"questions":1,"describe":1,"steps":1,"construct":1,"perpendicular":1,"segment":1,"explain":1,"why":1,"guarantee":1,"accuracy":1}'::jsonb),
('chunk_a177e8cb885ff9d755','file_3393b5fbe4e9b31e26','mathematics.md','Concept: Nets, surface area and volume of prisms and cylinders','**Definition:** A net is the 2D unfolding of a 3D solid. Surface area = total area of the net. Volume of a prism `= cross-sectional area × length`; cylinder volume `= πr²h`, surface area `= 2πr² + 2πrh`.
**Worked example:** Cuboid 3×4×5: volume `= 60`; surface area `= 2(3·4 + 4·5 + 3·5) = 2(12+20+15) = 94`. Cylinder r=2, h=10: volume `= π(4)(10) = 40π ≈ 125.7`.
**Real-world use:** Packaging design, tank capacities, paint quantities.
**Analogy:** A net is the "flattened cardboard box" you fold back into the solid.
**Method:** volume — area of base × height/length; surface area — add every face of the net.
**Misconception:** Confusing surface area with volume. Corrective: surface area is a 2D "wrapping" (units²); volume is 3D "filling" (units³).
**Questions:** (1) *Calculate* the volume of a cuboid 2×5×6. (2) *Find* the surface area of a cube of side 4. (3) *Explain* the difference between a solid''s surface area and volume.','{"125":1,"concept":1,"nets":1,"surface":9,"area":12,"and":3,"volume":10,"prisms":1,"cylinders":1,"definition":1,"net":4,"the":8,"unfolding":1,"solid":3,"total":1,"prism":1,"cross":1,"sectional":1,"length":2,"cylinder":2,"worked":1,"example":1,"cuboid":2,"real":1,"world":1,"use":1,"packaging":1,"design":1,"tank":1,"capacities":1,"paint":1,"quantities":1,"analogy":1,"flattened":1,"cardboard":1,"box":1,"you":1,"fold":1,"back":1,"into":1,"method":1,"base":1,"height":1,"add":1,"every":1,"face":1,"misconception":1,"confusing":1,"with":1,"corrective":1,"wrapping":1,"units":2,"filling":1,"questions":1,"calculate":1,"find":1,"cube":1,"side":1,"explain":1,"difference":1,"between":1}'::jsonb),
('chunk_33587a0482d6868add','file_3393b5fbe4e9b31e26','mathematics.md','Concept: 3D diagonals and Pythagoras in solids','**Definition:** The space diagonal of a cuboid uses Pythagoras twice: `d = √(l² + w² + h²)`.
**Worked example:** Cuboid 3×4×12: `d = √(9+16+144) = √169 = 13`.
**Real-world use:** Longest object fitting in a box, cable runs across a room.
**Analogy:** Reaching corner-to-corner through a room is a triangle standing on the floor''s diagonal.
**Method:** find the base diagonal (Pythagoras) → combine with the height (Pythagoras again).
**Misconception:** Adding the three edges: `3+4+12 = 19`. Corrective: use the square-root formula → 13.
**Questions:** (1) *Calculate* the space diagonal of a 2×3×6 cuboid. (2) *Find* the longest rod fitting in a 6×8×10 box. (3) *Explain* why the 3D diagonal uses Pythagoras twice.

---','{"144":1,"169":1,"concept":1,"diagonals":1,"and":1,"pythagoras":5,"solids":1,"definition":1,"the":9,"space":2,"diagonal":5,"cuboid":3,"uses":2,"twice":2,"worked":1,"example":1,"real":1,"world":1,"use":2,"longest":2,"object":1,"fitting":2,"box":2,"cable":1,"runs":1,"across":1,"room":2,"analogy":1,"reaching":1,"corner":2,"through":1,"triangle":1,"standing":1,"floor":1,"method":1,"find":2,"base":1,"combine":1,"with":1,"height":1,"again":1,"misconception":1,"adding":1,"three":1,"edges":1,"corrective":1,"square":1,"root":1,"formula":1,"questions":1,"calculate":1,"rod":1,"explain":1,"why":1}'::jsonb),
('chunk_98ebf50f3d3d60b2be','file_3393b5fbe4e9b31e26','mathematics.md','Concept: Pythagoras'' theorem and Pythagorean triples','**Definition:** In a right-angled triangle, `a² + b² = c²`, where c is the hypotenuse. Integer sets satisfying this (3,4,5; 5,12,13; 8,15,17) are Pythagorean triples.
**Worked example:** Legs 6 and 8: `c = √(36+64) = √100 = 10`. Given hypotenuse 13 and leg 5: other leg `= √(169−25) = √144 = 12`.
**Real-world use:** Checking a corner is square (3-4-5 method), ladder lengths, navigation.
**Analogy:** The square built on the longest side has exactly the same area as the other two squares combined.
**Method:** identify the hypotenuse (opposite the right angle) → add squares of legs for c, subtract for a leg.
**Misconception:** Treating any side as the hypotenuse. Corrective: c is always the longest side, opposite the 90° angle.
**Questions:** (1) *Calculate* the hypotenuse for legs 9 and 12. (2) *Find* the missing leg if the hypotenuse is 25 and one leg is 7. (3) *Determine* whether 6, 8, 11 form a right triangle; justify.

---','{"100":1,"144":1,"169":1,"concept":1,"pythagoras":1,"theorem":1,"and":5,"pythagorean":2,"triples":2,"definition":1,"right":3,"angled":1,"triangle":2,"where":1,"the":13,"hypotenuse":6,"integer":1,"sets":1,"satisfying":1,"this":1,"are":1,"worked":1,"example":1,"legs":3,"given":1,"leg":5,"other":2,"real":1,"world":1,"use":1,"checking":1,"corner":1,"square":2,"method":2,"ladder":1,"lengths":1,"navigation":1,"analogy":1,"built":1,"longest":2,"side":3,"has":1,"exactly":1,"same":1,"area":1,"two":1,"squares":2,"combined":1,"identify":1,"opposite":2,"angle":2,"add":1,"for":3,"subtract":1,"misconception":1,"treating":1,"any":1,"corrective":1,"always":1,"questions":1,"calculate":1,"find":1,"missing":1,"one":1,"determine":1,"whether":1,"form":1,"justify":1}'::jsonb),
('chunk_d24067fe2b9a9d52ff','file_3393b5fbe4e9b31e26','mathematics.md','Concept: The coordinate plane — plotting and reading points','**Definition:** The Cartesian plane uses an x-axis (horizontal) and y-axis (vertical) meeting at the origin (0,0). A point is `(x, y)`: across then up.
**Worked example:** (3, 2) is 3 right, 2 up; (−4, 1) is 4 left, 1 up; the point 5 left and 3 down of origin is (−5, −3).
**Real-world use:** Maps, GPS, screen pixels, graphs of data.
**Analogy:** Coordinates are like giving a seat as "row and column" in a cinema.
**Method:** draw and label axes → read x first, then y → plot across then up/down.
**Misconception:** Reading y before x. Corrective: always (x, y) — horizontal first.
**Questions:** (1) *State* the coordinates of a point 2 left, 4 up of the origin. (2) *Plot* (−3, −2) and name its quadrant. (3) *Explain* why (2, 5) and (5, 2) are different points.

---','{"concept":1,"the":6,"coordinate":1,"plane":2,"plotting":1,"and":7,"reading":2,"points":2,"definition":1,"cartesian":1,"uses":1,"axis":2,"horizontal":2,"vertical":1,"meeting":1,"origin":3,"point":3,"across":2,"then":3,"worked":1,"example":1,"right":1,"left":3,"down":2,"real":1,"world":1,"use":1,"maps":1,"gps":1,"screen":1,"pixels":1,"graphs":1,"data":1,"analogy":1,"coordinates":2,"are":2,"like":1,"giving":1,"seat":1,"row":1,"column":1,"cinema":1,"method":1,"draw":1,"label":1,"axes":1,"read":1,"first":2,"plot":2,"misconception":1,"before":1,"corrective":1,"always":1,"questions":1,"state":1,"name":1,"its":1,"quadrant":1,"explain":1,"why":1,"different":1}'::jsonb),
('chunk_b232a6125e6f8b17bb','file_3393b5fbe4e9b31e26','mathematics.md','UNIT 4: Reasoning with Data','**Key Concept:** Relationships (with Logic)
**Related Concepts:** Quantity, Representation, Model, Justification
**Global Context:** Identities and relationships / Fairness and development (how we collect, summarise and interpret data to understand groups and make fair judgements).
**Statement of Inquiry:** Representing and summarising data reveals relationships and patterns that let us describe uncertainty and make justified decisions.

**Inquiry questions**
- *Factual:* How do we calculate probability and measures of central tendency and spread?
- *Conceptual:* How does the way we represent data change the story it tells?
- *Debatable:* Can an average ever be misleading, and should we trust it alone?

---','{"unit":1,"reasoning":1,"with":2,"data":4,"key":1,"concept":1,"relationships":3,"logic":1,"related":1,"concepts":1,"quantity":1,"representation":1,"model":1,"justification":1,"global":1,"context":1,"identities":1,"and":10,"fairness":1,"development":1,"how":3,"collect":1,"summarise":1,"interpret":1,"understand":1,"groups":1,"make":2,"fair":1,"judgements":1,"statement":1,"inquiry":2,"representing":1,"summarising":1,"reveals":1,"patterns":1,"that":1,"let":1,"describe":1,"uncertainty":1,"justified":1,"decisions":1,"questions":1,"factual":1,"calculate":1,"probability":1,"measures":1,"central":1,"tendency":1,"spread":1,"conceptual":1,"does":1,"the":2,"way":1,"represent":1,"change":1,"story":1,"tells":1,"debatable":1,"can":1,"average":1,"ever":1,"misleading":1,"should":1,"trust":1,"alone":1}'::jsonb),
('chunk_c58e7bb5995b73ce66','file_3393b5fbe4e9b31e26','mathematics.md','Concept: Probability, its scale, and simple events','**Definition:** Probability measures how likely an event is, from 0 (impossible) to 1 (certain). `P(event) = favourable outcomes ÷ total outcomes` (theoretical). It can be written as a fraction, decimal or percentage.
**Worked example:** Rolling a 4 on a fair die: `P = 1/6 ≈ 0.17 = 17%`. P(even) `= 3/6 = 1/2`. Terms: 0 impossible, 0.5 even chance, 1 certain.
**Real-world use:** Weather forecasts, insurance, games, risk.
**Analogy:** The probability scale is a ruler from "no way" (0) to "for sure" (1).
**Method:** list the sample space → count favourable → divide by total → convert form as needed.
**Misconception:** "Probability can be 2 or 150%." Corrective: probabilities lie in 0–1 (0–100%); never above 1.
**Questions:** (1) *State* the probability of rolling a 7 on a normal die. (2) *Calculate* P(heart) from a 52-card deck. (3) *Explain* the difference between "unlikely" and "impossible".','{"100":1,"150":1,"concept":1,"probability":5,"its":1,"scale":2,"and":2,"simple":1,"events":1,"definition":1,"measures":1,"how":1,"likely":1,"event":2,"from":3,"impossible":3,"certain":2,"favourable":2,"outcomes":2,"total":2,"theoretical":1,"can":2,"written":1,"fraction":1,"decimal":1,"percentage":1,"worked":1,"example":1,"rolling":2,"fair":1,"die":2,"even":2,"terms":1,"chance":1,"real":1,"world":1,"use":1,"weather":1,"forecasts":1,"insurance":1,"games":1,"risk":1,"analogy":1,"the":4,"ruler":1,"way":1,"for":1,"sure":1,"method":1,"list":1,"sample":1,"space":1,"count":1,"divide":1,"convert":1,"form":1,"needed":1,"misconception":1,"corrective":1,"probabilities":1,"lie":1,"never":1,"above":1,"questions":1,"state":1,"normal":1,"calculate":1,"heart":1,"card":1,"deck":1,"explain":1,"difference":1,"between":1,"unlikely":1}'::jsonb),
('chunk_2b536b05cf2e46e30d','file_3393b5fbe4e9b31e26','mathematics.md','Concept: Sample space, trials, theoretical vs experimental probability','**Definition:** A trial is one performance of an experiment; the sample space is the set of all possible outcomes. Theoretical probability is predicted; experimental is observed (`frequency ÷ number of trials`).
**Worked example:** Sample space of one coin = {H, T}. Tossing 50 times gives 28 heads → experimental `P(H) = 28/50 = 0.56`, near the theoretical 0.5.
**Real-world use:** Testing whether a die or coin is fair; quality control.
**Analogy:** Theoretical is the recipe''s promised servings; experimental is what you actually got when you cooked.
**Method:** theoretical from equally likely outcomes; experimental from recorded results; more trials → closer to theoretical.
**Misconception:** "Experimental must equal theoretical." Corrective: they only converge over many trials; short runs vary.
**Questions:** (1) *List* the sample space for rolling one die. (2) *Calculate* the experimental probability of a 6 seen 9 times in 60 rolls. (3) *Discuss* why experimental probability approaches theoretical as trials increase.

---','{"concept":1,"sample":4,"space":4,"trials":5,"theoretical":8,"experimental":8,"probability":4,"definition":1,"trial":1,"one":3,"performance":1,"experiment":1,"the":6,"set":1,"all":1,"possible":1,"outcomes":2,"predicted":1,"observed":1,"frequency":1,"number":1,"worked":1,"example":1,"coin":2,"tossing":1,"times":2,"gives":1,"heads":1,"near":1,"real":1,"world":1,"use":1,"testing":1,"whether":1,"die":2,"fair":1,"quality":1,"control":1,"analogy":1,"recipe":1,"promised":1,"servings":1,"what":1,"you":2,"actually":1,"got":1,"when":1,"cooked":1,"method":1,"from":2,"equally":1,"likely":1,"recorded":1,"results":1,"more":1,"closer":1,"misconception":1,"must":1,"equal":1,"corrective":1,"they":1,"only":1,"converge":1,"over":1,"many":1,"short":1,"runs":1,"vary":1,"questions":1,"list":1,"for":1,"rolling":1,"calculate":1,"seen":1,"rolls":1,"discuss":1,"why":1,"approaches":1,"increase":1}'::jsonb),
('chunk_a72631fd141622542a','file_3393b5fbe4e9b31e26','mathematics.md','Concept: Qualitative vs quantitative; discrete vs continuous; frequency tables','**Definition:** Qualitative data describes categories (colour); quantitative is numeric. Quantitative is discrete (counts, e.g. goals) or continuous (measured, e.g. height). Tally/frequency tables organise raw data; continuous data is grouped into classes.
**Worked example:** Eye colour = qualitative; number of siblings = discrete; mass in kg = continuous. Grouping heights: 150–159, 160–169, … with tallies and a cumulative frequency column.
**Real-world use:** Surveys, census, scientific measurement.
**Analogy:** Discrete data are whole steps on a staircase; continuous data is a ramp with every value in between.
**Method:** decide category vs number → if number, can it take in-between values? continuous : discrete → tabulate.
**Misconception:** "Shoe size is continuous." Corrective: shoe size comes in fixed steps → discrete; foot length is continuous.
**Questions:** (1) *Classify* "favourite sport" and "time to run 100 m". (2) *State* whether number of cars is discrete or continuous. (3) *Explain* why age can be treated as continuous.

---','{"100":1,"150":1,"159":1,"160":1,"169":1,"concept":1,"qualitative":3,"quantitative":3,"discrete":7,"continuous":10,"frequency":3,"tables":2,"definition":1,"data":5,"describes":1,"categories":1,"colour":2,"numeric":1,"counts":1,"goals":1,"measured":1,"height":1,"tally":1,"organise":1,"raw":1,"grouped":1,"into":1,"classes":1,"worked":1,"example":1,"eye":1,"number":4,"siblings":1,"mass":1,"grouping":1,"heights":1,"with":2,"tallies":1,"and":2,"cumulative":1,"column":1,"real":1,"world":1,"use":1,"surveys":1,"census":1,"scientific":1,"measurement":1,"analogy":1,"are":1,"whole":1,"steps":2,"staircase":1,"ramp":1,"every":1,"value":1,"between":2,"method":1,"decide":1,"category":1,"can":2,"take":1,"values":1,"tabulate":1,"misconception":1,"shoe":2,"size":2,"corrective":1,"comes":1,"fixed":1,"foot":1,"length":1,"questions":1,"classify":1,"favourite":1,"sport":1,"time":1,"run":1,"state":1,"whether":1,"cars":1,"explain":1,"why":1,"age":1,"treated":1}'::jsonb),
('chunk_10b2203b34f21860c8','file_3393b5fbe4e9b31e26','mathematics.md','Concept: Data representations (tables, pictograms, bar charts, stem-and-leaf)','**Definition:** Raw data is processed into displays: frequency tables/tally, pictograms (a symbol = a number), bar charts (discrete), and stem-and-leaf (keeps original values while showing shape).
**Worked example:** Scores 21, 24, 24, 31, 35 → stem-and-leaf: 2 | 1 4 4  ;  3 | 1 5 (key 2|1 = 21). A pictogram where one star = 10 uses 3.5 stars for 35.
**Real-world use:** Reports, dashboards, newspapers.
**Analogy:** A stem-and-leaf is a bar chart that still remembers the exact numbers.
**Method:** pick the display for the data type → keep scales/keys consistent → label axes.
**Misconception:** Using a bar chart with gaps for continuous data. Corrective: continuous data uses a histogram (bars touch).
**Questions:** (1) *Draw* a stem-and-leaf for 12, 15, 15, 23, 29. (2) *State* what one symbol represents in a given pictogram. (3) *Explain* why the choice of scale can mislead a reader.','{"concept":1,"data":5,"representations":1,"tables":2,"pictograms":2,"bar":4,"charts":2,"stem":5,"and":6,"leaf":5,"definition":1,"raw":1,"processed":1,"into":1,"displays":1,"frequency":1,"tally":1,"symbol":2,"number":1,"discrete":1,"keeps":1,"original":1,"values":1,"while":1,"showing":1,"shape":1,"worked":1,"example":1,"scores":1,"key":1,"pictogram":2,"where":1,"one":2,"star":1,"uses":2,"stars":1,"for":4,"real":1,"world":1,"use":1,"reports":1,"dashboards":1,"newspapers":1,"analogy":1,"chart":2,"that":1,"still":1,"remembers":1,"the":4,"exact":1,"numbers":1,"method":1,"pick":1,"display":1,"type":1,"keep":1,"scales":1,"keys":1,"consistent":1,"label":1,"axes":1,"misconception":1,"using":1,"with":1,"gaps":1,"continuous":2,"corrective":1,"histogram":1,"bars":1,"touch":1,"questions":1,"draw":1,"state":1,"what":1,"represents":1,"given":1,"explain":1,"why":1,"choice":1,"scale":1,"can":1,"mislead":1,"reader":1}'::jsonb);