INSERT INTO syllabus_chunks (id, file_id, file_name, heading, body, tf) VALUES
('chunk_bf7b8311230dfadc94','file_162fce15bbe62004d5','geography.md','Concept: North–South Divide and the Brandt Line','**Definition:** The **Brandt Line** (1980) is an imaginary line dividing the wealthier "Global North" from the poorer "Global South."
**Purpose:** A simple visual to show global inequality in development.
**Limitations:** It is outdated and oversimplified — fast-growing economies like China, India and Brazil are in the "South," and there is poverty within the "North." Development is not neatly split by a line.
**Country categories (case studies):**
- **LIC (Low-Income Country):** e.g. **Malawi** — low GDP, reliant on subsistence farming.
- **HIC (High-Income Country):** e.g. **Japan / Germany** — high GDP & HDI, service/industry economy.
- **NEE (Newly Emerging Economy):** e.g. **India / Brazil** — rapidly industrialising, rising incomes, but still inequality.
**Why it matters:** Categories and indicators help target aid and policy, but must be used carefully.
**Misconception:** *"All countries in the Global South are equally poor."* Wrong: the "South" includes wealthy oil states and booming NEEs. Corrective: development is a spectrum, not two boxes.
**IB command-term questions:**
1. (Recall) **Define** GDP and HDI.
2. (Apply) **Explain** why HDI is often preferred to GDP as a development measure.
3. (Analyse/Evaluate) **Evaluate** the usefulness of the Brandt Line today.

---','{"1980":1,"concept":1,"north":3,"south":5,"divide":1,"and":8,"the":10,"brandt":3,"line":5,"definition":1,"imaginary":1,"dividing":1,"wealthier":1,"global":4,"from":1,"poorer":1,"purpose":1,"simple":1,"visual":1,"show":1,"inequality":2,"development":4,"limitations":1,"outdated":1,"oversimplified":1,"fast":1,"growing":1,"economies":1,"like":1,"china":1,"india":2,"brazil":2,"are":2,"there":1,"poverty":1,"within":1,"not":2,"neatly":1,"split":1,"country":3,"categories":2,"case":1,"studies":1,"lic":1,"low":2,"income":2,"malawi":1,"gdp":4,"reliant":1,"subsistence":1,"farming":1,"hic":1,"high":2,"japan":1,"germany":1,"hdi":3,"service":1,"industry":1,"economy":2,"nee":1,"newly":1,"emerging":1,"rapidly":1,"industrialising":1,"rising":1,"incomes":1,"but":2,"still":1,"why":2,"matters":1,"indicators":1,"help":1,"target":1,"aid":1,"policy":1,"must":1,"used":1,"carefully":1,"misconception":1,"all":1,"countries":1,"equally":1,"poor":1,"wrong":1,"includes":1,"wealthy":1,"oil":1,"states":1,"booming":1,"nees":1,"corrective":1,"spectrum":1,"two":1,"boxes":1,"command":1,"term":1,"questions":1,"recall":1,"define":1,"apply":1,"explain":1,"often":1,"preferred":1,"measure":1,"analyse":1,"evaluate":2,"usefulness":1,"today":1}'::jsonb),
('chunk_b7ad1b897e201b0d91','file_162fce15bbe62004d5','geography.md','Concept: Poverty','**Definition:** A state where people lack the money and resources to meet basic needs (food, shelter, health, education).
**Real-world example:** Rural poverty in Malawi, where drought and lack of schooling trap families.
**Causes:** Lack of education, conflict/war, inequality, poor health, unemployment, debt.
**Cycle of poverty:** Low income → poor education/health → low-skilled work → low income again — a self-repeating trap passed to the next generation.
**Impact:** Poor health, child labour, hunger, limited opportunity, social unrest.
**Analogy:** The cycle of poverty is like a wheel stuck in mud — without an outside push (education, aid, jobs) it keeps spinning in place.
**Misconception:** *"Poor people are poor because they don''t work hard."* Wrong: poverty is largely structural — caused by lack of education, conflict and inequality beyond individual control. Corrective: breaking the cycle needs systemic change, not just effort.
**IB questions:** (Recall) **List** three causes of poverty. (Apply) **Explain** the cycle of poverty. (Analyse) **Discuss** how education can break the cycle of poverty. *(SDG 1 No Poverty.)*','{"concept":1,"poverty":9,"definition":1,"state":1,"where":2,"people":2,"lack":4,"the":6,"money":1,"and":3,"resources":1,"meet":1,"basic":1,"needs":2,"food":1,"shelter":1,"health":4,"education":6,"real":1,"world":1,"example":1,"rural":1,"malawi":1,"drought":1,"schooling":1,"trap":2,"families":1,"causes":2,"conflict":2,"war":1,"inequality":2,"poor":5,"unemployment":1,"debt":1,"cycle":5,"low":3,"income":2,"skilled":1,"work":2,"again":1,"self":1,"repeating":1,"passed":1,"next":1,"generation":1,"impact":1,"child":1,"labour":1,"hunger":1,"limited":1,"opportunity":1,"social":1,"unrest":1,"analogy":1,"like":1,"wheel":1,"stuck":1,"mud":1,"without":1,"outside":1,"push":1,"aid":1,"jobs":1,"keeps":1,"spinning":1,"place":1,"misconception":1,"are":1,"because":1,"they":1,"don":1,"hard":1,"wrong":1,"largely":1,"structural":1,"caused":1,"beyond":1,"individual":1,"control":1,"corrective":1,"breaking":1,"systemic":1,"change":1,"not":1,"just":1,"effort":1,"questions":1,"recall":1,"list":1,"three":1,"apply":1,"explain":1,"analyse":1,"discuss":1,"how":1,"can":1,"break":1,"sdg":1}'::jsonb),
('chunk_70158c4477a7ed73ec','file_162fce15bbe62004d5','geography.md','Concept: Food Security','**Definition:** When all people, at all times, have physical and economic access to enough safe, nutritious food for an active, healthy life.
**Real-world example:** Yemen faces severe food insecurity due to conflict and drought.
**Factors affecting supply:** **Climate** (drought, floods), **technology** (irrigation, machinery, GM crops), **population** (more mouths to feed), conflict, poverty, trade.
**Environmental impacts of food production:** Deforestation, water use, soil degradation, greenhouse gases, pollution from fertilisers.
**Concept/challenges:** Unequal distribution, food waste, price shocks, climate change.
**Strategies — local:** Community gardens, improved seeds, irrigation, storage, education. **Global:** Fair trade, food aid, technology transfer, reducing waste, the Green Revolution.
**Undernutrition vs overnutrition:** **Undernutrition** = too little/insufficient nutrients (hunger, stunting); **overnutrition** = too much/unbalanced food (obesity, diet-related disease). Both are forms of malnutrition.
**Analogy:** Food security is like a household pantry that is reliably stocked, affordable and healthy — not just full one week and empty the next.
**Misconception:** *"There isn''t enough food in the world to feed everyone."* Wrong: the world produces enough food; the problem is unequal distribution, waste and poverty. Corrective: hunger is mainly an access and distribution problem, not total shortage.
**IB questions:** (Recall) **Define** food security. (Apply) **Explain** how climate affects food supply. (Analyse) **Evaluate** local vs global strategies to improve food security. *(SDG 2 Zero Hunger.)*','{"concept":2,"food":13,"security":4,"definition":1,"when":1,"all":2,"people":1,"times":1,"have":1,"physical":1,"and":6,"economic":1,"access":2,"enough":3,"safe":1,"nutritious":1,"for":1,"active":1,"healthy":2,"life":1,"real":1,"world":3,"example":1,"yemen":1,"faces":1,"severe":1,"insecurity":1,"due":1,"conflict":2,"drought":2,"factors":1,"affecting":1,"supply":2,"climate":3,"floods":1,"technology":2,"irrigation":2,"machinery":1,"crops":1,"population":1,"more":1,"mouths":1,"feed":2,"poverty":2,"trade":2,"environmental":1,"impacts":1,"production":1,"deforestation":1,"water":1,"use":1,"soil":1,"degradation":1,"greenhouse":1,"gases":1,"pollution":1,"from":1,"fertilisers":1,"challenges":1,"unequal":2,"distribution":3,"waste":3,"price":1,"shocks":1,"change":1,"strategies":2,"local":2,"community":1,"gardens":1,"improved":1,"seeds":1,"storage":1,"education":1,"global":2,"fair":1,"aid":1,"transfer":1,"reducing":1,"the":5,"green":1,"revolution":1,"undernutrition":2,"overnutrition":2,"too":2,"little":1,"insufficient":1,"nutrients":1,"hunger":3,"stunting":1,"much":1,"unbalanced":1,"obesity":1,"diet":1,"related":1,"disease":1,"both":1,"are":1,"forms":1,"malnutrition":1,"analogy":1,"like":1,"household":1,"pantry":1,"that":1,"reliably":1,"stocked":1,"affordable":1,"not":2,"just":1,"full":1,"one":1,"week":1,"empty":1,"next":1,"misconception":1,"there":1,"isn":1,"everyone":1,"wrong":1,"produces":1,"problem":2,"corrective":1,"mainly":1,"total":1,"shortage":1,"questions":1,"recall":1,"define":1,"apply":1,"explain":1,"how":1,"affects":1,"analyse":1,"evaluate":1,"improve":1,"sdg":1,"zero":1}'::jsonb),
('chunk_103715fd6db1145d7c','file_162fce15bbe62004d5','geography.md','Concept: Water Scarcity','**Definition:** When the demand for safe water exceeds the available supply.
**Types:**
- **Physical scarcity** — not enough water naturally exists (e.g. Middle East, North Africa).
- **Economic scarcity** — water exists but people lack the money/infrastructure to access it (e.g. parts of Sub-Saharan Africa).
**Real-world example:** Cape Town, South Africa nearly reached "Day Zero" (taps off) in 2018.
**Water-stressed regions:** Middle East, North Africa, parts of India, southwestern USA.
**Impacts:** Disease, crop failure, conflict, migration, lost economic productivity, hardship for women/children who fetch water.
**Conservation strategies:** Drip irrigation, rainwater harvesting, fixing leaks, desalination, wastewater recycling, dams, education.
**Case studies:** **Cape Town** (physical/management crisis); **India** (groundwater over-abstraction and rainwater harvesting schemes).
**Analogy:** Physical scarcity is an empty well; economic scarcity is a full well with no bucket or rope.
**Misconception:** *"Water scarcity only happens in deserts."* Wrong: economic scarcity can affect water-rich regions that lack pipes, treatment and money. Corrective: scarcity is about *access* as well as physical availability.
**IB questions:** (Recall) **Distinguish** physical and economic water scarcity. (Apply) **Describe** two water conservation strategies. (Analyse) **Discuss** the impacts of water scarcity on a named region. *(SDG 6 Clean Water and Sanitation.)*','{"2018":1,"concept":1,"water":12,"scarcity":10,"definition":1,"when":1,"the":4,"demand":1,"for":2,"safe":1,"exceeds":1,"available":1,"supply":1,"types":1,"physical":5,"not":1,"enough":1,"naturally":1,"exists":2,"middle":2,"east":2,"north":2,"africa":4,"economic":5,"but":1,"people":1,"lack":2,"money":2,"infrastructure":1,"access":2,"parts":2,"sub":1,"saharan":1,"real":1,"world":1,"example":1,"cape":2,"town":2,"south":1,"nearly":1,"reached":1,"day":1,"zero":1,"taps":1,"off":1,"stressed":1,"regions":2,"india":2,"southwestern":1,"usa":1,"impacts":2,"disease":1,"crop":1,"failure":1,"conflict":1,"migration":1,"lost":1,"productivity":1,"hardship":1,"women":1,"children":1,"who":1,"fetch":1,"conservation":2,"strategies":2,"drip":1,"irrigation":1,"rainwater":2,"harvesting":2,"fixing":1,"leaks":1,"desalination":1,"wastewater":1,"recycling":1,"dams":1,"education":1,"case":1,"studies":1,"management":1,"crisis":1,"groundwater":1,"over":1,"abstraction":1,"and":4,"schemes":1,"analogy":1,"empty":1,"well":3,"full":1,"with":1,"bucket":1,"rope":1,"misconception":1,"only":1,"happens":1,"deserts":1,"wrong":1,"can":1,"affect":1,"rich":1,"that":1,"pipes":1,"treatment":1,"corrective":1,"about":1,"availability":1,"questions":1,"recall":1,"distinguish":1,"apply":1,"describe":1,"two":1,"analyse":1,"discuss":1,"named":1,"region":1,"sdg":1,"clean":1,"sanitation":1}'::jsonb),
('chunk_b5d46df900cb747705','file_162fce15bbe62004d5','geography.md','Concept: Energy Security','**Definition:** Reliable, affordable access to enough energy to meet a country''s needs.
**Real-world example:** Europe''s 2022 energy crisis after gas supply disruption showed the risk of depending on imported energy.
**Importance of energy conservation:** Reduces costs, cuts emissions, extends resource life, improves security.
**Strategies to reduce consumption:** Efficient appliances, insulation, public transport, LED lighting, smart grids, behaviour change.
**Role of technology:** Renewables (solar, wind), battery storage, smart meters, electric vehicles, efficient design.
**Challenges of clean-energy transition:** High upfront cost, intermittency (sun/wind not constant), storage limits, need for new infrastructure, jobs lost in fossil-fuel industries.
**Analogy:** Energy security is like a phone that''s always charged and never suddenly dies mid-call.
**Misconception:** *"Switching to renewable energy is quick and easy."* Wrong: transition needs huge investment, storage solutions and grid changes over decades. Corrective: it is essential but gradual and challenging.
**IB questions:** (Recall) **Define** energy security. (Apply) **Explain** two strategies to reduce energy consumption. (Analyse) **Evaluate** the challenges of moving to clean energy. *(SDG 7 Affordable and Clean Energy.)*

---','{"2022":1,"concept":1,"energy":12,"security":4,"definition":1,"reliable":1,"affordable":2,"access":1,"enough":1,"meet":1,"country":1,"needs":2,"real":1,"world":1,"example":1,"europe":1,"crisis":1,"after":1,"gas":1,"supply":1,"disruption":1,"showed":1,"the":2,"risk":1,"depending":1,"imported":1,"importance":1,"conservation":1,"reduces":1,"costs":1,"cuts":1,"emissions":1,"extends":1,"resource":1,"life":1,"improves":1,"strategies":2,"reduce":2,"consumption":2,"efficient":2,"appliances":1,"insulation":1,"public":1,"transport":1,"led":1,"lighting":1,"smart":2,"grids":1,"behaviour":1,"change":1,"role":1,"technology":1,"renewables":1,"solar":1,"wind":2,"battery":1,"storage":3,"meters":1,"electric":1,"vehicles":1,"design":1,"challenges":2,"clean":3,"transition":2,"high":1,"upfront":1,"cost":1,"intermittency":1,"sun":1,"not":1,"constant":1,"limits":1,"need":1,"for":1,"new":1,"infrastructure":1,"jobs":1,"lost":1,"fossil":1,"fuel":1,"industries":1,"analogy":1,"like":1,"phone":1,"that":1,"always":1,"charged":1,"and":5,"never":1,"suddenly":1,"dies":1,"mid":1,"call":1,"misconception":1,"switching":1,"renewable":1,"quick":1,"easy":1,"wrong":1,"huge":1,"investment":1,"solutions":1,"grid":1,"changes":1,"over":1,"decades":1,"corrective":1,"essential":1,"but":1,"gradual":1,"challenging":1,"questions":1,"recall":1,"define":1,"apply":1,"explain":1,"two":1,"analyse":1,"evaluate":1,"moving":1,"sdg":1}'::jsonb),
('chunk_4685ad4231f08bb9a4','file_162fce15bbe62004d5','geography.md','Concept: International Aid','**Definition:** Help (money, goods, expertise) given by one country or organisation to another to support development or respond to crises.
**Real-world example:** Emergency aid after the 2010 Haiti earthquake (short-term); long-term development aid building schools and clinics in Rwanda.
**Purpose of aid:** Reduce poverty, respond to disasters, improve health/education, support development and stability.
**Types of aid:**
| Type | Timescale | Purpose | Example |
|------|-----------|---------|---------|
| **Short-term / emergency** | Immediate | Save lives after disaster | Food, water, shelter, medics after an earthquake |
| **Long-term / development** | Years | Build lasting capacity | Schools, clean water systems, training, infrastructure |
**Role of international organizations:** The **UN**, **World Bank**, **IMF**, **WHO**, and NGOs (Oxfam, Red Cross) fund, coordinate and deliver aid and set development goals (the SDGs).
**Analogy:** Emergency aid is a plaster for a wound; development aid is physiotherapy that helps the patient walk again.
**Misconception:** *"Aid always helps the receiving country."* Wrong: poorly planned aid can create dependency, debt or benefit donors more than recipients. Corrective: aid works best when it is long-term, locally led and builds self-reliance.','{"2010":1,"concept":1,"international":2,"aid":11,"definition":1,"help":1,"money":1,"goods":1,"expertise":1,"given":1,"one":1,"country":2,"organisation":1,"another":1,"support":2,"development":6,"respond":2,"crises":1,"real":1,"world":2,"example":2,"emergency":3,"after":3,"the":5,"haiti":1,"earthquake":2,"short":2,"term":5,"long":3,"building":1,"schools":2,"and":6,"clinics":1,"rwanda":1,"purpose":2,"reduce":1,"poverty":1,"disasters":1,"improve":1,"health":1,"education":1,"stability":1,"types":1,"type":1,"timescale":1,"immediate":1,"save":1,"lives":1,"disaster":1,"food":1,"water":2,"shelter":1,"medics":1,"years":1,"build":1,"lasting":1,"capacity":1,"clean":1,"systems":1,"training":1,"infrastructure":1,"role":1,"organizations":1,"bank":1,"imf":1,"who":1,"ngos":1,"oxfam":1,"red":1,"cross":1,"fund":1,"coordinate":1,"deliver":1,"set":1,"goals":1,"sdgs":1,"analogy":1,"plaster":1,"for":1,"wound":1,"physiotherapy":1,"that":1,"helps":2,"patient":1,"walk":1,"again":1,"misconception":1,"always":1,"receiving":1,"wrong":1,"poorly":1,"planned":1,"can":1,"create":1,"dependency":1,"debt":1,"benefit":1,"donors":1,"more":1,"than":1,"recipients":1,"corrective":1,"works":1,"best":1,"when":1,"locally":1,"led":1,"builds":1,"self":1,"reliance":1}'::jsonb),
('chunk_20394deda219ca8006','file_162fce15bbe62004d5','geography.md','Concept: International Agreements and the Role of Governments','**Definition:** Countries cooperate through treaties and agreements to manage shared resources and problems that cross borders.
**Real-world example:** The **Paris Agreement (2015)** on climate change; the **Kyoto Protocol**; **Agenda 21** and the **UN Sustainable Development Goals (2015)**.
**Role of governments:** Make laws, set targets, fund conservation, sign international agreements, regulate industry, provide services, and balance economic growth with sustainability.
**Why it matters:** Resource problems (climate, oceans, rivers) don''t stop at borders, so governance must be cooperative and global.
**Misconception:** *"One country acting alone can solve global resource problems."* Wrong: issues like climate change need cooperation because emissions and pollution cross borders. Corrective: global problems require global governance and shared responsibility.
**IB command-term questions:**
1. (Recall) **State** the difference between emergency and development aid.
2. (Apply) **Explain** the role of one international organisation in resource management.
3. (Analyse/Evaluate) **Evaluate** the claim that international aid does more harm than good.

---','{"2015":2,"concept":1,"international":4,"agreements":3,"and":9,"the":7,"role":3,"governments":2,"definition":1,"countries":1,"cooperate":1,"through":1,"treaties":1,"manage":1,"shared":2,"resources":1,"problems":4,"that":2,"cross":2,"borders":3,"real":1,"world":1,"example":1,"paris":1,"agreement":1,"climate":3,"change":2,"kyoto":1,"protocol":1,"agenda":1,"sustainable":1,"development":2,"goals":1,"make":1,"laws":1,"set":1,"targets":1,"fund":1,"conservation":1,"sign":1,"regulate":1,"industry":1,"provide":1,"services":1,"balance":1,"economic":1,"growth":1,"with":1,"sustainability":1,"why":1,"matters":1,"resource":3,"oceans":1,"rivers":1,"don":1,"stop":1,"governance":2,"must":1,"cooperative":1,"global":4,"misconception":1,"one":2,"country":1,"acting":1,"alone":1,"can":1,"solve":1,"wrong":1,"issues":1,"like":1,"need":1,"cooperation":1,"because":1,"emissions":1,"pollution":1,"corrective":1,"require":1,"responsibility":1,"command":1,"term":1,"questions":1,"recall":1,"state":1,"difference":1,"between":1,"emergency":1,"aid":2,"apply":1,"explain":1,"organisation":1,"management":1,"analyse":1,"evaluate":2,"claim":1,"does":1,"more":1,"harm":1,"than":1,"good":1}'::jsonb),
('chunk_0505ad6d35c64fd79c','file_162fce15bbe62004d5','geography.md','Common Misconceptions Master List','1. **Biome = ecosystem.** No — biome is global-scale; ecosystem is local.
2. **Rainforest soil is rich.** No — it is nutrient-poor; richness is in the living plants.
3. **Poles are the rainiest places because they are cold.** No — cold, sinking air is dry; poles are "cold deserts."
4. **Evergreen trees never lose leaves.** No — they shed needles gradually all year.
5. **Deserts are lifeless seas of sand.** No — mostly rocky and full of adapted life; defined by low rainfall.
6. **Savanna fires are always disasters.** No — periodic fire is natural and needed.
7. **Grasslands are empty, unused land.** No — the world''s richest farmland.
8. **Nothing lives in the tundra.** No — caribou, foxes, birds and hardy plants thrive.
9. **Renewable resources can never run out.** No — forests, fish and groundwater can be depleted.
10. **Soil is just dead dirt.** No — living and effectively non-renewable on human timescales.
11. **Only poor/overpopulated countries cause depletion.** No — high per-capita consumption matters as much.
12. **Recycling alone makes an economy circular.** No — reduce and reuse come first.
13. **Sustainable development means stopping growth.** No — it means growing cleaner and fairer.
14. **A rich country is automatically developed.** No — wealth can be unequally shared.
15. **Resource-rich countries are always developed.** No — the "resource curse."
16. **All Global South countries are equally poor.** No — development is a spectrum.
17. **Poverty is caused by laziness.** No — it is largely structural.
18. **There isn''t enough food for everyone.** No — it''s a distribution and waste problem.
19. **Water scarcity only happens in deserts.** No — economic scarcity affects water-rich regions.
20. **Renewable transition is quick and easy.** No — costly, gradual and challenging.
21. **Aid always helps.** No — poorly planned aid can create dependency.','{"common":1,"misconceptions":1,"master":1,"list":1,"biome":2,"ecosystem":2,"global":2,"scale":1,"local":1,"rainforest":1,"soil":2,"rich":4,"nutrient":1,"poor":3,"richness":1,"the":5,"living":2,"plants":2,"poles":2,"are":8,"rainiest":1,"places":1,"because":1,"they":2,"cold":3,"sinking":1,"air":1,"dry":1,"deserts":3,"evergreen":1,"trees":1,"never":2,"lose":1,"leaves":1,"shed":1,"needles":1,"gradually":1,"all":2,"year":1,"lifeless":1,"seas":1,"sand":1,"mostly":1,"rocky":1,"and":10,"full":1,"adapted":1,"life":1,"defined":1,"low":1,"rainfall":1,"savanna":1,"fires":1,"always":3,"disasters":1,"periodic":1,"fire":1,"natural":1,"needed":1,"grasslands":1,"empty":1,"unused":1,"land":1,"world":1,"richest":1,"farmland":1,"nothing":1,"lives":1,"tundra":1,"caribou":1,"foxes":1,"birds":1,"hardy":1,"thrive":1,"renewable":3,"resources":1,"can":4,"run":1,"out":1,"forests":1,"fish":1,"groundwater":1,"depleted":1,"just":1,"dead":1,"dirt":1,"effectively":1,"non":1,"human":1,"timescales":1,"only":2,"overpopulated":1,"countries":3,"cause":1,"depletion":1,"high":1,"per":1,"capita":1,"consumption":1,"matters":1,"much":1,"recycling":1,"alone":1,"makes":1,"economy":1,"circular":1,"reduce":1,"reuse":1,"come":1,"first":1,"sustainable":1,"development":2,"means":2,"stopping":1,"growth":1,"growing":1,"cleaner":1,"fairer":1,"country":1,"automatically":1,"developed":2,"wealth":1,"unequally":1,"shared":1,"resource":2,"curse":1,"south":1,"equally":1,"spectrum":1,"poverty":1,"caused":1,"laziness":1,"largely":1,"structural":1,"there":1,"isn":1,"enough":1,"food":1,"for":1,"everyone":1,"distribution":1,"waste":1,"problem":1,"water":2,"scarcity":2,"happens":1,"economic":1,"affects":1,"regions":1,"transition":1,"quick":1,"easy":1,"costly":1,"gradual":1,"challenging":1,"aid":2,"helps":1,"poorly":1,"planned":1,"create":1,"dependency":1}'::jsonb),
('chunk_dc29525115151e9329','file_162fce15bbe62004d5','geography.md','Command-Term / GRASPS Question Bank','1. **Define** "biome" and **outline** two factors that determine biome distribution. *(Criterion A)*
2. **Compare and contrast** the tropical rainforest and the taiga in terms of climate, soil and human use. Present your answer as a table. *(Criterion A/C)*
3. **GRASPS task:** *Goal* — advise a government; *Role* — you are a sustainability consultant; *Audience* — the Ministry of Environment; *Situation* — rapid deforestation; *Product* — a one-page conservation strategy proposal; *Standards* — uses named examples, the 3 Rs and SDG links. *(Criterion C/D)*
4. **Investigate** (Criterion B): "How does water scarcity affect daily life in a named water-stressed region?" Write a research question, plan and list two sources.
5. **OPVL / source analysis:** You are given a photograph of Amazon deforestation and a mining company''s press release. **Evaluate** the **Origin, Purpose, Value and Limitation** of each source, and explain how each shapes the message. *(Criterion D)*
6. **OPVL / source analysis:** Examine a choropleth map of HDI. **Analyse** what it shows about the North–South divide and **identify two limitations** of using such a map. *(Criterion D)*
7. **To what extent** is international aid an effective way to promote long-term development? Use at least one case study. *(Criterion D)*
8. **Evaluate** the view that a circular economy is the only realistic path to sustainable development. *(Criterion D)*','{"command":1,"term":2,"grasps":2,"question":2,"bank":1,"define":1,"biome":2,"and":10,"outline":1,"two":3,"factors":1,"that":2,"determine":1,"distribution":1,"criterion":8,"compare":1,"contrast":1,"the":9,"tropical":1,"rainforest":1,"taiga":1,"terms":1,"climate":1,"soil":1,"human":1,"use":2,"present":1,"your":1,"answer":1,"table":1,"task":1,"goal":1,"advise":1,"government":1,"role":1,"you":2,"are":2,"sustainability":1,"consultant":1,"audience":1,"ministry":1,"environment":1,"situation":1,"rapid":1,"deforestation":2,"product":1,"one":2,"page":1,"conservation":1,"strategy":1,"proposal":1,"standards":1,"uses":1,"named":2,"examples":1,"sdg":1,"links":1,"investigate":1,"how":2,"does":1,"water":2,"scarcity":1,"affect":1,"daily":1,"life":1,"stressed":1,"region":1,"write":1,"research":1,"plan":1,"list":1,"sources":1,"opvl":2,"source":3,"analysis":2,"given":1,"photograph":1,"amazon":1,"mining":1,"company":1,"press":1,"release":1,"evaluate":2,"origin":1,"purpose":1,"value":1,"limitation":1,"each":2,"explain":1,"shapes":1,"message":1,"examine":1,"choropleth":1,"map":2,"hdi":1,"analyse":1,"what":2,"shows":1,"about":1,"north":1,"south":1,"divide":1,"identify":1,"limitations":1,"using":1,"such":1,"extent":1,"international":1,"aid":1,"effective":1,"way":1,"promote":1,"long":1,"development":2,"least":1,"case":1,"study":1,"view":1,"circular":1,"economy":1,"only":1,"realistic":1,"path":1,"sustainable":1}'::jsonb),
('chunk_c2f7465690dc1c1517','file_162fce15bbe62004d5','geography.md','Cross-Subject Connections','- **Biology:** Adaptation, food chains/webs, nutrient cycling, photosynthesis, biodiversity and conservation directly overlap with biome study; permafrost thaw links to the carbon and methane cycles.
- **Chemistry:** The carbon cycle, greenhouse gases and combustion of fossil fuels, soil chemistry (nutrients, pH, salinisation), water treatment and desalination, and materials in the recycling/circular economy.
- **History:** Colonialism and its role in the North–South divide and the "resource curse"; the Industrial Revolution and fossil-fuel dependence; the 1930s Dust Bowl; the displacement of indigenous peoples; the history of international cooperation (UN, Earth Summit 1992, Paris 2015).
- **Physics (extension):** Energy transfer and efficiency, how solar/wind/hydro generate electricity, and heat/pressure in the atmospheric circulation that drives pressure belts.

---
*End of Grade 7 Geography knowledge base — IISH MYP 2026–2027.*','{"1992":1,"2015":1,"2026":1,"2027":1,"cross":1,"subject":1,"connections":1,"biology":1,"adaptation":1,"food":1,"chains":1,"webs":1,"nutrient":1,"cycling":1,"photosynthesis":1,"biodiversity":1,"and":10,"conservation":1,"directly":1,"overlap":1,"with":1,"biome":1,"study":1,"permafrost":1,"thaw":1,"links":1,"the":10,"carbon":2,"methane":1,"cycles":1,"chemistry":2,"cycle":1,"greenhouse":1,"gases":1,"combustion":1,"fossil":2,"fuels":1,"soil":1,"nutrients":1,"salinisation":1,"water":1,"treatment":1,"desalination":1,"materials":1,"recycling":1,"circular":1,"economy":1,"history":2,"colonialism":1,"its":1,"role":1,"north":1,"south":1,"divide":1,"resource":1,"curse":1,"industrial":1,"revolution":1,"fuel":1,"dependence":1,"1930s":1,"dust":1,"bowl":1,"displacement":1,"indigenous":1,"peoples":1,"international":1,"cooperation":1,"earth":1,"summit":1,"paris":1,"physics":1,"extension":1,"energy":1,"transfer":1,"efficiency":1,"how":1,"solar":1,"wind":1,"hydro":1,"generate":1,"electricity":1,"heat":1,"pressure":2,"atmospheric":1,"circulation":1,"that":1,"drives":1,"belts":1,"end":1,"grade":1,"geography":1,"knowledge":1,"base":1,"iish":1,"myp":1}'::jsonb),
('chunk_99bbe1954ef21960be','file_04bb580a3d99034261','history.md','Grade 7 History (Individuals & Societies) — Knowledge Base','**IISH MYP | 2026–2027 | MYP Year 2 (Grade 7)**

This file is part of a Retrieval-Augmented Generation (RAG) knowledge base powering an IB MYP teaching assistant. It covers the Historians'' Toolkit and four units for Grade 7 History within the Individuals & Societies (I&S) subject group. Each entry provides factual grounding, a significance note, a perspective/interpretation note, at least one misconception with correction, and three IB command-term questions.

---','{"2026":1,"2027":1,"grade":3,"history":2,"individuals":2,"societies":2,"knowledge":2,"base":2,"iish":1,"myp":3,"year":1,"this":1,"file":1,"part":1,"retrieval":1,"augmented":1,"generation":1,"rag":1,"powering":1,"teaching":1,"assistant":1,"covers":1,"the":2,"historians":1,"toolkit":1,"and":2,"four":1,"units":1,"for":1,"within":1,"subject":1,"group":1,"each":1,"entry":1,"provides":1,"factual":1,"grounding":1,"significance":1,"note":2,"perspective":1,"interpretation":1,"least":1,"one":1,"misconception":1,"with":1,"correction":1,"three":1,"command":1,"term":1,"questions":1}'::jsonb),
('chunk_6a0f53133f3c87cb28','file_04bb580a3d99034261','history.md','Subject Overview: Individuals & Societies in the MYP','History at IISH sits inside the MYP **Individuals & Societies (I&S)** subject group. I&S encourages learners to appreciate the diversity of human culture, attitudes and beliefs, and to investigate human systems (historical, geographical, economic, political, social) using disciplined inquiry. History specifically develops students as young historians who work with **evidence**, weigh **interpretations**, and construct **reasoned arguments** about the past.','{"subject":2,"overview":1,"individuals":2,"societies":2,"the":4,"myp":2,"history":2,"iish":1,"sits":1,"inside":1,"group":1,"encourages":1,"learners":1,"appreciate":1,"diversity":1,"human":2,"culture":1,"attitudes":1,"and":3,"beliefs":1,"investigate":1,"systems":1,"historical":1,"geographical":1,"economic":1,"political":1,"social":1,"using":1,"disciplined":1,"inquiry":1,"specifically":1,"develops":1,"students":1,"young":1,"historians":1,"who":1,"work":1,"with":1,"evidence":1,"weigh":1,"interpretations":1,"construct":1,"reasoned":1,"arguments":1,"about":1,"past":1}'::jsonb),
('chunk_fedf0dc8ca46ae1201','file_04bb580a3d99034261','history.md','The Four MYP I&S Assessment Criteria','Each criterion is marked out of 8 (four achievement bands: 1–2, 3–4, 5–6, 7–8).

- **Criterion A — Knowing and understanding.** Use terminology in context; demonstrate knowledge and understanding of content and concepts through descriptions, explanations and examples.
- **Criterion B — Investigating.** Formulate a clear and focused research question; follow an action plan; collect and record relevant information; evaluate the process and results of the investigation.
- **Criterion C — Communicating.** Communicate information and ideas in a way appropriate to the audience and purpose; structure information logically; reference sources of information (documenting/citing).
- **Criterion D — Thinking critically.** Analyse concepts, issues, models and arguments; analyse and evaluate a range of sources/data for **origin, purpose, value and limitations (OPVL)**; recognise different perspectives and their implications; synthesise information to make valid, well-supported arguments.

> Teaching note: Source evaluation (OPVL) lives primarily in **Criterion D**. When students "evaluate a source," they are being marked on Criterion D, not just recalling facts (Criterion A).','{"the":4,"four":2,"myp":1,"assessment":1,"criteria":1,"each":1,"criterion":8,"marked":2,"out":1,"achievement":1,"bands":1,"knowing":1,"and":13,"understanding":2,"use":1,"terminology":1,"context":1,"demonstrate":1,"knowledge":1,"content":1,"concepts":2,"through":1,"descriptions":1,"explanations":1,"examples":1,"investigating":1,"formulate":1,"clear":1,"focused":1,"research":1,"question":1,"follow":1,"action":1,"plan":1,"collect":1,"record":1,"relevant":1,"information":5,"evaluate":3,"process":1,"results":1,"investigation":1,"communicating":1,"communicate":1,"ideas":1,"way":1,"appropriate":1,"audience":1,"purpose":2,"structure":1,"logically":1,"reference":1,"sources":2,"documenting":1,"citing":1,"thinking":1,"critically":1,"analyse":2,"issues":1,"models":1,"arguments":2,"range":1,"data":1,"for":1,"origin":1,"value":1,"limitations":1,"opvl":2,"recognise":1,"different":1,"perspectives":1,"their":1,"implications":1,"synthesise":1,"make":1,"valid":1,"well":1,"supported":1,"teaching":1,"note":1,"source":2,"evaluation":1,"lives":1,"primarily":1,"when":1,"students":1,"they":1,"are":1,"being":1,"not":1,"just":1,"recalling":1,"facts":1}'::jsonb),
('chunk_fdc307a3aeff2576f1','file_04bb580a3d99034261','history.md','Key Concepts (I&S drivers used in History)','The three key concepts most often driving MYP History units are **Change**, **Global interactions**, and **Systems** (with **Time, place and space** as an important supporting concept). A key concept is a big, transferable idea that frames a whole unit.','{"key":3,"concepts":2,"drivers":1,"used":1,"history":2,"the":1,"three":1,"most":1,"often":1,"driving":1,"myp":1,"units":1,"are":1,"change":1,"global":1,"interactions":1,"and":2,"systems":1,"with":1,"time":1,"place":1,"space":1,"important":1,"supporting":1,"concept":2,"big":1,"transferable":1,"idea":1,"that":1,"frames":1,"whole":1,"unit":1}'::jsonb),
('chunk_bdad59366f8400ba04','file_04bb580a3d99034261','history.md','I&S Related Concepts (History)','Related concepts are subject-specific lenses that sharpen a unit. The IB I&S related concepts most used in History include:

- **Causality (cause and consequence)** — why events happen and what follows.
- **Perspective** — the viewpoint from which people experience and record events.
- **Significance** — why something matters, then and now.
- **Empire** — the extension of one state''s control over other peoples/territories.
- **Power / Governance** — how authority is organised and exercised.
- **Innovation and revolution** — transformative change in ideas, technology or society.
- Others used across units: **Civilization, Culture, Conflict, Cooperation, Trade, Interdependence, Identity, Ideology, Resources.**','{"related":3,"concepts":3,"history":2,"are":1,"subject":1,"specific":1,"lenses":1,"that":1,"sharpen":1,"unit":1,"the":3,"most":1,"used":2,"include":1,"causality":1,"cause":1,"and":6,"consequence":1,"why":2,"events":2,"happen":1,"what":1,"follows":1,"perspective":1,"viewpoint":1,"from":1,"which":1,"people":1,"experience":1,"record":1,"significance":1,"something":1,"matters":1,"then":1,"now":1,"empire":1,"extension":1,"one":1,"state":1,"control":1,"over":1,"other":1,"peoples":1,"territories":1,"power":1,"governance":1,"how":1,"authority":1,"organised":1,"exercised":1,"innovation":1,"revolution":1,"transformative":1,"change":1,"ideas":1,"technology":1,"society":1,"others":1,"across":1,"units":1,"civilization":1,"culture":1,"conflict":1,"cooperation":1,"trade":1,"interdependence":1,"identity":1,"ideology":1,"resources":1}'::jsonb),
('chunk_94c5e1d8fe69d302bc','file_04bb580a3d99034261','history.md','Global Contexts (the six MYP lenses)','Units are framed by one of six global contexts: **Identities and relationships; Orientation in space and time; Personal and cultural expression; Scientific and technical innovation; Fairness and development; Globalization and sustainability.**

---','{"global":2,"contexts":2,"the":1,"six":2,"myp":1,"lenses":1,"units":1,"are":1,"framed":1,"one":1,"identities":1,"and":6,"relationships":1,"orientation":1,"space":1,"time":1,"personal":1,"cultural":1,"expression":1,"scientific":1,"technical":1,"innovation":1,"fairness":1,"development":1,"globalization":1,"sustainability":1}'::jsonb),
('chunk_d32c9fb632867945b0','file_04bb580a3d99034261','history.md','HISTORIANS'' TOOLKIT (Prerequisites)','Before the units, students master the historian''s core skills: identifying and analysing sources, and judging bias and reliability. These skills are assessed all year, mainly under **Criterion D**.','{"historians":1,"toolkit":1,"prerequisites":1,"before":1,"the":2,"units":1,"students":1,"master":1,"historian":1,"core":1,"skills":2,"identifying":1,"and":3,"analysing":1,"sources":1,"judging":1,"bias":1,"reliability":1,"these":1,"are":1,"assessed":1,"all":1,"year":1,"mainly":1,"under":1,"criterion":1}'::jsonb),
('chunk_7d3e80f4fbad980b1b','file_04bb580a3d99034261','history.md','Primary vs Secondary Sources','- **Primary source:** produced *at the time* of the event by someone with direct experience or connection. Examples: a Roman coin, a Chola temple inscription, Ibn Battuta''s travel account, a ship''s log, a Renaissance painting, an eyewitness letter, a photograph, an artefact.
- **Secondary source:** produced *later*, interpreting or analysing primary material. Examples: a modern textbook, a historian''s biography of Galileo, a documentary, an encyclopaedia entry.
- **Key subtlety:** The same object can be primary or secondary depending on the question. A 1960s history book is a *secondary* source about the Roman Empire, but a *primary* source about how 1960s historians thought.

**Significance ("so what"):** History is an argument built from evidence. Knowing whether a source is primary or secondary tells you how close it is to events and what kind of claim it can support.

**Perspective/interpretation note:** Neither type is automatically "better." Primary sources are close but may be biased or fragmentary; secondary sources have hindsight and can compare evidence but depend on the primaries they used.

**Misconception:** *"Primary sources are always more reliable/true than secondary sources."*
- *Why believed:* "Primary" sounds like "first-hand = truth."
- *Why wrong:* A primary source may lie, exaggerate, be propaganda, or record only one viewpoint (e.g., a king''s inscription praising himself). A careful secondary source that cross-checks many primaries can be more accurate.
- *Corrective:* Reliability depends on the source''s **origin, purpose, value and limitations**, not on the primary/secondary label alone.

**Command-term questions:**
1. *(Recall)* **State** the difference between a primary and a secondary source and give one example of each from medieval India.
2. *(Apply)* **Classify** these as primary or secondary for a study of the Roman Empire, and justify: a Roman coin; a 2020 documentary; a letter by Cicero; a modern atlas.
3. *(Analyse/Evaluate)* **To what extent** is a primary source always more useful to a historian than a secondary source? Support with examples.','{"2020":1,"primary":14,"secondary":12,"sources":5,"source":11,"produced":2,"the":10,"time":1,"event":1,"someone":1,"with":2,"direct":1,"experience":1,"connection":1,"examples":3,"roman":4,"coin":2,"chola":1,"temple":1,"inscription":2,"ibn":1,"battuta":1,"travel":1,"account":1,"ship":1,"log":1,"renaissance":1,"painting":1,"eyewitness":1,"letter":2,"photograph":1,"artefact":1,"later":1,"interpreting":1,"analysing":1,"material":1,"modern":2,"textbook":1,"historian":2,"biography":1,"galileo":1,"documentary":2,"encyclopaedia":1,"entry":1,"key":1,"subtlety":1,"same":1,"object":1,"can":4,"depending":1,"question":1,"1960s":2,"history":2,"book":1,"about":2,"empire":2,"but":3,"how":2,"historians":1,"thought":1,"significance":1,"what":3,"argument":1,"built":1,"from":2,"evidence":2,"knowing":1,"whether":1,"tells":1,"you":1,"close":2,"events":1,"and":6,"kind":1,"claim":1,"support":2,"perspective":1,"interpretation":1,"note":1,"neither":1,"type":1,"automatically":1,"better":1,"are":2,"may":2,"biased":1,"fragmentary":1,"have":1,"hindsight":1,"compare":1,"depend":1,"primaries":2,"they":1,"used":1,"misconception":1,"always":2,"more":3,"reliable":1,"true":1,"than":2,"why":2,"believed":1,"sounds":1,"like":1,"first":1,"hand":1,"truth":1,"wrong":1,"lie":1,"exaggerate":1,"propaganda":1,"record":1,"only":1,"one":2,"viewpoint":1,"king":1,"praising":1,"himself":1,"careful":1,"that":1,"cross":1,"checks":1,"many":1,"accurate":1,"corrective":1,"reliability":1,"depends":1,"origin":1,"purpose":1,"value":1,"limitations":1,"not":1,"label":1,"alone":1,"command":1,"term":1,"questions":1,"recall":1,"state":1,"difference":1,"between":1,"give":1,"example":1,"each":1,"medieval":1,"india":1,"apply":1,"classify":1,"these":1,"for":1,"study":1,"justify":1,"cicero":1,"atlas":1,"analyse":1,"evaluate":1,"extent":1,"useful":1}'::jsonb),
('chunk_1c5cabed4ea39d2d31','file_04bb580a3d99034261','history.md','Full teaching entry: The OPVL Method','OPVL is a structured way to evaluate any source. It stands for **Origin, Purpose, Value, Limitation**. It is the backbone of MYP **Criterion D** source analysis.

- **O — Origin:** *Who made it, what is it, when and where?* Author, type of source, date, place, primary/secondary. (You describe the source.)
- **P — Purpose:** *Why was it made, and for whom?* To inform, persuade, record, entertain, glorify, warn, sell? Who was the intended audience?
- **V — Value:** *What can a historian usefully learn from it?* Value flows from origin and purpose — e.g., an eyewitness gives us authentic first-hand detail; a government poster reveals what leaders wanted people to believe.
- **L — Limitation:** *What are the weaknesses or gaps?* One-sided viewpoint, missing context, propaganda, translation issues, incompleteness, hindsight, small sample. (Limitation is **not** the same as "it''s a bad source" — every source has limitations.)

**How to apply it (method):**
1. Read/observe the source carefully.
2. Establish **Origin** from the caption/attribution and content.
3. Infer **Purpose** from tone, language, imagery and intended audience.
4. Derive **Value** *from* origin and purpose (link them — don''t list generic values).
5. Derive **Limitation** *from* origin and purpose too.
6. Conclude with a judgement on reliability/usefulness **for a specific enquiry**.

**Worked mini-example.**
> *Source:* A stone inscription commissioned by a Chola king (c. 1010 CE) at the Brihadisvara temple, Thanjavur, listing his military conquests and temple donations.
- **Origin:** A royal inscription in stone, carved in Tamil, c. 1010 CE, at Thanjavur, commissioned by the Chola ruler — a **primary** source.
- **Purpose:** To glorify the king, record his piety and conquests, and legitimise his rule for subjects and posterity (intended audience: the public, priests, future rulers).
- **Value:** Excellent first-hand evidence of Chola self-image, administrative reach, religious patronage, place-names and the resources devoted to temple-building.
- **Limitation:** It is royal propaganda — it exaggerates victories, omits defeats and the peasant/ordinary perspective, and gives the *king''s* view, not an objective account.
- **Judgement:** Very useful for studying how Chola kings projected power and legitimacy, but unreliable as a neutral record of what actually happened in battle.

**Command-term questions:**
1. *(Recall)* **Identify** what each letter of OPVL stands for.
2. *(Apply)* **Analyse** the origin and purpose of a wartime propaganda poster and explain how each shapes its value and limitations.
3. *(Analyse/Evaluate)* Using OPVL, **evaluate** the value and limitations of the Chola royal inscription above for a historian studying ordinary medieval life.

---','{"1010":2,"full":1,"teaching":1,"entry":1,"the":18,"opvl":4,"method":2,"structured":1,"way":1,"evaluate":3,"any":1,"source":9,"stands":2,"for":7,"origin":8,"purpose":8,"value":7,"limitation":5,"backbone":1,"myp":1,"criterion":1,"analysis":1,"who":2,"made":2,"what":6,"when":1,"and":19,"where":1,"author":1,"type":1,"date":1,"place":2,"primary":2,"secondary":1,"you":1,"describe":1,"why":1,"was":2,"whom":1,"inform":1,"persuade":1,"record":3,"entertain":1,"glorify":2,"warn":1,"sell":1,"intended":3,"audience":3,"can":1,"historian":2,"usefully":1,"learn":1,"from":6,"flows":1,"eyewitness":1,"gives":2,"authentic":1,"first":2,"hand":2,"detail":1,"government":1,"poster":2,"reveals":1,"leaders":1,"wanted":1,"people":1,"believe":1,"are":1,"weaknesses":1,"gaps":1,"one":1,"sided":1,"viewpoint":1,"missing":1,"context":1,"propaganda":3,"translation":1,"issues":1,"incompleteness":1,"hindsight":1,"small":1,"sample":1,"not":2,"same":1,"bad":1,"every":1,"has":1,"limitations":3,"how":3,"apply":2,"read":1,"observe":1,"carefully":1,"establish":1,"caption":1,"attribution":1,"content":1,"infer":1,"tone":1,"language":1,"imagery":1,"derive":2,"link":1,"them":1,"don":1,"list":1,"generic":1,"values":1,"too":1,"conclude":1,"with":1,"judgement":2,"reliability":1,"usefulness":1,"specific":1,"enquiry":1,"worked":1,"mini":1,"example":1,"stone":2,"inscription":3,"commissioned":2,"chola":5,"king":3,"brihadisvara":1,"temple":3,"thanjavur":2,"listing":1,"his":3,"military":1,"conquests":2,"donations":1,"royal":3,"carved":1,"tamil":1,"ruler":1,"piety":1,"legitimise":1,"rule":1,"subjects":1,"posterity":1,"public":1,"priests":1,"future":1,"rulers":1,"excellent":1,"evidence":1,"self":1,"image":1,"administrative":1,"reach":1,"religious":1,"patronage":1,"names":1,"resources":1,"devoted":1,"building":1,"exaggerates":1,"victories":1,"omits":1,"defeats":1,"peasant":1,"ordinary":2,"perspective":1,"view":1,"objective":1,"account":1,"very":1,"useful":1,"studying":2,"kings":1,"projected":1,"power":1,"legitimacy":1,"but":1,"unreliable":1,"neutral":1,"actually":1,"happened":1,"battle":1,"command":1,"term":1,"questions":1,"recall":1,"identify":1,"each":2,"letter":1,"analyse":2,"wartime":1,"explain":1,"shapes":1,"its":1,"using":1,"above":1,"medieval":1,"life":1}'::jsonb),
('chunk_35e9ec95927f79a3f6','file_04bb580a3d99034261','history.md','UNIT 1: Rise and Fall of Empires','**Key Concept:** Systems
**Related Concepts:** Empire, Power/Governance, Causality, Significance
**Global Context:** Orientation in space and time
**Statement of Inquiry:** *The building and collapse of empires reveal how systems of power and governance rise, adapt and fail across time and place.*

**Inquiry Questions**
- *Factual:* What factors allowed empires such as the Gupta, Roman, Byzantine, Chola and Vijayanagara to form and expand?
- *Conceptual:* How do systems of governance sustain — and eventually undermine — imperial power?
- *Debatable:* Do empires collapse mainly because of internal weakness or external pressure?','{"unit":1,"rise":2,"and":9,"fall":1,"empires":4,"key":1,"concept":1,"systems":3,"related":1,"concepts":1,"empire":1,"power":3,"governance":3,"causality":1,"significance":1,"global":1,"context":1,"orientation":1,"space":1,"time":2,"statement":1,"inquiry":2,"the":2,"building":1,"collapse":2,"reveal":1,"how":2,"adapt":1,"fail":1,"across":1,"place":1,"questions":1,"factual":1,"what":1,"factors":1,"allowed":1,"such":1,"gupta":1,"roman":1,"byzantine":1,"chola":1,"vijayanagara":1,"form":1,"expand":1,"conceptual":1,"sustain":1,"eventually":1,"undermine":1,"imperial":1,"debatable":1,"mainly":1,"because":1,"internal":1,"weakness":1,"external":1,"pressure":1}'::jsonb),
('chunk_85bc03c6305009242c','file_04bb580a3d99034261','history.md','Chapter 1.1 — Why Empires Rise: Factors in Empire-Building','**Factual grounding.** An **empire** is a political unit in which a dominant centre (a state or people) rules over multiple territories and peoples, often of different cultures. Recurring factors that enable empire-building:
- **Military strength & technology** (organised armies, cavalry, war-elephants, siege craft, weapons).
- **Strong leadership & administration** (capable rulers, bureaucracy, tax systems, law codes).
- **Economic resources & trade** (fertile agriculture, control of trade routes, wealth to fund armies).
- **Geography** (defensible borders, rivers, ports, strategic location).
- **Ideology & religion** (a unifying belief system or claim to divine/legitimate rule).
- **Communication & infrastructure** (roads, ports, a common language or coinage).

**Significance ("so what").** These factors form a repeatable pattern (a "system"), so historians can compare very different empires — Roman, Gupta, Chola — using the same analytical lens of causality.

**Perspective/interpretation note.** Rulers described expansion as bringing order, faith or civilisation; conquered peoples often experienced it as loss of freedom, tribute and cultural disruption. Both perspectives are part of the historical record.

**Misconception:** *"Empires were built mainly by military conquest."*
- *Why believed:* Battles and famous conquerors dominate popular stories.
- *Why wrong:* Conquest starts an empire, but **administration, trade, law and ideology** are what let it grow and last. The Guptas and Cholas expanded partly through alliances, trade and cultural prestige, not conquest alone.
- *Corrective:* Empire-building is multi-causal; military power alone rarely sustains an empire.

**Command-term questions:**
1. *(Recall)* **List** four factors that help an empire expand.
2. *(Apply)* **Explain** how control of trade routes could strengthen an empire, using one example.
3. *(Analyse/Evaluate)* **To what extent** is strong administration more important than military conquest in building a lasting empire?','{"chapter":1,"why":3,"empires":3,"rise":1,"factors":4,"empire":9,"building":4,"factual":1,"grounding":1,"political":1,"unit":1,"which":1,"dominant":1,"centre":1,"state":1,"people":1,"rules":1,"over":1,"multiple":1,"territories":1,"and":7,"peoples":2,"often":2,"different":2,"cultures":1,"recurring":1,"that":2,"enable":1,"military":4,"strength":1,"technology":1,"organised":1,"armies":2,"cavalry":1,"war":1,"elephants":1,"siege":1,"craft":1,"weapons":1,"strong":2,"leadership":1,"administration":3,"capable":1,"rulers":2,"bureaucracy":1,"tax":1,"systems":1,"law":2,"codes":1,"economic":1,"resources":1,"trade":5,"fertile":1,"agriculture":1,"control":2,"routes":2,"wealth":1,"fund":1,"geography":1,"defensible":1,"borders":1,"rivers":1,"ports":2,"strategic":1,"location":1,"ideology":2,"religion":1,"unifying":1,"belief":1,"system":2,"claim":1,"divine":1,"legitimate":1,"rule":1,"communication":1,"infrastructure":1,"roads":1,"common":1,"language":1,"coinage":1,"significance":1,"what":3,"these":1,"form":1,"repeatable":1,"pattern":1,"historians":1,"can":1,"compare":1,"very":1,"roman":1,"gupta":1,"chola":1,"using":2,"the":3,"same":1,"analytical":1,"lens":1,"causality":1,"perspective":1,"interpretation":1,"note":1,"described":1,"expansion":1,"bringing":1,"order":1,"faith":1,"civilisation":1,"conquered":1,"experienced":1,"loss":1,"freedom":1,"tribute":1,"cultural":2,"disruption":1,"both":1,"perspectives":1,"are":2,"part":1,"historical":1,"record":1,"misconception":1,"were":1,"built":1,"mainly":1,"conquest":4,"believed":1,"battles":1,"famous":1,"conquerors":1,"dominate":1,"popular":1,"stories":1,"wrong":1,"starts":1,"but":1,"let":1,"grow":1,"last":1,"guptas":1,"cholas":1,"expanded":1,"partly":1,"through":1,"alliances":1,"prestige":1,"not":1,"alone":2,"corrective":1,"multi":1,"causal":1,"power":1,"rarely":1,"sustains":1,"command":1,"term":1,"questions":1,"recall":1,"list":1,"four":1,"help":1,"expand":1,"apply":1,"explain":1,"how":1,"could":1,"strengthen":1,"one":1,"example":1,"analyse":1,"evaluate":1,"extent":1,"more":1,"important":1,"than":1,"lasting":1}'::jsonb),
('chunk_293b1364b0e05b90e4','file_04bb580a3d99034261','history.md','Chapter 1.2 — Medieval Empires and Governance','**Factual grounding.** In the medieval period (roughly 500–1500 CE), empires developed varied systems of **governance**: centralised bureaucracies (Byzantine, Chola), provincial/administrative divisions (Gupta *bhuktis* and *vishayas*; Chola *nadu*, *mandalam* and famous village self-government assemblies called **sabha/ur**), law and taxation systems, and the use of religion to legitimise rule. The **Byzantine** Empire codified Roman law under **Justinian I** (the *Corpus Juris Civilis*, c. 529–534 CE). The **Cholas** ran a remarkably organised state with local elected village councils recorded in inscriptions (e.g., **Uttaramerur**, 10th century).

**Significance.** Governance systems, not just conquest, decided how effectively an empire collected revenue, kept order and endured. Chola village self-government and Byzantine law codes are among the most studied medieval institutions.

**Perspective/interpretation note.** "Good governance" looks different depending on viewpoint: to the ruling elite it meant stability and revenue; to villagers it might mean tax burdens or, in the Chola case, genuine local participation.

**Misconception:** *"Medieval government was pure chaos with no real administration."*
- *Why believed:* The label "medieval" is popularly (and wrongly) linked with "backward" or "dark."
- *Why wrong:* Byzantine law, Chola village assemblies and Gupta provincial administration were sophisticated systems.
- *Corrective:* Medieval empires had complex, documented governance.

**Command-term questions:**
1. *(Recall)* **Identify** one governance feature of the Chola state and one of the Byzantine state.
2. *(Apply)* **Describe** how the Uttaramerur inscriptions help us understand Chola local government.
3. *(Analyse/Evaluate)* **Evaluate** how far religion was used as a tool of governance in one medieval empire.','{"500":1,"529":1,"534":1,"1500":1,"chapter":1,"medieval":7,"empires":3,"and":11,"governance":7,"factual":1,"grounding":1,"the":12,"period":1,"roughly":1,"developed":1,"varied":1,"systems":4,"centralised":1,"bureaucracies":1,"byzantine":5,"chola":7,"provincial":2,"administrative":1,"divisions":1,"gupta":2,"bhuktis":1,"vishayas":1,"nadu":1,"mandalam":1,"famous":1,"village":4,"self":2,"government":4,"assemblies":2,"called":1,"sabha":1,"law":4,"taxation":1,"use":1,"religion":2,"legitimise":1,"rule":1,"empire":3,"codified":1,"roman":1,"under":1,"justinian":1,"corpus":1,"juris":1,"civilis":1,"cholas":1,"ran":1,"remarkably":1,"organised":1,"state":3,"with":3,"local":3,"elected":1,"councils":1,"recorded":1,"inscriptions":2,"uttaramerur":2,"10th":1,"century":1,"significance":1,"not":1,"just":1,"conquest":1,"decided":1,"how":3,"effectively":1,"collected":1,"revenue":2,"kept":1,"order":1,"endured":1,"codes":1,"are":1,"among":1,"most":1,"studied":1,"institutions":1,"perspective":1,"interpretation":1,"note":1,"good":1,"looks":1,"different":1,"depending":1,"viewpoint":1,"ruling":1,"elite":1,"meant":1,"stability":1,"villagers":1,"might":1,"mean":1,"tax":1,"burdens":1,"case":1,"genuine":1,"participation":1,"misconception":1,"was":2,"pure":1,"chaos":1,"real":1,"administration":2,"why":2,"believed":1,"label":1,"popularly":1,"wrongly":1,"linked":1,"backward":1,"dark":1,"wrong":1,"were":1,"sophisticated":1,"corrective":1,"had":1,"complex":1,"documented":1,"command":1,"term":1,"questions":1,"recall":1,"identify":1,"one":3,"feature":1,"apply":1,"describe":1,"help":1,"understand":1,"analyse":1,"evaluate":2,"far":1,"used":1,"tool":1}'::jsonb),
('chunk_c5db537b56299a9ad4','file_04bb580a3d99034261','history.md','Chapter 1.3 — Political Legacies and Their Evolution','**Factual grounding.** Empires leave **legacies** — institutions and ideas that outlive them. Roman legacy: **Roman law**, republican/administrative concepts, Latin, engineering (roads, aqueducts, arches). Byzantine legacy: preservation of Greco-Roman knowledge, **Justinian''s Code** (a foundation of later European law), Orthodox Christianity, and Cyrillic script''s spread. Gupta legacy: the decimal place-value number system and the concept of **zero**, advances in astronomy (Aryabhata) and Sanskrit literature (Kalidasa). Chola legacy: temple architecture, bronze sculpture, maritime and administrative models. These legacies **evolved** as later societies adapted them.

**Significance.** Studying legacies shows **continuity and change** — how the modern world inherited law, mathematics, art and governance from earlier empires.

**Perspective/interpretation note.** Legacies are selectively remembered; nations sometimes emphasise a glorious imperial past to build modern identity, which historians must read critically.

**Misconception:** *"When an empire falls, its influence disappears."*
- *Why believed:* "Fall" sounds like total erasure.
- *Why wrong:* Roman law, Gupta mathematics and Byzantine scholarship survived and shaped later civilisations.
- *Corrective:* Political and cultural legacies often outlast the empire itself.

**Command-term questions:**
1. *(Recall)* **State** two legacies of the Roman Empire.
2. *(Apply)* **Explain** how the Gupta contribution to mathematics still affects us today.
3. *(Analyse/Evaluate)* **To what extent** is the Byzantine Empire''s greatest legacy the preservation of earlier knowledge?','{"chapter":1,"political":2,"legacies":7,"and":11,"their":1,"evolution":1,"factual":1,"grounding":1,"empires":2,"leave":1,"institutions":1,"ideas":1,"that":1,"outlive":1,"them":2,"roman":5,"legacy":5,"law":4,"republican":1,"administrative":2,"concepts":1,"latin":1,"engineering":1,"roads":1,"aqueducts":1,"arches":1,"byzantine":3,"preservation":2,"greco":1,"knowledge":2,"justinian":1,"code":1,"foundation":1,"later":3,"european":1,"orthodox":1,"christianity":1,"cyrillic":1,"script":1,"spread":1,"gupta":3,"the":8,"decimal":1,"place":1,"value":1,"number":1,"system":1,"concept":1,"zero":1,"advances":1,"astronomy":1,"aryabhata":1,"sanskrit":1,"literature":1,"kalidasa":1,"chola":1,"temple":1,"architecture":1,"bronze":1,"sculpture":1,"maritime":1,"models":1,"these":1,"evolved":1,"societies":1,"adapted":1,"significance":1,"studying":1,"shows":1,"continuity":1,"change":1,"how":2,"modern":2,"world":1,"inherited":1,"mathematics":3,"art":1,"governance":1,"from":1,"earlier":2,"perspective":1,"interpretation":1,"note":1,"are":1,"selectively":1,"remembered":1,"nations":1,"sometimes":1,"emphasise":1,"glorious":1,"imperial":1,"past":1,"build":1,"identity":1,"which":1,"historians":1,"must":1,"read":1,"critically":1,"misconception":1,"when":1,"empire":4,"falls":1,"its":1,"influence":1,"disappears":1,"why":2,"believed":1,"fall":1,"sounds":1,"like":1,"total":1,"erasure":1,"wrong":1,"scholarship":1,"survived":1,"shaped":1,"civilisations":1,"corrective":1,"cultural":1,"often":1,"outlast":1,"itself":1,"command":1,"term":1,"questions":1,"recall":1,"state":1,"two":1,"apply":1,"explain":1,"contribution":1,"still":1,"affects":1,"today":1,"analyse":1,"evaluate":1,"what":1,"extent":1,"greatest":1}'::jsonb),
('chunk_6547e5c62f28a89291','file_04bb580a3d99034261','history.md','Chapter 1.4 — Why Empires Fall: Causes of Collapse','**Factual grounding.** Empires collapse through combinations of causes:
- **Internal:** weak/corrupt leadership, succession disputes, civil war, economic decline, overtaxation, overextension, administrative breakdown, social unrest.
- **External:** invasions and migrations, military defeat, pressure from rival powers.
- **Environmental/economic:** plague, famine, climate stress, disrupted trade, inflation (Rome debased its coinage).
Examples: the **Western Roman Empire** fell in **476 CE** (deposition of Romulus Augustulus) after decades of overextension, economic strain, civil war and Germanic invasions. The **Gupta Empire** declined in the 6th century under **Huna (Hephthalite) invasions** and internal fragmentation. **Constantinople** (last Byzantine capital) fell to the **Ottomans in 1453**. **Vijayanagara** was crippled after the **Battle of Talikota, 1565**.

**Significance.** Collapse is rarely one cause; understanding multi-causality helps students avoid simplistic "one big reason" explanations — a core historical-thinking skill.

**Perspective/interpretation note.** "Fall" vs "transformation": some historians argue Rome didn''t so much "fall" as gradually transform into medieval kingdoms and the surviving Eastern (Byzantine) Empire.

**Misconception:** *"The Roman Empire fell suddenly in 476 CE."*
- *Why believed:* Textbooks give a single dramatic date.
- *Why wrong:* Decline unfolded over centuries; only the **Western** empire ended in 476, while the **Eastern (Byzantine)** empire continued for nearly another thousand years until 1453.
- *Corrective:* 476 marks the end of the *Western* Roman Empire, a gradual process, not a single collapse of "Rome."

**Command-term questions:**
1. *(Recall)* **Identify** two internal and two external causes of imperial collapse.
2. *(Apply)* **Explain** how economic problems contributed to the fall of the Western Roman Empire.
3. *(Analyse/Evaluate)* **To what extent** do empires collapse because of internal weakness rather than external attack? Use two case studies.','{"476":4,"1453":2,"1565":1,"chapter":1,"why":3,"empires":3,"fall":4,"causes":3,"collapse":6,"factual":1,"grounding":1,"through":1,"combinations":1,"internal":4,"weak":1,"corrupt":1,"leadership":1,"succession":1,"disputes":1,"civil":2,"war":2,"economic":4,"decline":2,"overtaxation":1,"overextension":2,"administrative":1,"breakdown":1,"social":1,"unrest":1,"external":3,"invasions":3,"and":5,"migrations":1,"military":1,"defeat":1,"pressure":1,"from":1,"rival":1,"powers":1,"environmental":1,"plague":1,"famine":1,"climate":1,"stress":1,"disrupted":1,"trade":1,"inflation":1,"rome":3,"debased":1,"its":1,"coinage":1,"examples":1,"the":13,"western":4,"roman":4,"empire":8,"fell":3,"deposition":1,"romulus":1,"augustulus":1,"after":2,"decades":1,"strain":1,"germanic":1,"gupta":1,"declined":1,"6th":1,"century":1,"under":1,"huna":1,"hephthalite":1,"fragmentation":1,"constantinople":1,"last":1,"byzantine":3,"capital":1,"ottomans":1,"vijayanagara":1,"was":1,"crippled":1,"battle":1,"talikota":1,"significance":1,"rarely":1,"one":2,"cause":1,"understanding":1,"multi":1,"causality":1,"helps":1,"students":1,"avoid":1,"simplistic":1,"big":1,"reason":1,"explanations":1,"core":1,"historical":1,"thinking":1,"skill":1,"perspective":1,"interpretation":1,"note":1,"transformation":1,"some":1,"historians":1,"argue":1,"didn":1,"much":1,"gradually":1,"transform":1,"into":1,"medieval":1,"kingdoms":1,"surviving":1,"eastern":2,"misconception":1,"suddenly":1,"believed":1,"textbooks":1,"give":1,"single":2,"dramatic":1,"date":1,"wrong":1,"unfolded":1,"over":1,"centuries":1,"only":1,"ended":1,"while":1,"continued":1,"for":1,"nearly":1,"another":1,"thousand":1,"years":1,"until":1,"corrective":1,"marks":1,"end":1,"gradual":1,"process":1,"not":1,"command":1,"term":1,"questions":1,"recall":1,"identify":1,"two":3,"imperial":1,"apply":1,"explain":1,"how":1,"problems":1,"contributed":1,"analyse":1,"evaluate":1,"what":1,"extent":1,"because":1,"weakness":1,"rather":1,"than":1,"attack":1,"use":1,"case":1,"studies":1}'::jsonb),
('chunk_9a5a5a5e7791c48e51','file_04bb580a3d99034261','history.md','Chapter 1.5 — The Rise of Feudalism in the Medieval Period','**Factual grounding.** After the Western Roman Empire''s collapse, centralised authority in Western Europe weakened. **Feudalism** emerged (roughly 9th–13th centuries) as a decentralised system of mutual obligations: a **king** granted land (**fiefs**) to **lords/nobles** in exchange for military service and loyalty; lords gave protection and land use to **vassals/knights**; at the base, **peasants/serfs** worked the land (the **manor**) in exchange for protection, but were tied to it. It was reinforced by the manorial economy and the Church.

**Significance.** Feudalism was the political and social answer to the loss of imperial security — a direct **consequence** of Rome''s fall and a key feature of medieval Europe. It shaped land, law, warfare and class for centuries.

**Perspective/interpretation note.** From a lord''s view feudalism provided order and service; from a serf''s view it meant obligation and limited freedom. Modern historians debate whether "feudalism" is even a single, coherent system or a label imposed later.

**Misconception:** *"Feudalism was a single, uniform system planned across all of Europe."*
- *Why believed:* Neat pyramid diagrams make it look designed and universal.
- *Why wrong:* It developed unevenly, varied by region, and the tidy "pyramid" is a later simplification.
- *Corrective:* Feudalism was a loose, evolving set of local arrangements, not a planned, identical system everywhere.

**Command-term questions:**
1. *(Recall)* **List** the main levels of feudal society from top to bottom.
2. *(Apply)* **Explain** how the fall of the Western Roman Empire helped feudalism develop.
3. *(Analyse/Evaluate)* **Evaluate** the claim that feudalism benefited lords far more than peasants.','{"chapter":1,"the":15,"rise":1,"feudalism":9,"medieval":2,"period":1,"factual":1,"grounding":1,"after":1,"western":3,"roman":2,"empire":2,"collapse":1,"centralised":1,"authority":1,"europe":3,"weakened":1,"emerged":1,"roughly":1,"9th":1,"13th":1,"centuries":2,"decentralised":1,"system":4,"mutual":1,"obligations":1,"king":1,"granted":1,"land":4,"fiefs":1,"lords":3,"nobles":1,"exchange":2,"for":3,"military":1,"service":2,"and":10,"loyalty":1,"gave":1,"protection":2,"use":1,"vassals":1,"knights":1,"base":1,"peasants":2,"serfs":1,"worked":1,"manor":1,"but":1,"were":1,"tied":1,"was":4,"reinforced":1,"manorial":1,"economy":1,"church":1,"significance":1,"political":1,"social":1,"answer":1,"loss":1,"imperial":1,"security":1,"direct":1,"consequence":1,"rome":1,"fall":2,"key":1,"feature":1,"shaped":1,"law":1,"warfare":1,"class":1,"perspective":1,"interpretation":1,"note":1,"from":3,"lord":1,"view":2,"provided":1,"order":1,"serf":1,"meant":1,"obligation":1,"limited":1,"freedom":1,"modern":1,"historians":1,"debate":1,"whether":1,"even":1,"single":2,"coherent":1,"label":1,"imposed":1,"later":2,"misconception":1,"uniform":1,"planned":2,"across":1,"all":1,"why":2,"believed":1,"neat":1,"pyramid":2,"diagrams":1,"make":1,"look":1,"designed":1,"universal":1,"wrong":1,"developed":1,"unevenly":1,"varied":1,"region":1,"tidy":1,"simplification":1,"corrective":1,"loose":1,"evolving":1,"set":1,"local":1,"arrangements":1,"not":1,"identical":1,"everywhere":1,"command":1,"term":1,"questions":1,"recall":1,"list":1,"main":1,"levels":1,"feudal":1,"society":1,"top":1,"bottom":1,"apply":1,"explain":1,"how":1,"helped":1,"develop":1,"analyse":1,"evaluate":2,"claim":1,"that":1,"benefited":1,"far":1,"more":1,"than":1}'::jsonb),
('chunk_5b96515e218fb6dfe3','file_04bb580a3d99034261','history.md','Chapter 1.6 — Empire Case Study Profiles','Below are compact profiles for each required case study. Each covers **dates, location, rise factors, governance, achievements, and causes of decline.**','{"chapter":1,"empire":1,"case":2,"study":2,"profiles":2,"below":1,"are":1,"compact":1,"for":1,"each":2,"required":1,"covers":1,"dates":1,"location":1,"rise":1,"factors":1,"governance":1,"achievements":1,"and":1,"causes":1,"decline":1}'::jsonb),
('chunk_895c87d320568cee9b','file_04bb580a3d99034261','history.md','Gupta Empire','- **Dates:** c. 320 CE – c. 550 CE (often called India''s "Golden Age").
- **Location:** Northern India, centred on the Ganges plain; capital **Pataliputra**.
- **Rise factors:** Founded by **Chandragupta I**; expansion under **Samudragupta** (conquests) and **Chandragupta II / Vikramaditya**; strong agriculture, trade wealth, capable rulers.
- **Governance:** Comparatively decentralised; provinces (*bhuktis*) under governors, districts (*vishayas*); lighter central control than the earlier Mauryas; revenue from land tax and trade.
- **Achievements:** Decimal system and the concept of **zero**; **Aryabhata** (astronomy/mathematics, c. 499 CE); **Kalidasa** (Sanskrit literature); advances in medicine and metallurgy (the rust-resistant **Iron Pillar of Delhi**); flourishing art and temple architecture.
- **Causes of decline:** **Huna (Hephthalite) invasions** from the northwest, weakening later rulers, loss of revenue and provincial fragmentation by the mid-6th century.','{"320":1,"499":1,"550":1,"gupta":1,"empire":1,"dates":1,"often":1,"called":1,"india":2,"golden":1,"age":1,"location":1,"northern":1,"centred":1,"the":6,"ganges":1,"plain":1,"capital":1,"pataliputra":1,"rise":1,"factors":1,"founded":1,"chandragupta":2,"expansion":1,"under":2,"samudragupta":1,"conquests":1,"and":6,"vikramaditya":1,"strong":1,"agriculture":1,"trade":2,"wealth":1,"capable":1,"rulers":2,"governance":1,"comparatively":1,"decentralised":1,"provinces":1,"bhuktis":1,"governors":1,"districts":1,"vishayas":1,"lighter":1,"central":1,"control":1,"than":1,"earlier":1,"mauryas":1,"revenue":2,"from":2,"land":1,"tax":1,"achievements":1,"decimal":1,"system":1,"concept":1,"zero":1,"aryabhata":1,"astronomy":1,"mathematics":1,"kalidasa":1,"sanskrit":1,"literature":1,"advances":1,"medicine":1,"metallurgy":1,"rust":1,"resistant":1,"iron":1,"pillar":1,"delhi":1,"flourishing":1,"art":1,"temple":1,"architecture":1,"causes":1,"decline":1,"huna":1,"hephthalite":1,"invasions":1,"northwest":1,"weakening":1,"later":1,"loss":1,"provincial":1,"fragmentation":1,"mid":1,"6th":1,"century":1}'::jsonb),
('chunk_f9b0744883b66c6b82','file_04bb580a3d99034261','history.md','Roman Empire','- **Dates:** Empire from **27 BCE** (Augustus) ; Western Empire fell **476 CE**; (Republic preceded it from 509 BCE).
- **Location:** Centred on Rome/Italy, spanning the Mediterranean — Europe, North Africa, the Near East.
- **Rise factors:** Disciplined **legions**, engineering, expansion via conquest and alliances, integration through **citizenship**, roads and trade.
- **Governance:** Emperor at the head; provinces run by governors; codified **Roman law**; professional army; extensive infrastructure (roads, aqueducts).
- **Achievements:** Roman law, engineering (roads, aqueducts, concrete, the arch), Latin language, urban planning, a long period of relative peace (**Pax Romana**, c. 27 BCE–180 CE).
- **Causes of decline:** Political instability and civil wars, economic strain and **inflation/debased coinage**, overextension, division of the empire (**395 CE**), and **Germanic invasions**; Western Empire ended 476 CE.','{"180":1,"395":1,"476":2,"509":1,"roman":3,"empire":5,"dates":1,"from":2,"bce":3,"augustus":1,"western":2,"fell":1,"republic":1,"preceded":1,"location":1,"centred":1,"rome":1,"italy":1,"spanning":1,"the":5,"mediterranean":1,"europe":1,"north":1,"africa":1,"near":1,"east":1,"rise":1,"factors":1,"disciplined":1,"legions":1,"engineering":2,"expansion":1,"via":1,"conquest":1,"and":5,"alliances":1,"integration":1,"through":1,"citizenship":1,"roads":3,"trade":1,"governance":1,"emperor":1,"head":1,"provinces":1,"run":1,"governors":1,"codified":1,"law":2,"professional":1,"army":1,"extensive":1,"infrastructure":1,"aqueducts":2,"achievements":1,"concrete":1,"arch":1,"latin":1,"language":1,"urban":1,"planning":1,"long":1,"period":1,"relative":1,"peace":1,"pax":1,"romana":1,"causes":1,"decline":1,"political":1,"instability":1,"civil":1,"wars":1,"economic":1,"strain":1,"inflation":1,"debased":1,"coinage":1,"overextension":1,"division":1,"germanic":1,"invasions":1,"ended":1}'::jsonb),
('chunk_ad03a3d098d2c9e6af','file_04bb580a3d99034261','history.md','Byzantine Empire','- **Dates:** c. **330 CE** (Constantinople founded/dedicated by Constantine) – **1453 CE** (Ottoman conquest); i.e., the surviving Eastern Roman Empire.
- **Location:** Eastern Mediterranean; capital **Constantinople** (modern Istanbul), straddling Europe and Asia.
- **Rise factors:** Wealthy, defensible capital at a strategic trade crossroads; continuity of Roman institutions; strong walls; control of trade.
- **Governance:** Highly centralised bureaucracy; emperor with religious authority; **Justinian''s Code** (*Corpus Juris Civilis*, 529–534 CE) systematised Roman law; Orthodox Christianity closely tied to the state.
- **Achievements:** Preserved Greco-Roman knowledge; **Hagia Sophia** (completed 537 CE); Justinian''s legal code; art and mosaics; long survival as a Christian bulwark.
- **Causes of decline:** Wars with Persia and later Arabs and Turks; the **Fourth Crusade sack of Constantinople (1204)**; loss of territory; economic decline; final **Ottoman conquest in 1453**.','{"330":1,"529":1,"534":1,"537":1,"1204":1,"1453":2,"byzantine":1,"empire":2,"dates":1,"constantinople":3,"founded":1,"dedicated":1,"constantine":1,"ottoman":2,"conquest":2,"the":3,"surviving":1,"eastern":2,"roman":4,"location":1,"mediterranean":1,"capital":2,"modern":1,"istanbul":1,"straddling":1,"europe":1,"and":4,"asia":1,"rise":1,"factors":1,"wealthy":1,"defensible":1,"strategic":1,"trade":2,"crossroads":1,"continuity":1,"institutions":1,"strong":1,"walls":1,"control":1,"governance":1,"highly":1,"centralised":1,"bureaucracy":1,"emperor":1,"with":2,"religious":1,"authority":1,"justinian":2,"code":2,"corpus":1,"juris":1,"civilis":1,"systematised":1,"law":1,"orthodox":1,"christianity":1,"closely":1,"tied":1,"state":1,"achievements":1,"preserved":1,"greco":1,"knowledge":1,"hagia":1,"sophia":1,"completed":1,"legal":1,"art":1,"mosaics":1,"long":1,"survival":1,"christian":1,"bulwark":1,"causes":1,"decline":2,"wars":1,"persia":1,"later":1,"arabs":1,"turks":1,"fourth":1,"crusade":1,"sack":1,"loss":1,"territory":1,"economic":1,"final":1}'::jsonb),
('chunk_7a1b8c004c158a8249','file_04bb580a3d99034261','history.md','Imperial Cholas','- **Dates:** Imperial Chola period c. **850 CE – 1279 CE** (revived under Vijayalaya c. 850; peak c. 985–1120).
- **Location:** South India (Tamil region), Kaveri delta; capital **Thanjavur** (later Gangaikonda Cholapuram); a strong maritime empire reaching Sri Lanka and Southeast Asia.
- **Rise factors:** Fertile Kaveri agriculture, naval power, control of Indian Ocean trade; strong rulers **Rajaraja I** (r. 985–1014) and **Rajendra I** (r. 1014–1044).
- **Governance:** Well-organised administration; provinces (*mandalam*), districts and **nadu**; famous **village self-government** (elected assemblies — *sabha/ur*) recorded in the **Uttaramerur** inscriptions; land surveys and taxation.
- **Achievements:** **Brihadisvara Temple, Thanjavur** (completed c. 1010 CE, a UNESCO site); superb **bronze sculpture** (e.g., Nataraja); powerful navy; overseas expeditions to Srivijaya (Southeast Asia) under Rajendra I; spread of Tamil culture.
- **Causes of decline:** Rising power of rivals (Hoysalas, Pandyas), weakening central control and succession problems; the empire faded by the late 13th century (c. 1279).','{"850":2,"985":2,"1010":1,"1014":2,"1044":1,"1120":1,"1279":2,"imperial":2,"cholas":1,"dates":1,"chola":1,"period":1,"revived":1,"under":2,"vijayalaya":1,"peak":1,"location":1,"south":1,"india":1,"tamil":2,"region":1,"kaveri":2,"delta":1,"capital":1,"thanjavur":2,"later":1,"gangaikonda":1,"cholapuram":1,"strong":2,"maritime":1,"empire":2,"reaching":1,"sri":1,"lanka":1,"and":5,"southeast":2,"asia":2,"rise":1,"factors":1,"fertile":1,"agriculture":1,"naval":1,"power":2,"control":2,"indian":1,"ocean":1,"trade":1,"rulers":1,"rajaraja":1,"rajendra":2,"governance":1,"well":1,"organised":1,"administration":1,"provinces":1,"mandalam":1,"districts":1,"nadu":1,"famous":1,"village":1,"self":1,"government":1,"elected":1,"assemblies":1,"sabha":1,"recorded":1,"the":3,"uttaramerur":1,"inscriptions":1,"land":1,"surveys":1,"taxation":1,"achievements":1,"brihadisvara":1,"temple":1,"completed":1,"unesco":1,"site":1,"superb":1,"bronze":1,"sculpture":1,"nataraja":1,"powerful":1,"navy":1,"overseas":1,"expeditions":1,"srivijaya":1,"spread":1,"culture":1,"causes":1,"decline":1,"rising":1,"rivals":1,"hoysalas":1,"pandyas":1,"weakening":1,"central":1,"succession":1,"problems":1,"faded":1,"late":1,"13th":1,"century":1}'::jsonb);