INSERT INTO syllabus_chunks (id, file_id, file_name, heading, body, tf) VALUES
('chunk_e3cc11f552b5b85c6c','file_162fce15bbe62004d5','geography.md','MYP Individuals & Societies Assessment Criteria','Each criterion is marked out of 8 (levels 1–8) using published rubrics.

| Criterion | Title | What it assesses |
|-----------|-------|------------------|
| **A** | Knowing and understanding | Use terminology in context; demonstrate knowledge and understanding of content and concepts through descriptions, explanations and examples. |
| **B** | Investigating | Formulate a clear research question; develop and follow an action plan; collect and record information; reflect on the process. |
| **C** | Communicating | Communicate information and ideas with a clear structure; organise information appropriately; document sources correctly. |
| **D** | Thinking critically | Analyse concepts, issues, models and arguments; interpret and evaluate sources (OPVL); recognise different perspectives and their implications; synthesise information to make arguments. |','{"myp":1,"individuals":1,"societies":1,"assessment":1,"criteria":1,"each":1,"criterion":2,"marked":1,"out":1,"levels":1,"using":1,"published":1,"rubrics":1,"title":1,"what":1,"assesses":1,"knowing":1,"and":10,"understanding":2,"use":1,"terminology":1,"context":1,"demonstrate":1,"knowledge":1,"content":1,"concepts":2,"through":1,"descriptions":1,"explanations":1,"examples":1,"investigating":1,"formulate":1,"clear":2,"research":1,"question":1,"develop":1,"follow":1,"action":1,"plan":1,"collect":1,"record":1,"information":4,"reflect":1,"the":1,"process":1,"communicating":1,"communicate":1,"ideas":1,"with":1,"structure":1,"organise":1,"appropriately":1,"document":1,"sources":2,"correctly":1,"thinking":1,"critically":1,"analyse":1,"issues":1,"models":1,"arguments":2,"interpret":1,"evaluate":1,"opvl":1,"recognise":1,"different":1,"perspectives":1,"their":1,"implications":1,"synthesise":1,"make":1}'::jsonb),
('chunk_6f882cdd206375b32c','file_162fce15bbe62004d5','geography.md','I&S Related Concepts (used throughout the year)','- **Causality** (cause and effect) — why biomes, poverty or scarcity occur.
- **Processes** — soil formation, nutrient cycling, the water cycle, development.
- **Sustainability** — meeting present needs without harming the future.
- **Resources** — natural, human and man-made means of meeting needs.
- **Disparity / equity** — the North–South divide, inequality, uneven development.
- **Perspective** — different stakeholders view resource use and development differently.
- **Globalization, power, culture, cooperation** — supporting concepts used in Units 2–3.','{"related":1,"concepts":2,"used":2,"throughout":1,"the":4,"year":1,"causality":1,"cause":1,"and":3,"effect":1,"why":1,"biomes":1,"poverty":1,"scarcity":1,"occur":1,"processes":1,"soil":1,"formation":1,"nutrient":1,"cycling":1,"water":1,"cycle":1,"development":3,"sustainability":1,"meeting":2,"present":1,"needs":2,"without":1,"harming":1,"future":1,"resources":1,"natural":1,"human":1,"man":1,"made":1,"means":1,"disparity":1,"equity":1,"north":1,"south":1,"divide":1,"inequality":1,"uneven":1,"perspective":1,"different":1,"stakeholders":1,"view":1,"resource":1,"use":1,"differently":1,"globalization":1,"power":1,"culture":1,"cooperation":1,"supporting":1,"units":1}'::jsonb),
('chunk_70a036ba6aa328f41e','file_162fce15bbe62004d5','geography.md','MYP Key Concepts most used this year','**Systems, Global interactions, Change,** and **Time, place and space.**

---','{"myp":1,"key":1,"concepts":1,"most":1,"used":1,"this":1,"year":1,"systems":1,"global":1,"interactions":1,"change":1,"and":2,"time":1,"place":1,"space":1}'::jsonb),
('chunk_df2433553a2ef5c814','file_162fce15bbe62004d5','geography.md','UNIT 1: Environmental Regions and Societies','**Key Concept:** Systems
**Related Concepts:** Processes, Causality, Sustainability
**Global Context:** *Orientation in space and time* (natural landscapes and the relationships between people and the environments they inhabit).
**Statement of Inquiry:** *Climatic and physical processes create distinct environmental systems whose fragile balance shapes how societies adapt, survive and must conserve them.*

**Inquiry Questions**
- **Factual:** What are the world''s major biomes and where are they located?
- **Conceptual:** How do climate processes and pressure belts cause the distribution of biomes?
- **Debatable:** Should the survival of indigenous cultures matter more than the economic development of the biomes they live in?

---','{"unit":1,"environmental":2,"regions":1,"and":8,"societies":2,"key":1,"concept":1,"systems":2,"related":1,"concepts":1,"processes":3,"causality":1,"sustainability":1,"global":1,"context":1,"orientation":1,"space":1,"time":1,"natural":1,"landscapes":1,"the":7,"relationships":1,"between":1,"people":1,"environments":1,"they":3,"inhabit":1,"statement":1,"inquiry":2,"climatic":1,"physical":1,"create":1,"distinct":1,"whose":1,"fragile":1,"balance":1,"shapes":1,"how":2,"adapt":1,"survive":1,"must":1,"conserve":1,"them":1,"questions":1,"factual":1,"what":1,"are":2,"world":1,"major":1,"biomes":3,"where":1,"located":1,"conceptual":1,"climate":1,"pressure":1,"belts":1,"cause":1,"distribution":1,"debatable":1,"should":1,"survival":1,"indigenous":1,"cultures":1,"matter":1,"more":1,"than":1,"economic":1,"development":1,"live":1}'::jsonb),
('chunk_2c5ad4fbbef2fb1594','file_162fce15bbe62004d5','geography.md','Concept: Biome','**Definition:** A biome is a large-scale community of plants and animals adapted to a particular climate, spread across large regions of the Earth.
**Real-world example:** The Amazon in Brazil is part of the tropical rainforest biome; the Sahara in North Africa is part of the hot desert biome.
**Analogy:** A biome is like a "neighbourhood" of the natural world — every home (species) in it is built to suit the same climate "weather rules."
**Why it matters:** Biomes determine what can grow, what animals live there, how people make a living, and how vulnerable a region is to climate change.
**Key facts/data:**
- Biomes are defined mainly by **climate (temperature + precipitation)** and **vegetation**, not by country borders.
- Major biomes: tropical rainforest, taiga/coniferous forest, savanna, temperate grassland, hot desert, tundra, Mediterranean, temperate deciduous forest.
- Biomes generally form in **latitudinal bands** because temperature and rainfall change with latitude.
**Misconception:** *"A biome is the same as an ecosystem."* Believed because both involve plants, animals and environment. Wrong because an **ecosystem** is a smaller local unit (a single pond or forest patch) while a **biome** is a global-scale grouping of many similar ecosystems. Corrective: think biome = global category, ecosystem = local example within it.
**IB command-term questions:**
1. (Recall) **Define** the term "biome." 
2. (Apply) **Describe** how latitude influences the location of two named biomes.
3. (Analyse/Evaluate) **Analyse** why biome boundaries rarely match political (country) boundaries.','{"concept":1,"biome":10,"definition":1,"large":2,"scale":2,"community":1,"plants":2,"and":5,"animals":3,"adapted":1,"particular":1,"climate":4,"spread":1,"across":1,"regions":1,"the":10,"earth":1,"real":1,"world":2,"example":2,"amazon":1,"brazil":1,"part":2,"tropical":2,"rainforest":2,"sahara":1,"north":1,"africa":1,"hot":2,"desert":2,"analogy":1,"like":1,"neighbourhood":1,"natural":1,"every":1,"home":1,"species":1,"built":1,"suit":1,"same":2,"weather":1,"rules":1,"why":2,"matters":1,"biomes":5,"determine":1,"what":2,"can":1,"grow":1,"live":1,"there":1,"how":3,"people":1,"make":1,"living":1,"vulnerable":1,"region":1,"change":2,"key":1,"facts":1,"data":1,"are":1,"defined":1,"mainly":1,"temperature":2,"precipitation":1,"vegetation":1,"not":1,"country":2,"borders":1,"major":1,"taiga":1,"coniferous":1,"forest":3,"savanna":1,"temperate":2,"grassland":1,"tundra":1,"mediterranean":1,"deciduous":1,"generally":1,"form":1,"latitudinal":1,"bands":1,"because":3,"rainfall":1,"with":1,"latitude":2,"misconception":1,"ecosystem":3,"believed":1,"both":1,"involve":1,"environment":1,"wrong":1,"smaller":1,"local":2,"unit":1,"single":1,"pond":1,"patch":1,"while":1,"global":2,"grouping":1,"many":1,"similar":1,"ecosystems":1,"corrective":1,"think":1,"category":1,"within":1,"command":1,"term":2,"questions":1,"recall":1,"define":1,"apply":1,"describe":1,"influences":1,"location":1,"two":1,"named":1,"analyse":2,"evaluate":1,"boundaries":2,"rarely":1,"match":1,"political":1}'::jsonb),
('chunk_30806da3f8a4a837ac','file_162fce15bbe62004d5','geography.md','Concept: Global Pressure Belt System and Prevailing Winds','**Definition:** A pattern of alternating high- and low-pressure zones circling the Earth that controls where air rises (wet) and sinks (dry), driving the location of biomes; prevailing winds are the dominant direction winds blow in a region.
**Real-world example:** Rising air at the Equator (low pressure) produces the rain that feeds the Congo rainforest; sinking air around 30°N (high pressure) creates the Sahara Desert.
**Analogy:** The pressure belts are like a global conveyor belt of air — where the belt lifts air it "wrings out" rain; where it presses air down it "dries the towel."
**Why it matters:** Explains *why* deserts sit near 30° latitude and rainforests near the Equator — connecting physics to ecology.
**Key facts/data:**
- **Equatorial low (0°):** rising air, heavy rain → rainforests.
- **Subtropical high (~30° N/S):** sinking air, dry → hot deserts.
- **Subpolar low (~60°):** rising air, moderate rain → temperate forests/taiga.
- **Polar high (~90°):** sinking cold air, very dry → tundra/ice.
- Prevailing winds (e.g. **trade winds** near the tropics, **westerlies** in mid-latitudes) carry moisture and shape rainfall.
**Misconception:** *"It rains most at the poles because they are cold."* Believed because cold feels wet. Wrong: cold air holds little moisture and polar highs make air sink and dry — poles are technically "cold deserts." Corrective: rainfall depends on rising air and warmth, not coldness.
**IB command-term questions:**
1. (Recall) **State** what happens to air at the equatorial low-pressure belt.
2. (Apply) **Explain** how the subtropical high-pressure belt helps create hot deserts.
3. (Analyse/Evaluate) **Evaluate** the claim that pressure belts are the single most important cause of biome distribution.','{"concept":1,"global":2,"pressure":8,"belt":5,"system":1,"and":8,"prevailing":3,"winds":5,"definition":1,"pattern":1,"alternating":1,"high":5,"low":5,"zones":1,"circling":1,"the":17,"earth":1,"that":3,"controls":1,"where":3,"air":14,"rises":1,"wet":2,"sinks":1,"dry":4,"driving":1,"location":1,"biomes":1,"are":5,"dominant":1,"direction":1,"blow":1,"region":1,"real":1,"world":1,"example":1,"rising":4,"equator":2,"produces":1,"rain":4,"feeds":1,"congo":1,"rainforest":1,"sinking":3,"around":1,"creates":1,"sahara":1,"desert":1,"analogy":1,"belts":2,"like":1,"conveyor":1,"lifts":1,"wrings":1,"out":1,"presses":1,"down":1,"dries":1,"towel":1,"why":2,"matters":1,"explains":1,"deserts":4,"sit":1,"near":3,"latitude":1,"rainforests":2,"connecting":1,"physics":1,"ecology":1,"key":1,"facts":1,"data":1,"equatorial":2,"heavy":1,"subtropical":2,"hot":2,"subpolar":1,"moderate":1,"temperate":1,"forests":1,"taiga":1,"polar":2,"cold":5,"very":1,"tundra":1,"ice":1,"trade":1,"tropics":1,"westerlies":1,"mid":1,"latitudes":1,"carry":1,"moisture":2,"shape":1,"rainfall":2,"misconception":1,"rains":1,"most":2,"poles":2,"because":2,"they":1,"believed":1,"feels":1,"wrong":1,"holds":1,"little":1,"highs":1,"make":1,"sink":1,"technically":1,"corrective":1,"depends":1,"warmth":1,"not":1,"coldness":1,"command":1,"term":1,"questions":1,"recall":1,"state":1,"what":1,"happens":1,"apply":1,"explain":1,"how":1,"helps":1,"create":1,"analyse":1,"evaluate":2,"claim":1,"single":1,"important":1,"cause":1,"biome":1,"distribution":1}'::jsonb),
('chunk_be906c29aa04931fce','file_162fce15bbe62004d5','geography.md','Climate Zones — Comparison Table','| Climate zone | Temperature | Rainfall | Location example | Linked biome |
|--------------|-------------|----------|------------------|--------------|
| Equatorial | Hot all year (~27°C) | Very high, all year (>2000 mm) | Amazon Basin, Brazil | Tropical rainforest |
| Tropical monsoon | Hot | Very high in wet season, dry season present | India, SE Asia | Monsoon forest |
| Hot desert | Very hot days, cold nights | Very low (<250 mm) | Sahara, Africa | Hot desert |
| Savanna (tropical grassland) | Hot | Distinct wet & dry seasons | Serengeti, Tanzania | Savanna grassland |
| Temperate grassland | Warm summers, cold winters | Moderate | Prairies, USA; Steppes, Ukraine | Temperate grassland |
| Warm temperate (Mediterranean) | Hot dry summers, mild wet winters | Moderate, winter rain | Southern Spain, California | Mediterranean scrub |
| Cool temperate (Taiga) | Cold winters, short cool summers | Low–moderate | Siberia, Russia; Canada | Coniferous forest/taiga |
| Arctic (Tundra) | Freezing most of year | Very low | Northern Alaska, N. Canada | Tundra |

**Relationship between climate zones and biomes:** Each climate zone produces a matching biome because vegetation and animals evolve to survive that specific temperature and rainfall pattern. Climate is the *cause*; the biome is the *result*.

---','{"250":1,"2000":1,"climate":5,"zones":2,"comparison":1,"table":1,"zone":2,"temperature":2,"rainfall":2,"location":1,"example":1,"linked":1,"biome":3,"equatorial":1,"hot":7,"all":2,"year":3,"very":5,"high":2,"amazon":1,"basin":1,"brazil":1,"tropical":3,"rainforest":1,"monsoon":2,"wet":3,"season":2,"dry":3,"present":1,"india":1,"asia":1,"forest":2,"desert":2,"days":1,"cold":3,"nights":1,"low":3,"sahara":1,"africa":1,"savanna":2,"grassland":4,"distinct":1,"seasons":1,"serengeti":1,"tanzania":1,"temperate":4,"warm":2,"summers":3,"winters":3,"moderate":3,"prairies":1,"usa":1,"steppes":1,"ukraine":1,"mediterranean":2,"mild":1,"winter":1,"rain":1,"southern":1,"spain":1,"california":1,"scrub":1,"cool":2,"taiga":2,"short":1,"siberia":1,"russia":1,"canada":2,"coniferous":1,"arctic":1,"tundra":2,"freezing":1,"most":1,"northern":1,"alaska":1,"relationship":1,"between":1,"and":3,"biomes":1,"each":1,"produces":1,"matching":1,"because":1,"vegetation":1,"animals":1,"evolve":1,"survive":1,"that":1,"specific":1,"pattern":1,"the":3,"cause":1,"result":1}'::jsonb),
('chunk_2841f5f184ba3edc10','file_162fce15bbe62004d5','geography.md','Biome Profile: Tropical Rainforest','| Feature | Detail |
|---------|--------|
| **Location** | Around the Equator — Amazon (Brazil), Congo Basin (DR Congo), Southeast Asia (Indonesia, Malaysia). |
| **Climate** | Hot (~27°C) and wet all year (>2000 mm); no real seasons. |
| **Soil & nutrient cycling** | Soils (latosols) are surprisingly **poor/infertile**; nutrients are stored in the *vegetation*, not the soil. Fast **nutrient cycling**: dead leaves decompose rapidly in heat and humidity and are taken straight back up by plants. |
| **Plant adaptations** | Buttress roots for support in thin soil; drip-tip leaves to shed water; lianas and epiphytes climb to reach light; layered canopy. |
| **Animal adaptations** | Camouflage, prehensile tails, bright warning colours, nocturnal habits; many species living at different canopy levels. |
| **Indigenous lifestyle** | Peoples such as the **Yanomami (Amazon)** practise shifting cultivation, hunting, fishing and gathering — using the forest sustainably without permanently clearing it. |
| **Threats** | Deforestation for cattle ranching, soya, palm oil, logging, roads and mining. |
| **Global importance** | "Lungs of the Earth" — produces oxygen, absorbs CO₂, stores carbon, holds ~50% of the world''s biodiversity, drives the water cycle. |
| **Conservation** | Protected reserves/national parks, ecotourism, selective logging, agroforestry, debt-for-nature swaps, indigenous land rights, REDD+ carbon schemes. |

**Analogy:** The rainforest soil is like a bank account with almost no cash saved — all the "money" (nutrients) is constantly circulating in the "economy" of living plants.
**Why it matters:** Rainforests regulate global climate; losing them accelerates climate change and biodiversity loss.
**Misconception:** *"Rainforests have rich, fertile soil because they are so green and full of life."* Believed because lush vegetation suggests rich ground. Wrong: the soil is nutrient-poor; the richness is stored in the fast-cycling living biomass. Corrective: cut the forest down and the fertility disappears within a few years.
**IB command-term questions:**
1. (Recall) **List** three plant adaptations of the tropical rainforest.
2. (Apply) **Explain** why rainforest soils become infertile soon after clearing.
3. (Analyse/Evaluate) **Discuss** whether conservation of the Amazon should override national economic development. *(Related SDGs: 13 Climate Action, 15 Life on Land.)*','{"2000":1,"biome":1,"profile":1,"tropical":2,"rainforest":4,"feature":1,"detail":1,"location":1,"around":1,"the":18,"equator":1,"amazon":3,"brazil":1,"congo":2,"basin":1,"southeast":1,"asia":1,"indonesia":1,"malaysia":1,"climate":4,"hot":1,"and":9,"wet":1,"all":2,"year":1,"real":1,"seasons":1,"soil":6,"nutrient":3,"cycling":3,"soils":2,"latosols":1,"are":4,"surprisingly":1,"poor":2,"infertile":2,"nutrients":2,"stored":2,"vegetation":2,"not":1,"fast":2,"dead":1,"leaves":2,"decompose":1,"rapidly":1,"heat":1,"humidity":1,"taken":1,"straight":1,"back":1,"plants":2,"plant":2,"adaptations":3,"buttress":1,"roots":1,"for":3,"support":1,"thin":1,"drip":1,"tip":1,"shed":1,"water":2,"lianas":1,"epiphytes":1,"climb":1,"reach":1,"light":1,"layered":1,"canopy":2,"animal":1,"camouflage":1,"prehensile":1,"tails":1,"bright":1,"warning":1,"colours":1,"nocturnal":1,"habits":1,"many":1,"species":1,"living":3,"different":1,"levels":1,"indigenous":2,"lifestyle":1,"peoples":1,"such":1,"yanomami":1,"practise":1,"shifting":1,"cultivation":1,"hunting":1,"fishing":1,"gathering":1,"using":1,"forest":2,"sustainably":1,"without":1,"permanently":1,"clearing":2,"threats":1,"deforestation":1,"cattle":1,"ranching":1,"soya":1,"palm":1,"oil":1,"logging":2,"roads":1,"mining":1,"global":2,"importance":1,"lungs":1,"earth":1,"produces":1,"oxygen":1,"absorbs":1,"stores":1,"carbon":2,"holds":1,"world":1,"biodiversity":2,"drives":1,"cycle":1,"conservation":2,"protected":1,"reserves":1,"national":2,"parks":1,"ecotourism":1,"selective":1,"agroforestry":1,"debt":1,"nature":1,"swaps":1,"land":2,"rights":1,"redd":1,"schemes":1,"analogy":1,"like":1,"bank":1,"account":1,"with":1,"almost":1,"cash":1,"saved":1,"money":1,"constantly":1,"circulating":1,"economy":1,"why":2,"matters":1,"rainforests":2,"regulate":1,"losing":1,"them":1,"accelerates":1,"change":1,"loss":1,"misconception":1,"have":1,"rich":2,"fertile":1,"because":2,"they":1,"green":1,"full":1,"life":2,"believed":1,"lush":1,"suggests":1,"ground":1,"wrong":1,"richness":1,"biomass":1,"corrective":1,"cut":1,"down":1,"fertility":1,"disappears":1,"within":1,"few":1,"years":1,"command":1,"term":1,"questions":1,"recall":1,"list":1,"three":1,"apply":1,"explain":1,"become":1,"soon":1,"after":1,"analyse":1,"evaluate":1,"discuss":1,"whether":1,"should":1,"override":1,"economic":1,"development":1,"related":1,"sdgs":1,"action":1}'::jsonb),
('chunk_8971dd2a410d1a528a','file_162fce15bbe62004d5','geography.md','Biome Profile: Coniferous Forest / Taiga (Boreal Forest)','| Feature | Detail |
|---------|--------|
| **Location** | High northern latitudes (~50–60°N) — Siberia (Russia), Canada, Scandinavia. |
| **Climate** | Long, very cold winters; short, cool summers; low–moderate precipitation (much as snow). |
| **Soil** | Thin, acidic, nutrient-poor **podzols**; slow decomposition due to cold; needle litter adds acidity. |
| **Plant/animal adaptations** | Conifers (pine, spruce, fir) with needle leaves (reduce water loss, shed snow), conical shape, evergreen for quick growth in short summer; animals (bears, moose, lynx) with thick fur, hibernation, migration. |
| **Indigenous lifestyle** | Peoples such as the **Sami (Scandinavia)** herd reindeer; others hunt and trap, moving with the seasons. |
| **Threats** | Commercial logging, paper/pulp industry, mining, oil & gas, wildfires, acid rain, climate warming. |
| **Role in global climate** | Vast carbon store; the largest land biome; influences global oxygen and carbon balance. |
| **Conservation** | Sustainable forestry, replanting, protected areas, certification (FSC), fire management. |

**Analogy:** Conifer needles are like drinking straws with wax coats — they hold onto water through the frozen months when the ground water is locked as ice.
**Misconception:** *"Evergreen trees don''t lose their leaves."* Wrong: they shed needles gradually all year, just not all at once. Corrective: "evergreen" means never fully bare, not never dropping needles.
**IB command-term questions:**
1. (Recall) **Identify** two adaptations of coniferous trees.
2. (Apply) **Describe** how the Sami adapt their lifestyle to the taiga climate.
3. (Analyse/Evaluate) **Evaluate** the importance of the taiga as a global carbon store. *(SDG 13, 15.)*

---','{"biome":2,"profile":1,"coniferous":2,"forest":2,"taiga":3,"boreal":1,"feature":1,"detail":1,"location":1,"high":1,"northern":1,"latitudes":1,"siberia":1,"russia":1,"canada":1,"scandinavia":2,"climate":4,"long":1,"very":1,"cold":2,"winters":1,"short":2,"cool":1,"summers":1,"low":1,"moderate":1,"precipitation":1,"much":1,"snow":2,"soil":1,"thin":1,"acidic":1,"nutrient":1,"poor":1,"podzols":1,"slow":1,"decomposition":1,"due":1,"needle":2,"litter":1,"adds":1,"acidity":1,"plant":1,"animal":1,"adaptations":2,"conifers":1,"pine":1,"spruce":1,"fir":1,"with":4,"leaves":2,"reduce":1,"water":3,"loss":1,"shed":2,"conical":1,"shape":1,"evergreen":3,"for":1,"quick":1,"growth":1,"summer":1,"animals":1,"bears":1,"moose":1,"lynx":1,"thick":1,"fur":1,"hibernation":1,"migration":1,"indigenous":1,"lifestyle":2,"peoples":1,"such":1,"the":9,"sami":2,"herd":1,"reindeer":1,"others":1,"hunt":1,"and":2,"trap":1,"moving":1,"seasons":1,"threats":1,"commercial":1,"logging":1,"paper":1,"pulp":1,"industry":1,"mining":1,"oil":1,"gas":1,"wildfires":1,"acid":1,"rain":1,"warming":1,"role":1,"global":3,"vast":1,"carbon":3,"store":2,"largest":1,"land":1,"influences":1,"oxygen":1,"balance":1,"conservation":1,"sustainable":1,"forestry":1,"replanting":1,"protected":1,"areas":1,"certification":1,"fsc":1,"fire":1,"management":1,"analogy":1,"conifer":1,"needles":3,"are":1,"like":1,"drinking":1,"straws":1,"wax":1,"coats":1,"they":2,"hold":1,"onto":1,"through":1,"frozen":1,"months":1,"when":1,"ground":1,"locked":1,"ice":1,"misconception":1,"trees":2,"don":1,"lose":1,"their":2,"wrong":1,"gradually":1,"all":2,"year":1,"just":1,"not":2,"once":1,"corrective":1,"means":1,"never":2,"fully":1,"bare":1,"dropping":1,"command":1,"term":1,"questions":1,"recall":1,"identify":1,"two":1,"apply":1,"describe":1,"how":1,"adapt":1,"analyse":1,"evaluate":2,"importance":1,"sdg":1}'::jsonb),
('chunk_ed1fc7b1ed19cb7d8d','file_162fce15bbe62004d5','geography.md','Biome Profile: Tropical Grassland / Savanna','| Feature | Detail |
|---------|--------|
| **Location** | Between rainforests and hot deserts (~5–15° N/S) — Serengeti (Tanzania/Kenya), Sahel, northern Australia. |
| **Climate & seasonal change** | Hot all year; a distinct **wet season and dry season** — the defining feature. |
| **Soil** | Fairly fertile in places; dry-season fires return nutrients; can bake hard and crack. |
| **Adaptations** | Grasses grow fast in the wet season and lie dormant/deep-rooted in the dry; acacia trees have thorns and small waxy leaves; animals migrate to find water (wildebeest) or store fat. |
| **Threats** | Overgrazing, farming expansion, poaching, desertification, climate change. |
| **Ecological importance** | Supports the world''s largest herds and iconic megafauna; grazing/fire cycle maintains grassland. |
| **Conservation** | National parks (Serengeti NP), anti-poaching, controlled grazing, community conservancies, ecotourism. |

**Analogy:** Savanna grass is like a phone on low-power mode in the dry season — it shuts down above ground and stores energy in the roots until the "recharge" of the rains.
**Misconception:** *"Bushfires in the savanna are always disasters."* Wrong: periodic fire is natural and *necessary* — it recycles nutrients and stops forest taking over. Corrective: the savanna is a fire-adapted biome; suppressing all fire can harm it.
**IB command-term questions:**
1. (Recall) **State** the two seasons of the savanna.
2. (Apply) **Explain** how wildebeest are adapted to seasonal savanna change.
3. (Analyse/Evaluate) **Discuss** the role of fire in maintaining the savanna. *(SDG 15.)*','{"biome":2,"profile":1,"tropical":1,"grassland":2,"savanna":7,"feature":2,"detail":1,"location":1,"between":1,"rainforests":1,"and":9,"hot":2,"deserts":1,"serengeti":2,"tanzania":1,"kenya":1,"sahel":1,"northern":1,"australia":1,"climate":2,"seasonal":2,"change":3,"all":2,"year":1,"distinct":1,"wet":2,"season":5,"dry":4,"the":14,"defining":1,"soil":1,"fairly":1,"fertile":1,"places":1,"fires":1,"return":1,"nutrients":2,"can":2,"bake":1,"hard":1,"crack":1,"adaptations":1,"grasses":1,"grow":1,"fast":1,"lie":1,"dormant":1,"deep":1,"rooted":1,"acacia":1,"trees":1,"have":1,"thorns":1,"small":1,"waxy":1,"leaves":1,"animals":1,"migrate":1,"find":1,"water":1,"wildebeest":2,"store":1,"fat":1,"threats":1,"overgrazing":1,"farming":1,"expansion":1,"poaching":2,"desertification":1,"ecological":1,"importance":1,"supports":1,"world":1,"largest":1,"herds":1,"iconic":1,"megafauna":1,"grazing":2,"fire":5,"cycle":1,"maintains":1,"conservation":1,"national":1,"parks":1,"anti":1,"controlled":1,"community":1,"conservancies":1,"ecotourism":1,"analogy":1,"grass":1,"like":1,"phone":1,"low":1,"power":1,"mode":1,"shuts":1,"down":1,"above":1,"ground":1,"stores":1,"energy":1,"roots":1,"until":1,"recharge":1,"rains":1,"misconception":1,"bushfires":1,"are":2,"always":1,"disasters":1,"wrong":1,"periodic":1,"natural":1,"necessary":1,"recycles":1,"stops":1,"forest":1,"taking":1,"over":1,"corrective":1,"adapted":2,"suppressing":1,"harm":1,"command":1,"term":1,"questions":1,"recall":1,"state":1,"two":1,"seasons":1,"apply":1,"explain":1,"how":1,"analyse":1,"evaluate":1,"discuss":1,"role":1,"maintaining":1,"sdg":1}'::jsonb),
('chunk_15f4f63a1a0d3a9d8f','file_162fce15bbe62004d5','geography.md','Biome Profile: Temperate Grassland','| Feature | Detail |
|---------|--------|
| **Location** | Mid-latitude continental interiors — Prairies (North America), Pampas (Argentina), Steppes (Ukraine/Central Asia), Veld (S. Africa). |
| **Climate** | Warm summers, cold winters; moderate rainfall (mostly in summer); no trees over much of the area. |
| **Soil & agriculture** | Deep, dark, very **fertile chernozem** soils rich in humus — among the best farmland on Earth ("breadbaskets"). |
| **Adaptations** | Grasses with deep, dense root mats; grazing animals (bison, pronghorn) with speed and herding; burrowing animals (prairie dogs). |
| **Indigenous lifestyle** | Plains peoples (e.g. **Native American Plains nations**) historically followed bison herds; Mongolian steppe herders are nomadic pastoralists. |
| **Threats** | Ploughing for cereals, overgrazing, soil erosion (Dust Bowl), urban spread. |
| **Economic importance** | Grow the world''s wheat, maize and support cattle ranching — vital to global food supply. |
| **Conservation** | Contour ploughing, crop rotation, shelter belts, protected prairie reserves, no-till farming. |

**Analogy:** Prairie roots form a mat like a woven carpet holding the soil — rip up the carpet (plough badly) and the wind blows the "floor" away, as in the 1930s Dust Bowl.
**Misconception:** *"Grasslands are empty, unused land."* Wrong: they are the planet''s most productive farmland and rich ecosystems. Corrective: "few trees" does not mean "unimportant."
**IB command-term questions:**
1. (Recall) **Name** two temperate grasslands and their continents.
2. (Apply) **Explain** why chernozem soils make grasslands important for agriculture.
3. (Analyse/Evaluate) **Analyse** the causes and consequences of the 1930s Dust Bowl. *(SDG 2, 15.)*

---','{"biome":1,"profile":1,"temperate":2,"grassland":1,"feature":1,"detail":1,"location":1,"mid":1,"latitude":1,"continental":1,"interiors":1,"prairies":1,"north":1,"america":1,"pampas":1,"argentina":1,"steppes":1,"ukraine":1,"central":1,"asia":1,"veld":1,"africa":1,"climate":1,"warm":1,"summers":1,"cold":1,"winters":1,"moderate":1,"rainfall":1,"mostly":1,"summer":1,"trees":2,"over":1,"much":1,"the":11,"area":1,"soil":3,"agriculture":2,"deep":2,"dark":1,"very":1,"fertile":1,"chernozem":2,"soils":2,"rich":2,"humus":1,"among":1,"best":1,"farmland":2,"earth":1,"breadbaskets":1,"adaptations":1,"grasses":1,"with":2,"dense":1,"root":1,"mats":1,"grazing":1,"animals":2,"bison":2,"pronghorn":1,"speed":1,"and":6,"herding":1,"burrowing":1,"prairie":3,"dogs":1,"indigenous":1,"lifestyle":1,"plains":2,"peoples":1,"native":1,"american":1,"nations":1,"historically":1,"followed":1,"herds":1,"mongolian":1,"steppe":1,"herders":1,"are":3,"nomadic":1,"pastoralists":1,"threats":1,"ploughing":2,"for":2,"cereals":1,"overgrazing":1,"erosion":1,"dust":3,"bowl":3,"urban":1,"spread":1,"economic":1,"importance":1,"grow":1,"world":1,"wheat":1,"maize":1,"support":1,"cattle":1,"ranching":1,"vital":1,"global":1,"food":1,"supply":1,"conservation":1,"contour":1,"crop":1,"rotation":1,"shelter":1,"belts":1,"protected":1,"reserves":1,"till":1,"farming":1,"analogy":1,"roots":1,"form":1,"mat":1,"like":1,"woven":1,"carpet":2,"holding":1,"rip":1,"plough":1,"badly":1,"wind":1,"blows":1,"floor":1,"away":1,"1930s":2,"misconception":1,"grasslands":3,"empty":1,"unused":1,"land":1,"wrong":1,"they":1,"planet":1,"most":1,"productive":1,"ecosystems":1,"corrective":1,"few":1,"does":1,"not":1,"mean":1,"unimportant":1,"command":1,"term":1,"questions":1,"recall":1,"name":1,"two":1,"their":1,"continents":1,"apply":1,"explain":1,"why":1,"make":1,"important":1,"analyse":2,"evaluate":1,"causes":1,"consequences":1,"sdg":1}'::jsonb),
('chunk_27b36907b909141216','file_162fce15bbe62004d5','geography.md','Biome Profile: Hot Desert','| Feature | Detail |
|---------|--------|
| **Location** | Around 30° N/S under subtropical high pressure — Sahara (Africa), Arabian, Thar (India), Australian outback. |
| **Climate** | Very hot days, cold nights; extreme temperature range; rainfall <250 mm/year, very unreliable. |
| **Soil** | Thin, sandy/stony, low organic matter, often salty; little vegetation to enrich it. |
| **Adaptations** | Plants: cacti store water, spines reduce loss and deter grazers, deep or wide roots, waxy skins. Animals: camels store fat, nocturnal habits, water conservation, light coloured fur. |
| **Indigenous lifestyle** | Nomads such as the **Tuareg (Sahara)** and **Bedouin (Arabia)** travel between water sources, herd camels/goats, use tents and light clothing. |
| **Threats & uniqueness** | Mining, oil extraction, over-abstraction of water, tourism, desertification at edges; unique adaptations found nowhere else. |
| **Conservation** | Protected reserves, sustainable water use, solar-energy projects, controlled grazing, anti-desertification tree planting (e.g. Great Green Wall). |

**Analogy:** A cactus is like a living water bottle with a spiky lid — it hoards every drop and defends it.
**Misconception:** *"Deserts are just lifeless seas of sand."* Wrong: most deserts are rocky, not sandy, and teem with specially adapted life. Corrective: deserts are defined by low rainfall, not by sand or by being lifeless.
**IB command-term questions:**
1. (Recall) **Define** a hot desert by its rainfall.
2. (Apply) **Describe** two adaptations of the camel to desert life.
3. (Analyse/Evaluate) **Evaluate** the benefits and drawbacks of large-scale solar projects in deserts. *(SDG 7, 15.)*','{"250":1,"biome":1,"profile":1,"hot":3,"desert":3,"feature":1,"detail":1,"location":1,"around":1,"under":1,"subtropical":1,"high":1,"pressure":1,"sahara":2,"africa":1,"arabian":1,"thar":1,"india":1,"australian":1,"outback":1,"climate":1,"very":2,"days":1,"cold":1,"nights":1,"extreme":1,"temperature":1,"range":1,"rainfall":3,"year":1,"unreliable":1,"soil":1,"thin":1,"sandy":2,"stony":1,"low":2,"organic":1,"matter":1,"often":1,"salty":1,"little":1,"vegetation":1,"enrich":1,"adaptations":3,"plants":1,"cacti":1,"store":2,"water":6,"spines":1,"reduce":1,"loss":1,"and":6,"deter":1,"grazers":1,"deep":1,"wide":1,"roots":1,"waxy":1,"skins":1,"animals":1,"camels":2,"fat":1,"nocturnal":1,"habits":1,"conservation":2,"light":2,"coloured":1,"fur":1,"indigenous":1,"lifestyle":1,"nomads":1,"such":1,"the":3,"tuareg":1,"bedouin":1,"arabia":1,"travel":1,"between":1,"sources":1,"herd":1,"goats":1,"use":2,"tents":1,"clothing":1,"threats":1,"uniqueness":1,"mining":1,"oil":1,"extraction":1,"over":1,"abstraction":1,"tourism":1,"desertification":2,"edges":1,"unique":1,"found":1,"nowhere":1,"else":1,"protected":1,"reserves":1,"sustainable":1,"solar":2,"energy":1,"projects":2,"controlled":1,"grazing":1,"anti":1,"tree":1,"planting":1,"great":1,"green":1,"wall":1,"analogy":1,"cactus":1,"like":1,"living":1,"bottle":1,"with":2,"spiky":1,"lid":1,"hoards":1,"every":1,"drop":1,"defends":1,"misconception":1,"deserts":4,"are":3,"just":1,"lifeless":2,"seas":1,"sand":2,"wrong":1,"most":1,"rocky":1,"not":2,"teem":1,"specially":1,"adapted":1,"life":2,"corrective":1,"defined":1,"being":1,"command":1,"term":1,"questions":1,"recall":1,"define":1,"its":1,"apply":1,"describe":1,"two":1,"camel":1,"analyse":1,"evaluate":2,"benefits":1,"drawbacks":1,"large":1,"scale":1,"sdg":1}'::jsonb),
('chunk_6ad2829e028363979c','file_162fce15bbe62004d5','geography.md','Biome Profile: Tundra','| Feature | Detail |
|---------|--------|
| **Location** | Far north (Arctic) — northern Alaska, northern Canada, northern Russia; also alpine tundra on high mountains. |
| **Climate** | Freezing for most of the year; short cool summer; very low precipitation ("cold desert"). |
| **Soil & permafrost** | Thin, waterlogged soil over **permafrost** (permanently frozen subsoil) that blocks drainage and root growth. |
| **Adaptations** | Plants: low-growing cushions and mosses, grow fast in short summer, hairy stems. Animals: thick fur/blubber, white winter camouflage, migration (caribou), hibernation. |
| **Vulnerability to climate change** | Warming thaws permafrost, releasing stored methane/CO₂ (a feedback loop); very fragile, slow to recover. |
| **Indigenous lifestyle** | The **Inuit** hunt seals, caribou and fish; historically use skins, sleds and detailed knowledge of ice and seasons. |
| **Threats** | Oil & gas extraction, pipelines, mining, climate warming, pollution. |
| **Conservation** | Protected wilderness, strict extraction limits, cutting global emissions, supporting indigenous stewardship. |

**Analogy:** Permafrost is like a frozen freezer floor beneath a thin thawed rug — water can''t drain through it, so the surface stays soggy and boggy in summer.
**Misconception:** *"Nothing lives in the tundra."* Wrong: it hosts caribou, arctic foxes, migrating birds and hardy plants. Corrective: life is sparse and specialised, not absent.
**IB command-term questions:**
1. (Recall) **Define** "permafrost."
2. (Apply) **Explain** how the Inuit adapt their lifestyle to the tundra.
3. (Analyse/Evaluate) **Analyse** why the tundra is especially vulnerable to climate change. *(SDG 13, 15.)*','{"biome":1,"profile":1,"tundra":5,"feature":1,"detail":1,"location":1,"far":1,"north":1,"arctic":2,"northern":3,"alaska":1,"canada":1,"russia":1,"also":1,"alpine":1,"high":1,"mountains":1,"climate":4,"freezing":1,"for":1,"most":1,"the":7,"year":1,"short":2,"cool":1,"summer":3,"very":2,"low":2,"precipitation":1,"cold":1,"desert":1,"soil":2,"permafrost":5,"thin":2,"waterlogged":1,"over":1,"permanently":1,"frozen":2,"subsoil":1,"that":1,"blocks":1,"drainage":1,"and":8,"root":1,"growth":1,"adaptations":1,"plants":2,"growing":1,"cushions":1,"mosses":1,"grow":1,"fast":1,"hairy":1,"stems":1,"animals":1,"thick":1,"fur":1,"blubber":1,"white":1,"winter":1,"camouflage":1,"migration":1,"caribou":3,"hibernation":1,"vulnerability":1,"change":2,"warming":2,"thaws":1,"releasing":1,"stored":1,"methane":1,"feedback":1,"loop":1,"fragile":1,"slow":1,"recover":1,"indigenous":2,"lifestyle":2,"inuit":2,"hunt":1,"seals":1,"fish":1,"historically":1,"use":1,"skins":1,"sleds":1,"detailed":1,"knowledge":1,"ice":1,"seasons":1,"threats":1,"oil":1,"gas":1,"extraction":2,"pipelines":1,"mining":1,"pollution":1,"conservation":1,"protected":1,"wilderness":1,"strict":1,"limits":1,"cutting":1,"global":1,"emissions":1,"supporting":1,"stewardship":1,"analogy":1,"like":1,"freezer":1,"floor":1,"beneath":1,"thawed":1,"rug":1,"water":1,"can":1,"drain":1,"through":1,"surface":1,"stays":1,"soggy":1,"boggy":1,"misconception":1,"nothing":1,"lives":1,"wrong":1,"hosts":1,"foxes":1,"migrating":1,"birds":1,"hardy":1,"corrective":1,"life":1,"sparse":1,"specialised":1,"not":1,"absent":1,"command":1,"term":1,"questions":1,"recall":1,"define":1,"apply":1,"explain":1,"how":1,"adapt":1,"their":1,"analyse":2,"evaluate":1,"why":1,"especially":1,"vulnerable":1,"sdg":1}'::jsonb),
('chunk_abd72f495f041927d7','file_162fce15bbe62004d5','geography.md','Biome Comparison Table (Unit 1 summary)','| Biome | Temperature | Rainfall | Soil | Key threat |
|-------|-------------|----------|------|-----------|
| Tropical rainforest | Hot all year | Very high | Poor (latosol) | Deforestation |
| Taiga | Cold winters | Low–moderate | Poor, acidic (podzol) | Logging |
| Savanna | Hot | Wet & dry seasons | Moderate | Overgrazing/desertification |
| Temperate grassland | Warm/cold seasons | Moderate | Very fertile (chernozem) | Ploughing/erosion |
| Hot desert | Very hot/cold nights | Very low | Thin, sandy | Water over-use |
| Tundra | Freezing | Very low | Frozen (permafrost) | Climate warming |

---','{"biome":2,"comparison":1,"table":1,"unit":1,"summary":1,"temperature":1,"rainfall":1,"soil":1,"key":1,"threat":1,"tropical":1,"rainforest":1,"hot":4,"all":1,"year":1,"very":5,"high":1,"poor":2,"latosol":1,"deforestation":1,"taiga":1,"cold":3,"winters":1,"low":3,"moderate":3,"acidic":1,"podzol":1,"logging":1,"savanna":1,"wet":1,"dry":1,"seasons":2,"overgrazing":1,"desertification":1,"temperate":1,"grassland":1,"warm":1,"fertile":1,"chernozem":1,"ploughing":1,"erosion":1,"desert":1,"nights":1,"thin":1,"sandy":1,"water":1,"over":1,"use":1,"tundra":1,"freezing":1,"frozen":1,"permafrost":1,"climate":1,"warming":1}'::jsonb),
('chunk_023644d2d80b55bde8','file_162fce15bbe62004d5','geography.md','UNIT 2: Resources and Environment','**Key Concept:** Change
**Related Concepts:** Resources, Sustainability, Processes
**Global Context:** *Globalization and sustainability* (how the consumption of finite resources connects communities and affects the future of the planet).
**Statement of Inquiry:** *As populations consume resources ever faster, only sustainable and circular use can prevent depletion and preserve the environment for future generations.*

**Inquiry Questions**
- **Factual:** What types of resources exist and how are they classified?
- **Conceptual:** How do consumption and population growth cause resource depletion?
- **Debatable:** Can a growing global economy ever be truly sustainable?

---','{"unit":1,"resources":5,"and":7,"environment":2,"key":1,"concept":1,"change":1,"related":1,"concepts":1,"sustainability":2,"processes":1,"global":2,"context":1,"globalization":1,"how":3,"the":4,"consumption":2,"finite":1,"connects":1,"communities":1,"affects":1,"future":2,"planet":1,"statement":1,"inquiry":2,"populations":1,"consume":1,"ever":2,"faster":1,"only":1,"sustainable":2,"circular":1,"use":1,"can":2,"prevent":1,"depletion":2,"preserve":1,"for":1,"generations":1,"questions":1,"factual":1,"what":1,"types":1,"exist":1,"are":1,"they":1,"classified":1,"conceptual":1,"population":1,"growth":1,"cause":1,"resource":1,"debatable":1,"growing":1,"economy":1,"truly":1}'::jsonb),
('chunk_34fabf835af02ced64','file_162fce15bbe62004d5','geography.md','Concept: Resource','**Definition:** A resource is anything useful to humans that helps satisfy a need or want.
**Real-world example:** Crude oil in Saudi Arabia, fertile soil in Ukraine, or the skills of software engineers in Bangalore are all resources.
**Analogy:** Resources are the "ingredients" a society cooks with — some are in the cupboard already (natural), some you make (man-made), some are the cook''s skill (human).
**Why it matters:** How wisely resources are classified and managed decides a country''s wealth and its environmental future.','{"concept":1,"resource":2,"definition":1,"anything":1,"useful":1,"humans":1,"that":1,"helps":1,"satisfy":1,"need":1,"want":1,"real":1,"world":1,"example":1,"crude":1,"oil":1,"saudi":1,"arabia":1,"fertile":1,"soil":1,"ukraine":1,"the":4,"skills":1,"software":1,"engineers":1,"bangalore":1,"are":5,"all":1,"resources":3,"analogy":1,"ingredients":1,"society":1,"cooks":1,"with":1,"some":3,"cupboard":1,"already":1,"natural":1,"you":1,"make":1,"man":1,"made":1,"cook":1,"skill":1,"human":1,"why":1,"matters":1,"how":1,"wisely":1,"classified":1,"and":2,"managed":1,"decides":1,"country":1,"wealth":1,"its":1,"environmental":1,"future":1}'::jsonb),
('chunk_8a386c195acccec19e','file_162fce15bbe62004d5','geography.md','Resource Classification Table','| Basis of classification | Types | Meaning | Example |
|--------------------------|-------|---------|---------|
| **Origin** | Natural | Provided by nature | Water, minerals, forests |
| | Human | People''s skills, labour, knowledge | Doctors, engineers |
| | Man-made (capital) | Made by people from natural resources | Buildings, machines, roads |
| **Usage/technology** | Conventional | Long-used, traditional | Coal, oil, firewood |
| | Non-conventional | Newer/alternative | Solar, wind, tidal, geothermal |
| **Renewability** | Renewable | Replaced naturally in a human lifetime | Solar, wind, water, forests |
| | Non-renewable | Finite; take millions of years to form | Coal, oil, gas, minerals |','{"resource":1,"classification":2,"table":1,"basis":1,"types":1,"meaning":1,"example":1,"origin":1,"natural":2,"provided":1,"nature":1,"water":2,"minerals":2,"forests":2,"human":2,"people":2,"skills":1,"labour":1,"knowledge":1,"doctors":1,"engineers":1,"man":1,"made":2,"capital":1,"from":1,"resources":1,"buildings":1,"machines":1,"roads":1,"usage":1,"technology":1,"conventional":2,"long":1,"used":1,"traditional":1,"coal":2,"oil":2,"firewood":1,"non":2,"newer":1,"alternative":1,"solar":2,"wind":2,"tidal":1,"geothermal":1,"renewability":1,"renewable":2,"replaced":1,"naturally":1,"lifetime":1,"finite":1,"take":1,"millions":1,"years":1,"form":1,"gas":1}'::jsonb),
('chunk_c2c58d9201776c3979','file_162fce15bbe62004d5','geography.md','Renewable vs Non-renewable — Advantages/Disadvantages','| | Advantages | Disadvantages |
|---|-----------|---------------|
| **Renewable** | Won''t run out; low/zero emissions; cleaner | Can be intermittent (no sun/wind); high set-up cost; land use |
| **Non-renewable** | Reliable, high energy density; established technology | Finite; pollution & CO₂; price volatility; depletion |','{"renewable":4,"non":2,"advantages":2,"disadvantages":2,"won":1,"run":1,"out":1,"low":1,"zero":1,"emissions":1,"cleaner":1,"can":1,"intermittent":1,"sun":1,"wind":1,"high":2,"set":1,"cost":1,"land":1,"use":1,"reliable":1,"energy":1,"density":1,"established":1,"technology":1,"finite":1,"pollution":1,"price":1,"volatility":1,"depletion":1}'::jsonb),
('chunk_49345c4bda6dc15858','file_162fce15bbe62004d5','geography.md','Concept: Resource Depletion','**Definition:** Using up a resource faster than it can be replaced, so its available amount shrinks.
**Real-world example:** Overfishing collapsed the Grand Banks cod stocks off Canada in the 1990s.
**Analogy:** Spending from a savings account without paying in — eventually the balance hits zero.
**Why it matters:** Depletion threatens future supply, raises prices and damages ecosystems.
**Misconception:** *"Renewable resources can never run out."* Wrong: renewables like forests, fish and groundwater *can* be depleted if used faster than they regenerate. Corrective: "renewable" means it *can* replace itself — but only if we don''t overuse it.
**IB command-term questions:**
1. (Recall) **Distinguish** between renewable and non-renewable resources.
2. (Apply) **Classify** solar power, coal, and a doctor''s skills by resource type.
3. (Analyse/Evaluate) **Evaluate** the claim that non-renewable resources should be abandoned immediately.

---','{"concept":1,"resource":3,"depletion":2,"definition":1,"using":1,"faster":2,"than":2,"can":4,"replaced":1,"its":1,"available":1,"amount":1,"shrinks":1,"real":1,"world":1,"example":1,"overfishing":1,"collapsed":1,"the":4,"grand":1,"banks":1,"cod":1,"stocks":1,"off":1,"canada":1,"1990s":1,"analogy":1,"spending":1,"from":1,"savings":1,"account":1,"without":1,"paying":1,"eventually":1,"balance":1,"hits":1,"zero":1,"why":1,"matters":1,"threatens":1,"future":1,"supply":1,"raises":1,"prices":1,"and":4,"damages":1,"ecosystems":1,"misconception":1,"renewable":5,"resources":3,"never":1,"run":1,"out":1,"wrong":1,"renewables":1,"like":1,"forests":1,"fish":1,"groundwater":1,"depleted":1,"used":1,"they":1,"regenerate":1,"corrective":1,"means":1,"replace":1,"itself":1,"but":1,"only":1,"don":1,"overuse":1,"command":1,"term":1,"questions":1,"recall":1,"distinguish":1,"between":1,"non":2,"apply":1,"classify":1,"solar":1,"power":1,"coal":1,"doctor":1,"skills":1,"type":1,"analyse":1,"evaluate":2,"claim":1,"that":1,"should":1,"abandoned":1,"immediately":1}'::jsonb),
('chunk_f38eb724bcd26d2f58','file_162fce15bbe62004d5','geography.md','Concept: Soil','**Definition:** Soil is the thin, living top layer of the Earth made of weathered rock, minerals, water, air and decayed organic matter (humus).
**Why soil is a resource:** It grows almost all our food, supports ecosystems, stores water and carbon, and filters water.
**Real-world example:** The fertile chernozem of Ukraine feeds much of the world''s wheat supply; degraded soil in the Sahel worsens food shortages.
**Analogy:** Soil is like a slow-baked cake — it takes centuries of "ingredients" and time to form a few centimetres, but minutes to ruin.
**Soil formation process:** Rock is broken down by **weathering** (physical, chemical, biological); over hundreds–thousands of years, plants, decomposers and climate add humus and structure to create soil layers (horizons). Forming ~1 cm can take 100+ years.
**Importance for agriculture & ecosystems:** Provides nutrients (nitrogen, phosphorus, potassium), anchors roots, holds water, hosts billions of organisms.
**Causes of soil erosion & degradation:** Deforestation, overgrazing, over-cultivation, wind and water erosion, chemical overuse, salinisation, urbanisation.
**Soil conservation measures:** Contour ploughing, terracing, crop rotation, cover crops, shelter belts/windbreaks, afforestation, adding organic matter, no-till farming.
**Why it matters:** Roughly a third of the world''s soil is already degraded; without conservation, food security collapses.
**Misconception:** *"Soil is just dead dirt."* Wrong: healthy soil is teeming with living organisms and is essentially non-renewable on a human timescale. Corrective: soil is a living, slowly-formed resource we must protect.
**IB command-term questions:**
1. (Recall) **List** three causes of soil erosion.
2. (Apply) **Describe** how contour ploughing reduces erosion.
3. (Analyse/Evaluate) **Discuss** why soil should be treated as a non-renewable resource. *(SDG 2, 15.)*

---','{"100":1,"concept":1,"soil":15,"definition":1,"the":6,"thin":1,"living":3,"top":1,"layer":1,"earth":1,"made":1,"weathered":1,"rock":2,"minerals":1,"water":5,"air":1,"and":8,"decayed":1,"organic":2,"matter":2,"humus":2,"why":3,"resource":3,"grows":1,"almost":1,"all":1,"our":1,"food":3,"supports":1,"ecosystems":2,"stores":1,"carbon":1,"filters":1,"real":1,"world":3,"example":1,"fertile":1,"chernozem":1,"ukraine":1,"feeds":1,"much":1,"wheat":1,"supply":1,"degraded":2,"sahel":1,"worsens":1,"shortages":1,"analogy":1,"like":1,"slow":1,"baked":1,"cake":1,"takes":1,"centuries":1,"ingredients":1,"time":1,"form":1,"few":1,"centimetres":1,"but":1,"minutes":1,"ruin":1,"formation":1,"process":1,"broken":1,"down":1,"weathering":1,"physical":1,"chemical":2,"biological":1,"over":2,"hundreds":1,"thousands":1,"years":2,"plants":1,"decomposers":1,"climate":1,"add":1,"structure":1,"create":1,"layers":1,"horizons":1,"forming":1,"can":1,"take":1,"importance":1,"for":1,"agriculture":1,"provides":1,"nutrients":1,"nitrogen":1,"phosphorus":1,"potassium":1,"anchors":1,"roots":1,"holds":1,"hosts":1,"billions":1,"organisms":2,"causes":2,"erosion":4,"degradation":1,"deforestation":1,"overgrazing":1,"cultivation":1,"wind":1,"overuse":1,"salinisation":1,"urbanisation":1,"conservation":2,"measures":1,"contour":2,"ploughing":2,"terracing":1,"crop":1,"rotation":1,"cover":1,"crops":1,"shelter":1,"belts":1,"windbreaks":1,"afforestation":1,"adding":1,"till":1,"farming":1,"matters":1,"roughly":1,"third":1,"already":1,"without":1,"security":1,"collapses":1,"misconception":1,"just":1,"dead":1,"dirt":1,"wrong":1,"healthy":1,"teeming":1,"with":1,"essentially":1,"non":2,"renewable":2,"human":1,"timescale":1,"corrective":1,"slowly":1,"formed":1,"must":1,"protect":1,"command":1,"term":1,"questions":1,"recall":1,"list":1,"three":1,"apply":1,"describe":1,"how":1,"reduces":1,"analyse":1,"evaluate":1,"discuss":1,"should":1,"treated":1,"sdg":1}'::jsonb),
('chunk_660d57597108d16418','file_162fce15bbe62004d5','geography.md','Concept: Depletion (causes and consequences)','**Definition:** Depletion is the reduction of a resource''s stock through consumption until it becomes scarce or exhausted.
**Real-world example:** Groundwater depletion in Punjab (India) and the near-drying of the Aral Sea from over-abstraction for cotton farming.
**Analogy:** Draining a bathtub faster than the tap fills it — soon it''s empty.
**Causes:**
- **Overconsumption** — high per-person use, especially in wealthy nations.
- **Population growth** — more people needing food, water, energy and materials.
- Waste, inefficiency and the throwaway (linear) economy.
**Consequences:**
- **On society:** rising prices, conflict over resources ("water wars"), poverty, migration, unemployment.
- **On environment:** habitat loss, pollution, biodiversity decline, climate change, desertification.
**Why it matters:** Understanding causes lets societies act before resources run out.
**Misconception:** *"Only poor, overpopulated countries cause resource depletion."* Wrong: wealthy nations with smaller populations often have far higher per-capita consumption and ecological footprints. Corrective: depletion is driven by *how much each person consumes* as much as by *how many people* there are.
**IB command-term questions:**
1. (Recall) **Define** resource depletion.
2. (Apply) **Explain** how population growth contributes to depletion.
3. (Analyse/Evaluate) **Evaluate** whether overconsumption or population growth is the bigger driver of depletion.

---','{"concept":1,"depletion":8,"causes":3,"and":5,"consequences":2,"definition":1,"the":6,"reduction":1,"resource":3,"stock":1,"through":1,"consumption":2,"until":1,"becomes":1,"scarce":1,"exhausted":1,"real":1,"world":1,"example":1,"groundwater":1,"punjab":1,"india":1,"near":1,"drying":1,"aral":1,"sea":1,"from":1,"over":2,"abstraction":1,"for":1,"cotton":1,"farming":1,"analogy":1,"draining":1,"bathtub":1,"faster":1,"than":1,"tap":1,"fills":1,"soon":1,"empty":1,"overconsumption":2,"high":1,"per":2,"person":2,"use":1,"especially":1,"wealthy":2,"nations":2,"population":3,"growth":3,"more":1,"people":2,"needing":1,"food":1,"water":2,"energy":1,"materials":1,"waste":1,"inefficiency":1,"throwaway":1,"linear":1,"economy":1,"society":1,"rising":1,"prices":1,"conflict":1,"resources":2,"wars":1,"poverty":1,"migration":1,"unemployment":1,"environment":1,"habitat":1,"loss":1,"pollution":1,"biodiversity":1,"decline":1,"climate":1,"change":1,"desertification":1,"why":1,"matters":1,"understanding":1,"lets":1,"societies":1,"act":1,"before":1,"run":1,"out":1,"misconception":1,"only":1,"poor":1,"overpopulated":1,"countries":1,"cause":1,"wrong":1,"with":1,"smaller":1,"populations":1,"often":1,"have":1,"far":1,"higher":1,"capita":1,"ecological":1,"footprints":1,"corrective":1,"driven":1,"how":3,"much":2,"each":1,"consumes":1,"many":1,"there":1,"are":1,"command":1,"term":1,"questions":1,"recall":1,"define":1,"apply":1,"explain":1,"contributes":1,"analyse":1,"evaluate":2,"whether":1,"bigger":1,"driver":1}'::jsonb),
('chunk_955e8b2f1fee7b6bc7','file_162fce15bbe62004d5','geography.md','Concept: Conservation','**Definition:** The careful management and protection of resources to prevent waste and depletion so they last for the future.
**Real-world example:** Germany''s recycling system (Green Dot) recovers a large share of packaging waste.
**Analogy:** Conservation is like budgeting pocket money so it lasts the whole month instead of the first day.
**Strategies — the 3 Rs:** **Reduce** (use less), **Reuse** (use again), **Recycle** (make into new products). Also **energy efficiency** (LED lighting, insulation, efficient appliances) and **alternative/renewable energy** (solar, wind, hydro).
**Why it matters:** Conservation slows depletion, cuts pollution and saves money.','{"concept":1,"conservation":3,"definition":1,"the":5,"careful":1,"management":1,"and":4,"protection":1,"resources":1,"prevent":1,"waste":2,"depletion":2,"they":1,"last":1,"for":1,"future":1,"real":1,"world":1,"example":1,"germany":1,"recycling":1,"system":1,"green":1,"dot":1,"recovers":1,"large":1,"share":1,"packaging":1,"analogy":1,"like":1,"budgeting":1,"pocket":1,"money":2,"lasts":1,"whole":1,"month":1,"instead":1,"first":1,"day":1,"strategies":1,"reduce":1,"use":2,"less":1,"reuse":1,"again":1,"recycle":1,"make":1,"into":1,"new":1,"products":1,"also":1,"energy":2,"efficiency":1,"led":1,"lighting":1,"insulation":1,"efficient":1,"appliances":1,"alternative":1,"renewable":1,"solar":1,"wind":1,"hydro":1,"why":1,"matters":1,"slows":1,"cuts":1,"pollution":1,"saves":1}'::jsonb),
('chunk_63f95ec464f4e2053f','file_162fce15bbe62004d5','geography.md','Concept: Linear vs Circular Economy','**Definition:** A **linear economy** follows "take → make → use → dispose." A **circular economy** keeps resources in use as long as possible by reusing, repairing, remanufacturing and recycling — designing out waste.
| | Linear economy | Circular economy |
|---|---------------|------------------|
| Model | Take–make–dispose | Reduce–reuse–recycle–regenerate |
| Waste | High | Minimised (waste = new input) |
| Resource use | One-way, wasteful | Looped, efficient |
| Sustainability | Low | High |
**Benefits of circular economy:** Less waste and pollution, resource security, new "green" jobs, lower emissions, cost savings.
**Case study (circular economy):** The **Netherlands** aims to be fully circular by 2050; the **Ellen MacArthur Foundation** promotes circular design; **Patagonia''s** "Worn Wear" repairs and resells clothing so garments loop back into use instead of landfill.
**Analogy:** Linear economy is a one-use paper plate; circular economy is a washable plate used again and again.
**Misconception:** *"Recycling alone makes an economy circular."* Wrong: recycling is only one loop and still uses energy; true circularity prioritises reducing and reusing first. Corrective: recycling is the last resort *after* reduce and reuse.
**IB command-term questions:**
1. (Recall) **State** the three Rs of conservation.
2. (Apply) **Compare** a linear and a circular economy.
3. (Analyse/Evaluate) **Evaluate** how a circular economy supports sustainable development.','{"2050":1,"concept":1,"linear":5,"circular":11,"economy":12,"definition":1,"follows":1,"take":2,"make":2,"use":5,"dispose":2,"keeps":1,"resources":1,"long":1,"possible":1,"reusing":2,"repairing":1,"remanufacturing":1,"and":8,"recycling":4,"designing":1,"out":1,"waste":4,"model":1,"reduce":2,"reuse":2,"recycle":1,"regenerate":1,"high":2,"minimised":1,"new":2,"input":1,"resource":2,"one":3,"way":1,"wasteful":1,"looped":1,"efficient":1,"sustainability":1,"low":1,"benefits":1,"less":1,"pollution":1,"security":1,"green":1,"jobs":1,"lower":1,"emissions":1,"cost":1,"savings":1,"case":1,"study":1,"the":4,"netherlands":1,"aims":1,"fully":1,"ellen":1,"macarthur":1,"foundation":1,"promotes":1,"design":1,"patagonia":1,"worn":1,"wear":1,"repairs":1,"resells":1,"clothing":1,"garments":1,"loop":2,"back":1,"into":1,"instead":1,"landfill":1,"analogy":1,"paper":1,"plate":2,"washable":1,"used":1,"again":2,"misconception":1,"alone":1,"makes":1,"wrong":1,"only":1,"still":1,"uses":1,"energy":1,"true":1,"circularity":1,"prioritises":1,"reducing":1,"first":1,"corrective":1,"last":1,"resort":1,"after":1,"command":1,"term":1,"questions":1,"recall":1,"state":1,"three":1,"conservation":1,"apply":1,"compare":1,"analyse":1,"evaluate":2,"how":1,"supports":1,"sustainable":1,"development":1}'::jsonb),
('chunk_c4563dd2d71cb53536','file_162fce15bbe62004d5','geography.md','Concept: Sustainable Development','**Definition:** Development that meets the needs of the present without compromising the ability of future generations to meet their own needs (Brundtland, 1987).
**Real-world example:** Costa Rica generates almost all its electricity from renewables while protecting its rainforests and growing ecotourism.
**Analogy:** Living off the interest of a bank account, not the capital — so the balance keeps producing forever.
**Key milestones:**
- **Earth Summit (Rio de Janeiro, 1992)** — a landmark UN conference on environment and development.
- **Agenda 21** — its global action plan for sustainable development in the 21st century.
**Three pillars of sustainability:**
| Pillar | Focus | Example |
|--------|-------|---------|
| Social | People, equity, health, education | Fair access to clean water |
| Economic | Jobs, growth, prosperity | Green industries |
| Environmental | Protecting ecosystems & resources | Cutting emissions, conserving forests |
**Balancing human needs with environmental protection:** Sustainable development seeks a middle path where the economy grows, people''s lives improve, *and* the environment is protected — none sacrificed for the others.
**Why it matters:** It is the guiding framework (and basis of the UN SDGs) for global policy today.
**Misconception:** *"Sustainable development means stopping all growth and development."* Wrong: it means developing *differently* — smarter, cleaner and fairer — not halting progress. Corrective: it balances growth with protection rather than ending growth.
**IB command-term questions:**
1. (Recall) **Define** sustainable development.
2. (Apply) **Describe** the three pillars of sustainability with an example of each.
3. (Analyse/Evaluate) **Discuss** the difficulty of balancing economic growth with environmental protection. *(Underpins all SDGs.)*

---','{"1987":1,"1992":1,"concept":1,"sustainable":5,"development":8,"definition":1,"that":1,"meets":1,"the":14,"needs":3,"present":1,"without":1,"compromising":1,"ability":1,"future":1,"generations":1,"meet":1,"their":1,"own":1,"brundtland":1,"real":1,"world":1,"example":3,"costa":1,"rica":1,"generates":1,"almost":1,"all":3,"its":3,"electricity":1,"from":1,"renewables":1,"while":1,"protecting":2,"rainforests":1,"and":6,"growing":1,"ecotourism":1,"analogy":1,"living":1,"off":1,"interest":1,"bank":1,"account":1,"not":2,"capital":1,"balance":1,"keeps":1,"producing":1,"forever":1,"key":1,"milestones":1,"earth":1,"summit":1,"rio":1,"janeiro":1,"landmark":1,"conference":1,"environment":2,"agenda":1,"global":2,"action":1,"plan":1,"for":3,"21st":1,"century":1,"three":2,"pillars":2,"sustainability":2,"pillar":1,"focus":1,"social":1,"people":2,"equity":1,"health":1,"education":1,"fair":1,"access":1,"clean":1,"water":1,"economic":2,"jobs":1,"growth":5,"prosperity":1,"green":1,"industries":1,"environmental":3,"ecosystems":1,"resources":1,"cutting":1,"emissions":1,"conserving":1,"forests":1,"balancing":2,"human":1,"with":4,"protection":3,"seeks":1,"middle":1,"path":1,"where":1,"economy":1,"grows":1,"lives":1,"improve":1,"protected":1,"none":1,"sacrificed":1,"others":1,"why":1,"matters":1,"guiding":1,"framework":1,"basis":1,"sdgs":2,"policy":1,"today":1,"misconception":1,"means":2,"stopping":1,"wrong":1,"developing":1,"differently":1,"smarter":1,"cleaner":1,"fairer":1,"halting":1,"progress":1,"corrective":1,"balances":1,"rather":1,"than":1,"ending":1,"command":1,"term":1,"questions":1,"recall":1,"define":1,"apply":1,"describe":1,"each":1,"analyse":1,"evaluate":1,"discuss":1,"difficulty":1,"underpins":1}'::jsonb),
('chunk_64ee248e83c8a49650','file_162fce15bbe62004d5','geography.md','UNIT 3: Policy and Governance','**Key Concept:** Global interactions
**Related Concepts:** Disparity, Power, Cooperation, Sustainability
**Global Context:** *Fairness and development* (rights and responsibilities; the relationship between resources, governance and inequality worldwide).
**Statement of Inquiry:** *Because development is uneven, cooperation between governments and international bodies is needed to manage resources fairly and reduce global disparities.*

**Inquiry Questions**
- **Factual:** How is development measured and where does the North–South divide lie?
- **Conceptual:** How do physical and human factors interact to cause uneven development?
- **Debatable:** Does international aid do more harm than good?

---','{"unit":1,"policy":1,"and":8,"governance":2,"key":1,"concept":1,"global":3,"interactions":1,"related":1,"concepts":1,"disparity":1,"power":1,"cooperation":2,"sustainability":1,"context":1,"fairness":1,"development":4,"rights":1,"responsibilities":1,"the":2,"relationship":1,"between":2,"resources":2,"inequality":1,"worldwide":1,"statement":1,"inquiry":2,"because":1,"uneven":2,"governments":1,"international":2,"bodies":1,"needed":1,"manage":1,"fairly":1,"reduce":1,"disparities":1,"questions":1,"factual":1,"how":2,"measured":1,"where":1,"does":2,"north":1,"south":1,"divide":1,"lie":1,"conceptual":1,"physical":1,"human":1,"factors":1,"interact":1,"cause":1,"debatable":1,"aid":1,"more":1,"harm":1,"than":1,"good":1}'::jsonb),
('chunk_72125ec8d95547dce4','file_162fce15bbe62004d5','geography.md','Concept: Development (growth vs development)','**Definition:** **Development** is the improvement in people''s quality of life — including economic wealth, social wellbeing and cultural opportunity. **Growth** is only the increase in the *size* of the economy (more output/income).
**Real-world example:** A country''s GDP may grow from an oil boom (growth), but if hospitals, schools and equality don''t improve, real development hasn''t happened.
**Analogy:** Growth is a plant getting taller; development is the plant getting healthier — stronger roots, fruit and flowers, not just height.
**Aspects of development:**
- **Economic** — income, jobs, industry, infrastructure.
- **Social** — health, education, life expectancy, clean water.
- **Cultural** — freedom, rights, arts, identity, participation.
**Why it matters:** Governments aim for development, not just growth, to genuinely improve lives.
**Misconception:** *"A rich country is automatically a developed country."* Wrong: wealth can be unequally shared; a country can be rich yet have poor health, education or rights. Corrective: development is about wellbeing for all, not just total money.
**IB command-term questions:**
1. (Recall) **Distinguish** between growth and development.
2. (Apply) **Describe** the economic, social and cultural aspects of development.
3. (Analyse/Evaluate) **Evaluate** whether economic growth always leads to development.

---','{"concept":1,"development":11,"growth":7,"definition":1,"the":6,"improvement":1,"people":1,"quality":1,"life":2,"including":1,"economic":4,"wealth":2,"social":3,"wellbeing":2,"and":5,"cultural":3,"opportunity":1,"only":1,"increase":1,"size":1,"economy":1,"more":1,"output":1,"income":2,"real":2,"world":1,"example":1,"country":4,"gdp":1,"may":1,"grow":1,"from":1,"oil":1,"boom":1,"but":1,"hospitals":1,"schools":1,"equality":1,"don":1,"improve":2,"hasn":1,"happened":1,"analogy":1,"plant":2,"getting":2,"taller":1,"healthier":1,"stronger":1,"roots":1,"fruit":1,"flowers":1,"not":3,"just":3,"height":1,"aspects":2,"jobs":1,"industry":1,"infrastructure":1,"health":2,"education":2,"expectancy":1,"clean":1,"water":1,"freedom":1,"rights":2,"arts":1,"identity":1,"participation":1,"why":1,"matters":1,"governments":1,"aim":1,"for":2,"genuinely":1,"lives":1,"misconception":1,"rich":2,"automatically":1,"developed":1,"wrong":1,"can":2,"unequally":1,"shared":1,"yet":1,"have":1,"poor":1,"corrective":1,"about":1,"all":1,"total":1,"money":1,"command":1,"term":1,"questions":1,"recall":1,"distinguish":1,"between":1,"apply":1,"describe":1,"analyse":1,"evaluate":2,"whether":1,"always":1,"leads":1}'::jsonb),
('chunk_7a63e14e59cd5c4389','file_162fce15bbe62004d5','geography.md','Concept: Physical Factors','**Definition:** Natural conditions of a place that help or hinder development.
- **Climate** — extreme climates (deserts, tropics with disease) can hinder farming and health; temperate climates often help.
- **Natural resources** — oil, minerals, fertile soil and water can boost development (e.g. oil wealth in the Gulf states).
**Analogy:** Physical factors are the "hand of cards" a country is dealt by nature.','{"concept":1,"physical":2,"factors":2,"definition":1,"natural":2,"conditions":1,"place":1,"that":1,"help":2,"hinder":2,"development":2,"climate":1,"extreme":1,"climates":2,"deserts":1,"tropics":1,"with":1,"disease":1,"can":2,"farming":1,"and":2,"health":1,"temperate":1,"often":1,"resources":1,"oil":2,"minerals":1,"fertile":1,"soil":1,"water":1,"boost":1,"wealth":1,"the":2,"gulf":1,"states":1,"analogy":1,"are":1,"hand":1,"cards":1,"country":1,"dealt":1,"nature":1}'::jsonb),
('chunk_69ad409591e6bc201a','file_162fce15bbe62004d5','geography.md','Concept: Human-made Factors','**Definition:** Human and economic conditions that shape development.
- **Population** — size, growth rate and structure. A very **high population** growth can strain jobs, food and services; too **low/ageing** a population can shrink the workforce. A balanced, educated population aids development.
- **Education** — a skilled workforce raises productivity and innovation.
- **Jobs** — stable employment reduces poverty and boosts income.
- **Trade** — **exports** (goods sold abroad), **imports** (goods bought in), and the **balance of trade** (exports minus imports). A trade surplus (exports > imports) brings in money; a deficit can create debt.
**How factors interact:** Factors combine and reinforce each other — e.g. a good climate → productive farming → income → schools → educated workers → industry → trade. A weakness in one (e.g. conflict or drought) can undermine the whole chain.
**Why it matters:** Development is never caused by one factor alone; understanding interaction guides better policy.
**Misconception:** *"Countries with lots of natural resources are always developed."* Wrong — the "resource curse": some resource-rich countries suffer conflict, corruption and inequality (e.g. DR Congo''s minerals). Corrective: resources help only when governance, education and fair trade turn them into wellbeing.
**IB command-term questions:**
1. (Recall) **Identify** two physical and two human factors affecting development.
2. (Apply) **Explain** how the balance of trade can affect a country''s development.
3. (Analyse/Evaluate) **Analyse** how physical and human factors interact to influence development.

---','{"concept":1,"human":4,"made":1,"factors":5,"definition":1,"and":11,"economic":1,"conditions":1,"that":1,"shape":1,"development":6,"population":4,"size":1,"growth":2,"rate":1,"structure":1,"very":1,"high":1,"can":5,"strain":1,"jobs":2,"food":1,"services":1,"too":1,"low":1,"ageing":1,"shrink":1,"the":5,"workforce":2,"balanced":1,"educated":2,"aids":1,"education":2,"skilled":1,"raises":1,"productivity":1,"innovation":1,"stable":1,"employment":1,"reduces":1,"poverty":1,"boosts":1,"income":2,"trade":6,"exports":3,"goods":2,"sold":1,"abroad":1,"imports":3,"bought":1,"balance":2,"minus":1,"surplus":1,"brings":1,"money":1,"deficit":1,"create":1,"debt":1,"how":3,"interact":2,"combine":1,"reinforce":1,"each":1,"other":1,"good":1,"climate":1,"productive":1,"farming":1,"schools":1,"workers":1,"industry":1,"weakness":1,"one":2,"conflict":2,"drought":1,"undermine":1,"whole":1,"chain":1,"why":1,"matters":1,"never":1,"caused":1,"factor":1,"alone":1,"understanding":1,"interaction":1,"guides":1,"better":1,"policy":1,"misconception":1,"countries":2,"with":1,"lots":1,"natural":1,"resources":2,"are":1,"always":1,"developed":1,"wrong":1,"resource":2,"curse":1,"some":1,"rich":1,"suffer":1,"corruption":1,"inequality":1,"congo":1,"minerals":1,"corrective":1,"help":1,"only":1,"when":1,"governance":1,"fair":1,"turn":1,"them":1,"into":1,"wellbeing":1,"command":1,"term":1,"questions":1,"recall":1,"identify":1,"two":2,"physical":2,"affecting":1,"apply":1,"explain":1,"affect":1,"country":1,"analyse":2,"evaluate":1,"influence":1}'::jsonb),
('chunk_5d9827de83e7866fd4','file_162fce15bbe62004d5','geography.md','Concept: Development Indicators','**Definition:** Statistics used to compare the level of development between places.','{"concept":1,"development":2,"indicators":1,"definition":1,"statistics":1,"used":1,"compare":1,"the":1,"level":1,"between":1,"places":1}'::jsonb),
('chunk_527e17919fca0c4dff','file_162fce15bbe62004d5','geography.md','Development Indicators Table','| Indicator | Full name | What it measures | Limitation |
|-----------|-----------|------------------|-----------|
| **GDP (per capita)** | Gross Domestic Product | Total value of goods & services ÷ population | Ignores inequality, informal economy, wellbeing |
| **HDI** | Human Development Index | Combines income, life expectancy & education (0–1) | Doesn''t measure freedom, environment or inequality |
| **Birth/death rate, life expectancy, literacy** | — | Social wellbeing | Single measures give a partial picture |

**Real-world example:** Norway has a very high HDI (~0.96); Niger has a low HDI (~0.4).
**Analogy:** Using one indicator is like judging a student on one test; HDI is like a report card combining several subjects.','{"development":2,"indicators":1,"table":1,"indicator":2,"full":1,"name":1,"what":1,"measures":2,"limitation":1,"gdp":1,"per":1,"capita":1,"gross":1,"domestic":1,"product":1,"total":1,"value":1,"goods":1,"services":1,"population":1,"ignores":1,"inequality":2,"informal":1,"economy":1,"wellbeing":2,"hdi":4,"human":1,"index":1,"combines":1,"income":1,"life":2,"expectancy":2,"education":1,"doesn":1,"measure":1,"freedom":1,"environment":1,"birth":1,"death":1,"rate":1,"literacy":1,"social":1,"single":1,"give":1,"partial":1,"picture":1,"real":1,"world":1,"example":1,"norway":1,"has":2,"very":1,"high":1,"niger":1,"low":1,"analogy":1,"using":1,"one":2,"like":2,"judging":1,"student":1,"test":1,"report":1,"card":1,"combining":1,"several":1,"subjects":1}'::jsonb);