INSERT INTO syllabus_chunks (id, file_id, file_name, heading, body, tf) VALUES
('chunk_10c37e83c5f5ae27bc','file_04bb580a3d99034261','history.md','Vijayanagara Empire','- **Dates:** c. **1336 CE – 1646 CE** (peak in the 15th–early 16th century).
- **Location:** South India (Deccan); capital **Vijayanagara** (Hampi), on the Tungabhadra River.
- **Rise factors:** Founded by **Harihara I and Bukka Raya I** (Sangama dynasty); strong military, wealth from agriculture and the cotton/spice/horse trade; role as a major Hindu power in the Deccan.
- **Governance:** Centralised monarchy with a military-fief (**nayaka**) system in which nobles held land in return for maintaining troops; provincial administration; substantial revenue system.
- **Achievements:** Splendid capital at **Hampi** (temples, markets, irrigation, UNESCO World Heritage); flourishing trade, art and literature; peak under **Krishnadevaraya** (r. 1509–1529).
- **Causes of decline:** Decisive defeat by a coalition of Deccan Sultanates at the **Battle of Talikota (1565)**, after which Vijayanagara city was sacked; the empire fragmented and declined, lingering until c. 1646.','{"1336":1,"1509":1,"1529":1,"1565":1,"1646":2,"vijayanagara":3,"empire":2,"dates":1,"peak":2,"the":6,"15th":1,"early":1,"16th":1,"century":1,"location":1,"south":1,"india":1,"deccan":3,"capital":2,"hampi":2,"tungabhadra":1,"river":1,"rise":1,"factors":1,"founded":1,"harihara":1,"and":4,"bukka":1,"raya":1,"sangama":1,"dynasty":1,"strong":1,"military":2,"wealth":1,"from":1,"agriculture":1,"cotton":1,"spice":1,"horse":1,"trade":2,"role":1,"major":1,"hindu":1,"power":1,"governance":1,"centralised":1,"monarchy":1,"with":1,"fief":1,"nayaka":1,"system":2,"which":2,"nobles":1,"held":1,"land":1,"return":1,"for":1,"maintaining":1,"troops":1,"provincial":1,"administration":1,"substantial":1,"revenue":1,"achievements":1,"splendid":1,"temples":1,"markets":1,"irrigation":1,"unesco":1,"world":1,"heritage":1,"flourishing":1,"art":1,"literature":1,"under":1,"krishnadevaraya":1,"causes":1,"decline":1,"decisive":1,"defeat":1,"coalition":1,"sultanates":1,"battle":1,"talikota":1,"after":1,"city":1,"was":1,"sacked":1,"fragmented":1,"declined":1,"lingering":1,"until":1}'::jsonb),
('chunk_4c412ad031156a201a','file_04bb580a3d99034261','history.md','Empire Comparison Table','| Empire | Dates | Core Region / Capital | Key Rise Factor | Governance Highlight | Signature Achievement | Main Cause of Decline |
|---|---|---|---|---|---|---|
| Gupta | c. 320–550 CE | N. India / Pataliputra | Strong rulers + trade wealth | Provincial (bhuktis/vishayas), decentralised | Zero & decimal system; Aryabhata; Kalidasa | Huna invasions + fragmentation |
| Roman | 27 BCE–476 CE (West) | Mediterranean / Rome | Legions, law, citizenship | Emperor + provinces + Roman law | Roman law, roads, Pax Romana | Instability, economy, Germanic invasions |
| Byzantine | c. 330–1453 CE | E. Mediterranean / Constantinople | Strategic, walled trade capital | Centralised bureaucracy + Justinian''s Code | Hagia Sophia; preserved classical knowledge | Crusader sack 1204; Ottoman conquest 1453 |
| Imperial Cholas | c. 850–1279 CE | S. India / Thanjavur | Kaveri agriculture + naval trade | Village self-government (Uttaramerur) | Brihadisvara Temple; bronzes; navy | Rival kingdoms + weak succession |
| Vijayanagara | 1336–1646 CE | Deccan / Hampi | Military + trade wealth | Nayaka (military-fief) system | City of Hampi; Krishnadevaraya''s reign | Defeat at Talikota (1565) |

---','{"320":1,"330":1,"476":1,"550":1,"850":1,"1204":1,"1279":1,"1336":1,"1453":2,"1565":1,"1646":1,"empire":2,"comparison":1,"table":1,"dates":1,"core":1,"region":1,"capital":2,"key":1,"rise":1,"factor":1,"governance":1,"highlight":1,"signature":1,"achievement":1,"main":1,"cause":1,"decline":1,"gupta":1,"india":2,"pataliputra":1,"strong":1,"rulers":1,"trade":4,"wealth":2,"provincial":1,"bhuktis":1,"vishayas":1,"decentralised":1,"zero":1,"decimal":1,"system":2,"aryabhata":1,"kalidasa":1,"huna":1,"invasions":2,"fragmentation":1,"roman":3,"bce":1,"west":1,"mediterranean":2,"rome":1,"legions":1,"law":3,"citizenship":1,"emperor":1,"provinces":1,"roads":1,"pax":1,"romana":1,"instability":1,"economy":1,"germanic":1,"byzantine":1,"constantinople":1,"strategic":1,"walled":1,"centralised":1,"bureaucracy":1,"justinian":1,"code":1,"hagia":1,"sophia":1,"preserved":1,"classical":1,"knowledge":1,"crusader":1,"sack":1,"ottoman":1,"conquest":1,"imperial":1,"cholas":1,"thanjavur":1,"kaveri":1,"agriculture":1,"naval":1,"village":1,"self":1,"government":1,"uttaramerur":1,"brihadisvara":1,"temple":1,"bronzes":1,"navy":1,"rival":1,"kingdoms":1,"weak":1,"succession":1,"vijayanagara":1,"deccan":1,"hampi":2,"military":2,"nayaka":1,"fief":1,"city":1,"krishnadevaraya":1,"reign":1,"defeat":1,"talikota":1}'::jsonb),
('chunk_773696f6312760c1f4','file_04bb580a3d99034261','history.md','UNIT 2: Medieval Life','**Key Concept:** Global interactions
**Related Concepts:** Trade, Interdependence, Culture, Significance
**Global Context:** Globalization and sustainability
**Statement of Inquiry:** *Trade routes connected distant societies, and the exchange of goods and ideas shaped the culture and prosperity of medieval cities.*

**Inquiry Questions**
- *Factual:* What goods, ideas and technologies travelled along medieval trade routes such as the Silk Route?
- *Conceptual:* How does trade create interdependence and cultural exchange between distant societies?
- *Debatable:* Was medieval Baghdad''s greatness the result of trade, or of ideas and learning?','{"unit":1,"medieval":4,"life":1,"key":1,"concept":1,"global":2,"interactions":1,"related":1,"concepts":1,"trade":5,"interdependence":2,"culture":2,"significance":1,"context":1,"globalization":1,"and":7,"sustainability":1,"statement":1,"inquiry":2,"routes":2,"connected":1,"distant":2,"societies":2,"the":4,"exchange":2,"goods":2,"ideas":3,"shaped":1,"prosperity":1,"cities":1,"questions":1,"factual":1,"what":1,"technologies":1,"travelled":1,"along":1,"such":1,"silk":1,"route":1,"conceptual":1,"how":1,"does":1,"create":1,"cultural":1,"between":1,"debatable":1,"was":1,"baghdad":1,"greatness":1,"result":1,"learning":1}'::jsonb),
('chunk_6abf84f141e03c7dfe','file_04bb580a3d99034261','history.md','Chapter 2.1 — Trade Routes','**Factual grounding.** Medieval **trade routes** were networks (overland and maritime) linking Asia, Africa and Europe. They moved not just goods but **ideas, religions, technologies and diseases**. Major networks included the overland **Silk Route**, the **Indian Ocean maritime trade** (spices, textiles, horses), and the **Trans-Saharan** gold–salt trade. Trade fostered **interdependence**: societies specialised in what they produced best and relied on others for the rest.

**Significance.** Trade routes were the "internet" of the medieval world — the main channel for cross-cultural exchange, urban wealth and the spread of religions (Buddhism, Islam) and technologies (paper, the compass).

**Perspective/interpretation note.** A merchant saw opportunity and profit; a ruler saw taxable wealth and strategic control; a religious traveller saw a path to spread faith. The same route meant different things to different people.

**Misconception:** *"Trade routes only carried luxury goods like silk and spices."*
- *Why believed:* The famous items (silk, spices) dominate the story.
- *Why wrong:* They also carried **ideas, religions, inventions, art styles and diseases** — arguably a bigger long-term impact than the goods.
- *Corrective:* Trade routes were channels of cultural and biological exchange, not just commerce.

**Command-term questions:**
1. *(Recall)* **Name** two major medieval trade networks.
2. *(Apply)* **Explain** how trade created interdependence between two regions.
3. *(Analyse/Evaluate)* **To what extent** were ideas more important than goods in the exchange along medieval trade routes?','{"chapter":1,"trade":11,"routes":6,"factual":1,"grounding":1,"medieval":4,"were":4,"networks":3,"overland":2,"and":12,"maritime":2,"linking":1,"asia":1,"africa":1,"europe":1,"they":3,"moved":1,"not":2,"just":2,"goods":4,"but":1,"ideas":3,"religions":3,"technologies":2,"diseases":2,"major":2,"included":1,"the":14,"silk":3,"route":2,"indian":1,"ocean":1,"spices":3,"textiles":1,"horses":1,"trans":1,"saharan":1,"gold":1,"salt":1,"fostered":1,"interdependence":2,"societies":1,"specialised":1,"what":2,"produced":1,"best":1,"relied":1,"others":1,"for":2,"rest":1,"significance":1,"internet":1,"world":1,"main":1,"channel":1,"cross":1,"cultural":2,"exchange":3,"urban":1,"wealth":2,"spread":2,"buddhism":1,"islam":1,"paper":1,"compass":1,"perspective":1,"interpretation":1,"note":1,"merchant":1,"saw":3,"opportunity":1,"profit":1,"ruler":1,"taxable":1,"strategic":1,"control":1,"religious":1,"traveller":1,"path":1,"faith":1,"same":1,"meant":1,"different":2,"things":1,"people":1,"misconception":1,"only":1,"carried":2,"luxury":1,"like":1,"why":2,"believed":1,"famous":1,"items":1,"dominate":1,"story":1,"wrong":1,"also":1,"inventions":1,"art":1,"styles":1,"arguably":1,"bigger":1,"long":1,"term":2,"impact":1,"than":2,"corrective":1,"channels":1,"biological":1,"commerce":1,"command":1,"questions":1,"recall":1,"name":1,"two":2,"apply":1,"explain":1,"how":1,"created":1,"between":1,"regions":1,"analyse":1,"evaluate":1,"extent":1,"more":1,"important":1,"along":1}'::jsonb),
('chunk_cac55f0cdadadd8bed','file_04bb580a3d99034261','history.md','Chapter 2.2 — The Silk Route','**Factual grounding.** The **Silk Route (Silk Road)** was a web of overland routes (flourishing especially c. 130 BCE–1450s CE) linking **China** with **Central Asia, India, Persia, the Arab world and the Mediterranean/Europe**. Named for Chinese **silk**, it also carried **paper, gunpowder, porcelain, spices, gems, horses and glassware**, plus **Buddhism, Islam, art and technologies**. Oasis cities like **Samarkand** and trading hubs prospered as waystations. It also transmitted disease — most infamously the **Black Death** in the 14th century (peaking in Europe **1347–1351**).

**Significance.** The Silk Route is the classic example of long-distance exchange shaping multiple civilisations at once; it explains how inventions (paper-making, the compass) and religions spread across Eurasia.

**Perspective/interpretation note.** "Silk Road" is a modern term (coined by geographer Ferdinand von Richthofen in 1877), not a name medieval travellers used — a reminder that historians impose labels on the past.

**Misconception:** *"The Silk Road was a single paved road that one merchant travelled end to end."*
- *Why believed:* The singular name "road" implies one route.
- *Why wrong:* It was a **shifting network of many routes**; goods usually passed through **many middlemen** in relay, rather than one trader going the whole way.
- *Corrective:* It was a network of relays, not a single highway.

**Command-term questions:**
1. *(Recall)* **List** three goods and one idea/religion carried on the Silk Route.
2. *(Apply)* **Describe** how the Silk Route helped spread both technology and disease.
3. *(Analyse/Evaluate)* **Evaluate** the claim that the Silk Route''s greatest impact was cultural, not economic.','{"130":1,"1347":1,"1351":1,"1877":1,"chapter":1,"the":17,"silk":10,"route":7,"factual":1,"grounding":1,"road":5,"was":5,"web":1,"overland":1,"routes":2,"flourishing":1,"especially":1,"bce":1,"1450s":1,"linking":1,"china":1,"with":1,"central":1,"asia":1,"india":1,"persia":1,"arab":1,"world":1,"and":7,"mediterranean":1,"europe":2,"named":1,"for":1,"chinese":1,"also":2,"carried":2,"paper":2,"gunpowder":1,"porcelain":1,"spices":1,"gems":1,"horses":1,"glassware":1,"plus":1,"buddhism":1,"islam":1,"art":1,"technologies":1,"oasis":1,"cities":1,"like":1,"samarkand":1,"trading":1,"hubs":1,"prospered":1,"waystations":1,"transmitted":1,"disease":2,"most":1,"infamously":1,"black":1,"death":1,"14th":1,"century":1,"peaking":1,"significance":1,"classic":1,"example":1,"long":1,"distance":1,"exchange":1,"shaping":1,"multiple":1,"civilisations":1,"once":1,"explains":1,"how":2,"inventions":1,"making":1,"compass":1,"religions":1,"spread":2,"across":1,"eurasia":1,"perspective":1,"interpretation":1,"note":1,"modern":1,"term":2,"coined":1,"geographer":1,"ferdinand":1,"von":1,"richthofen":1,"not":3,"name":2,"medieval":1,"travellers":1,"used":1,"reminder":1,"that":3,"historians":1,"impose":1,"labels":1,"past":1,"misconception":1,"single":2,"paved":1,"one":4,"merchant":1,"travelled":1,"end":2,"why":2,"believed":1,"singular":1,"implies":1,"wrong":1,"shifting":1,"network":2,"many":2,"goods":2,"usually":1,"passed":1,"through":1,"middlemen":1,"relay":1,"rather":1,"than":1,"trader":1,"going":1,"whole":1,"way":1,"corrective":1,"relays":1,"highway":1,"command":1,"questions":1,"recall":1,"list":1,"three":1,"idea":1,"religion":1,"apply":1,"describe":1,"helped":1,"both":1,"technology":1,"analyse":1,"evaluate":2,"claim":1,"greatest":1,"impact":1,"cultural":1,"economic":1}'::jsonb),
('chunk_e52210050b916ed8f5','file_04bb580a3d99034261','history.md','Chapter 2.3 — Medieval Baghdad','**Factual grounding.** Founded in **762 CE** by the Abbasid caliph **al-Mansur** as the round "City of Peace," **Baghdad** became the capital of the **Abbasid Caliphate** and, by the 9th–10th centuries, one of the world''s largest, richest cities and the centre of the **Islamic Golden Age**. Its **House of Wisdom (Bayt al-Hikma)** was a hub of translation and scholarship where Greek, Persian and Indian works were translated into Arabic and advanced. Scholars like **al-Khwarizmi** (algebra; the words *algorithm* and *algebra* derive from his work) and physicians and astronomers flourished. Baghdad thrived on trade, paper-making (learned from China) and learning — until it was **sacked by the Mongols under Hulagu Khan in 1258 CE**, a devastating blow to the city.

**Significance.** Baghdad shows how a trade-and-learning hub could preserve and advance human knowledge (mathematics, medicine, astronomy) that later fed into the European Renaissance.

**Perspective/interpretation note.** For Abbasid subjects Baghdad symbolised a golden age of faith and learning; the 1258 Mongol account frames the sack very differently. Sources on Baghdad''s glory are often later and celebratory, requiring OPVL scrutiny.

**Misconception:** *"During the ''Dark Ages'' the whole world stagnated intellectually."*
- *Why believed:* "Dark Ages" is a Eurocentric label applied to early medieval Europe and wrongly generalised.
- *Why wrong:* While parts of Western Europe were less centralised, **Baghdad, the Islamic world, Song China, and the Cholas** were experiencing golden ages of science, trade and art.
- *Corrective:* The "Dark Ages" is a misleading term; much of the medieval world was vibrant and innovative.

**Command-term questions:**
1. *(Recall)* **State** who founded Baghdad and in what year, and name its famous centre of learning.
2. *(Apply)* **Explain** how Baghdad''s House of Wisdom contributed to mathematics and science.
3. *(Analyse/Evaluate)* **To what extent** was Baghdad''s greatness due to trade rather than to scholarship?','{"762":1,"1258":2,"chapter":1,"medieval":3,"baghdad":10,"factual":1,"grounding":1,"founded":2,"the":20,"abbasid":3,"caliph":1,"mansur":1,"round":1,"city":2,"peace":1,"became":1,"capital":1,"caliphate":1,"and":20,"9th":1,"10th":1,"centuries":1,"one":1,"world":4,"largest":1,"richest":1,"cities":1,"centre":2,"islamic":2,"golden":3,"age":2,"its":2,"house":2,"wisdom":2,"bayt":1,"hikma":1,"was":4,"hub":2,"translation":1,"scholarship":2,"where":1,"greek":1,"persian":1,"indian":1,"works":1,"were":3,"translated":1,"into":2,"arabic":1,"advanced":1,"scholars":1,"like":1,"khwarizmi":1,"algebra":2,"words":1,"algorithm":1,"derive":1,"from":2,"his":1,"work":1,"physicians":1,"astronomers":1,"flourished":1,"thrived":1,"trade":4,"paper":1,"making":1,"learned":1,"china":2,"learning":4,"until":1,"sacked":1,"mongols":1,"under":1,"hulagu":1,"khan":1,"devastating":1,"blow":1,"significance":1,"shows":1,"how":2,"could":1,"preserve":1,"advance":1,"human":1,"knowledge":1,"mathematics":2,"medicine":1,"astronomy":1,"that":1,"later":2,"fed":1,"european":1,"renaissance":1,"perspective":1,"interpretation":1,"note":1,"for":1,"subjects":1,"symbolised":1,"faith":1,"mongol":1,"account":1,"frames":1,"sack":1,"very":1,"differently":1,"sources":1,"glory":1,"are":1,"often":1,"celebratory":1,"requiring":1,"opvl":1,"scrutiny":1,"misconception":1,"during":1,"dark":3,"ages":4,"whole":1,"stagnated":1,"intellectually":1,"why":2,"believed":1,"eurocentric":1,"label":1,"applied":1,"early":1,"europe":2,"wrongly":1,"generalised":1,"wrong":1,"while":1,"parts":1,"western":1,"less":1,"centralised":1,"song":1,"cholas":1,"experiencing":1,"science":2,"art":1,"corrective":1,"misleading":1,"term":2,"much":1,"vibrant":1,"innovative":1,"command":1,"questions":1,"recall":1,"state":1,"who":1,"what":2,"year":1,"name":1,"famous":1,"apply":1,"explain":1,"contributed":1,"analyse":1,"evaluate":1,"extent":1,"greatness":1,"due":1,"rather":1,"than":1}'::jsonb),
('chunk_af023ef4e70a1b6cbc','file_04bb580a3d99034261','history.md','Chapter 2.4 — Life in Another Medieval City (Comparative Study)','**Factual grounding.** Students compare Baghdad with **another contemporary city** to see shared and distinct features of medieval urban life. Strong options include **Constantinople** (Byzantine capital, huge trade emporium, Hagia Sophia), **Córdoba** (capital of Al-Andalus, famed for libraries and its Great Mosque, a major centre of learning in 10th-century Europe), **Hangzhou/Kaifeng** (wealthy Song-China cities with markets and paper money), **Timbuktu** (West African trade and Islamic learning hub), or **Vijayanagara/Hampi** (a bustling South Indian imperial capital). Across these, medieval cities shared: **markets and trade**, **religious institutions**, **craft workers and guilds**, **walls and gates**, **social hierarchy**, and **centres of learning**.

**Significance.** Comparing cities builds the concept of **interdependence** and shows that urban prosperity everywhere depended on trade, governance and cultural exchange — not on one region alone.

**Perspective/interpretation note.** Life in a medieval city differed sharply by class and gender — a wealthy merchant, an artisan, a servant and a scholar experienced the same city very differently.

**Misconception:** *"Medieval cities were tiny, dirty and unimportant compared to modern cities."*
- *Why believed:* Modern bias assumes the past was primitive.
- *Why wrong:* Cities like Baghdad, Constantinople and Córdoba had **hundreds of thousands of inhabitants**, running water/bathhouses, libraries, hospitals and thriving markets.
- *Corrective:* Major medieval cities were large, sophisticated centres of trade and learning.

**Command-term questions:**
1. *(Recall)* **Identify** one medieval city (other than Baghdad) and one feature that made it important.
2. *(Apply)* **Compare** one similarity and one difference between Baghdad and your chosen city.
3. *(Analyse/Evaluate)* **Evaluate** which factor — trade, religion or learning — most shaped daily life in your chosen medieval city.

---','{"chapter":1,"life":4,"another":2,"medieval":8,"city":7,"comparative":1,"study":1,"factual":1,"grounding":1,"students":1,"compare":2,"baghdad":4,"with":2,"contemporary":1,"see":1,"shared":2,"and":19,"distinct":1,"features":1,"urban":2,"strong":1,"options":1,"include":1,"constantinople":2,"byzantine":1,"capital":3,"huge":1,"trade":6,"emporium":1,"hagia":1,"sophia":1,"rdoba":2,"andalus":1,"famed":1,"for":1,"libraries":2,"its":1,"great":1,"mosque":1,"major":2,"centre":1,"learning":5,"10th":1,"century":1,"europe":1,"hangzhou":1,"kaifeng":1,"wealthy":2,"song":1,"china":1,"cities":7,"markets":3,"paper":1,"money":1,"timbuktu":1,"west":1,"african":1,"islamic":1,"hub":1,"vijayanagara":1,"hampi":1,"bustling":1,"south":1,"indian":1,"imperial":1,"across":1,"these":1,"religious":1,"institutions":1,"craft":1,"workers":1,"guilds":1,"walls":1,"gates":1,"social":1,"hierarchy":1,"centres":2,"significance":1,"comparing":1,"builds":1,"the":3,"concept":1,"interdependence":1,"shows":1,"that":2,"prosperity":1,"everywhere":1,"depended":1,"governance":1,"cultural":1,"exchange":1,"not":1,"one":5,"region":1,"alone":1,"perspective":1,"interpretation":1,"note":1,"differed":1,"sharply":1,"class":1,"gender":1,"merchant":1,"artisan":1,"servant":1,"scholar":1,"experienced":1,"same":1,"very":1,"differently":1,"misconception":1,"were":2,"tiny":1,"dirty":1,"unimportant":1,"compared":1,"modern":2,"why":2,"believed":1,"bias":1,"assumes":1,"past":1,"was":1,"primitive":1,"wrong":1,"like":1,"had":1,"hundreds":1,"thousands":1,"inhabitants":1,"running":1,"water":1,"bathhouses":1,"hospitals":1,"thriving":1,"corrective":1,"large":1,"sophisticated":1,"command":1,"term":1,"questions":1,"recall":1,"identify":1,"other":1,"than":1,"feature":1,"made":1,"important":1,"apply":1,"similarity":1,"difference":1,"between":1,"your":2,"chosen":2,"analyse":1,"evaluate":2,"which":1,"factor":1,"religion":1,"most":1,"shaped":1,"daily":1}'::jsonb),
('chunk_a828387b7d5bf6dc45','file_04bb580a3d99034261','history.md','UNIT 3: Geographical Explorations and Their Impact','**Key Concept:** Global interactions
**Related Concepts:** Innovation and revolution, Causality, Perspective, Significance
**Global Context:** Scientific and technical innovation
**Statement of Inquiry:** *Motivated by faith, wealth and glory, and enabled by new technologies, exploration connected the world and transformed societies through exchange — for better and for worse.*

**Inquiry Questions**
- *Factual:* Which technologies and explorers made long-distance ocean voyages possible?
- *Conceptual:* How did motivation and innovation combine to drive the Age of Exploration?
- *Debatable:* Was the Columbian Exchange more beneficial or more harmful overall?','{"unit":1,"geographical":1,"explorations":1,"and":9,"their":1,"impact":1,"key":1,"concept":1,"global":2,"interactions":1,"related":1,"concepts":1,"innovation":3,"revolution":1,"causality":1,"perspective":1,"significance":1,"context":1,"scientific":1,"technical":1,"statement":1,"inquiry":2,"motivated":1,"faith":1,"wealth":1,"glory":1,"enabled":1,"new":1,"technologies":2,"exploration":2,"connected":1,"the":3,"world":1,"transformed":1,"societies":1,"through":1,"exchange":2,"for":2,"better":1,"worse":1,"questions":1,"factual":1,"which":1,"explorers":1,"made":1,"long":1,"distance":1,"ocean":1,"voyages":1,"possible":1,"conceptual":1,"how":1,"did":1,"motivation":1,"combine":1,"drive":1,"age":1,"debatable":1,"was":1,"columbian":1,"more":2,"beneficial":1,"harmful":1,"overall":1}'::jsonb),
('chunk_2cadddc847a27c8cfa','file_04bb580a3d99034261','history.md','Chapter 3.1 — The Age of Exploration and Motivations: The 3 Gs','**Factual grounding.** The **Age of Exploration** (roughly the 15th–17th centuries) was the European push to find new sea routes to Asia and to explore, trade and colonise. Historians summarise the motivations as the **3 Gs**:
- **God** — spreading Christianity to new lands.
- **Glory** — national prestige, competition between kingdoms (Portugal, Spain), and personal fame.
- **Gold** — wealth: direct access to Asian spices, silk and gold, bypassing costly overland/Middle-Eastern middlemen (especially after the Ottomans controlled key routes).
Portugal and Spain led early, backed by rulers such as Portugal''s **Prince Henry the Navigator** (who promoted exploration in the early–mid 1400s).

**Significance.** The 3 Gs explain **causality** — why Europeans risked dangerous voyages. Understanding motivation links directly to consequences (colonisation, the Columbian Exchange, globalisation).

**Perspective/interpretation note.** "Exploration" and "discovery" are European-centred terms; the peoples of the Americas, Africa and Asia already lived in these lands. From their perspective, this was invasion or contact, not discovery.

**Misconception:** *"Explorers set sail mainly out of scientific curiosity to see the world."*
- *Why believed:* Modern admiration for explorers frames them as pure adventurers/scientists.
- *Why wrong:* The core drivers were **economic (Gold) and religious/political (God, Glory)**; curiosity was secondary and usually funded by profit-seeking monarchs and merchants.
- *Corrective:* Exploration was driven mainly by wealth, faith and national rivalry.

**Command-term questions:**
1. *(Recall)* **State** what each of the 3 Gs stands for.
2. *(Apply)* **Explain** how the Ottoman control of trade routes encouraged Europeans to seek sea routes to Asia.
3. *(Analyse/Evaluate)* **To what extent** was "Gold" the most important of the 3 Gs?','{"chapter":1,"the":20,"age":2,"exploration":5,"and":12,"motivations":2,"factual":1,"grounding":1,"roughly":1,"15th":1,"17th":1,"centuries":1,"was":5,"european":2,"push":1,"find":1,"new":2,"sea":2,"routes":4,"asia":3,"explore":1,"trade":2,"colonise":1,"historians":1,"summarise":1,"god":2,"spreading":1,"christianity":1,"lands":2,"glory":2,"national":2,"prestige":1,"competition":1,"between":1,"kingdoms":1,"portugal":3,"spain":2,"personal":1,"fame":1,"gold":4,"wealth":2,"direct":1,"access":1,"asian":1,"spices":1,"silk":1,"bypassing":1,"costly":1,"overland":1,"middle":1,"eastern":1,"middlemen":1,"especially":1,"after":1,"ottomans":1,"controlled":1,"key":1,"led":1,"early":2,"backed":1,"rulers":1,"such":1,"prince":1,"henry":1,"navigator":1,"who":1,"promoted":1,"mid":1,"1400s":1,"significance":1,"explain":2,"causality":1,"why":3,"europeans":2,"risked":1,"dangerous":1,"voyages":1,"understanding":1,"motivation":1,"links":1,"directly":1,"consequences":1,"colonisation":1,"columbian":1,"exchange":1,"globalisation":1,"perspective":2,"interpretation":1,"note":1,"discovery":2,"are":1,"centred":1,"terms":1,"peoples":1,"americas":1,"africa":1,"already":1,"lived":1,"these":1,"from":1,"their":1,"this":1,"invasion":1,"contact":1,"not":1,"misconception":1,"explorers":2,"set":1,"sail":1,"mainly":2,"out":1,"scientific":1,"curiosity":2,"see":1,"world":1,"believed":1,"modern":1,"admiration":1,"for":2,"frames":1,"them":1,"pure":1,"adventurers":1,"scientists":1,"wrong":1,"core":1,"drivers":1,"were":1,"economic":1,"religious":1,"political":1,"secondary":1,"usually":1,"funded":1,"profit":1,"seeking":1,"monarchs":1,"merchants":1,"corrective":1,"driven":1,"faith":1,"rivalry":1,"command":1,"term":1,"questions":1,"recall":1,"state":1,"what":2,"each":1,"stands":1,"apply":1,"how":1,"ottoman":1,"control":1,"encouraged":1,"seek":1,"analyse":1,"evaluate":1,"extent":1,"most":1,"important":1}'::jsonb),
('chunk_aac09f6cbb963d613a','file_04bb580a3d99034261','history.md','Chapter 3.2 — Early Explorers','**Factual grounding.** Key figures who opened new routes and knowledge:
- **Marco Polo (1254–1324):** Venetian merchant-traveller whose account of his journey to **Kublai Khan''s China** along the Silk Route (published c. 1300) fed European fascination with Asia''s wealth. (He predates the sea-voyage Age of Exploration but inspired it.)
- **Zheng He (1371–1433):** Chinese Ming-dynasty admiral who led **seven massive treasure-fleet voyages (1405–1433)** across the Indian Ocean to Southeast Asia, India, Arabia and East Africa — decades before the Portuguese, with far larger ships.
- **Bartolomeu Dias (c. 1450–1500):** Portuguese explorer who in **1488** became the first European to round the southern tip of Africa (the **Cape of Good Hope**), proving a sea route toward the Indian Ocean was possible.
- **Vasco da Gama (c. 1460s–1524):** Portuguese explorer who **reached Calicut (Kozhikode), India, by sea in 1498**, opening the direct ocean route from Europe to India around Africa.

**Significance.** These voyages connected previously separate worlds, launched European maritime empires and the global spice/trade economy, and showed that non-European powers (Ming China) were world-leading navigators.

**Perspective/interpretation note.** Zheng He''s voyages were largely diplomatic/tributary, not colonising; the Portuguese voyages were about seizing trade and territory. Comparing them challenges a Europe-only view of exploration.

**Misconception:** *"Europeans were the first and only advanced ocean explorers."*
- *Why believed:* Western textbooks foreground Columbus and da Gama.
- *Why wrong:* **Zheng He''s Chinese fleets (from 1405)** sailed vast distances in enormous ships decades before da Gama''s 1498 voyage; Arab, Indian and Polynesian navigators had long crossed oceans.
- *Corrective:* Ocean exploration was a global phenomenon; Europeans were not first, only later dominant.','{"1254":1,"1300":1,"1324":1,"1371":1,"1405":2,"1433":2,"1450":1,"1488":1,"1498":2,"1500":1,"1524":1,"chapter":1,"early":1,"explorers":2,"factual":1,"grounding":1,"key":1,"figures":1,"who":4,"opened":1,"new":1,"routes":1,"and":8,"knowledge":1,"marco":1,"polo":1,"venetian":1,"merchant":1,"traveller":1,"whose":1,"account":1,"his":1,"journey":1,"kublai":1,"khan":1,"china":2,"along":1,"the":12,"silk":1,"route":3,"published":1,"fed":1,"european":4,"fascination":1,"with":2,"asia":2,"wealth":1,"predates":1,"sea":3,"voyage":2,"age":1,"exploration":3,"but":1,"inspired":1,"zheng":3,"chinese":2,"ming":2,"dynasty":1,"admiral":1,"led":1,"seven":1,"massive":1,"treasure":1,"fleet":1,"voyages":4,"across":1,"indian":3,"ocean":5,"southeast":1,"india":3,"arabia":1,"east":1,"africa":3,"decades":2,"before":2,"portuguese":4,"far":1,"larger":1,"ships":2,"bartolomeu":1,"dias":1,"explorer":2,"became":1,"first":3,"round":1,"southern":1,"tip":1,"cape":1,"good":1,"hope":1,"proving":1,"toward":1,"was":2,"possible":1,"vasco":1,"gama":3,"1460s":1,"reached":1,"calicut":1,"kozhikode":1,"opening":1,"direct":1,"from":2,"europe":2,"around":1,"significance":1,"these":1,"connected":1,"previously":1,"separate":1,"worlds":1,"launched":1,"maritime":1,"empires":1,"global":2,"spice":1,"trade":2,"economy":1,"showed":1,"that":1,"non":1,"powers":1,"were":5,"world":1,"leading":1,"navigators":2,"perspective":1,"interpretation":1,"note":1,"largely":1,"diplomatic":1,"tributary":1,"not":2,"colonising":1,"about":1,"seizing":1,"territory":1,"comparing":1,"them":1,"challenges":1,"only":3,"view":1,"misconception":1,"europeans":2,"advanced":1,"why":2,"believed":1,"western":1,"textbooks":1,"foreground":1,"columbus":1,"wrong":1,"fleets":1,"sailed":1,"vast":1,"distances":1,"enormous":1,"arab":1,"polynesian":1,"had":1,"long":1,"crossed":1,"oceans":1,"corrective":1,"phenomenon":1,"later":1,"dominant":1}'::jsonb),
('chunk_3784b9d4b373c6474c','file_04bb580a3d99034261','history.md','Explorer Voyages Table','| Explorer | Dates | Sponsor / Origin | Key Voyage(s) | Achievement | Significance |
|---|---|---|---|---|---|
| Marco Polo | 1254–1324 | Venice (Italy) | Overland to China, returned c. 1295 | Detailed account of Asia (c. 1300) | Sparked European interest in Asian wealth |
| Zheng He | 1371–1433 | Ming China | 7 treasure voyages, 1405–1433 | Reached India, Arabia, E. Africa | Showed China''s naval supremacy; diplomacy/trade |
| Bartolomeu Dias | c. 1450–1500 | Portugal | 1488 | First European to round the Cape of Good Hope | Proved route around Africa possible |
| Vasco da Gama | c. 1460s–1524 | Portugal | 1497–1499; reached Calicut 1498 | First sea route Europe→India | Opened European–Asian ocean trade/empire |

**Command-term questions:**
1. *(Recall)* **State** what Vasco da Gama achieved in 1498 and what Bartolomeu Dias achieved in 1488.
2. *(Apply)* **Compare** the purpose of Zheng He''s voyages with that of the Portuguese voyages.
3. *(Analyse/Evaluate)* **To what extent** does Zheng He''s achievement challenge the idea that Europeans led world exploration?','{"1254":1,"1295":1,"1300":1,"1324":1,"1371":1,"1405":1,"1433":2,"1450":1,"1488":2,"1497":1,"1498":2,"1499":1,"1500":1,"1524":1,"explorer":2,"voyages":4,"table":1,"dates":1,"sponsor":1,"origin":1,"key":1,"voyage":1,"achievement":2,"significance":1,"marco":1,"polo":1,"venice":1,"italy":1,"overland":1,"china":3,"returned":1,"detailed":1,"account":1,"asia":1,"sparked":1,"european":3,"interest":1,"asian":2,"wealth":1,"zheng":3,"ming":1,"treasure":1,"reached":2,"india":2,"arabia":1,"africa":2,"showed":1,"naval":1,"supremacy":1,"diplomacy":1,"trade":2,"bartolomeu":2,"dias":2,"portugal":2,"first":2,"round":1,"the":4,"cape":1,"good":1,"hope":1,"proved":1,"route":2,"around":1,"possible":1,"vasco":2,"gama":2,"1460s":1,"calicut":1,"sea":1,"europe":1,"opened":1,"ocean":1,"empire":1,"command":1,"term":1,"questions":1,"recall":1,"state":1,"what":3,"achieved":2,"and":1,"apply":1,"compare":1,"purpose":1,"with":1,"that":2,"portuguese":1,"analyse":1,"evaluate":1,"extent":1,"does":1,"challenge":1,"idea":1,"europeans":1,"led":1,"world":1,"exploration":1}'::jsonb),
('chunk_fcdc71e0a402df6e08','file_04bb580a3d99034261','history.md','Chapter 3.3 — Technologies of Exploration','**Factual grounding.** Long ocean voyages depended on navigation and ship technology, much of it adapted from Chinese, Arab and Mediterranean know-how:
- **Magnetic compass** — a magnetised needle showing direction (north), invented in **China** and transmitted westward; let sailors navigate out of sight of land and in poor weather.
- **Lateen sail** — a triangular sail (from the Arab/Mediterranean world) that let ships sail **closer into the wind** and tack, giving much greater manoeuvrability than square sails alone.
- **Sextant** — an instrument to measure the angle of the sun/stars above the horizon to find **latitude** (the earlier **astrolabe/quadrant** did this; the sextant itself was perfected in the **1730s**, slightly after the peak Age of Exploration but the key latitude-finding tools were in use earlier).
- **Dead reckoning** — estimating current position from a known starting point using **speed, heading and time elapsed** (no instruments for position); essential but error-prone.
- **The caravel** — a small, fast, highly manoeuvrable Portuguese ship developed in the 15th century, combining square and **lateen** sails, with a shallow draft ideal for coastal exploration; central to Portuguese voyages.

**Significance.** These innovations made the Age of Exploration possible — a clear example of the related concept **innovation and revolution**: without them, transoceanic voyages could not succeed.

**Perspective/interpretation note.** Much "European" navigation technology was **borrowed and combined** from Chinese and Arab inventions, complicating any story of purely European genius.

**Misconception:** *"Europeans invented all the navigation technology that powered exploration."*
- *Why believed:* Exploration is told as a European triumph.
- *Why wrong:* The **compass came from China**; the **lateen sail** from the Arab/Mediterranean world; the astrolabe was refined by Muslim scholars. Europeans **combined and improved** existing technologies.
- *Corrective:* Exploration technology was a global inheritance, adapted by Europeans.','{"chapter":1,"technologies":2,"exploration":7,"factual":1,"grounding":1,"long":1,"ocean":1,"voyages":3,"depended":1,"navigation":3,"and":11,"ship":2,"technology":4,"much":3,"adapted":2,"from":6,"chinese":2,"arab":4,"mediterranean":3,"know":1,"how":1,"magnetic":1,"compass":2,"magnetised":1,"needle":1,"showing":1,"direction":1,"north":1,"invented":2,"china":2,"transmitted":1,"westward":1,"let":2,"sailors":1,"navigate":1,"out":1,"sight":1,"land":1,"poor":1,"weather":1,"lateen":3,"sail":4,"triangular":1,"the":19,"world":2,"that":2,"ships":1,"closer":1,"into":1,"wind":1,"tack":1,"giving":1,"greater":1,"manoeuvrability":1,"than":1,"square":2,"sails":2,"alone":1,"sextant":2,"instrument":1,"measure":1,"angle":1,"sun":1,"stars":1,"above":1,"horizon":1,"find":1,"latitude":2,"earlier":2,"astrolabe":2,"quadrant":1,"did":1,"this":1,"itself":1,"was":4,"perfected":1,"1730s":1,"slightly":1,"after":1,"peak":1,"age":2,"but":2,"key":1,"finding":1,"tools":1,"were":1,"use":1,"dead":1,"reckoning":1,"estimating":1,"current":1,"position":2,"known":1,"starting":1,"point":1,"using":1,"speed":1,"heading":1,"time":1,"elapsed":1,"instruments":1,"for":2,"essential":1,"error":1,"prone":1,"caravel":1,"small":1,"fast":1,"highly":1,"manoeuvrable":1,"portuguese":2,"developed":1,"15th":1,"century":1,"combining":1,"with":1,"shallow":1,"draft":1,"ideal":1,"coastal":1,"central":1,"significance":1,"these":1,"innovations":1,"made":1,"possible":1,"clear":1,"example":1,"related":1,"concept":1,"innovation":1,"revolution":1,"without":1,"them":1,"transoceanic":1,"could":1,"not":1,"succeed":1,"perspective":1,"interpretation":1,"note":1,"european":3,"borrowed":1,"combined":2,"inventions":1,"complicating":1,"any":1,"story":1,"purely":1,"genius":1,"misconception":1,"europeans":3,"all":1,"powered":1,"why":2,"believed":1,"told":1,"triumph":1,"wrong":1,"came":1,"refined":1,"muslim":1,"scholars":1,"improved":1,"existing":1,"corrective":1,"global":1,"inheritance":1}'::jsonb),
('chunk_75bc6f194100ceb11b','file_04bb580a3d99034261','history.md','Exploration Technologies Table','| Technology | What it did | Origin | Impact on voyages |
|---|---|---|---|
| Magnetic compass | Shows direction (north) | China | Navigate out of sight of land / in fog |
| Lateen sail | Triangular sail; sail into the wind | Arab/Mediterranean | Manoeuvrability; tacking against wind |
| Sextant (& astrolabe/quadrant) | Measures sun/star angle → latitude | Muslim scholars refined astrolabe; sextant perfected 1730s | Find how far north/south you are |
| Dead reckoning | Estimate position from speed, heading, time | Long-standing method | Best-guess navigation without instruments |
| Caravel | Small, fast, manoeuvrable ship (square + lateen sails) | Portugal, 15th c. | Ideal ship for exploration |

**Command-term questions:**
1. *(Recall)* **Identify** what the lateen sail and the magnetic compass each allowed sailors to do.
2. *(Apply)* **Explain** why the caravel was well suited to exploration.
3. *(Analyse/Evaluate)* **To what extent** was the caravel the single most important technology of the Age of Exploration?','{"exploration":4,"technologies":1,"table":1,"technology":2,"what":3,"did":1,"origin":1,"impact":1,"voyages":1,"magnetic":2,"compass":2,"shows":1,"direction":1,"north":2,"china":1,"navigate":1,"out":1,"sight":1,"land":1,"fog":1,"lateen":3,"sail":4,"triangular":1,"into":1,"the":7,"wind":2,"arab":1,"mediterranean":1,"manoeuvrability":1,"tacking":1,"against":1,"sextant":2,"astrolabe":2,"quadrant":1,"measures":1,"sun":1,"star":1,"angle":1,"latitude":1,"muslim":1,"scholars":1,"refined":1,"perfected":1,"1730s":1,"find":1,"how":1,"far":1,"south":1,"you":1,"are":1,"dead":1,"reckoning":1,"estimate":1,"position":1,"from":1,"speed":1,"heading":1,"time":1,"long":1,"standing":1,"method":1,"best":1,"guess":1,"navigation":1,"without":1,"instruments":1,"caravel":3,"small":1,"fast":1,"manoeuvrable":1,"ship":2,"square":1,"sails":1,"portugal":1,"15th":1,"ideal":1,"for":1,"command":1,"term":1,"questions":1,"recall":1,"identify":1,"and":1,"each":1,"allowed":1,"sailors":1,"apply":1,"explain":1,"why":1,"was":2,"well":1,"suited":1,"analyse":1,"evaluate":1,"extent":1,"single":1,"most":1,"important":1,"age":1}'::jsonb),
('chunk_dc0bcaa820273a4626','file_04bb580a3d99034261','history.md','Chapter 3.4 — The Columbian Exchange','**Factual grounding.** The **Columbian Exchange** is the vast transfer of **plants, animals, people, ideas, technology and diseases** between the **Old World (Europe, Africa, Asia)** and the **New World (the Americas)** after **Christopher Columbus''s 1492 voyage**.
- **From the Americas to the Old World:** maize (corn), potatoes, tomatoes, cacao (chocolate), tobacco, chilli peppers, beans, vanilla, turkey. (Potatoes and maize boosted populations in Europe, Asia and Africa.)
- **From the Old World to the Americas:** wheat, rice, sugar, horses, cattle, pigs, sheep — and, catastrophically, **diseases** such as **smallpox, measles and influenza**.
- **Human cost:** Old World diseases killed a huge share of Indigenous American populations (who had no immunity) — many estimates suggest up to around 90% mortality in some regions over the following century. It also drove the **transatlantic slave trade**, forcibly moving millions of Africans to the Americas.

**Significance ("so what").** The Columbian Exchange reshaped **global diets, populations, economies and ecosystems** and truly began the interconnected modern world (globalisation). Its impact was both transformative and, for Indigenous peoples, devastating.

**Perspective/interpretation note.** From a European view it brought new foods, wealth and empire; from an Indigenous American view it meant death, conquest and cultural destruction; for Africans it meant enslavement. A single event, radically different meanings.

**Misconception:** *"The Columbian Exchange was mostly a positive sharing of new foods."*
- *Why believed:* We enjoy the foods (potatoes, tomatoes, chocolate) it spread.
- *Why wrong:* Its deadliest effect was **disease**, which killed a large fraction of Indigenous Americans, alongside conquest and the slave trade.
- *Corrective:* The exchange had enormous benefits and catastrophic harms; judging it requires weighing both.

**Command-term questions:**
1. *(Recall)* **List** two foods that went from the Americas to Europe and two things that went from Europe to the Americas.
2. *(Apply)* **Explain** why Old World diseases had such a devastating effect on Indigenous American populations.
3. *(Analyse/Evaluate)* **To what extent** did the benefits of the Columbian Exchange outweigh its harms?

---','{"1492":1,"chapter":1,"the":23,"columbian":5,"exchange":6,"factual":1,"grounding":1,"vast":1,"transfer":1,"plants":1,"animals":1,"people":1,"ideas":1,"technology":1,"and":14,"diseases":4,"between":1,"old":5,"world":7,"europe":4,"africa":2,"asia":2,"new":3,"americas":6,"after":1,"christopher":1,"columbus":1,"voyage":1,"from":6,"maize":2,"corn":1,"potatoes":3,"tomatoes":2,"cacao":1,"chocolate":2,"tobacco":1,"chilli":1,"peppers":1,"beans":1,"vanilla":1,"turkey":1,"boosted":1,"populations":4,"wheat":1,"rice":1,"sugar":1,"horses":1,"cattle":1,"pigs":1,"sheep":1,"catastrophically":1,"such":2,"smallpox":1,"measles":1,"influenza":1,"human":1,"cost":1,"killed":2,"huge":1,"share":1,"indigenous":5,"american":3,"who":1,"had":3,"immunity":1,"many":1,"estimates":1,"suggest":1,"around":1,"mortality":1,"some":1,"regions":1,"over":1,"following":1,"century":1,"also":1,"drove":1,"transatlantic":1,"slave":2,"trade":2,"forcibly":1,"moving":1,"millions":1,"africans":2,"significance":1,"what":2,"reshaped":1,"global":1,"diets":1,"economies":1,"ecosystems":1,"truly":1,"began":1,"interconnected":1,"modern":1,"globalisation":1,"its":3,"impact":1,"was":3,"both":2,"transformative":1,"for":2,"peoples":1,"devastating":2,"perspective":1,"interpretation":1,"note":1,"european":1,"view":2,"brought":1,"foods":4,"wealth":1,"empire":1,"meant":2,"death":1,"conquest":2,"cultural":1,"destruction":1,"enslavement":1,"single":1,"event":1,"radically":1,"different":1,"meanings":1,"misconception":1,"mostly":1,"positive":1,"sharing":1,"why":3,"believed":1,"enjoy":1,"spread":1,"wrong":1,"deadliest":1,"effect":2,"disease":1,"which":1,"large":1,"fraction":1,"americans":1,"alongside":1,"corrective":1,"enormous":1,"benefits":2,"catastrophic":1,"harms":2,"judging":1,"requires":1,"weighing":1,"command":1,"term":1,"questions":1,"recall":1,"list":1,"two":2,"that":2,"went":2,"things":1,"apply":1,"explain":1,"analyse":1,"evaluate":1,"extent":1,"did":1,"outweigh":1}'::jsonb),
('chunk_b4189b7530a6b60df8','file_04bb580a3d99034261','history.md','UNIT 4: Renaissance and the Rise of Scientific Thought','**Key Concept:** Change
**Related Concepts:** Innovation and revolution, Perspective, Significance
**Global Context:** Personal and cultural expression / Scientific and technical innovation
**Statement of Inquiry:** *A revival of learning and a new emphasis on human reason revolutionised art and science, changing how people understood the world and their place in it.*

**Inquiry Questions**
- *Factual:* What were the key ideas, figures and breakthroughs of the Renaissance and the Scientific Revolution?
- *Conceptual:* How did humanism change the way people viewed the individual, art and knowledge?
- *Debatable:* Was the Scientific Revolution a sudden break from the past or a gradual evolution of earlier ideas?','{"unit":1,"renaissance":2,"and":10,"the":9,"rise":1,"scientific":4,"thought":1,"key":2,"concept":1,"change":2,"related":1,"concepts":1,"innovation":2,"revolution":3,"perspective":1,"significance":1,"global":1,"context":1,"personal":1,"cultural":1,"expression":1,"technical":1,"statement":1,"inquiry":2,"revival":1,"learning":1,"new":1,"emphasis":1,"human":1,"reason":1,"revolutionised":1,"art":2,"science":1,"changing":1,"how":2,"people":2,"understood":1,"world":1,"their":1,"place":1,"questions":1,"factual":1,"what":1,"were":1,"ideas":2,"figures":1,"breakthroughs":1,"conceptual":1,"did":1,"humanism":1,"way":1,"viewed":1,"individual":1,"knowledge":1,"debatable":1,"was":1,"sudden":1,"break":1,"from":1,"past":1,"gradual":1,"evolution":1,"earlier":1}'::jsonb),
('chunk_dac17ec64aa075b8e1','file_04bb580a3d99034261','history.md','Chapter 4.1 — The Renaissance','**Factual grounding.** The **Renaissance** ("rebirth," roughly **14th–17th centuries**, beginning in **Italy** — especially **Florence** — c. 1300s and spreading across Europe) was a period of renewed interest in the **classical learning of ancient Greece and Rome** and a flourishing of art, literature, science and thought. It was fuelled by: wealthy trading cities and patrons (e.g., the **Medici** of Florence); the fall of Constantinople (1453) sending Greek scholars/texts west; and **Johannes Gutenberg''s printing press** (c. **1440s**), which spread ideas cheaply and rapidly.

**Significance.** The Renaissance marks a major **change** in European culture — the bridge from the medieval to the modern world — reshaping art, education, religion and science.

**Perspective/interpretation note.** The term "Renaissance" (a "rebirth") was popularised later (19th century) and implies the Middle Ages were "asleep." Many historians stress **continuity**: medieval and Islamic scholars had preserved and advanced the classical knowledge that the Renaissance built on.

**Misconception:** *"The Renaissance suddenly rediscovered ancient knowledge that had been completely lost."*
- *Why believed:* "Rebirth" implies knowledge was dead and revived from nothing.
- *Why wrong:* Classical texts were **preserved and studied** through the medieval period by **Byzantine and Islamic scholars** (e.g., in Baghdad and Córdoba); the Renaissance **built on** this, aided by the printing press.
- *Corrective:* The Renaissance revived and expanded knowledge that had been kept alive, not resurrected from total loss.

**Command-term questions:**
1. *(Recall)* **State** where and roughly when the Renaissance began, and name one factor that fuelled it.
2. *(Apply)* **Explain** how the printing press helped spread Renaissance ideas.
3. *(Analyse/Evaluate)* **To what extent** was the Renaissance a genuine break from the medieval period?','{"1453":1,"chapter":1,"the":22,"renaissance":11,"factual":1,"grounding":1,"rebirth":3,"roughly":2,"14th":1,"17th":1,"centuries":1,"beginning":1,"italy":1,"especially":1,"florence":2,"1300s":1,"and":18,"spreading":1,"across":1,"europe":1,"was":5,"period":3,"renewed":1,"interest":1,"classical":3,"learning":1,"ancient":2,"greece":1,"rome":1,"flourishing":1,"art":2,"literature":1,"science":2,"thought":1,"fuelled":2,"wealthy":1,"trading":1,"cities":1,"patrons":1,"medici":1,"fall":1,"constantinople":1,"sending":1,"greek":1,"scholars":3,"texts":2,"west":1,"johannes":1,"gutenberg":1,"printing":3,"press":3,"1440s":1,"which":1,"spread":2,"ideas":2,"cheaply":1,"rapidly":1,"significance":1,"marks":1,"major":1,"change":1,"european":1,"culture":1,"bridge":1,"from":4,"medieval":4,"modern":1,"world":1,"reshaping":1,"education":1,"religion":1,"perspective":1,"interpretation":1,"note":1,"term":2,"popularised":1,"later":1,"19th":1,"century":1,"implies":2,"middle":1,"ages":1,"were":2,"asleep":1,"many":1,"historians":1,"stress":1,"continuity":1,"islamic":2,"had":3,"preserved":2,"advanced":1,"knowledge":4,"that":4,"built":2,"misconception":1,"suddenly":1,"rediscovered":1,"been":2,"completely":1,"lost":1,"why":2,"believed":1,"dead":1,"revived":2,"nothing":1,"wrong":1,"studied":1,"through":1,"byzantine":1,"baghdad":1,"rdoba":1,"this":1,"aided":1,"corrective":1,"expanded":1,"kept":1,"alive":1,"not":1,"resurrected":1,"total":1,"loss":1,"command":1,"questions":1,"recall":1,"state":1,"where":1,"when":1,"began":1,"name":1,"one":1,"factor":1,"apply":1,"explain":1,"how":1,"helped":1,"analyse":1,"evaluate":1,"what":1,"extent":1,"genuine":1,"break":1}'::jsonb),
('chunk_5f77f354aa6bdfe615','file_04bb580a3d99034261','history.md','Chapter 4.2 — Humanism, Art and Scientific Innovation','**Factual grounding.** **Humanism** was the defining intellectual movement of the Renaissance: it emphasised the **value, potential and achievements of the individual human being**, studied the *humanities* (grammar, rhetoric, history, poetry, philosophy) based on classical texts, and encouraged **observation, reason and secular alongside religious inquiry** (humanists were still mostly religious). In **art**, this produced **realism, perspective (3-D depth on a flat surface), anatomical accuracy, and the celebration of human beauty and emotion** — a clear break from flatter medieval styles. This same spirit of **observation and questioning** fed **scientific innovation**.

**Significance.** Humanism shifted the focus of thought toward the individual and observation — a mindset that underpins both Renaissance art and the later Scientific Revolution. It is a foundational idea of modern Western thought.

**Perspective/interpretation note.** Humanism did not reject religion; most humanists were devout Christians who saw studying the human and natural world as compatible with faith. Popular accounts sometimes over-state a "science vs religion" split.

**Misconception:** *"Humanism meant rejecting religion and becoming atheist."*
- *Why believed:* The modern word "humanism" is often linked to secularism/atheism.
- *Why wrong:* Renaissance humanists were **overwhelmingly religious**; humanism valued human potential *and* faith, studying classical and Christian texts together.
- *Corrective:* Renaissance humanism celebrated human reason and dignity *within* a largely Christian worldview.

**Command-term questions:**
1. *(Recall)* **Define** humanism and name one feature of Renaissance art.
2. *(Apply)* **Explain** how the use of perspective in painting reflected humanist values.
3. *(Analyse/Evaluate)* **Evaluate** how far humanism was responsible for both the artistic and scientific achievements of the Renaissance.','{"chapter":1,"humanism":10,"art":4,"and":16,"scientific":4,"innovation":2,"factual":1,"grounding":1,"was":2,"the":14,"defining":1,"intellectual":1,"movement":1,"renaissance":6,"emphasised":1,"value":1,"potential":2,"achievements":2,"individual":2,"human":5,"being":1,"studied":1,"humanities":1,"grammar":1,"rhetoric":1,"history":1,"poetry":1,"philosophy":1,"based":1,"classical":2,"texts":2,"encouraged":1,"observation":3,"reason":2,"secular":1,"alongside":1,"religious":3,"inquiry":1,"humanists":3,"were":3,"still":1,"mostly":1,"this":2,"produced":1,"realism":1,"perspective":3,"depth":1,"flat":1,"surface":1,"anatomical":1,"accuracy":1,"celebration":1,"beauty":1,"emotion":1,"clear":1,"break":1,"from":1,"flatter":1,"medieval":1,"styles":1,"same":1,"spirit":1,"questioning":1,"fed":1,"significance":1,"shifted":1,"focus":1,"thought":2,"toward":1,"mindset":1,"that":1,"underpins":1,"both":2,"later":1,"revolution":1,"foundational":1,"idea":1,"modern":2,"western":1,"interpretation":1,"note":1,"did":1,"not":1,"reject":1,"religion":3,"most":1,"devout":1,"christians":1,"who":1,"saw":1,"studying":2,"natural":1,"world":1,"compatible":1,"with":1,"faith":2,"popular":1,"accounts":1,"sometimes":1,"over":1,"state":1,"science":1,"split":1,"misconception":1,"meant":1,"rejecting":1,"becoming":1,"atheist":1,"why":2,"believed":1,"word":1,"often":1,"linked":1,"secularism":1,"atheism":1,"wrong":1,"overwhelmingly":1,"valued":1,"christian":2,"together":1,"corrective":1,"celebrated":1,"dignity":1,"within":1,"largely":1,"worldview":1,"command":1,"term":1,"questions":1,"recall":1,"define":1,"name":1,"one":1,"feature":1,"apply":1,"explain":1,"how":2,"use":1,"painting":1,"reflected":1,"humanist":1,"values":1,"analyse":1,"evaluate":2,"far":1,"responsible":1,"for":1,"artistic":1}'::jsonb),
('chunk_98168579aa28f41558','file_04bb580a3d99034261','history.md','Chapter 4.3 — Key Figures of the Renaissance and Scientific Revolution','**Factual grounding.**
- **Leonardo da Vinci (1452–1519):** Italian painter, inventor and anatomist — the archetypal "Renaissance man." Works: **Mona Lisa**, **The Last Supper**; thousands of notebook studies of anatomy, machines and nature. Embodies the union of art and science.
- **Michelangelo (1475–1564):** Italian sculptor, painter and architect. Works: statue of **David**, the **Sistine Chapel ceiling** (1508–1512), designs for **St Peter''s Basilica**. Master of the human form.
- **Nicolaus Copernicus (1473–1543):** Polish astronomer who proposed the **heliocentric model** — the **Sun**, not the Earth, at the centre of the solar system — in *On the Revolutions of the Heavenly Spheres* (**1543**). This challenged the long-accepted Earth-centred (geocentric) view.
- **Galileo Galilei (1564–1642):** Italian scientist; improved the **telescope** (from 1609) and observed Jupiter''s moons, lunar craters and the phases of Venus, providing evidence for the heliocentric model. Championed **observation and experiment**; famously tried by the Inquisition (1633) for supporting Copernicus.
- **Isaac Newton (1643–1727):** English scientist who unified physics with the **laws of motion** and **universal gravitation** in his ***Principia Mathematica* (1687)** — a capstone of the Scientific Revolution.

**Significance.** These figures show the Renaissance/Scientific Revolution''s core shift: from accepting authority/tradition to trusting **observation, evidence and reason**. Their work still underpins modern art and science.

**Perspective/interpretation note.** Galileo''s conflict is often told as "science vs. the Church," but it also involved politics, personality and how evidence was interpreted at the time — a caution against oversimplified good-vs-evil narratives.

**Misconception:** *"Copernicus/Galileo were the first to ever suggest the Earth moves, and everyone before thought the Earth was flat."*
- *Why believed:* Popular myths about a "flat-Earth Middle Ages."
- *Why wrong:* Educated people had known the Earth was **round** since antiquity (e.g., the ancient Greeks); the ancient thinker **Aristarchus** had even proposed a Sun-centred idea. The debate was **geocentric vs heliocentric**, not flat vs round.
- *Corrective:* The Scientific Revolution changed the model of the *cosmos* (Sun-centred), not a belief in a flat Earth.','{"1452":1,"1473":1,"1475":1,"1508":1,"1512":1,"1519":1,"1543":2,"1564":2,"1609":1,"1633":1,"1642":1,"1643":1,"1687":1,"1727":1,"chapter":1,"key":1,"figures":2,"the":33,"renaissance":3,"and":13,"scientific":4,"revolution":4,"factual":1,"grounding":1,"leonardo":1,"vinci":1,"italian":3,"painter":2,"inventor":1,"anatomist":1,"archetypal":1,"man":1,"works":2,"mona":1,"lisa":1,"last":1,"supper":1,"thousands":1,"notebook":1,"studies":1,"anatomy":1,"machines":1,"nature":1,"embodies":1,"union":1,"art":2,"science":3,"michelangelo":1,"sculptor":1,"architect":1,"statue":1,"david":1,"sistine":1,"chapel":1,"ceiling":1,"designs":1,"for":3,"peter":1,"basilica":1,"master":1,"human":1,"form":1,"nicolaus":1,"copernicus":3,"polish":1,"astronomer":1,"who":2,"proposed":2,"heliocentric":3,"model":3,"sun":3,"not":3,"earth":7,"centre":1,"solar":1,"system":1,"revolutions":1,"heavenly":1,"spheres":1,"this":1,"challenged":1,"long":1,"accepted":1,"centred":3,"geocentric":2,"view":1,"galileo":3,"galilei":1,"scientist":2,"improved":1,"telescope":1,"from":2,"observed":1,"jupiter":1,"moons":1,"lunar":1,"craters":1,"phases":1,"venus":1,"providing":1,"evidence":3,"championed":1,"observation":2,"experiment":1,"famously":1,"tried":1,"inquisition":1,"supporting":1,"isaac":1,"newton":1,"english":1,"unified":1,"physics":1,"with":1,"laws":1,"motion":1,"universal":1,"gravitation":1,"his":1,"principia":1,"mathematica":1,"capstone":1,"significance":1,"these":1,"show":1,"core":1,"shift":1,"accepting":1,"authority":1,"tradition":1,"trusting":1,"reason":1,"their":1,"work":1,"still":1,"underpins":1,"modern":1,"perspective":1,"interpretation":1,"note":1,"conflict":1,"often":1,"told":1,"church":1,"but":1,"also":1,"involved":1,"politics":1,"personality":1,"how":1,"was":4,"interpreted":1,"time":1,"caution":1,"against":1,"oversimplified":1,"good":1,"evil":1,"narratives":1,"misconception":1,"were":1,"first":1,"ever":1,"suggest":1,"moves":1,"everyone":1,"before":1,"thought":1,"flat":4,"why":2,"believed":1,"popular":1,"myths":1,"about":1,"middle":1,"ages":1,"wrong":1,"educated":1,"people":1,"had":2,"known":1,"round":2,"since":1,"antiquity":1,"ancient":2,"greeks":1,"thinker":1,"aristarchus":1,"even":1,"idea":1,"debate":1,"corrective":1,"changed":1,"cosmos":1,"belief":1}'::jsonb),
('chunk_618725de1de0465f28','file_04bb580a3d99034261','history.md','Renaissance & Scientific Revolution Figures Table','| Figure | Dates | Field | Key Work / Contribution | Significance |
|---|---|---|---|---|
| Leonardo da Vinci | 1452–1519 | Art, science, invention | Mona Lisa; Last Supper; anatomy/machine studies | Union of art and science; "Renaissance man" |
| Michelangelo | 1475–1564 | Sculpture, painting, architecture | David; Sistine Chapel ceiling (1508–12) | Peak mastery of the human form |
| Copernicus | 1473–1543 | Astronomy | Heliocentric model (1543) | Displaced Earth from the centre |
| Galileo | 1564–1642 | Physics, astronomy | Telescopic evidence; experiment | Championed observation; backed heliocentrism |
| Newton | 1643–1727 | Physics, mathematics | Laws of motion & gravity; *Principia* (1687) | Unified physics; capstone of the revolution |

**Command-term questions:**
1. *(Recall)* **Match** each figure to their key contribution: Copernicus, Galileo, Newton, Leonardo, Michelangelo.
2. *(Apply)* **Explain** how Galileo''s use of the telescope supported Copernicus''s model.
3. *(Analyse/Evaluate)* **To what extent** was Newton''s work the true climax of the Scientific Revolution?','{"1452":1,"1473":1,"1475":1,"1508":1,"1519":1,"1543":2,"1564":2,"1642":1,"1643":1,"1687":1,"1727":1,"renaissance":2,"scientific":2,"revolution":3,"figures":1,"table":1,"figure":2,"dates":1,"field":1,"key":2,"work":2,"contribution":2,"significance":1,"leonardo":2,"vinci":1,"art":2,"science":2,"invention":1,"mona":1,"lisa":1,"last":1,"supper":1,"anatomy":1,"machine":1,"studies":1,"union":1,"and":1,"man":1,"michelangelo":2,"sculpture":1,"painting":1,"architecture":1,"david":1,"sistine":1,"chapel":1,"ceiling":1,"peak":1,"mastery":1,"the":6,"human":1,"form":1,"copernicus":3,"astronomy":2,"heliocentric":1,"model":2,"displaced":1,"earth":1,"from":1,"centre":1,"galileo":3,"physics":3,"telescopic":1,"evidence":1,"experiment":1,"championed":1,"observation":1,"backed":1,"heliocentrism":1,"newton":3,"mathematics":1,"laws":1,"motion":1,"gravity":1,"principia":1,"unified":1,"capstone":1,"command":1,"term":1,"questions":1,"recall":1,"match":1,"each":1,"their":1,"apply":1,"explain":1,"how":1,"use":1,"telescope":1,"supported":1,"analyse":1,"evaluate":1,"what":1,"extent":1,"was":1,"true":1,"climax":1}'::jsonb),
('chunk_1b0df63cbbdca7dfd6','file_04bb580a3d99034261','history.md','Chapter 4.4 — The Scientific Revolution and Early Scientific Thought','**Factual grounding.** The **Scientific Revolution** (roughly **1543–1687**, from Copernicus''s book to Newton''s *Principia*) was the transformation in how Europeans understood the natural world. Its heart was the **scientific method**: knowledge based on **observation, hypothesis, experiment and mathematics**, rather than solely on ancient authorities (like Aristotle) or religious doctrine. Thinkers such as **Francis Bacon** (championed inductive, experimental method) and **René Descartes** (mathematical reasoning) shaped this new approach. Breakthroughs spanned astronomy (heliocentrism), physics (motion, gravity), and biology/medicine (e.g., **William Harvey''s** description of blood circulation, 1628).

**Significance.** The Scientific Revolution created **modern science** and the evidence-based way of thinking that drives technology and inquiry today — a genuine **revolution** in knowledge, closely tied to the Renaissance emphasis on reason and observation.

**Perspective/interpretation note.** Historians debate whether it was a sudden "**revolution**" or a gradual **evolution** building on medieval Islamic and European scholarship (e.g., Ibn al-Haytham''s optics and emphasis on experiment centuries earlier). The dramatic term "revolution" is itself an interpretation.

**Misconception:** *"Before the Scientific Revolution, no one did any real science or experiments."*
- *Why believed:* The word "revolution" implies science began from nothing.
- *Why wrong:* **Ancient Greek, Islamic (e.g., Ibn al-Haytham, al-Khwarizmi) and medieval scholars** made major advances in mathematics, astronomy, optics and medicine; the Scientific Revolution **built on** them.
- *Corrective:* The Scientific Revolution transformed and systematised science; it did not invent inquiry from scratch.

**Command-term questions:**
1. *(Recall)* **State** the roughly agreed start and end points (and dates) of the Scientific Revolution.
2. *(Apply)* **Explain** how the scientific method differed from relying on ancient authorities.
3. *(Analyse/Evaluate)* **To what extent** was the Scientific Revolution a sudden break rather than a gradual evolution of earlier knowledge?

---','{"1543":1,"1628":1,"1687":1,"chapter":1,"the":17,"scientific":11,"revolution":12,"and":14,"early":1,"thought":1,"factual":1,"grounding":1,"roughly":2,"from":4,"copernicus":1,"book":1,"newton":1,"principia":1,"was":4,"transformation":1,"how":2,"europeans":1,"understood":1,"natural":1,"world":1,"its":1,"heart":1,"method":3,"knowledge":3,"based":2,"observation":2,"hypothesis":1,"experiment":2,"mathematics":2,"rather":2,"than":2,"solely":1,"ancient":3,"authorities":2,"like":1,"aristotle":1,"religious":1,"doctrine":1,"thinkers":1,"such":1,"francis":1,"bacon":1,"championed":1,"inductive":1,"experimental":1,"ren":1,"descartes":1,"mathematical":1,"reasoning":1,"shaped":1,"this":1,"new":1,"approach":1,"breakthroughs":1,"spanned":1,"astronomy":2,"heliocentrism":1,"physics":1,"motion":1,"gravity":1,"biology":1,"medicine":2,"william":1,"harvey":1,"description":1,"blood":1,"circulation":1,"significance":1,"created":1,"modern":1,"science":4,"evidence":1,"way":1,"thinking":1,"that":1,"drives":1,"technology":1,"inquiry":2,"today":1,"genuine":1,"closely":1,"tied":1,"renaissance":1,"emphasis":2,"reason":1,"perspective":1,"interpretation":2,"note":1,"historians":1,"debate":1,"whether":1,"sudden":2,"gradual":2,"evolution":2,"building":1,"medieval":2,"islamic":2,"european":1,"scholarship":1,"ibn":2,"haytham":2,"optics":2,"centuries":1,"earlier":2,"dramatic":1,"term":2,"itself":1,"misconception":1,"before":1,"one":1,"did":2,"any":1,"real":1,"experiments":1,"why":2,"believed":1,"word":1,"implies":1,"began":1,"nothing":1,"wrong":1,"greek":1,"khwarizmi":1,"scholars":1,"made":1,"major":1,"advances":1,"built":1,"them":1,"corrective":1,"transformed":1,"systematised":1,"not":1,"invent":1,"scratch":1,"command":1,"questions":1,"recall":1,"state":1,"agreed":1,"start":1,"end":1,"points":1,"dates":1,"apply":1,"explain":1,"differed":1,"relying":1,"analyse":1,"evaluate":1,"what":1,"extent":1,"break":1}'::jsonb),
('chunk_10858ed5116eab338c','file_04bb580a3d99034261','history.md','SUBJECT-WIDE: Common Misconceptions Master List','1. **Primary sources are always more reliable than secondary sources.** — Reliability depends on OPVL, not the label; primaries can be biased/propaganda.
2. **A source''s "limitation" means it is a bad source.** — Every source has limitations; identifying them is normal analysis, not condemnation.
3. **Empires are built mainly by military conquest.** — Administration, trade, law and ideology sustain empires; conquest alone rarely lasts.
4. **The Roman Empire fell suddenly in 476 CE.** — Only the *Western* empire ended (gradually); the *Eastern/Byzantine* empire lasted until 1453.
5. **The "Middle Ages / Dark Ages" were a time of total stagnation everywhere.** — Baghdad, Córdoba, Song China and the Cholas had golden ages of learning and trade.
6. **Feudalism was a single, planned, uniform system.** — It was a loose, regionally varied set of arrangements; the neat pyramid is a later simplification.
7. **The Silk Road was one paved road travelled end-to-end by single merchants.** — It was a shifting network of relays and middlemen.
8. **Trade routes only moved luxury goods.** — They also carried ideas, religions, technologies and diseases.
9. **Europeans were the first/only great ocean explorers.** — Zheng He''s Chinese fleets (from 1405), plus Arab, Indian and Polynesian navigators, came earlier.
10. **Europeans invented all navigation technology.** — The compass (China) and lateen sail (Arab/Mediterranean) were borrowed and improved.
11. **Explorers sailed mainly out of scientific curiosity.** — Core motives were the 3 Gs: God, Glory and Gold.
12. **The Columbian Exchange was mostly a happy sharing of foods.** — Its deadliest effect was disease that devastated Indigenous Americans, plus the slave trade.
13. **The Renaissance rediscovered knowledge that had been completely lost.** — Byzantine and Islamic scholars had preserved it; the Renaissance built on that.
14. **Humanism meant rejecting religion/atheism.** — Renaissance humanists were mostly devout; humanism valued human reason *and* faith.
15. **People before Copernicus thought the Earth was flat.** — Educated people knew it was round; the real shift was geocentric → heliocentric.
16. **No real science existed before the Scientific Revolution.** — Greek, Islamic and medieval scholars made major advances first.

---','{"476":1,"1405":1,"1453":1,"subject":1,"wide":1,"common":1,"misconceptions":1,"master":1,"list":1,"primary":1,"sources":2,"are":2,"always":1,"more":1,"reliable":1,"than":1,"secondary":1,"reliability":1,"depends":1,"opvl":1,"not":2,"the":18,"label":1,"primaries":1,"can":1,"biased":1,"propaganda":1,"source":3,"limitation":1,"means":1,"bad":1,"every":1,"has":1,"limitations":1,"identifying":1,"them":1,"normal":1,"analysis":1,"condemnation":1,"empires":2,"built":2,"mainly":2,"military":1,"conquest":2,"administration":1,"trade":4,"law":1,"and":12,"ideology":1,"sustain":1,"alone":1,"rarely":1,"lasts":1,"roman":1,"empire":3,"fell":1,"suddenly":1,"only":3,"western":1,"ended":1,"gradually":1,"eastern":1,"byzantine":2,"lasted":1,"until":1,"middle":1,"ages":3,"dark":1,"were":5,"time":1,"total":1,"stagnation":1,"everywhere":1,"baghdad":1,"rdoba":1,"song":1,"china":2,"cholas":1,"had":3,"golden":1,"learning":1,"feudalism":1,"was":9,"single":2,"planned":1,"uniform":1,"system":1,"loose":1,"regionally":1,"varied":1,"set":1,"arrangements":1,"neat":1,"pyramid":1,"later":1,"simplification":1,"silk":1,"road":2,"one":1,"paved":1,"travelled":1,"end":2,"merchants":1,"shifting":1,"network":1,"relays":1,"middlemen":1,"routes":1,"moved":1,"luxury":1,"goods":1,"they":1,"also":1,"carried":1,"ideas":1,"religions":1,"technologies":1,"diseases":1,"europeans":2,"first":2,"great":1,"ocean":1,"explorers":2,"zheng":1,"chinese":1,"fleets":1,"from":1,"plus":2,"arab":2,"indian":1,"polynesian":1,"navigators":1,"came":1,"earlier":1,"invented":1,"all":1,"navigation":1,"technology":1,"compass":1,"lateen":1,"sail":1,"mediterranean":1,"borrowed":1,"improved":1,"sailed":1,"out":1,"scientific":2,"curiosity":1,"core":1,"motives":1,"god":1,"glory":1,"gold":1,"columbian":1,"exchange":1,"mostly":2,"happy":1,"sharing":1,"foods":1,"its":1,"deadliest":1,"effect":1,"disease":1,"that":3,"devastated":1,"indigenous":1,"americans":1,"slave":1,"renaissance":3,"rediscovered":1,"knowledge":1,"been":1,"completely":1,"lost":1,"islamic":2,"scholars":2,"preserved":1,"humanism":2,"meant":1,"rejecting":1,"religion":1,"atheism":1,"humanists":1,"devout":1,"valued":1,"human":1,"reason":1,"faith":1,"people":2,"before":2,"copernicus":1,"thought":1,"earth":1,"flat":1,"educated":1,"knew":1,"round":1,"real":2,"shift":1,"geocentric":1,"heliocentric":1,"science":1,"existed":1,"revolution":1,"greek":1,"medieval":1,"made":1,"major":1,"advances":1}'::jsonb),
('chunk_2ee1217e354d07bca4','file_04bb580a3d99034261','history.md','SUBJECT-WIDE: Command-Term & Source-Analysis Question Bank','Use these to model IB command terms (define, identify, describe, outline, explain, compare, analyse, evaluate, discuss, "to what extent") and source skills (OPVL).

1. **Identify** the origin, purpose, value and limitations (OPVL) of a given royal inscription, propaganda poster, or explorer''s journal. *(Criterion D)*
2. **Compare and contrast** the two provided sources on the fall of an empire. In what ways do they agree and differ, and how do their **origins and purposes** explain the differences? *(Criterion D)*
3. **Evaluate** the value and limitations of a **primary** source and a **secondary** source for studying medieval Baghdad. Which is more useful, and for what enquiry? *(Criterion D)*
4. **To what extent** do empires collapse because of internal weakness rather than external attack? Support your answer with at least two case studies. *(Criteria A & D)*
5. **Analyse** the causes of the Age of Exploration using the 3 Gs, and explain which was most important. *(Criteria A & D)*
6. **Discuss** the extent to which the Columbian Exchange''s benefits outweighed its harms, considering multiple perspectives. *(Criterion D)*
7. **Using the source provided, and your own knowledge, explain** how far the source supports the view that the Renaissance was a complete break from the medieval past. *(Criterion D)*
8. **Formulate** a focused research question and outline a source-based investigation into the achievements of one empire (Gupta, Roman, Byzantine, Chola or Vijayanagara). *(Criterion B)*

---','{"subject":1,"wide":1,"command":2,"term":1,"source":7,"analysis":1,"question":2,"bank":1,"use":1,"these":1,"model":1,"terms":1,"define":1,"identify":2,"describe":1,"outline":2,"explain":4,"compare":2,"analyse":2,"evaluate":2,"discuss":2,"what":4,"extent":3,"and":12,"skills":1,"opvl":2,"the":16,"origin":1,"purpose":1,"value":2,"limitations":2,"given":1,"royal":1,"inscription":1,"propaganda":1,"poster":1,"explorer":1,"journal":1,"criterion":6,"contrast":1,"two":2,"provided":2,"sources":1,"fall":1,"empire":2,"ways":1,"they":1,"agree":1,"differ":1,"how":2,"their":1,"origins":1,"purposes":1,"differences":1,"primary":1,"secondary":1,"for":2,"studying":1,"medieval":2,"baghdad":1,"which":3,"more":1,"useful":1,"enquiry":1,"empires":1,"collapse":1,"because":1,"internal":1,"weakness":1,"rather":1,"than":1,"external":1,"attack":1,"support":1,"your":2,"answer":1,"with":1,"least":1,"case":1,"studies":1,"criteria":2,"causes":1,"age":1,"exploration":1,"using":2,"was":2,"most":1,"important":1,"columbian":1,"exchange":1,"benefits":1,"outweighed":1,"its":1,"harms":1,"considering":1,"multiple":1,"perspectives":1,"own":1,"knowledge":1,"far":1,"supports":1,"view":1,"that":1,"renaissance":1,"complete":1,"break":1,"from":1,"past":1,"formulate":1,"focused":1,"research":1,"based":1,"investigation":1,"into":1,"achievements":1,"one":1,"gupta":1,"roman":1,"byzantine":1,"chola":1,"vijayanagara":1}'::jsonb),
('chunk_4af7ae96ee39afbc26','file_04bb580a3d99034261','history.md','CROSS-SUBJECT CONNECTIONS','- **Geography (I&S / MYP Geography):** Trade routes, the Silk Route and exploration all depend on **maps, latitude/longitude, coastlines, winds, monsoons and resources**. The geographic factors in empire-building (rivers, defensible borders, ports) connect directly to Geography''s study of location, climate and settlement. The Columbian Exchange links to **biomes, ecosystems and human migration**.
- **Chemistry / Physics (MYP Sciences — for the Scientific Revolution):** Newton''s **laws of motion and gravity** and Galileo''s studies of falling bodies and the **telescope** connect to Physics (forces, motion, optics, astronomy). Renaissance metallurgy, gunpowder and the later development of the scientific method connect to Chemistry and the **experimental method** taught in Sciences. Gupta-era metallurgy (the rust-resistant Iron Pillar) links to Chemistry (corrosion/oxidation).
- **Visual Art (MYP Arts — for the Renaissance):** Renaissance innovations in **linear perspective, proportion, anatomy, chiaroscuro (light and shadow) and realism** are foundational to Visual Art. Studying Leonardo and Michelangelo connects historical context to art techniques, composition and the role of patronage (the Medici) in cultural production.
- **Mathematics:** The Gupta **decimal system and zero**, al-Khwarizmi''s **algebra** in Baghdad, and Renaissance perspective (geometry) all connect History to Mathematics.
- **Language & Literature / Language Acquisition:** OPVL, bias and reliability build critical reading skills; the printing press and the spread of vernacular literature connect to the study of texts and communication.

---
*End of Grade 7 History knowledge base.*','{"cross":1,"subject":1,"connections":1,"geography":3,"myp":3,"trade":1,"routes":1,"the":16,"silk":1,"route":1,"and":18,"exploration":1,"all":2,"depend":1,"maps":1,"latitude":1,"longitude":1,"coastlines":1,"winds":1,"monsoons":1,"resources":1,"geographic":1,"factors":1,"empire":1,"building":1,"rivers":1,"defensible":1,"borders":1,"ports":1,"connect":5,"directly":1,"study":2,"location":1,"climate":1,"settlement":1,"columbian":1,"exchange":1,"links":2,"biomes":1,"ecosystems":1,"human":1,"migration":1,"chemistry":3,"physics":2,"sciences":2,"for":2,"scientific":2,"revolution":1,"newton":1,"laws":1,"motion":2,"gravity":1,"galileo":1,"studies":1,"falling":1,"bodies":1,"telescope":1,"forces":1,"optics":1,"astronomy":1,"renaissance":4,"metallurgy":2,"gunpowder":1,"later":1,"development":1,"method":2,"experimental":1,"taught":1,"gupta":2,"era":1,"rust":1,"resistant":1,"iron":1,"pillar":1,"corrosion":1,"oxidation":1,"visual":2,"art":3,"arts":1,"innovations":1,"linear":1,"perspective":2,"proportion":1,"anatomy":1,"chiaroscuro":1,"light":1,"shadow":1,"realism":1,"are":1,"foundational":1,"studying":1,"leonardo":1,"michelangelo":1,"connects":1,"historical":1,"context":1,"techniques":1,"composition":1,"role":1,"patronage":1,"medici":1,"cultural":1,"production":1,"mathematics":2,"decimal":1,"system":1,"zero":1,"khwarizmi":1,"algebra":1,"baghdad":1,"geometry":1,"history":2,"language":2,"literature":2,"acquisition":1,"opvl":1,"bias":1,"reliability":1,"build":1,"critical":1,"reading":1,"skills":1,"printing":1,"press":1,"spread":1,"vernacular":1,"texts":1,"communication":1,"end":1,"grade":1,"knowledge":1,"base":1}'::jsonb),
('chunk_42d4ae074b1e77a512','file_9635f055da2d10cf4a','language-and-literature.md','Grade 7 Language & Literature (English) — Knowledge Base','**School:** IISH MYP | **Academic Year:** 2026-2027 | **MYP Year:** 2 (Grade 7)
**Subject group:** Language and Literature | **Language:** English

This file is a teaching-assistant reference for the Grade 7 English Language & Literature course. It is organised Unit → component (literary text / poetry / non-literary form / writing form / grammar) → concept entries, followed by whole-course reference sections (glossary, misconceptions, question bank, cross-subject links).

---','{"2026":1,"2027":1,"grade":3,"language":4,"literature":3,"english":3,"knowledge":1,"base":1,"school":1,"iish":1,"myp":2,"academic":1,"year":2,"subject":2,"group":1,"and":1,"this":1,"file":1,"teaching":1,"assistant":1,"reference":2,"for":1,"the":1,"course":2,"organised":1,"unit":1,"component":1,"literary":2,"text":1,"poetry":1,"non":1,"form":2,"writing":1,"grammar":1,"concept":1,"entries":1,"followed":1,"whole":1,"sections":1,"glossary":1,"misconceptions":1,"question":1,"bank":1,"cross":1,"links":1}'::jsonb),
('chunk_33888dfce11eb5bd8f','file_9635f055da2d10cf4a','language-and-literature.md','What Language & Literature is in the MYP','Language & Literature is one of the eight MYP subject groups. It develops students as analytical, imaginative and critical readers, writers, listeners and speakers. Students study a balance of **literary texts** (novels, short stories, poetry, drama) and **non-literary texts** (advertisements, film, blogs, articles, speeches). The aim is not just to understand *what* a text says, but *how* and *why* it produces meaning and effect, and then to produce and use language skilfully themselves.','{"what":2,"language":3,"literature":2,"the":3,"myp":2,"one":1,"eight":1,"subject":1,"groups":1,"develops":1,"students":2,"analytical":1,"imaginative":1,"and":7,"critical":1,"readers":1,"writers":1,"listeners":1,"speakers":1,"study":1,"balance":1,"literary":2,"texts":2,"novels":1,"short":1,"stories":1,"poetry":1,"drama":1,"non":1,"advertisements":1,"film":1,"blogs":1,"articles":1,"speeches":1,"aim":1,"not":1,"just":1,"understand":1,"text":1,"says":1,"but":1,"how":1,"why":1,"produces":1,"meaning":1,"effect":1,"then":1,"produce":1,"use":1,"skilfully":1,"themselves":1}'::jsonb),
('chunk_bb128c0e9cb2254872','file_9635f055da2d10cf4a','language-and-literature.md','The four assessment criteria','Each criterion is marked out of 8, using level descriptors (1-2, 3-4, 5-6, 7-8).

| Criterion | Name | Focuses on |
|-----------|------|-----------|
| **A** | Analysing | Identifying and interpreting content, context, meaning; analysing the effects of the creator''s choices; justifying opinions with evidence from the text. |
| **B** | Organizing | Structuring ideas and arguments coherently; using organisational structures that suit the form; following conventions of referencing and layout. |
| **C** | Producing text | Producing creative, original texts; making stylistic and thoughtful choices; showing awareness of impact on an audience; demonstrating personal engagement. |
| **D** | Using language | Using accurate and varied vocabulary, grammar and syntax; using correct register and style; using appropriate spelling, punctuation and pronunciation. |

A quick way to remember: **A** = read and think, **B** = shape it, **C** = create it, **D** = say/write it correctly.','{"the":5,"four":1,"assessment":1,"criteria":1,"each":1,"criterion":2,"marked":1,"out":1,"using":6,"level":1,"descriptors":1,"name":1,"focuses":1,"analysing":2,"identifying":1,"and":9,"interpreting":1,"content":1,"context":1,"meaning":1,"effects":1,"creator":1,"choices":2,"justifying":1,"opinions":1,"with":1,"evidence":1,"from":1,"text":2,"organizing":1,"structuring":1,"ideas":1,"arguments":1,"coherently":1,"organisational":1,"structures":1,"that":1,"suit":1,"form":1,"following":1,"conventions":1,"referencing":1,"layout":1,"producing":2,"creative":1,"original":1,"texts":1,"making":1,"stylistic":1,"thoughtful":1,"showing":1,"awareness":1,"impact":1,"audience":1,"demonstrating":1,"personal":1,"engagement":1,"language":1,"accurate":1,"varied":1,"vocabulary":1,"grammar":1,"syntax":1,"correct":1,"register":1,"style":1,"appropriate":1,"spelling":1,"punctuation":1,"pronunciation":1,"quick":1,"way":1,"remember":1,"read":1,"think":1,"shape":1,"create":1,"say":1,"write":1,"correctly":1}'::jsonb),
('chunk_fa46b245f2d02b64a8','file_9635f055da2d10cf4a','language-and-literature.md','Key concepts (the big MYP lenses)','In Language & Literature the three key concepts most used are **Communication**, **Connections**, and **Creativity** (with **Perspective**, **Culture** and **Identity** appearing across other subjects). Each unit below states its key concept.','{"key":3,"concepts":2,"the":2,"big":1,"myp":1,"lenses":1,"language":1,"literature":1,"three":1,"most":1,"used":1,"are":1,"communication":1,"connections":1,"and":2,"creativity":1,"with":1,"perspective":1,"culture":1,"identity":1,"appearing":1,"across":1,"other":1,"subjects":1,"each":1,"unit":1,"below":1,"states":1,"its":1,"concept":1}'::jsonb),
('chunk_3291a40b074091d244','file_9635f055da2d10cf4a','language-and-literature.md','Related concepts for Language & Literature','These are the subject-specific "middle-sized" ideas that focus a unit:

- **Theme** — the central idea or message.
- **Character** — the people/agents in a text and how they are constructed.
- **Setting** — time and place, and its effect.
- **Point of view** — who tells the story and from what position.
- **Purpose** — why a text was made (to persuade, inform, entertain, etc.).
- **Audience imperatives** — what a particular audience needs/expects.
- **Style** — the distinctive way language is used.
- **Structure** — how a text is organised.
- **Self-expression** — communicating one''s own identity, feelings, ideas.
- **Context** — the historical, cultural, social circumstances around a text.
- **Genre** — the type/category of text and its conventions.
- **Voice** — the distinctive personality or attitude in a text.

---','{"related":1,"concepts":1,"for":1,"language":2,"literature":1,"these":1,"are":2,"the":8,"subject":1,"specific":1,"middle":1,"sized":1,"ideas":2,"that":1,"focus":1,"unit":1,"theme":1,"central":1,"idea":1,"message":1,"character":1,"people":1,"agents":1,"text":6,"and":5,"how":2,"they":1,"constructed":1,"setting":1,"time":1,"place":1,"its":2,"effect":1,"point":1,"view":1,"who":1,"tells":1,"story":1,"from":1,"what":2,"position":1,"purpose":1,"why":1,"was":1,"made":1,"persuade":1,"inform":1,"entertain":1,"etc":1,"audience":2,"imperatives":1,"particular":1,"needs":1,"expects":1,"style":1,"distinctive":2,"way":1,"used":1,"structure":1,"organised":1,"self":1,"expression":1,"communicating":1,"one":1,"own":1,"identity":1,"feelings":1,"context":1,"historical":1,"cultural":1,"social":1,"circumstances":1,"around":1,"genre":1,"type":1,"category":1,"conventions":1,"voice":1,"personality":1,"attitude":1}'::jsonb),
('chunk_0bbf77735882a78e29','file_9635f055da2d10cf4a','language-and-literature.md','Unit 1: Identity in Making','- **Key Concept:** Identity (with Communication)
- **Related Concepts:** Character, Point of view, Purpose, Audience imperatives
- **Global Context:** Identities and Relationships
- **Statement of Inquiry:** The way people communicate their identity through language and choices shapes how others perceive and relate to them.
- **Inquiry Questions:**
  - *Factual:* What choices does an author or advertiser make to present a character or product? What are the features of a persuasive text?
  - *Conceptual:* How do our relationships and circumstances shape our identity? How does point of view influence what we believe about a character?
  - *Debatable:* Can we ever fully control how others perceive our identity? Is persuasion a form of manipulation or empowerment?','{"unit":1,"identity":5,"making":1,"key":1,"concept":1,"with":1,"communication":1,"related":1,"concepts":1,"character":3,"point":2,"view":2,"purpose":1,"audience":1,"imperatives":1,"global":1,"context":1,"identities":1,"and":4,"relationships":2,"statement":1,"inquiry":2,"the":2,"way":1,"people":1,"communicate":1,"their":1,"through":1,"language":1,"choices":2,"shapes":1,"how":4,"others":2,"perceive":2,"relate":1,"them":1,"questions":1,"factual":1,"what":3,"does":2,"author":1,"advertiser":1,"make":1,"present":1,"product":1,"are":1,"features":1,"persuasive":1,"text":1,"conceptual":1,"our":3,"circumstances":1,"shape":1,"influence":1,"believe":1,"about":1,"debatable":1,"can":1,"ever":1,"fully":1,"control":1,"persuasion":1,"form":1,"manipulation":1,"empowerment":1}'::jsonb),
('chunk_712a02008ac8b17a63','file_9635f055da2d10cf4a','language-and-literature.md','Literary text — *Ghost* by Jason Reynolds','**Summary.** *Ghost* (2016) is the first book in Jason Reynolds'' *Track* series. Castle Cranshaw, who calls himself "Ghost," is a talented but troubled middle-school boy from a poor neighbourhood. He carries trauma: his father, drunk, once fired a gun at him and his mother, and they had to run for their lives — the moment that made Ghost a fast runner. When he impulsively challenges a runner at a track practice and keeps pace in his everyday clothes, Coach Brody recruits him onto an elite youth track team, the Defenders. Ghost must learn self-control, deal with a shoplifting incident (he steals running shoes), face bullying about his poverty, and decide whether to let his past define him or run toward a better future.

**Author & context.** Jason Reynolds is an award-winning American author known for writing honestly for young people, especially Black boys, in accessible, first-person voices. The novel is contemporary, set in an unnamed American city, and deals with poverty, family trauma, and second chances.

**Key themes.** Identity and self-definition; the weight of the past vs. the possibility of change; running as both escape and pursuit; mentorship and belonging; poverty and dignity; anger and self-control.

**Main characters.**
- *Castle "Ghost" Cranshaw* — narrator; impulsive, funny, wounded, quick.
- *Coach Brody* — former Olympic hopeful; taxi driver; firm mentor who believes in Ghost.
- *Ghost''s mother* — works long hours in a hospital cafeteria; loving, exhausted.
- *Ghost''s father* — imprisoned for the shooting; source of Ghost''s trauma.
- *Teammates* — Lu, Patina (Patty), and Sunny, each with their own struggles.

**Literary devices to teach.** First-person narrative voice and colloquial register; the extended metaphor of *running* (from vs. toward); symbolism of the silver running shoes; foreshadowing (the "scream inside"); characterisation through dialogue; internal conflict.

**Link to the unit concept.** Ghost is literally an identity "in the making." The novel shows how relationships (with Coach, teammates, mother) and context (poverty, trauma) shape who he is becoming. Point of view matters: because Ghost narrates, readers experience his self-perception versus how others see him — a direct route into the Global Context *Identities and Relationships*.

**Command-term questions.**
- *Analyse* how Reynolds uses the first-person voice to build sympathy for Ghost.
- *Interpret* the symbolism of the new running shoes.
- *Evaluate* whether Coach Brody is a good mentor. Justify with evidence.','{"2016":1,"literary":2,"text":1,"ghost":13,"jason":3,"reynolds":4,"summary":1,"the":18,"first":4,"book":1,"track":3,"series":1,"castle":2,"cranshaw":2,"who":3,"calls":1,"himself":1,"talented":1,"but":1,"troubled":1,"middle":1,"school":1,"boy":1,"from":2,"poor":1,"neighbourhood":1,"carries":1,"trauma":4,"his":6,"father":2,"drunk":1,"once":1,"fired":1,"gun":1,"him":4,"and":15,"mother":3,"they":1,"had":1,"run":2,"for":5,"their":2,"lives":1,"moment":1,"that":1,"made":1,"fast":1,"runner":2,"when":1,"impulsively":1,"challenges":1,"practice":1,"keeps":1,"pace":1,"everyday":1,"clothes":1,"coach":4,"brody":3,"recruits":1,"onto":1,"elite":1,"youth":1,"team":1,"defenders":1,"must":1,"learn":1,"self":4,"control":2,"deal":1,"with":5,"shoplifting":1,"incident":1,"steals":1,"running":5,"shoes":3,"face":1,"bullying":1,"about":1,"poverty":4,"decide":1,"whether":2,"let":1,"past":2,"define":1,"toward":2,"better":1,"future":1,"author":2,"context":3,"award":1,"winning":1,"american":2,"known":1,"writing":1,"honestly":1,"young":1,"people":1,"especially":1,"black":1,"boys":1,"accessible":1,"person":3,"voices":1,"novel":2,"contemporary":1,"set":1,"unnamed":1,"city":1,"deals":1,"family":1,"second":1,"chances":1,"key":1,"themes":1,"identity":2,"definition":1,"weight":1,"possibility":1,"change":1,"both":1,"escape":1,"pursuit":1,"mentorship":1,"belonging":1,"dignity":1,"anger":1,"main":1,"characters":1,"narrator":1,"impulsive":1,"funny":1,"wounded":1,"quick":1,"former":1,"olympic":1,"hopeful":1,"taxi":1,"driver":1,"firm":1,"mentor":2,"believes":1,"works":1,"long":1,"hours":1,"hospital":1,"cafeteria":1,"loving":1,"exhausted":1,"imprisoned":1,"shooting":1,"source":1,"teammates":2,"patina":1,"patty":1,"sunny":1,"each":1,"own":1,"struggles":1,"devices":1,"teach":1,"narrative":1,"voice":2,"colloquial":1,"register":1,"extended":1,"metaphor":1,"symbolism":2,"silver":1,"foreshadowing":1,"scream":1,"inside":1,"characterisation":1,"through":1,"dialogue":1,"internal":1,"conflict":1,"link":1,"unit":1,"concept":1,"literally":1,"making":1,"shows":1,"how":3,"relationships":2,"shape":1,"becoming":1,"point":1,"view":1,"matters":1,"because":1,"narrates":1,"readers":1,"experience":1,"perception":1,"versus":1,"others":1,"see":1,"direct":1,"route":1,"into":1,"global":1,"identities":1,"command":1,"term":1,"questions":1,"analyse":1,"uses":1,"build":1,"sympathy":1,"interpret":1,"new":1,"evaluate":1,"good":1,"justify":1,"evidence":1}'::jsonb);