INSERT INTO syllabus_chunks (id, file_id, file_name, heading, body, tf) VALUES
('chunk_d4aabf673cfd470edd','file_9635f055da2d10cf4a','language-and-literature.md','Non-literary text — The Advertisement','**Why study it.** Advertisements are compact persuasive texts that reveal how creators shape identity and desire. They belong to Criterion A (analysing non-literary text) and feed the unit''s writing on persuasion.

**Analysis toolkit.**

| Element | Questions to ask |
|---------|------------------|
| **Purpose** | Is it selling a product, an idea, a lifestyle, a brand image? What action does it want? |
| **Target audience** | Who is it for (age, gender, interests)? How do you know? |
| **Visual elements** | Colour (warm/cool, brand colours), images, models, layout, focal point, use of space, typography/font. |
| **Language** | Slogan, tagline, imperatives ("Buy now"), puns, exaggeration. |
| **Persuasive techniques** | Ethos (credibility/celebrity endorsement), pathos (emotion), logos (facts/statistics), bandwagon ("everyone''s using it"), aspiration, humour, repetition. |

**Real-world use.** Being able to decode ads makes students critical consumers who resist manipulation and understand marketing — a media-literacy life skill.

**Analogy.** An advertisement is like a stage magician: it directs your attention to one shining thing (the focal image) so you don''t notice the choices being made to influence you.

**Command-term question.** *Analyse* how the visual elements and language of a chosen advertisement work together to persuade its target audience.','{"non":2,"literary":2,"text":2,"the":5,"advertisement":3,"why":1,"study":1,"advertisements":1,"are":1,"compact":1,"persuasive":2,"texts":1,"that":1,"reveal":1,"how":3,"creators":1,"shape":1,"identity":1,"and":4,"desire":1,"they":1,"belong":1,"criterion":1,"analysing":1,"feed":1,"unit":1,"writing":1,"persuasion":1,"analysis":1,"toolkit":1,"element":1,"questions":1,"ask":1,"purpose":1,"selling":1,"product":1,"idea":1,"lifestyle":1,"brand":2,"image":2,"what":1,"action":1,"does":1,"want":1,"target":2,"audience":2,"who":2,"for":1,"age":1,"gender":1,"interests":1,"you":3,"know":1,"visual":2,"elements":2,"colour":1,"warm":1,"cool":1,"colours":1,"images":1,"models":1,"layout":1,"focal":2,"point":1,"use":2,"space":1,"typography":1,"font":1,"language":2,"slogan":1,"tagline":1,"imperatives":1,"buy":1,"now":1,"puns":1,"exaggeration":1,"techniques":1,"ethos":1,"credibility":1,"celebrity":1,"endorsement":1,"pathos":1,"emotion":1,"logos":1,"facts":1,"statistics":1,"bandwagon":1,"everyone":1,"using":1,"aspiration":1,"humour":1,"repetition":1,"real":1,"world":1,"being":2,"able":1,"decode":1,"ads":1,"makes":1,"students":1,"critical":1,"consumers":1,"resist":1,"manipulation":1,"understand":1,"marketing":1,"media":1,"literacy":1,"life":1,"skill":1,"analogy":1,"like":1,"stage":1,"magician":1,"directs":1,"your":1,"attention":1,"one":1,"shining":1,"thing":1,"don":1,"notice":1,"choices":1,"made":1,"influence":1,"command":1,"term":1,"question":1,"analyse":1,"chosen":1,"work":1,"together":1,"persuade":1,"its":1}'::jsonb),
('chunk_7bea3459b920ec6a58','file_9635f055da2d10cf4a','language-and-literature.md','Writing forms — Speech, Persuasive text, Persuasive blog','These three share the goal of **persuasion** but differ in medium and audience.','{"writing":1,"forms":1,"speech":1,"persuasive":2,"text":1,"blog":1,"these":1,"three":1,"share":1,"the":1,"goal":1,"persuasion":1,"but":1,"differ":1,"medium":1,"and":1,"audience":1}'::jsonb),
('chunk_169da8230c72e81273','file_9635f055da2d10cf4a','language-and-literature.md','Speech writing','- **Purpose:** to persuade, inspire or move a *listening* audience.
- **Audience:** present, live; cannot re-read, so ideas must be clear and repeated.
- **Structure/features:** strong hook/opening; clear thesis; 2-3 developed points; memorable close (call to action). Signposting ("First… Second… Finally").
- **Rhetorical devices:** *rhetorical questions*, *tricolon* (rule of three), *direct address* ("you"), *repetition/anaphora*, *emotive language*, *pauses*.
- **Checklist:** Hook? Clear stance? Rule of three? Rhetorical question? Call to action? Written for the ear (short sentences)?','{"speech":1,"writing":1,"purpose":1,"persuade":1,"inspire":1,"move":1,"listening":1,"audience":2,"present":1,"live":1,"cannot":1,"read":1,"ideas":1,"must":1,"clear":3,"and":1,"repeated":1,"structure":1,"features":1,"strong":1,"hook":2,"opening":1,"thesis":1,"developed":1,"points":1,"memorable":1,"close":1,"call":2,"action":2,"signposting":1,"first":1,"second":1,"finally":1,"rhetorical":3,"devices":1,"questions":1,"tricolon":1,"rule":2,"three":2,"direct":1,"address":1,"you":1,"repetition":1,"anaphora":1,"emotive":1,"language":1,"pauses":1,"checklist":1,"stance":1,"question":1,"written":1,"for":1,"the":1,"ear":1,"short":1,"sentences":1}'::jsonb),
('chunk_c4031ccf1291be3bca','file_9635f055da2d10cf4a','language-and-literature.md','Persuasive text','- **Purpose:** to convince a reader to accept a viewpoint or take action.
- **Structure:** introduction with a clear position → body paragraphs (point–evidence–explanation) → counter-argument + rebuttal → conclusion restating position.
- **Devices:** facts and statistics (logos), expert opinion (ethos), emotive appeals (pathos), modal verbs ("we must"), connectives of persuasion ("therefore," "as a result").','{"persuasive":1,"text":1,"purpose":1,"convince":1,"reader":1,"accept":1,"viewpoint":1,"take":1,"action":1,"structure":1,"introduction":1,"with":1,"clear":1,"position":2,"body":1,"paragraphs":1,"point":1,"evidence":1,"explanation":1,"counter":1,"argument":1,"rebuttal":1,"conclusion":1,"restating":1,"devices":1,"facts":1,"and":1,"statistics":1,"logos":1,"expert":1,"opinion":1,"ethos":1,"emotive":1,"appeals":1,"pathos":1,"modal":1,"verbs":1,"must":1,"connectives":1,"persuasion":1,"therefore":1,"result":1}'::jsonb),
('chunk_2189951ac6a2af512a','file_9635f055da2d10cf4a','language-and-literature.md','Persuasive blog','- **Purpose:** persuade an online audience; often personal and opinion-led.
- **Audience:** readers scrolling online — needs an engaging title, short paragraphs, subheadings.
- **Features:** informal but purposeful register; first-person voice; hyperlinks; a hook opening; direct reader address; a shareable, opinionated stance; call to action / invitation to comment.

**Mini worked model (blog opening).** *"Every morning, 800 million people wake up hungry — and I used to scroll right past that fact. Not anymore. Here''s why you should care too, and three things you can do before lunch today."* (Hook = statistic + personal turn; direct address; promise of a list.)

**Command-term question.** *Justify* which persuasive device is most effective for a live speech versus an online blog.','{"800":1,"persuasive":2,"blog":3,"purpose":1,"persuade":1,"online":3,"audience":2,"often":1,"personal":2,"and":3,"opinion":1,"led":1,"readers":1,"scrolling":1,"needs":1,"engaging":1,"title":1,"short":1,"paragraphs":1,"subheadings":1,"features":1,"informal":1,"but":1,"purposeful":1,"register":1,"first":1,"person":1,"voice":1,"hyperlinks":1,"hook":2,"opening":2,"direct":2,"reader":1,"address":2,"shareable":1,"opinionated":1,"stance":1,"call":1,"action":1,"invitation":1,"comment":1,"mini":1,"worked":1,"model":1,"every":1,"morning":1,"million":1,"people":1,"wake":1,"hungry":1,"used":1,"scroll":1,"right":1,"past":1,"that":1,"fact":1,"not":1,"anymore":1,"here":1,"why":1,"you":2,"should":1,"care":1,"too":1,"three":1,"things":1,"can":1,"before":1,"lunch":1,"today":1,"statistic":1,"turn":1,"promise":1,"list":1,"command":1,"term":1,"question":1,"justify":1,"which":1,"device":1,"most":1,"effective":1,"for":1,"live":1,"speech":1,"versus":1}'::jsonb),
('chunk_d295c8ffabb0b9e972','file_9635f055da2d10cf4a','language-and-literature.md','Nouns','| Type | Definition | Example |
|------|-----------|---------|
| Common | general person/place/thing | *city, coach, shoe* |
| Proper | specific name (capitalised) | *Ghost, Brody, October* |
| Abstract | idea/feeling | *identity, courage, fear* |
| Collective | group | *team, crowd, family* |
| Countable/Uncountable | can/can''t be counted | *shoes / advice* |

- **Rule:** Proper nouns are always capitalised; abstract nouns name things you cannot touch.
- **Common error:** Capitalising common nouns for emphasis ("I love my School"). *Correction:* only proper nouns are capitalised → "I love my school."
- **Real-world use:** precise nouns make persuasive writing concrete.
- **Practice:** Identify the abstract noun — "His *bravery* on the track surprised everyone." (Answer: bravery.)','{"nouns":6,"type":1,"definition":1,"example":1,"common":3,"general":1,"person":1,"place":1,"thing":1,"city":1,"coach":1,"shoe":1,"proper":3,"specific":1,"name":2,"capitalised":3,"ghost":1,"brody":1,"october":1,"abstract":3,"idea":1,"feeling":1,"identity":1,"courage":1,"fear":1,"collective":1,"group":1,"team":1,"crowd":1,"family":1,"countable":1,"uncountable":1,"can":2,"counted":1,"shoes":1,"advice":1,"rule":1,"are":2,"always":1,"things":1,"you":1,"cannot":1,"touch":1,"error":1,"capitalising":1,"for":1,"emphasis":1,"love":2,"school":2,"correction":1,"only":1,"real":1,"world":1,"use":1,"precise":1,"make":1,"persuasive":1,"writing":1,"concrete":1,"practice":1,"identify":1,"the":2,"noun":1,"his":1,"bravery":2,"track":1,"surprised":1,"everyone":1,"answer":1}'::jsonb),
('chunk_dfa321f11ec5e3f3cc','file_9635f055da2d10cf4a','language-and-literature.md','Adjectives — degrees of comparison','| Degree | Use | Short adj. | Long adj. |
|--------|-----|-----------|-----------|
| Positive | describe one | fast | interesting |
| Comparative | compare two | faster | more interesting |
| Superlative | compare 3+ | fastest | most interesting |

- **Rule:** short (1-syllable) adjectives add *-er/-est*; longer adjectives use *more/most*. Irregulars: good–better–best; bad–worse–worst.
- **Common error:** "double comparatives" — "more faster," "most fastest." *Correction:* "faster," "fastest."
- **Analogy:** think of a podium — positive = one runner, comparative = two runners racing, superlative = the whole medal stand.
- **Practice:** Complete — "Ghost is the ___ (fast) runner on the team." (Answer: fastest.)','{"adjectives":3,"degrees":1,"comparison":1,"degree":1,"use":2,"short":2,"adj":2,"long":1,"positive":2,"describe":1,"one":2,"fast":2,"interesting":3,"comparative":2,"compare":2,"two":2,"faster":3,"more":3,"superlative":2,"fastest":4,"most":3,"rule":1,"syllable":1,"add":1,"est":1,"longer":1,"irregulars":1,"good":1,"better":1,"best":1,"bad":1,"worse":1,"worst":1,"common":1,"error":1,"double":1,"comparatives":1,"correction":1,"analogy":1,"think":1,"podium":1,"runner":2,"runners":1,"racing":1,"the":3,"whole":1,"medal":1,"stand":1,"practice":1,"complete":1,"ghost":1,"team":1,"answer":1}'::jsonb),
('chunk_e5d9c310a4aacec2ac','file_9635f055da2d10cf4a','language-and-literature.md','Articles','- **Rule:** *a/an* = indefinite (any one; *an* before a vowel *sound*); *the* = definite (a specific one). Use no article for general plurals/uncountables ("Shoes are expensive").
- **Common error:** "an university," "a hour." *Correction:* "a university" (yoo-sound), "an hour" (silent h) — go by sound, not spelling.
- **Practice:** "Ghost wanted ___ new pair of shoes; ___ shoes he chose were silver." (Answer: a; the.)','{"articles":1,"rule":1,"indefinite":1,"any":1,"one":2,"before":1,"vowel":1,"sound":3,"the":2,"definite":1,"specific":1,"use":1,"article":1,"for":1,"general":1,"plurals":1,"uncountables":1,"shoes":3,"are":1,"expensive":1,"common":1,"error":1,"university":2,"hour":2,"correction":1,"yoo":1,"silent":1,"not":1,"spelling":1,"practice":1,"ghost":1,"wanted":1,"new":1,"pair":1,"chose":1,"were":1,"silver":1,"answer":1}'::jsonb),
('chunk_3922c74ee27eb2f787','file_9635f055da2d10cf4a','language-and-literature.md','Pronouns','| Type | Examples |
|------|----------|
| Personal | I, you, he, she, it, we, they |
| Possessive | mine, yours, his, hers, ours, theirs |
| Reflexive | myself, yourself, themselves |
| Relative | who, whom, which, that |
| Demonstrative | this, that, these, those |

- **Rule:** a pronoun must agree with its antecedent (the noun it replaces) in number and gender.
- **Common error:** unclear reference — "Ghost told Lu that he was wrong" (who?). *Correction:* rewrite for clarity.
- **Practice:** Replace the repeated noun — "Coach praised Ghost because Ghost tried hard." (Answer: …because *he* tried hard.)','{"pronouns":1,"type":1,"examples":1,"personal":1,"you":1,"she":1,"they":1,"possessive":1,"mine":1,"yours":1,"his":1,"hers":1,"ours":1,"theirs":1,"reflexive":1,"myself":1,"yourself":1,"themselves":1,"relative":1,"who":2,"whom":1,"which":1,"that":3,"demonstrative":1,"this":1,"these":1,"those":1,"rule":1,"pronoun":1,"must":1,"agree":1,"with":1,"its":1,"antecedent":1,"the":2,"noun":2,"replaces":1,"number":1,"and":1,"gender":1,"common":1,"error":1,"unclear":1,"reference":1,"ghost":3,"told":1,"was":1,"wrong":1,"correction":1,"rewrite":1,"for":1,"clarity":1,"practice":1,"replace":1,"repeated":1,"coach":1,"praised":1,"because":2,"tried":2,"hard":2,"answer":1}'::jsonb),
('chunk_31538c088485bf5fcd','file_9635f055da2d10cf4a','language-and-literature.md','Adverbs','- **Rule:** adverbs modify verbs, adjectives or other adverbs, telling *how, when, where, how often, to what degree* (quickly, yesterday, here, always, very). Many end in *-ly*.
- **Common error:** using an adjective for an adverb — "He ran quick." *Correction:* "He ran quickly."
- **Analogy:** if adjectives are make-up for nouns, adverbs are make-up for verbs.
- **Practice:** Identify the adverb — "Ghost *impulsively* joined the race." (Answer: impulsively.)

---','{"adverbs":4,"rule":1,"modify":1,"verbs":2,"adjectives":2,"other":1,"telling":1,"how":2,"when":1,"where":1,"often":1,"what":1,"degree":1,"quickly":2,"yesterday":1,"here":1,"always":1,"very":1,"many":1,"end":1,"common":1,"error":1,"using":1,"adjective":1,"for":3,"adverb":2,"ran":2,"quick":1,"correction":1,"analogy":1,"are":2,"make":2,"nouns":1,"practice":1,"identify":1,"the":2,"ghost":1,"impulsively":2,"joined":1,"race":1,"answer":1}'::jsonb),
('chunk_4d58389e279b5e9445','file_9635f055da2d10cf4a','language-and-literature.md','Unit 2: How Do We Separate Fact from Fiction?','- **Key Concept:** Communication (with Connections)
- **Related Concepts:** Context, Genre, Point of view, Purpose
- **Global Context:** Fairness and Development
- **Statement of Inquiry:** Writers blend historical fact and imaginative fiction to communicate truths about fairness, injustice and the human experience.
- **Inquiry Questions:**
  - *Factual:* What is historical fiction? What features distinguish fact from fiction in a text?
  - *Conceptual:* How does context shape the way a story about injustice is told and received? How does genre guide a reader''s expectations?
  - *Debatable:* Can fiction tell a "truer" truth than a history textbook? Is it fair for writers to reimagine real historical events?','{"unit":1,"how":3,"separate":1,"fact":3,"from":2,"fiction":5,"key":1,"concept":1,"communication":1,"with":1,"connections":1,"related":1,"concepts":1,"context":3,"genre":2,"point":1,"view":1,"purpose":1,"global":1,"fairness":2,"and":4,"development":1,"statement":1,"inquiry":2,"writers":2,"blend":1,"historical":3,"imaginative":1,"communicate":1,"truths":1,"about":2,"injustice":2,"the":2,"human":1,"experience":1,"questions":1,"factual":1,"what":2,"features":1,"distinguish":1,"text":1,"conceptual":1,"does":2,"shape":1,"way":1,"story":1,"told":1,"received":1,"guide":1,"reader":1,"expectations":1,"debatable":1,"can":1,"tell":1,"truer":1,"truth":1,"than":1,"history":1,"textbook":1,"fair":1,"for":1,"reimagine":1,"real":1,"events":1}'::jsonb),
('chunk_677ec16cd65c665e3d','file_9635f055da2d10cf4a','language-and-literature.md','"The Last Leaf" — William Sydney Porter (O. Henry)','**Summary.** In Greenwich Village, a young artist, Johnsy, falls gravely ill with pneumonia and becomes convinced she will die when the last leaf falls from the ivy vine outside her window. Her friend Sue cares for her. An old, failed artist downstairs, Behrman, who has long dreamed of painting a masterpiece, secretly paints a leaf on the wall during a freezing, stormy night so that the "last leaf" never falls — giving Johnsy the will to live. Johnsy recovers, but Behrman catches pneumonia from the exposure and dies. The painted leaf was his masterpiece.
**Author & context.** O. Henry (pen name of William Sydney Porter) was an American writer famous for warm, ironic stories with surprise "twist" endings. Early 20th-century New York.
**Themes.** Self-sacrifice; hope and the will to live; art as an act of love; the value of an unnoticed life.
**Devices.** Situational irony and the twist ending; symbolism (the leaf = hope/life); foreshadowing; characterisation of Behrman.
**Link to unit:** blends realistic setting with a fictional, meaningful event — communicating a truth about sacrifice and fairness (the "worthless" old man is the true hero).','{"the":14,"last":3,"leaf":6,"william":2,"sydney":2,"porter":2,"henry":2,"summary":1,"greenwich":1,"village":1,"young":1,"artist":2,"johnsy":3,"falls":3,"gravely":1,"ill":1,"with":3,"pneumonia":2,"and":5,"becomes":1,"convinced":1,"she":1,"will":3,"die":1,"when":1,"from":2,"ivy":1,"vine":1,"outside":1,"her":3,"window":1,"friend":1,"sue":1,"cares":1,"for":2,"old":2,"failed":1,"downstairs":1,"behrman":3,"who":1,"has":1,"long":1,"dreamed":1,"painting":1,"masterpiece":2,"secretly":1,"paints":1,"wall":1,"during":1,"freezing":1,"stormy":1,"night":1,"that":1,"never":1,"giving":1,"live":2,"recovers":1,"but":1,"catches":1,"exposure":1,"dies":1,"painted":1,"was":2,"his":1,"author":1,"context":1,"pen":1,"name":1,"american":1,"writer":1,"famous":1,"warm":1,"ironic":1,"stories":1,"surprise":1,"twist":2,"endings":1,"early":1,"20th":1,"century":1,"new":1,"york":1,"themes":1,"self":1,"sacrifice":2,"hope":2,"art":1,"act":1,"love":1,"value":1,"unnoticed":1,"life":2,"devices":1,"situational":1,"irony":1,"ending":1,"symbolism":1,"foreshadowing":1,"characterisation":1,"link":1,"unit":1,"blends":1,"realistic":1,"setting":1,"fictional":1,"meaningful":1,"event":1,"communicating":1,"truth":1,"about":1,"fairness":1,"worthless":1,"man":1,"true":1,"hero":1}'::jsonb),
('chunk_6e1dceaff332276ca1','file_9635f055da2d10cf4a','language-and-literature.md','"The Drummer Boy of Shiloh" — Ray Bradbury','**Summary.** On the eve of the Battle of Shiloh (American Civil War, 1862), a frightened young drummer boy, Joby, lies awake, afraid he will be useless because he carries only a drum, not a weapon. The General walks the camp and speaks to him, explaining that the drummer is the "heart" of the army — his drumbeat sets the courage and pace of every soldier. Joby is reassured that he has a vital role.
**Author & context.** Ray Bradbury, celebrated American author; here writing historical fiction about a real Civil War battle.
**Themes.** Courage and fear; the importance of every individual; leadership and reassurance; coming of age.
**Devices.** Setting/atmosphere; the drum as a symbol of the army''s heartbeat; dialogue; imagery of the peach orchard soon to become a battlefield (dramatic irony — readers know Shiloh was horrific).
**Link to unit:** real historical battle + invented boy = fiction illuminating the human cost of war.','{"1862":1,"the":14,"drummer":3,"boy":3,"shiloh":3,"ray":2,"bradbury":2,"summary":1,"eve":1,"battle":3,"american":2,"civil":2,"war":3,"frightened":1,"young":1,"joby":2,"lies":1,"awake":1,"afraid":1,"will":1,"useless":1,"because":1,"carries":1,"only":1,"drum":2,"not":1,"weapon":1,"general":1,"walks":1,"camp":1,"and":4,"speaks":1,"him":1,"explaining":1,"that":2,"heart":1,"army":2,"his":1,"drumbeat":1,"sets":1,"courage":2,"pace":1,"every":2,"soldier":1,"reassured":1,"has":1,"vital":1,"role":1,"author":2,"context":1,"celebrated":1,"here":1,"writing":1,"historical":2,"fiction":2,"about":1,"real":2,"themes":1,"fear":1,"importance":1,"individual":1,"leadership":1,"reassurance":1,"coming":1,"age":1,"devices":1,"setting":1,"atmosphere":1,"symbol":1,"heartbeat":1,"dialogue":1,"imagery":1,"peach":1,"orchard":1,"soon":1,"become":1,"battlefield":1,"dramatic":1,"irony":1,"readers":1,"know":1,"was":1,"horrific":1,"link":1,"unit":1,"invented":1,"illuminating":1,"human":1,"cost":1}'::jsonb),
('chunk_3625edce4fc5448919','file_9635f055da2d10cf4a','language-and-literature.md','"The Bracelet" — Yoshiko Uchida','**Summary.** During World War II, a Japanese-American girl, Ruri, and her family are forced from their California home into an internment camp. Her best friend Laurie gives her a gold bracelet as a keepsake. At the bleak camp, Ruri loses the bracelet — and realises she does not need an object to remember her friend; the memory lives inside her.
**Author & context.** Yoshiko Uchida drew on her own family''s internment. Set 1942, based on the real, unjust internment of Japanese Americans.
**Themes.** Injustice and prejudice; memory and friendship; loss of home and dignity; resilience.
**Devices.** First-person narration; symbolism (the bracelet = friendship/memory); setting as instrument of injustice; understated tone.
**Link to unit:** directly connects fiction to a factual injustice — the core of the *Fairness and Development* context.','{"1942":1,"the":8,"bracelet":4,"yoshiko":2,"uchida":2,"summary":1,"during":1,"world":1,"war":1,"japanese":2,"american":1,"girl":1,"ruri":2,"and":6,"her":6,"family":2,"are":1,"forced":1,"from":1,"their":1,"california":1,"home":2,"into":1,"internment":3,"camp":2,"best":1,"friend":2,"laurie":1,"gives":1,"gold":1,"keepsake":1,"bleak":1,"loses":1,"realises":1,"she":1,"does":1,"not":1,"need":1,"object":1,"remember":1,"memory":3,"lives":1,"inside":1,"author":1,"context":2,"drew":1,"own":1,"set":1,"based":1,"real":1,"unjust":1,"americans":1,"themes":1,"injustice":3,"prejudice":1,"friendship":2,"loss":1,"dignity":1,"resilience":1,"devices":1,"first":1,"person":1,"narration":1,"symbolism":1,"setting":1,"instrument":1,"understated":1,"tone":1,"link":1,"unit":1,"directly":1,"connects":1,"fiction":1,"factual":1,"core":1,"fairness":1,"development":1}'::jsonb),
('chunk_191ef116e36887ea19','file_9635f055da2d10cf4a','language-and-literature.md','"Boxes" — Sampurna Chattarji','**Summary.** A contemporary story exploring how people and identities get put into "boxes" — categories, labels and confinements, literal and metaphorical. It invites students to question rigid categorisation and the way society sorts people.
**Author & context.** Sampurna Chattarji is an Indian poet, writer and translator known for inventive, layered work.
**Themes.** Labels and categorisation; identity; the limits imposed by society; perspective.
**Devices.** Extended metaphor of the "box"; symbolism; shifting perspective.
**Link to unit:** questions how we categorise "fact" about people and how fair such labelling is.

**Command-term questions (short stories).**
- *Compare* how "The Bracelet" and "The Last Leaf" use a single object as a symbol.
- *Analyse* how Bradbury builds atmosphere before the battle.
- *Evaluate* which story most powerfully communicates injustice. Justify.','{"boxes":2,"sampurna":2,"chattarji":2,"summary":1,"contemporary":1,"story":2,"exploring":1,"how":5,"people":3,"and":8,"identities":1,"get":1,"put":1,"into":1,"categories":1,"labels":2,"confinements":1,"literal":1,"metaphorical":1,"invites":1,"students":1,"question":1,"rigid":1,"categorisation":2,"the":6,"way":1,"society":2,"sorts":1,"author":1,"context":1,"indian":1,"poet":1,"writer":1,"translator":1,"known":1,"for":1,"inventive":1,"layered":1,"work":1,"themes":1,"identity":1,"limits":1,"imposed":1,"perspective":2,"devices":1,"extended":1,"metaphor":1,"box":1,"symbolism":1,"shifting":1,"link":1,"unit":1,"questions":2,"categorise":1,"fact":1,"about":1,"fair":1,"such":1,"labelling":1,"command":1,"term":1,"short":1,"stories":1,"compare":1,"bracelet":1,"last":1,"leaf":1,"use":1,"single":1,"object":1,"symbol":1,"analyse":1,"bradbury":1,"builds":1,"atmosphere":1,"before":1,"battle":1,"evaluate":1,"which":1,"most":1,"powerfully":1,"communicates":1,"injustice":1,"justify":1}'::jsonb),
('chunk_ccdcecebf1b728ebcd','file_9635f055da2d10cf4a','language-and-literature.md','"These Are the Times We Live In" — Imtiaz Dharker','- **Poet:** Imtiaz Dharker, Pakistan-born British poet exploring identity, borders and belonging.
- **Subject:** the alienation and suspicion faced by migrants/travellers, especially the experience of being scrutinised at borders and treated as an outsider.
- **Form/structure:** free verse; fragmented, unsettling movement mirroring dislocation.
- **Devices:** second-person address, repetition, imagery of documents/checkpoints, irony.
- **Theme:** identity under suspicion; belonging and displacement in the modern world.
- **Teaching angle:** connect to real news about migration and borders — how poetry captures "these times."','{"these":2,"are":1,"the":4,"times":2,"live":1,"imtiaz":2,"dharker":2,"poet":2,"pakistan":1,"born":1,"british":1,"exploring":1,"identity":2,"borders":3,"and":5,"belonging":2,"subject":1,"alienation":1,"suspicion":2,"faced":1,"migrants":1,"travellers":1,"especially":1,"experience":1,"being":1,"scrutinised":1,"treated":1,"outsider":1,"form":1,"structure":1,"free":1,"verse":1,"fragmented":1,"unsettling":1,"movement":1,"mirroring":1,"dislocation":1,"devices":1,"second":1,"person":1,"address":1,"repetition":1,"imagery":1,"documents":1,"checkpoints":1,"irony":1,"theme":1,"under":1,"displacement":1,"modern":1,"world":1,"teaching":1,"angle":1,"connect":1,"real":1,"news":1,"about":1,"migration":1,"how":1,"poetry":1,"captures":1}'::jsonb),
('chunk_314e1319e6c7fab9a1','file_9635f055da2d10cf4a','language-and-literature.md','"The Migrants"','- **Subject:** the plight, journey and hopes of migrants forced to leave home.
- **Form/structure:** typically free verse; collective voice.
- **Devices:** imagery of journey and loss, symbolism of home, contrast between old and new lands.
- **Theme:** displacement, survival, dignity, and fairness toward the displaced.
- **Teaching angle:** pair with "These Are the Times We Live In" to compare two treatments of migration; discuss *Fairness and Development*.','{"the":4,"migrants":2,"subject":1,"plight":1,"journey":2,"and":5,"hopes":1,"forced":1,"leave":1,"home":2,"form":1,"structure":1,"typically":1,"free":1,"verse":1,"collective":1,"voice":1,"devices":1,"imagery":1,"loss":1,"symbolism":1,"contrast":1,"between":1,"old":1,"new":1,"lands":1,"theme":1,"displacement":1,"survival":1,"dignity":1,"fairness":2,"toward":1,"displaced":1,"teaching":1,"angle":1,"pair":1,"with":1,"these":1,"are":1,"times":1,"live":1,"compare":1,"two":1,"treatments":1,"migration":1,"discuss":1,"development":1}'::jsonb),
('chunk_1bc190dfc0228dc7d2','file_9635f055da2d10cf4a','language-and-literature.md','"We Wear the Mask" — Paul Laurence Dunbar','- **Poet:** Paul Laurence Dunbar (1872-1906), one of the first African-American poets to gain national prominence; son of formerly enslaved parents.
- **Subject:** how oppressed people — specifically African Americans after slavery — hide their real pain and suffering behind a smiling, cheerful "mask" to survive in a prejudiced society.
- **Form/structure:** a *rondeau* — 15 lines, tight rhyme scheme, with the refrain "We wear the mask" repeated. The controlled form mirrors controlled, hidden emotion.
- **Devices:** the central metaphor/symbol of the *mask*; refrain; contrast between outward smile and inward "torn and bleeding hearts"; the collective "we."
- **Theme:** concealment of suffering; the psychological cost of oppression; dignity under injustice.
- **Teaching angle:** the gap between appearance (fiction of the smile) and reality (fact of the pain) — a perfect fit for "fact vs fiction" and *Fairness*.

**Command-term question (poetry).** *Compare* how Dunbar and Dharker use a controlling image (mask / border) to expose injustice.','{"1872":1,"1906":1,"wear":2,"the":12,"mask":5,"paul":2,"laurence":2,"dunbar":3,"poet":1,"one":1,"first":1,"african":2,"american":1,"poets":1,"gain":1,"national":1,"prominence":1,"son":1,"formerly":1,"enslaved":1,"parents":1,"subject":1,"how":2,"oppressed":1,"people":1,"specifically":1,"americans":1,"after":1,"slavery":1,"hide":1,"their":1,"real":1,"pain":2,"and":6,"suffering":2,"behind":1,"smiling":1,"cheerful":1,"survive":1,"prejudiced":1,"society":1,"form":2,"structure":1,"rondeau":1,"lines":1,"tight":1,"rhyme":1,"scheme":1,"with":1,"refrain":2,"repeated":1,"controlled":2,"mirrors":1,"hidden":1,"emotion":1,"devices":1,"central":1,"metaphor":1,"symbol":1,"contrast":1,"between":2,"outward":1,"smile":2,"inward":1,"torn":1,"bleeding":1,"hearts":1,"collective":1,"theme":1,"concealment":1,"psychological":1,"cost":1,"oppression":1,"dignity":1,"under":1,"injustice":2,"teaching":1,"angle":1,"gap":1,"appearance":1,"fiction":2,"reality":1,"fact":2,"perfect":1,"fit":1,"for":1,"fairness":1,"command":1,"term":1,"question":1,"poetry":1,"compare":1,"dharker":1,"use":1,"controlling":1,"image":1,"border":1,"expose":1}'::jsonb),
('chunk_43d7556f3c7d369070','file_9635f055da2d10cf4a','language-and-literature.md','Non-literary / Writing — Narrative Writing and Alternate Ending','- **Purpose:** to tell an engaging, coherent story (or to reimagine an existing one).
- **Audience:** readers seeking to be entertained and moved.
- **Structure/features:** orientation (setting/characters) → rising action → climax → falling action → resolution (Freytag''s pyramid). Point of view, consistent tense, showing not telling.
- **Devices:** vivid imagery, dialogue, sensory detail, pacing, foreshadowing.
- **Alternate ending:** rewrite a studied text''s conclusion while staying true to established characters, setting and voice. Ask: what if Behrman had *not* painted the leaf? What if Ruri had *kept* the bracelet?
- **Checklist:** Consistent point of view? Established characters stay believable? Clear turning point? Sensory detail? Satisfying (even if unhappy) resolution?

**Command-term question.** *Justify* how your alternate ending remains consistent with the original characters.','{"non":1,"literary":1,"writing":2,"narrative":1,"and":3,"alternate":3,"ending":3,"purpose":1,"tell":1,"engaging":1,"coherent":1,"story":1,"reimagine":1,"existing":1,"one":1,"audience":1,"readers":1,"seeking":1,"entertained":1,"moved":1,"structure":1,"features":1,"orientation":1,"setting":2,"characters":4,"rising":1,"action":2,"climax":1,"falling":1,"resolution":2,"freytag":1,"pyramid":1,"point":3,"view":2,"consistent":3,"tense":1,"showing":1,"not":2,"telling":1,"devices":1,"vivid":1,"imagery":1,"dialogue":1,"sensory":2,"detail":2,"pacing":1,"foreshadowing":1,"rewrite":1,"studied":1,"text":1,"conclusion":1,"while":1,"staying":1,"true":1,"established":2,"voice":1,"ask":1,"what":2,"behrman":1,"had":2,"painted":1,"the":3,"leaf":1,"ruri":1,"kept":1,"bracelet":1,"checklist":1,"stay":1,"believable":1,"clear":1,"turning":1,"satisfying":1,"even":1,"unhappy":1,"command":1,"term":1,"question":1,"justify":1,"how":1,"your":1,"remains":1,"with":1,"original":1}'::jsonb),
('chunk_51eb6e1907ba5e4da8','file_9635f055da2d10cf4a','language-and-literature.md','Prepositions','- **Rule:** prepositions show relationships of place, time or direction between a noun/pronoun and other words (*in, on, at, under, before, between, across*).
- **Common error:** "different than" vs "different from"; ending confusion. Also *in/on/at* time rules: *at* 5 o''clock, *on* Monday, *in* July.
- **Practice:** "The ivy grew ___ the wall ___ November." (Answer: on; in.)','{"prepositions":2,"rule":1,"show":1,"relationships":1,"place":1,"time":2,"direction":1,"between":2,"noun":1,"pronoun":1,"and":1,"other":1,"words":1,"under":1,"before":1,"across":1,"common":1,"error":1,"different":2,"than":1,"from":1,"ending":1,"confusion":1,"also":1,"rules":1,"clock":1,"monday":1,"july":1,"practice":1,"the":2,"ivy":1,"grew":1,"wall":1,"november":1,"answer":1}'::jsonb),
('chunk_6f9f89d876a637f889','file_9635f055da2d10cf4a','language-and-literature.md','Conjunctions','| Type | Examples | Job |
|------|----------|-----|
| Coordinating (FANBOYS) | for, and, nor, but, or, yet, so | join equal parts |
| Subordinating | because, although, while, since, if | join a dependent clause |
| Correlative | either…or, neither…nor, not only…but also | work in pairs |

- **Common error:** comma splice — joining two full sentences with only a comma. *Correction:* use a coordinating conjunction or a semicolon: "Johnsy was ill, *but* Behrman helped."
- **Practice:** Join with a subordinating conjunction — "Ruri lost the bracelet. She still remembered Laurie." (e.g., *Although* Ruri lost the bracelet, she still remembered Laurie.)','{"conjunctions":1,"type":1,"examples":1,"job":1,"coordinating":2,"fanboys":1,"for":1,"and":1,"nor":2,"but":3,"yet":1,"join":3,"equal":1,"parts":1,"subordinating":2,"because":1,"although":2,"while":1,"since":1,"dependent":1,"clause":1,"correlative":1,"either":1,"neither":1,"not":1,"only":2,"also":1,"work":1,"pairs":1,"common":1,"error":1,"comma":2,"splice":1,"joining":1,"two":1,"full":1,"sentences":1,"with":2,"correction":1,"use":1,"conjunction":2,"semicolon":1,"johnsy":1,"was":1,"ill":1,"behrman":1,"helped":1,"practice":1,"ruri":2,"lost":2,"the":2,"bracelet":2,"she":2,"still":2,"remembered":2,"laurie":2}'::jsonb),
('chunk_285552fbc3f144d940','file_9635f055da2d10cf4a','language-and-literature.md','Tenses — Perfect and Continuous','| Tense | Form | Example | Use |
|-------|------|---------|-----|
| Present perfect | have/has + past participle | She *has painted* a leaf. | past action, present relevance |
| Past perfect | had + past participle | He *had dreamed* of a masterpiece. | earlier of two past actions |
| Present continuous | am/is/are + -ing | The snow *is falling*. | action happening now |
| Past continuous | was/were + -ing | They *were waiting* for the leaf to fall. | ongoing past action |
| Present perfect continuous | have/has been + -ing | It *has been snowing* all night. | ongoing up to now |

- **Common error:** mixing tenses within one narrative ("She walks to the window and saw the leaf"). *Correction:* keep tense consistent — "She walked… and saw…"
- **Practice:** Choose — "By the time Johnsy recovered, Behrman ___ (die)." (Answer: had died — past perfect.)','{"tenses":2,"perfect":5,"and":3,"continuous":4,"tense":2,"form":1,"example":1,"use":1,"present":4,"have":2,"has":4,"past":8,"participle":2,"she":3,"painted":1,"leaf":3,"action":3,"relevance":1,"had":3,"dreamed":1,"masterpiece":1,"earlier":1,"two":1,"actions":1,"are":1,"ing":3,"the":5,"snow":1,"falling":1,"happening":1,"now":2,"was":1,"were":2,"they":1,"waiting":1,"for":1,"fall":1,"ongoing":2,"been":2,"snowing":1,"all":1,"night":1,"common":1,"error":1,"mixing":1,"within":1,"one":1,"narrative":1,"walks":1,"window":1,"saw":2,"correction":1,"keep":1,"consistent":1,"walked":1,"practice":1,"choose":1,"time":1,"johnsy":1,"recovered":1,"behrman":1,"die":1,"answer":1,"died":1}'::jsonb),
('chunk_4ac49d616537e53ebb','file_9635f055da2d10cf4a','language-and-literature.md','Subject-verb agreement','- **Rule:** the verb agrees with the subject in number. Singular subject → singular verb.
- **Common errors:** (1) intervening phrases — "The box of letters *were* lost" → *was* (subject is *box*). (2) Collective nouns usually take singular — "The team *is* ready." (3) *Either/neither… nor* → verb agrees with the nearer subject.
- **Practice:** "Each of the migrants ___ (carry) a story." (Answer: carries.)

---','{"subject":5,"verb":4,"agreement":1,"rule":1,"the":6,"agrees":2,"with":2,"number":1,"singular":3,"common":1,"errors":1,"intervening":1,"phrases":1,"box":2,"letters":1,"were":1,"lost":1,"was":1,"collective":1,"nouns":1,"usually":1,"take":1,"team":1,"ready":1,"either":1,"neither":1,"nor":1,"nearer":1,"practice":1,"each":1,"migrants":1,"carry":1,"story":1,"answer":1,"carries":1}'::jsonb),
('chunk_528190a1d712a9b6e4','file_9635f055da2d10cf4a','language-and-literature.md','Unit 3: Expressions in Art — Crafting Connections','- **Key Concept:** Creativity (with Communication)
- **Related Concepts:** Self-expression, Style, Voice, Theme
- **Global Context:** Personal and Cultural Expression
- **Statement of Inquiry:** Artists across forms use style and voice to express personal and cultural identity, creating connections between creator and audience.
- **Inquiry Questions:**
  - *Factual:* What techniques do poets, writers and filmmakers use to express ideas? What are the main camera shots and angles?
  - *Conceptual:* How does an artist''s voice communicate personal or cultural identity? How does form shape self-expression?
  - *Debatable:* Is all art a form of protest? Can a film express an idea more powerfully than a poem?','{"unit":1,"expressions":1,"art":2,"crafting":1,"connections":2,"key":1,"concept":1,"creativity":1,"with":1,"communication":1,"related":1,"concepts":1,"self":2,"expression":3,"style":2,"voice":3,"theme":1,"global":1,"context":1,"personal":3,"and":6,"cultural":3,"statement":1,"inquiry":2,"artists":1,"across":1,"forms":1,"use":2,"express":3,"identity":2,"creating":1,"between":1,"creator":1,"audience":1,"questions":1,"factual":1,"what":2,"techniques":1,"poets":1,"writers":1,"filmmakers":1,"ideas":1,"are":1,"the":1,"main":1,"camera":1,"shots":1,"angles":1,"conceptual":1,"how":2,"does":2,"artist":1,"communicate":1,"form":2,"shape":1,"debatable":1,"all":1,"protest":1,"can":1,"film":1,"idea":1,"more":1,"powerfully":1,"than":1,"poem":1}'::jsonb),
('chunk_19d25dd479728a95b0','file_9635f055da2d10cf4a','language-and-literature.md','Literary text — "Eleven" by Sandra Cisneros','**Summary.** On her eleventh birthday, Rachel narrates a humiliating school day. Her teacher, Mrs. Price, wrongly insists an ugly, unclaimed red sweater in the coat closet belongs to Rachel and forces her to put it on. Rachel, too shy and powerless to protest convincingly, ends up crying at her desk in front of the class — on the very day she should feel grown-up. She reflects that growing older doesn''t mean feeling older; all the ages she has ever been are still inside her ("like the rings inside a tree trunk").
**Author & context.** Sandra Cisneros is a celebrated Mexican-American writer (best known for *The House on Mango Street*). "Eleven" explores childhood psychology and voice.
**Themes.** Child psychology and cognition (how children experience emotion and age); powerlessness of children before adults; identity and growing up; gender sensitisation (a girl silenced and dismissed). The story is a window into how age and selfhood are layered.
**Main character.** *Rachel* — sensitive, articulate in thought but voiceless aloud; *Mrs. Price* — the dismissive authority figure.
**Devices.** First-person stream-of-consciousness voice; the famous simile/metaphor of ages as *rings of a tree* / *onion layers* / *nesting dolls*; the red sweater as a symbol of shame and imposed identity; hyperbole and childlike syntax; repetition.
**Link to unit:** a masterclass in *voice* and *self-expression*. Cisneros expresses a universal childhood truth through a highly individual narrative voice — connecting creator and reader.

**Command-term questions.** *Analyse* how Cisneros creates a convincing child''s voice. *Interpret* the tree-ring metaphor. *Evaluate* how the story raises awareness of how children (and girls) can be silenced.','{"literary":1,"text":1,"eleven":2,"sandra":2,"cisneros":4,"summary":1,"her":5,"eleventh":1,"birthday":1,"rachel":4,"narrates":1,"humiliating":1,"school":1,"day":2,"teacher":1,"mrs":2,"price":2,"wrongly":1,"insists":1,"ugly":1,"unclaimed":1,"red":2,"sweater":2,"the":12,"coat":1,"closet":1,"belongs":1,"and":13,"forces":1,"put":1,"too":1,"shy":1,"powerless":1,"protest":1,"convincingly":1,"ends":1,"crying":1,"desk":1,"front":1,"class":1,"very":1,"she":3,"should":1,"feel":1,"grown":1,"reflects":1,"that":1,"growing":2,"older":2,"doesn":1,"mean":1,"feeling":1,"all":1,"ages":2,"has":1,"ever":1,"been":1,"are":2,"still":1,"inside":2,"like":1,"rings":2,"tree":3,"trunk":1,"author":1,"context":1,"celebrated":1,"mexican":1,"american":1,"writer":1,"best":1,"known":1,"for":1,"house":1,"mango":1,"street":1,"explores":1,"childhood":2,"psychology":2,"voice":5,"themes":1,"child":2,"cognition":1,"how":5,"children":3,"experience":1,"emotion":1,"age":2,"powerlessness":1,"before":1,"adults":1,"identity":2,"gender":1,"sensitisation":1,"girl":1,"silenced":2,"dismissed":1,"story":2,"window":1,"into":1,"selfhood":1,"layered":1,"main":1,"character":1,"sensitive":1,"articulate":1,"thought":1,"but":1,"voiceless":1,"aloud":1,"dismissive":1,"authority":1,"figure":1,"devices":1,"first":1,"person":1,"stream":1,"consciousness":1,"famous":1,"simile":1,"metaphor":2,"onion":1,"layers":1,"nesting":1,"dolls":1,"symbol":1,"shame":1,"imposed":1,"hyperbole":1,"childlike":1,"syntax":1,"repetition":1,"link":1,"unit":1,"masterclass":1,"self":1,"expression":1,"expresses":1,"universal":1,"truth":1,"through":1,"highly":1,"individual":1,"narrative":1,"connecting":1,"creator":1,"reader":1,"command":1,"term":1,"questions":1,"analyse":1,"creates":1,"convincing":1,"interpret":1,"ring":1,"evaluate":1,"raises":1,"awareness":1,"girls":1,"can":1}'::jsonb),
('chunk_7a8144cc448ac24ed0','file_9635f055da2d10cf4a','language-and-literature.md','"America" — Langston Hughes','- **Poet:** Langston Hughes, leading voice of the Harlem Renaissance, giving powerful expression to Black American life.
- **Subject:** the gap between America''s promise of freedom/equality and the lived reality of exclusion; a call for the nation to *become* the dream it professes. (Hughes''s work on this theme — famously "Let America be America Again" — insists the dream must be made real for all.)
- **Form/structure:** varied line lengths; a mix of soaring ideal and grounded protest voices.
- **Devices:** contrast/juxtaposition, repetition, apostrophe (addressing "America"), symbolism of the "dream."
- **Theme:** freedom vs. inequality; hope; the unfinished promise of a nation.
- **Teaching angle:** cultural self-expression as protest; connect to Individuals & Societies.','{"america":5,"langston":2,"hughes":3,"poet":1,"leading":1,"voice":1,"the":8,"harlem":1,"renaissance":1,"giving":1,"powerful":1,"expression":2,"black":1,"american":1,"life":1,"subject":1,"gap":1,"between":1,"promise":2,"freedom":2,"equality":1,"and":2,"lived":1,"reality":1,"exclusion":1,"call":1,"for":2,"nation":2,"become":1,"dream":3,"professes":1,"work":1,"this":1,"theme":2,"famously":1,"let":1,"again":1,"insists":1,"must":1,"made":1,"real":1,"all":1,"form":1,"structure":1,"varied":1,"line":1,"lengths":1,"mix":1,"soaring":1,"ideal":1,"grounded":1,"protest":2,"voices":1,"devices":1,"contrast":1,"juxtaposition":1,"repetition":1,"apostrophe":1,"addressing":1,"symbolism":1,"inequality":1,"hope":1,"unfinished":1,"teaching":1,"angle":1,"cultural":1,"self":1,"connect":1,"individuals":1,"societies":1}'::jsonb),
('chunk_8049e1be02235c306d','file_9635f055da2d10cf4a','language-and-literature.md','"Caged Bird" — Maya Angelou','- **Poet:** Maya Angelou, American poet and civil-rights figure.
- **Subject:** the contrast between a *free bird* that floats on the wind and claims the sky, and a *caged bird* that can only sing of freedom it has never known; an allegory for oppression (especially of Black Americans) and the resilient voice that sings despite it.
- **Form/structure:** free verse; alternating stanzas contrast the free and caged birds; a repeated refrain about the caged bird''s song.
- **Devices:** extended metaphor/allegory (birds = free vs. oppressed people), symbolism (cage, sky, "clipped wings," "tied feet"), personification, repetition/refrain, contrast.
- **Theme:** freedom vs. oppression; the endurance of hope; the power of voice/song as resistance.
- **Teaching angle:** pair with Dunbar''s "We Wear the Mask" and Hughes''s "America" for a mini-unit on how oppressed voices use art. Perfect for *Personal and Cultural Expression*.

**Command-term question.** *Compare* how Angelou and Hughes use symbolism to express a longing for freedom.','{"caged":4,"bird":4,"maya":2,"angelou":3,"poet":2,"american":1,"and":8,"civil":1,"rights":1,"figure":1,"subject":1,"the":9,"contrast":3,"between":1,"free":4,"that":3,"floats":1,"wind":1,"claims":1,"sky":2,"can":1,"only":1,"sing":1,"freedom":3,"has":1,"never":1,"known":1,"allegory":2,"for":4,"oppression":2,"especially":1,"black":1,"americans":1,"resilient":1,"voice":2,"sings":1,"despite":1,"form":1,"structure":1,"verse":1,"alternating":1,"stanzas":1,"birds":2,"repeated":1,"refrain":2,"about":1,"song":2,"devices":1,"extended":1,"metaphor":1,"oppressed":2,"people":1,"symbolism":2,"cage":1,"clipped":1,"wings":1,"tied":1,"feet":1,"personification":1,"repetition":1,"theme":1,"endurance":1,"hope":1,"power":1,"resistance":1,"teaching":1,"angle":1,"pair":1,"with":1,"dunbar":1,"wear":1,"mask":1,"hughes":2,"america":1,"mini":1,"unit":1,"how":2,"voices":1,"use":2,"art":1,"perfect":1,"personal":1,"cultural":1,"expression":1,"command":1,"term":1,"question":1,"compare":1,"express":1,"longing":1}'::jsonb),
('chunk_c24e8930151d27185c','file_9635f055da2d10cf4a','language-and-literature.md','Non-literary — Film (as expression)','**Why study it.** Film communicates through images and sound as well as words. Studying camera technique teaches students that meaning is *constructed* through deliberate choices — an audiovisual parallel to authorial word-choice.','{"non":1,"literary":1,"film":2,"expression":1,"why":1,"study":1,"communicates":1,"through":2,"images":1,"and":1,"sound":1,"well":1,"words":1,"studying":1,"camera":1,"technique":1,"teaches":1,"students":1,"that":1,"meaning":1,"constructed":1,"deliberate":1,"choices":1,"audiovisual":1,"parallel":1,"authorial":1,"word":1,"choice":1}'::jsonb),
('chunk_c4f7ae452d12d8b69d','file_9635f055da2d10cf4a','language-and-literature.md','Camera shots and angles toolkit','| Technique | What it is | Typical meaning/effect |
|-----------|-----------|------------------------|
| **Extreme long shot / establishing shot** | subject tiny, wide view | sets location; makes subject small/isolated |
| **Long shot** | full body in setting | shows character in context |
| **Mid shot** | waist up | conversation; balanced, neutral |
| **Close-up** | face fills frame | emotion, intimacy, importance |
| **Extreme close-up** | eyes/detail only | intense feeling, tension |
| **High angle** | camera looks down on subject | subject seems weak, small, vulnerable |
| **Low angle** | camera looks up at subject | subject seems powerful, dominant, threatening |
| **Eye-level** | neutral height | equality, realism |
| **Bird''s-eye / overhead** | directly above | pattern, God-like overview, helplessness |
| **Point-of-view (POV) shot** | what a character sees | audience shares character''s perspective |
| **Dutch/canted angle** | tilted frame | unease, disorientation |

**Also teach:** *camera movement* (pan, tilt, zoom, tracking), *lighting* (high-key = bright/happy; low-key = shadowy/tense), *mise-en-scène* (everything arranged in the frame), and *sound* (diegetic vs. non-diegetic music).

**How it makes meaning.** A low-angle close-up on a character bathed in shadow tells us they are powerful *and* menacing before they speak a word — the audience "reads" the shot the way a reader reads a metaphor.

**Analogy.** The camera is the narrator''s *eye*: where it stands and how close it gets is the film''s equivalent of point of view in a novel.

**Command-term question.** *Analyse* how camera angle and lighting in a chosen scene shape the audience''s feelings about a character.','{"camera":6,"shots":1,"and":5,"angles":1,"toolkit":1,"technique":1,"what":2,"typical":1,"meaning":2,"effect":1,"extreme":2,"long":2,"shot":6,"establishing":1,"subject":6,"tiny":1,"wide":1,"view":3,"sets":1,"location":1,"makes":2,"small":2,"isolated":1,"full":1,"body":1,"setting":1,"shows":1,"character":5,"context":1,"mid":1,"waist":1,"conversation":1,"balanced":1,"neutral":2,"close":4,"face":1,"fills":1,"frame":3,"emotion":1,"intimacy":1,"importance":1,"eyes":1,"detail":1,"only":1,"intense":1,"feeling":1,"tension":1,"high":2,"angle":5,"looks":2,"down":1,"seems":2,"weak":1,"vulnerable":1,"low":3,"powerful":2,"dominant":1,"threatening":1,"eye":3,"level":1,"height":1,"equality":1,"realism":1,"bird":1,"overhead":1,"directly":1,"above":1,"pattern":1,"god":1,"like":1,"overview":1,"helplessness":1,"point":2,"pov":1,"sees":1,"audience":3,"shares":1,"perspective":1,"dutch":1,"canted":1,"tilted":1,"unease":1,"disorientation":1,"also":1,"teach":1,"movement":1,"pan":1,"tilt":1,"zoom":1,"tracking":1,"lighting":2,"key":2,"bright":1,"happy":1,"shadowy":1,"tense":1,"mise":1,"everything":1,"arranged":1,"the":8,"sound":1,"diegetic":2,"non":1,"music":1,"how":3,"bathed":1,"shadow":1,"tells":1,"they":2,"are":1,"menacing":1,"before":1,"speak":1,"word":1,"reads":2,"way":1,"reader":1,"metaphor":1,"analogy":1,"narrator":1,"where":1,"stands":1,"gets":1,"film":1,"equivalent":1,"novel":1,"command":1,"term":1,"question":1,"analyse":1,"chosen":1,"scene":1,"shape":1,"feelings":1,"about":1}'::jsonb),
('chunk_8d608e24fa97b05295','file_9635f055da2d10cf4a','language-and-literature.md','Poetry writing — Spoken Word Poetry','- **Purpose:** performed poetry that expresses personal/political feeling aloud; meant to be *heard* and felt.
- **Audience:** a live audience; language chosen for rhythm and impact.
- **Features:** strong personal voice; rhythm and repetition; anaphora; internal rhyme; direct address; imagery; a build to an emotional climax; performance cues (pace, pause, volume).
- **Devices:** repetition/anaphora, metaphor, rhythm, enjambment, call-and-response.
- **Checklist:** Is there a clear "I"? Does it build? Is it written for the ear (sounds, beats)? A memorable last line?
- **Mini model line:** *"I am the maybe, the almost, the not-quite-yet — and I am still enough."*','{"poetry":3,"writing":1,"spoken":1,"word":1,"purpose":1,"performed":1,"that":1,"expresses":1,"personal":2,"political":1,"feeling":1,"aloud":1,"meant":1,"heard":1,"and":5,"felt":1,"audience":2,"live":1,"language":1,"chosen":1,"for":2,"rhythm":3,"impact":1,"features":1,"strong":1,"voice":1,"repetition":2,"anaphora":2,"internal":1,"rhyme":1,"direct":1,"address":1,"imagery":1,"build":2,"emotional":1,"climax":1,"performance":1,"cues":1,"pace":1,"pause":1,"volume":1,"devices":1,"metaphor":1,"enjambment":1,"call":1,"response":1,"checklist":1,"there":1,"clear":1,"does":1,"written":1,"the":4,"ear":1,"sounds":1,"beats":1,"memorable":1,"last":1,"line":2,"mini":1,"model":1,"maybe":1,"almost":1,"not":1,"quite":1,"yet":1,"still":1,"enough":1}'::jsonb);