INSERT INTO syllabus_chunks (id, file_id, file_name, heading, body, tf) VALUES
('chunk_54db193360145bfd6a','file_3393b5fbe4e9b31e26','mathematics.md','Concept: Central tendency — mean, median, mode (raw & from frequency tables)','**Definition:** Mean = sum ÷ count; median = middle value when ordered; mode = most frequent. From a frequency table the mean `= Σ(fx) ÷ Σf`.

| Measure | Best when | Affected by outliers? |
|---------|-----------|-----------------------|
| Mean | data fairly symmetric | Yes |
| Median | skewed data / outliers present | No |
| Mode | categorical / most common | No |

**Worked example:** Data 4, 6, 6, 8, 11: mean `= 35/5 = 7`; median `= 6`; mode `= 6`. Frequency table x=1,2,3 with f=2,5,3 → mean `= (1·2+2·5+3·3)/10 = 21/10 = 2.1`.
**Real-world use:** Average income (median avoids distortion by billionaires), exam averages, best-selling size (mode).
**Analogy:** The mean is the "balance point" of the data; the median is the "middle of the queue".
**Method:** order the data → mean adds and divides; median finds the middle; mode counts frequency.
**Misconception:** "The median is the middle of the unordered list." Corrective: you must sort first.
**Questions:** (1) *Calculate* the mean, median and mode of 3, 5, 5, 9, 13. (2) *Find* the mean from a given frequency table. (3) *Discuss* which average best describes house prices and why.','{"concept":1,"central":1,"tendency":1,"mean":10,"median":9,"mode":7,"raw":1,"from":3,"frequency":5,"tables":1,"definition":1,"sum":1,"count":1,"middle":4,"value":1,"when":2,"ordered":1,"most":2,"frequent":1,"table":3,"the":14,"measure":1,"best":3,"affected":1,"outliers":2,"data":5,"fairly":1,"symmetric":1,"yes":1,"skewed":1,"present":1,"categorical":1,"common":1,"worked":1,"example":1,"with":1,"real":1,"world":1,"use":1,"average":2,"income":1,"avoids":1,"distortion":1,"billionaires":1,"exam":1,"averages":1,"selling":1,"size":1,"analogy":1,"balance":1,"point":1,"queue":1,"method":1,"order":1,"adds":1,"and":3,"divides":1,"finds":1,"counts":1,"misconception":1,"unordered":1,"list":1,"corrective":1,"you":1,"must":1,"sort":1,"first":1,"questions":1,"calculate":1,"find":1,"given":1,"discuss":1,"which":1,"describes":1,"house":1,"prices":1,"why":1}'::jsonb),
('chunk_10c5cfa1b2eb417c60','file_3393b5fbe4e9b31e26','mathematics.md','Concept: Dispersion — range, mean deviation, standard deviation; histograms & ogives','**Definition:** Dispersion measures spread. Range `= max − min`. Mean deviation = average distance from the mean. Standard deviation measures typical spread about the mean (larger = more variable). A histogram shows grouped continuous frequencies (bars touch); an ogive is the cumulative-frequency curve.
**Worked example:** Data 4, 6, 8, 10, 12: mean 8, range `= 12−4 = 8`; deviations 4,2,0,2,4 → mean deviation `= 12/5 = 2.4`. An ogive lets you read the median at the cumulative frequency = n/2 point.
**Real-world use:** Comparing consistency (two players with the same mean but different spread), quality control, exam grade boundaries.
**Analogy:** Two classes can have the same average height but one is all similar and the other has giants and small children — spread tells them apart.
**Method:** range = max − min; mean deviation = mean of |x − mean|; ogive plots running totals, read median/quartiles from it.
**Misconception:** "Same mean means same data." Corrective: {5,5,5} and {0,5,10} both average 5 but have very different spreads.
**Questions:** (1) *Calculate* the range of 7, 3, 9, 2, 8. (2) *Find* the mean deviation of 2, 4, 6, 8. (3) *Compare* two data sets with equal means but different standard deviations and explain what the spread tells you.

---','{"concept":1,"dispersion":2,"range":5,"mean":12,"deviation":7,"standard":3,"histograms":1,"ogives":1,"definition":1,"measures":2,"spread":5,"max":2,"min":2,"average":3,"distance":1,"from":2,"the":11,"typical":1,"about":1,"larger":1,"more":1,"variable":1,"histogram":1,"shows":1,"grouped":1,"continuous":1,"frequencies":1,"bars":1,"touch":1,"ogive":3,"cumulative":2,"frequency":2,"curve":1,"worked":1,"example":1,"data":3,"deviations":2,"lets":1,"you":2,"read":2,"median":2,"point":1,"real":1,"world":1,"use":1,"comparing":1,"consistency":1,"two":3,"players":1,"with":2,"same":4,"but":4,"different":3,"quality":1,"control":1,"exam":1,"grade":1,"boundaries":1,"analogy":1,"classes":1,"can":1,"have":2,"height":1,"one":1,"all":1,"similar":1,"and":4,"other":1,"has":1,"giants":1,"small":1,"children":1,"tells":2,"them":1,"apart":1,"method":1,"plots":1,"running":1,"totals":1,"quartiles":1,"misconception":1,"means":2,"corrective":1,"both":1,"very":1,"spreads":1,"questions":1,"calculate":1,"find":1,"compare":1,"sets":1,"equal":1,"explain":1,"what":1}'::jsonb),
('chunk_502fa59ee7a42e4a19','file_3393b5fbe4e9b31e26','mathematics.md','Common Misconceptions Master List (whole subject)','1. **Percentage reversal:** taking a percentage of the final value instead of dividing by the multiplier (a 20% discount → divide by 0.8, not ×1.2).
2. **Repeated percentages add:** treating 3 years of 10% as 30% instead of `1.1³ = 33.1%`.
3. **Dividing change by the wrong base:** using the final value rather than the original for percentage change.
4. **π = 22/7:** treating an approximation as exact; π is irrational.
5. **Ratio = fraction of total:** reading 2:3 as "2/3 of the whole" instead of 2/5.
6. **Area/volume conversions:** using the linear factor (1 m² ≠ 100 cm², it is 10000).
7. **Minutes in base 100:** adding times as decimals rather than base 60.
8. **`(a+b)² = a² + b²`:** dropping the `2ab` cross-term.
9. **Index product multiplies indices:** `a^m × a^n` gives `a^(m+n)`, not `a^(mn)`.
10. **`a^(1/2) = a ÷ 2`:** confusing a root with division.
11. **Cancelling terms not factors:** `(x+3)/3 ≠ x+1`.
12. **Adding fractions'' denominators:** `x/2 + x/3 ≠ 2x/5`.
13. **Not flipping signs when transposing** across the equals sign.
14. **Quadrilateral angle sum = 180°:** it is 360°.
15. **A square is not a rectangle:** it is a special one.
16. **Exterior-angle sum varies with n:** it is always 360°.
17. **Slant side used as height** for parallelogram/triangle area.
18. **Using diameter as r** in `πr²`.
19. **Hypotenuse mis-identified:** c is always the longest side, opposite the right angle.
20. **Probability > 1** or experimental must equal theoretical.
21. **Median without sorting** the data first.
22. **Same mean ⇒ same data:** ignores spread/dispersion.

---','{"100":2,"180":1,"360":2,"10000":1,"common":1,"misconceptions":1,"master":1,"list":1,"whole":2,"subject":1,"percentage":3,"reversal":1,"taking":1,"the":12,"final":2,"value":2,"instead":3,"dividing":2,"multiplier":1,"discount":1,"divide":1,"not":5,"repeated":1,"percentages":1,"add":1,"treating":2,"years":1,"change":2,"wrong":1,"base":3,"using":3,"rather":2,"than":2,"original":1,"for":2,"approximation":1,"exact":1,"irrational":1,"ratio":1,"fraction":1,"total":1,"reading":1,"area":2,"volume":1,"conversions":1,"linear":1,"factor":1,"minutes":1,"adding":2,"times":1,"decimals":1,"dropping":1,"2ab":1,"cross":1,"term":1,"index":1,"product":1,"multiplies":1,"indices":1,"gives":1,"confusing":1,"root":1,"with":2,"division":1,"cancelling":1,"terms":1,"factors":1,"fractions":1,"denominators":1,"flipping":1,"signs":1,"when":1,"transposing":1,"across":1,"equals":1,"sign":1,"quadrilateral":1,"angle":3,"sum":2,"square":1,"rectangle":1,"special":1,"one":1,"exterior":1,"varies":1,"always":2,"slant":1,"side":2,"used":1,"height":1,"parallelogram":1,"triangle":1,"diameter":1,"hypotenuse":1,"mis":1,"identified":1,"longest":1,"opposite":1,"right":1,"probability":1,"experimental":1,"must":1,"equal":1,"theoretical":1,"median":1,"without":1,"sorting":1,"data":2,"first":1,"same":2,"mean":1,"ignores":1,"spread":1,"dispersion":1}'::jsonb),
('chunk_ec14a9e7dbd5271b31','file_3393b5fbe4e9b31e26','mathematics.md','Command-Term Question Bank (spanning units)','1. **(U1) Calculate** the original price of a jacket that costs €68 after a 15% discount. *(reverse percentage)*
2. **(U1) Determine** whether 4/11 gives a terminating or recurring decimal, and justify your reasoning. *(number theory)*
3. **(U2) Expand and simplify** `(x + 5)(x − 2)`, then **explain** how the middle term arises from the area model. *(expanding)*
4. **(U2) Solve** `3(2x − 1) = 4x + 7`, showing each transposition, and **verify** your answer. *(linear equations)*
5. **(U3) Find** the space diagonal of a 4 × 4 × 7 cuboid and **explain** why Pythagoras is applied twice. *(3D + Pythagoras)*
6. **(U3) Calculate** each interior angle of a regular nonagon (9 sides) and **justify** the formula you use. *(polygons)*
7. **(U4) Compare** two cricket batters who both average 40 runs but have standard deviations of 8 and 25, and **evaluate** who is more reliable. *(dispersion)*
8. **(U4) Determine** the experimental probability of rolling a 6 that appeared 14 times in 90 rolls, and **discuss** how this relates to the theoretical value. *(probability)*

---','{"command":1,"term":2,"question":1,"bank":1,"spanning":1,"units":1,"calculate":2,"the":7,"original":1,"price":1,"jacket":1,"that":2,"costs":1,"after":1,"discount":1,"reverse":1,"percentage":1,"determine":2,"whether":1,"gives":1,"terminating":1,"recurring":1,"decimal":1,"and":8,"justify":2,"your":2,"reasoning":1,"number":1,"theory":1,"expand":1,"simplify":1,"then":1,"explain":2,"how":2,"middle":1,"arises":1,"from":1,"area":1,"model":1,"expanding":1,"solve":1,"showing":1,"each":2,"transposition":1,"verify":1,"answer":1,"linear":1,"equations":1,"find":1,"space":1,"diagonal":1,"cuboid":1,"why":1,"pythagoras":2,"applied":1,"twice":1,"interior":1,"angle":1,"regular":1,"nonagon":1,"sides":1,"formula":1,"you":1,"use":1,"polygons":1,"compare":1,"two":1,"cricket":1,"batters":1,"who":2,"both":1,"average":1,"runs":1,"but":1,"have":1,"standard":1,"deviations":1,"evaluate":1,"more":1,"reliable":1,"dispersion":1,"experimental":1,"probability":2,"rolling":1,"appeared":1,"times":1,"rolls":1,"discuss":1,"this":1,"relates":1,"theoretical":1,"value":1}'::jsonb),
('chunk_9926ec898854178975','file_3393b5fbe4e9b31e26','mathematics.md','Cross-Subject Connections','- **Physics (MYP Sciences):** Rates, unit conversions and the D=S×T triangle underpin speed, velocity and acceleration; Pythagoras resolves vector components; standard form (indices) expresses very large/small quantities; graphs and gradients link to motion graphs.
- **Chemistry (MYP Sciences):** Ratio and proportion drive mole ratios and concentration; percentage calculations give percentage yield, composition and purity; significant figures and rounding relate to measurement accuracy.
- **Geography / Individuals & Societies:** Time zones and coordinates support map-reading and global scheduling; percentage change models population growth, GDP and resource change; central tendency and dispersion summarise climate and demographic data; scale ratios convert map to real distance.
- **Digital Design / Computing:** The coordinate plane maps to screen pixels and game positions; probability underlies randomness and simulations; binary and storage sizes use powers/indices (2^10); data representation and averages feed dashboards and data-visualisation projects; algebraic logic mirrors conditional and formula-based programming.','{"cross":1,"subject":1,"connections":1,"physics":1,"myp":2,"sciences":2,"rates":1,"unit":1,"conversions":1,"and":18,"the":2,"triangle":1,"underpin":1,"speed":1,"velocity":1,"acceleration":1,"pythagoras":1,"resolves":1,"vector":1,"components":1,"standard":1,"form":1,"indices":2,"expresses":1,"very":1,"large":1,"small":1,"quantities":1,"graphs":2,"gradients":1,"link":1,"motion":1,"chemistry":1,"ratio":1,"proportion":1,"drive":1,"mole":1,"ratios":2,"concentration":1,"percentage":3,"calculations":1,"give":1,"yield":1,"composition":1,"purity":1,"significant":1,"figures":1,"rounding":1,"relate":1,"measurement":1,"accuracy":1,"geography":1,"individuals":1,"societies":1,"time":1,"zones":1,"coordinates":1,"support":1,"map":2,"reading":1,"global":1,"scheduling":1,"change":2,"models":1,"population":1,"growth":1,"gdp":1,"resource":1,"central":1,"tendency":1,"dispersion":1,"summarise":1,"climate":1,"demographic":1,"data":3,"scale":1,"convert":1,"real":1,"distance":1,"digital":1,"design":1,"computing":1,"coordinate":1,"plane":1,"maps":1,"screen":1,"pixels":1,"game":1,"positions":1,"probability":1,"underlies":1,"randomness":1,"simulations":1,"binary":1,"storage":1,"sizes":1,"use":1,"powers":1,"representation":1,"averages":1,"feed":1,"dashboards":1,"visualisation":1,"projects":1,"algebraic":1,"logic":1,"mirrors":1,"conditional":1,"formula":1,"based":1,"programming":1}'::jsonb),
('chunk_1a1f9af0da8ada6232','file_c7904436411b2e478c','music.md','Grade 7 Music (MYP Arts) — Knowledge Base','**School:** IISH MYP | **Academic Year:** 2026–2027 | **Grade:** 7 (MYP Year 2) | **Subject Group:** Arts (Music)

> This file is a teaching reference for an IB MYP teaching assistant. It teaches the music accurately and age-appropriately, mapped to MYP Arts criteria, concepts, and command terms. Use it to answer student questions, plan lessons, and generate assessment tasks.

---','{"2026":1,"2027":1,"grade":2,"music":3,"myp":5,"arts":3,"knowledge":1,"base":1,"school":1,"iish":1,"academic":1,"year":2,"subject":1,"group":1,"this":1,"file":1,"teaching":2,"reference":1,"for":1,"assistant":1,"teaches":1,"the":1,"accurately":1,"and":3,"age":1,"appropriately":1,"mapped":1,"criteria":1,"concepts":1,"command":1,"terms":1,"use":1,"answer":1,"student":1,"questions":1,"plan":1,"lessons":1,"generate":1,"assessment":1,"tasks":1}'::jsonb),
('chunk_2a446c95dcd9618549','file_c7904436411b2e478c','music.md','1. Subject Overview: Music in MYP Arts','Music sits in the **MYP Arts** subject group. Students learn as **performers, creators, and reflective artists**. They investigate how music works, develop their skills, create and perform music, and evaluate their artistic process and product.','{"subject":2,"overview":1,"music":4,"myp":2,"arts":2,"sits":1,"the":1,"group":1,"students":1,"learn":1,"performers":1,"creators":1,"and":4,"reflective":1,"artists":1,"they":1,"investigate":1,"how":1,"works":1,"develop":1,"their":2,"skills":1,"create":1,"perform":1,"evaluate":1,"artistic":1,"process":1,"product":1}'::jsonb),
('chunk_fc67f9c33281a643ed','file_c7904436411b2e478c','music.md','1.1 The Four MYP Arts Assessment Criteria','Each criterion is marked out of **8** (four achievement bands: 1–2, 3–4, 5–6, 7–8).

| Criterion | Title | In plain language | What a Grade 7 musician does |
|-----------|-------|-------------------|------------------------------|
| **A** | Investigating / Knowing & Understanding | Research and knowledge | Investigates a style/genre, demonstrates knowledge of music elements and vocabulary, and links it to context. |
| **B** | Developing | Skills and planning | Practises and develops vocal/musical skills, plans and refines ideas, shows growth over time. |
| **C** | Creating / Performing | Making and doing | Creates (improvises/arranges) and performs music, applying skills and technique. |
| **D** | Evaluating | Reflection and appraisal | Evaluates own and others'' work against criteria, reflects on progress, sets next-step goals. |

> Note: Different MYP Arts guides phrase Criterion A as "Knowing and understanding" and Criterion C as "Creating/Thinking creatively" or "Performing." For Grade 7 Music at IISH, read A = **Investigating/Knowing**, B = **Developing**, C = **Creating/Performing**, D = **Evaluating**.','{"the":1,"four":2,"myp":2,"arts":2,"assessment":1,"criteria":2,"each":1,"criterion":4,"marked":1,"out":1,"achievement":1,"bands":1,"title":1,"plain":1,"language":1,"what":1,"grade":2,"musician":1,"does":1,"investigating":2,"knowing":3,"understanding":2,"research":1,"and":13,"knowledge":2,"investigates":1,"style":1,"genre":1,"demonstrates":1,"music":3,"elements":1,"vocabulary":1,"links":1,"context":1,"developing":2,"skills":3,"planning":1,"practises":1,"develops":1,"vocal":1,"musical":1,"plans":1,"refines":1,"ideas":1,"shows":1,"growth":1,"over":1,"time":1,"creating":3,"performing":3,"making":1,"doing":1,"creates":1,"improvises":1,"arranges":1,"performs":1,"applying":1,"technique":1,"evaluating":2,"reflection":1,"appraisal":1,"evaluates":1,"own":1,"others":1,"work":1,"against":1,"reflects":1,"progress":1,"sets":1,"next":1,"step":1,"goals":1,"note":1,"different":1,"guides":1,"phrase":1,"thinking":1,"creatively":1,"for":1,"iish":1,"read":1}'::jsonb),
('chunk_a8fd8991bf2e5d1215','file_c7904436411b2e478c','music.md','1.2 Arts Related Concepts','Related concepts are the specialised "lenses" of the Arts. Grade 7 Music draws on:

| Related concept | Meaning in music | Quick example |
|-----------------|------------------|---------------|
| **Expression** | Communicating emotion/ideas through sound | Singing a lullaby gently to convey calm |
| **Interpretation** | The performer''s personal reading of a piece | Two singers phrasing the same folk song differently |
| **Presentation** | How music is shared with an audience | Ensemble posture, entrance, stage presence |
| **Structure** | How music is organised (form, sections) | Verse–chorus–verse in a pop song |
| **Style** | The characteristic "sound" of a genre/era | The swing feel of jazz vs. straight folk |
| **Audience** | Who receives the music and how they respond | Adjusting volume/energy for a school assembly |
| **Role** | The function a musician plays | Melody singer vs. harmony singer vs. soloist |
| **Innovation** | Creating something new/original | Improvising a new melody over a known chord |
| **Boundaries** | Limits explored, stretched, or crossed | Extending vocal range; blending two genres |

---','{"arts":2,"related":3,"concepts":2,"are":1,"the":8,"specialised":1,"lenses":1,"grade":1,"music":5,"draws":1,"concept":1,"meaning":1,"quick":1,"example":1,"expression":1,"communicating":1,"emotion":1,"ideas":1,"through":1,"sound":2,"singing":1,"lullaby":1,"gently":1,"convey":1,"calm":1,"interpretation":1,"performer":1,"personal":1,"reading":1,"piece":1,"two":2,"singers":1,"phrasing":1,"same":1,"folk":2,"song":2,"differently":1,"presentation":1,"how":3,"shared":1,"with":1,"audience":2,"ensemble":1,"posture":1,"entrance":1,"stage":1,"presence":1,"structure":1,"organised":1,"form":1,"sections":1,"verse":2,"chorus":1,"pop":1,"style":1,"characteristic":1,"genre":1,"era":1,"swing":1,"feel":1,"jazz":1,"straight":1,"who":1,"receives":1,"and":1,"they":1,"respond":1,"adjusting":1,"volume":1,"energy":1,"for":1,"school":1,"assembly":1,"role":1,"function":1,"musician":1,"plays":1,"melody":2,"singer":2,"harmony":1,"soloist":1,"innovation":1,"creating":1,"something":1,"new":2,"original":1,"improvising":1,"over":1,"known":1,"chord":1,"boundaries":1,"limits":1,"explored":1,"stretched":1,"crossed":1,"extending":1,"vocal":1,"range":1,"blending":1,"genres":1}'::jsonb),
('chunk_7b87f4f484a0aa94a1','file_c7904436411b2e478c','music.md','2.1 Unit Planner (MYP Framework)','- **Key Concept:** **Aesthetics** — how we perceive, respond to, and create beauty and meaning in sound. (Secondary link: **Communication** — voice as a tool for sharing ideas and feeling.)
- **Related Concepts:** **Expression**, **Interpretation**, **Presentation**.
- **Global Context:** **Personal and cultural expression** — exploring the ways we discover and express identity, feelings, and culture through the singing voice.
- **Statement of Inquiry (SOI):**
  > *Singers use the elements of music and vocal technique to express personal and cultural identity, interpreting and presenting song for an audience.*

- **Inquiry Questions:**
  - **Factual:** What are the elements of music, and what are the parts of correct vocal technique (posture, breathing, diction, tone)?
  - **Conceptual:** How do dynamics, tempo, and phrasing shape the expression and interpretation of a song?
  - **Debatable:** Is a "good" singer born with talent, or made through technique and practice?

- **ATL (Approaches to Learning) in focus:**
  - *Self-management* — practice routines, warm-up discipline.
  - *Communication* — reading notation; conveying mood to an audience.
  - *Thinking (creative)* — improvisation and interpretation.
  - *Social* — blending and balancing in ensemble.

- **Learner Profile emphasis:** Communicators, Risk-takers (performing), Reflective (self-evaluation).

---','{"unit":1,"planner":1,"myp":1,"framework":1,"key":1,"concept":1,"aesthetics":1,"how":2,"perceive":1,"respond":1,"and":15,"create":1,"beauty":1,"meaning":1,"sound":1,"secondary":1,"link":1,"communication":2,"voice":2,"tool":1,"for":2,"sharing":1,"ideas":1,"feeling":1,"related":1,"concepts":1,"expression":3,"interpretation":3,"presentation":1,"global":1,"context":1,"personal":2,"cultural":2,"exploring":1,"the":6,"ways":1,"discover":1,"express":2,"identity":2,"feelings":1,"culture":1,"through":2,"singing":1,"statement":1,"inquiry":2,"soi":1,"singers":1,"use":1,"elements":2,"music":2,"vocal":2,"technique":3,"interpreting":1,"presenting":1,"song":2,"audience":2,"questions":1,"factual":1,"what":2,"are":2,"parts":1,"correct":1,"posture":1,"breathing":1,"diction":1,"tone":1,"conceptual":1,"dynamics":1,"tempo":1,"phrasing":1,"shape":1,"debatable":1,"good":1,"singer":1,"born":1,"with":1,"talent":1,"made":1,"practice":2,"atl":1,"approaches":1,"learning":1,"focus":1,"self":2,"management":1,"routines":1,"warm":1,"discipline":1,"reading":1,"notation":1,"conveying":1,"mood":1,"thinking":1,"creative":1,"improvisation":1,"social":1,"blending":1,"balancing":1,"ensemble":1,"learner":1,"profile":1,"emphasis":1,"communicators":1,"risk":1,"takers":1,"performing":1,"reflective":1,"evaluation":1}'::jsonb),
('chunk_369d03d24c9c14e0ef','file_c7904436411b2e478c','music.md','3. Sub-topic A — Warm-ups','**Why warm-ups matter:** The voice is produced by muscles (the vocal folds) and supported by breath. Just like a runner stretches before a race, a singer warms up to increase blood flow, relax the throat and jaw, engage the breath, and prevent strain or injury. Warming up also focuses the mind and tunes the ear before singing repertoire.','{"sub":1,"topic":1,"warm":2,"ups":2,"why":1,"matter":1,"the":6,"voice":1,"produced":1,"muscles":1,"vocal":1,"folds":1,"and":4,"supported":1,"breath":2,"just":1,"like":1,"runner":1,"stretches":1,"before":2,"race":1,"singer":1,"warms":1,"increase":1,"blood":1,"flow":1,"relax":1,"throat":1,"jaw":1,"engage":1,"prevent":1,"strain":1,"injury":1,"warming":1,"also":1,"focuses":1,"mind":1,"tunes":1,"ear":1,"singing":1,"repertoire":1}'::jsonb),
('chunk_31334beaf1267e7fb8','file_c7904436411b2e478c','music.md','3.1 Breathing exercises','- **Definition:** Controlled breathing drills that activate the **diaphragm** (the dome-shaped muscle below the lungs) so the singer has a steady, supported air stream.
- **How-to cue:** Stand tall. Place a hand on your belly. Breathe in silently through the nose so the belly expands outward (not the shoulders). Exhale slowly on a steady "sss" for 4, then 8, then 12 counts — keep the hiss even to the very end.
- **Real example:** "Hissing snake" — inhale for 4, hiss out for 8, aiming for a smooth, unbroken sound.
- **Why it matters:** Steady breath = steady tone, longer phrases, and better pitch control.
- **Common misconception:** *"You breathe with your shoulders / chest."* **Correction:** Good singing breath is low and expands the belly and lower ribs; raised shoulders create tension and shallow air.
- **Practice cue:** Watch your shoulders in a mirror — if they lift when you inhale, drop them and breathe into your belly instead.','{"breathing":2,"exercises":1,"definition":1,"controlled":1,"drills":1,"that":1,"activate":1,"the":10,"diaphragm":1,"dome":1,"shaped":1,"muscle":1,"below":1,"lungs":1,"singer":1,"has":1,"steady":4,"supported":1,"air":2,"stream":1,"how":1,"cue":2,"stand":1,"tall":1,"place":1,"hand":1,"your":4,"belly":4,"breathe":3,"silently":1,"through":1,"nose":1,"expands":2,"outward":1,"not":1,"shoulders":4,"exhale":1,"slowly":1,"sss":1,"for":4,"then":2,"counts":1,"keep":1,"hiss":2,"even":1,"very":1,"end":1,"real":1,"example":1,"hissing":1,"snake":1,"inhale":2,"out":1,"aiming":1,"smooth":1,"unbroken":1,"sound":1,"why":1,"matters":1,"breath":2,"tone":1,"longer":1,"phrases":1,"and":5,"better":1,"pitch":1,"control":1,"common":1,"misconception":1,"you":2,"with":1,"chest":1,"correction":1,"good":1,"singing":1,"low":1,"lower":1,"ribs":1,"raised":1,"create":1,"tension":1,"shallow":1,"practice":1,"watch":1,"mirror":1,"they":1,"lift":1,"when":1,"drop":1,"them":1,"into":1,"instead":1}'::jsonb),
('chunk_aa67490c415aa88681','file_c7904436411b2e478c','music.md','3.2 Vocal sirens / glissando','- **Definition:** A **glissando** (or "siren") is a smooth, continuous slide from a low pitch up to a high pitch and back, with no separate steps between notes.
- **How-to cue:** On an "ng" or "oo" sound, glide gently like a siren from your lowest comfortable note to your highest and back down. Keep it light — no pushing.
- **Real example:** Sliding "oooo" from low to high like an ambulance siren.
- **Analogy:** Like stretching an elastic band slowly and evenly — gentle and gradual, never a sudden yank.
- **Why it matters:** Sirens gently connect your low ("chest") and high ("head") voice, warming the whole range smoothly.
- **Common misconception:** *"Warm up loudly to get power."* **Correction:** Warm-ups should be light and easy; loud pushing on a cold voice risks strain.
- **Practice cue:** Keep the slide connected — imagine one unbroken line, not a staircase.','{"vocal":1,"sirens":2,"glissando":2,"definition":1,"siren":3,"smooth":1,"continuous":1,"slide":2,"from":3,"low":3,"pitch":2,"high":3,"and":6,"back":2,"with":1,"separate":1,"steps":1,"between":1,"notes":1,"how":1,"cue":2,"sound":1,"glide":1,"gently":2,"like":3,"your":3,"lowest":1,"comfortable":1,"note":1,"highest":1,"down":1,"keep":2,"light":2,"pushing":2,"real":1,"example":1,"sliding":1,"oooo":1,"ambulance":1,"analogy":1,"stretching":1,"elastic":1,"band":1,"slowly":1,"evenly":1,"gentle":1,"gradual":1,"never":1,"sudden":1,"yank":1,"why":1,"matters":1,"connect":1,"chest":1,"head":1,"voice":2,"warming":1,"the":2,"whole":1,"range":1,"smoothly":1,"common":1,"misconception":1,"warm":2,"loudly":1,"get":1,"power":1,"correction":1,"ups":1,"should":1,"easy":1,"loud":1,"cold":1,"risks":1,"strain":1,"practice":1,"connected":1,"imagine":1,"one":1,"unbroken":1,"line":1,"not":1,"staircase":1}'::jsonb),
('chunk_66b34814d01b7faf7c','file_c7904436411b2e478c','music.md','3.3 Scale warm-ups','- **Definition:** Singing short scale patterns (often on solfege or "ah/ee/oo") to warm the voice and train the ear for pitch.
- **How-to cue:** Sing a five-note pattern "do-re-mi-fa-sol-fa-mi-re-do," then move it up a step and repeat, keeping vowels tall and even.
- **Real example:** A rising and falling major five-note scale climbing by half-steps across the class range.
- **Why it matters:** Builds pitch accuracy, evenness of tone across the range, and vowel consistency.
- **Common misconception:** *"Scales are boring exercises with no purpose."* **Correction:** Scales train the ear and voice together — they are the "stretching and strengthening" that make songs easier.
- **Practice cue:** Match each note exactly to a keyboard or drone; listen before you sing.

---','{"scale":3,"warm":2,"ups":1,"definition":1,"singing":1,"short":1,"patterns":1,"often":1,"solfege":1,"the":6,"voice":2,"and":7,"train":2,"ear":2,"for":1,"pitch":2,"how":1,"cue":2,"sing":2,"five":2,"note":3,"pattern":1,"sol":1,"then":1,"move":1,"step":1,"repeat":1,"keeping":1,"vowels":1,"tall":1,"even":1,"real":1,"example":1,"rising":1,"falling":1,"major":1,"climbing":1,"half":1,"steps":1,"across":2,"class":1,"range":2,"why":1,"matters":1,"builds":1,"accuracy":1,"evenness":1,"tone":1,"vowel":1,"consistency":1,"common":1,"misconception":1,"scales":2,"are":2,"boring":1,"exercises":1,"with":1,"purpose":1,"correction":1,"together":1,"they":1,"stretching":1,"strengthening":1,"that":1,"make":1,"songs":1,"easier":1,"practice":1,"match":1,"each":1,"exactly":1,"keyboard":1,"drone":1,"listen":1,"before":1,"you":1}'::jsonb),
('chunk_3014d15b2d8645b998','file_c7904436411b2e478c','music.md','4. Sub-topic B — Vocal Technique','Good singing is a coordinated system: **posture supports breath, breath supports tone, and shaping (diction) makes it clear.**','{"sub":1,"topic":1,"vocal":1,"technique":1,"good":1,"singing":1,"coordinated":1,"system":1,"posture":1,"supports":2,"breath":2,"tone":1,"and":1,"shaping":1,"diction":1,"makes":1,"clear":1}'::jsonb),
('chunk_c4fb9874bc1062dff5','file_c7904436411b2e478c','music.md','4.1 Singing posture','- **Definition:** The aligned, balanced body position that lets breath flow freely.
- **How-to cue:** Feet shoulder-width apart, weight balanced; knees soft (not locked); spine tall; shoulders relaxed and down; chest comfortably open ("noble" posture); head level, chin parallel to the floor.
- **Why it matters:** A collapsed chest or slumped spine squashes the breath and dulls the tone.
- **Common misconception:** *"Standing stiff and rigid is good posture."* **Correction:** Posture should be tall but **relaxed and flexible** — tension anywhere (jaw, neck, shoulders) hurts the sound.
- **Practice cue:** Imagine a string gently lifting the crown of your head toward the ceiling.','{"singing":1,"posture":4,"definition":1,"the":7,"aligned":1,"balanced":2,"body":1,"position":1,"that":1,"lets":1,"breath":2,"flow":1,"freely":1,"how":1,"cue":2,"feet":1,"shoulder":1,"width":1,"apart":1,"weight":1,"knees":1,"soft":1,"not":1,"locked":1,"spine":2,"tall":2,"shoulders":2,"relaxed":2,"and":4,"down":1,"chest":2,"comfortably":1,"open":1,"noble":1,"head":2,"level":1,"chin":1,"parallel":1,"floor":1,"why":1,"matters":1,"collapsed":1,"slumped":1,"squashes":1,"dulls":1,"tone":1,"common":1,"misconception":1,"standing":1,"stiff":1,"rigid":1,"good":1,"correction":1,"should":1,"but":1,"flexible":1,"tension":1,"anywhere":1,"jaw":1,"neck":1,"hurts":1,"sound":1,"practice":1,"imagine":1,"string":1,"gently":1,"lifting":1,"crown":1,"your":1,"toward":1,"ceiling":1}'::jsonb),
('chunk_0e086a3d3bcb604cc9','file_c7904436411b2e478c','music.md','4.2 Diaphragmatic breathing (breath support)','- **Definition:** Using the diaphragm and lower-rib muscles to control a steady stream of air ("support").
- **How-to cue:** Inhale low (belly expands), then sing while keeping the ribs from collapsing too fast — as if gently holding the expansion.
- **Analogy:** Support is like slowly letting air out of a balloon by pinching the neck — controlled, not all at once.
- **Why it matters:** Support gives steady pitch, longer phrases, and dynamic control without strain.
- **Common misconception:** *"Take the biggest breath possible before every phrase."* **Correction:** You need an *appropriate*, low, relaxed breath — over-filling creates tension.
- **Practice cue:** Sing a phrase and try to end it with a little breath still in reserve.','{"diaphragmatic":1,"breathing":1,"breath":4,"support":4,"definition":1,"using":1,"the":5,"diaphragm":1,"and":3,"lower":1,"rib":1,"muscles":1,"control":2,"steady":2,"stream":1,"air":2,"how":1,"cue":2,"inhale":1,"low":2,"belly":1,"expands":1,"then":1,"sing":2,"while":1,"keeping":1,"ribs":1,"from":1,"collapsing":1,"too":1,"fast":1,"gently":1,"holding":1,"expansion":1,"analogy":1,"like":1,"slowly":1,"letting":1,"out":1,"balloon":1,"pinching":1,"neck":1,"controlled":1,"not":1,"all":1,"once":1,"why":1,"matters":1,"gives":1,"pitch":1,"longer":1,"phrases":1,"dynamic":1,"without":1,"strain":1,"common":1,"misconception":1,"take":1,"biggest":1,"possible":1,"before":1,"every":1,"phrase":2,"correction":1,"you":1,"need":1,"appropriate":1,"relaxed":1,"over":1,"filling":1,"creates":1,"tension":1,"practice":1,"try":1,"end":1,"with":1,"little":1,"still":1,"reserve":1}'::jsonb),
('chunk_6e59d737c07c4711c8','file_c7904436411b2e478c','music.md','4.3 Diction / articulation','- **Definition:** The clear pronunciation of **vowels** (which carry the tone) and **consonants** (which carry the words).
- **How-to cue:** Sustain sound on tall, open vowels; make consonants crisp and quick so they don''t interrupt the line. Keep the jaw loose and the tongue relaxed.
- **Real example:** In "night," hold the "ah" vowel and add a light, late "t" at the very end.
- **Why it matters:** Diction lets the audience understand the lyrics and helps the ensemble stay together.
- **Common misconception:** *"Sing loudly and people will understand the words."* **Correction:** Clarity comes from crisp consonants and tall vowels, not volume.
- **Practice cue:** Speak the lyrics in rhythm first, then sing them keeping the same clarity.','{"diction":2,"articulation":1,"definition":1,"the":14,"clear":1,"pronunciation":1,"vowels":3,"which":2,"carry":2,"tone":1,"and":7,"consonants":3,"words":2,"how":1,"cue":2,"sustain":1,"sound":1,"tall":2,"open":1,"make":1,"crisp":2,"quick":1,"they":1,"don":1,"interrupt":1,"line":1,"keep":1,"jaw":1,"loose":1,"tongue":1,"relaxed":1,"real":1,"example":1,"night":1,"hold":1,"vowel":1,"add":1,"light":1,"late":1,"very":1,"end":1,"why":1,"matters":1,"lets":1,"audience":1,"understand":2,"lyrics":2,"helps":1,"ensemble":1,"stay":1,"together":1,"common":1,"misconception":1,"sing":2,"loudly":1,"people":1,"will":1,"correction":1,"clarity":2,"comes":1,"from":1,"not":1,"volume":1,"practice":1,"speak":1,"rhythm":1,"first":1,"then":1,"them":1,"keeping":1,"same":1}'::jsonb),
('chunk_9900641f0b72ccaae0','file_c7904436411b2e478c','music.md','4.4 Tone quality / resonance','- **Definition:** The **timbre** or "colour" of the voice — how warm, bright, clear, or focused it sounds. Resonance is how sound vibrates and amplifies in the throat, mouth, and head spaces.
- **How-to cue:** Keep vowels tall and open, soft palate lifted (as in the start of a yawn), throat relaxed and free.
- **Analogy:** Resonance is like the hollow body of a guitar — the same string sounds fuller because of the space it vibrates in.
- **Why it matters:** A free, resonant tone carries better and sounds pleasant without forcing.
- **Common misconception:** *"A breathy or forced tone is more expressive."* **Correction:** A free, supported tone is healthiest and most flexible; expression comes from dynamics and phrasing, not strain.
- **Practice cue:** Sing "ng → ah" and feel the buzz/vibration move to the front of the face.','{"tone":4,"quality":1,"resonance":3,"definition":1,"the":10,"timbre":1,"colour":1,"voice":1,"how":3,"warm":1,"bright":1,"clear":1,"focused":1,"sounds":3,"sound":1,"vibrates":2,"and":8,"amplifies":1,"throat":2,"mouth":1,"head":1,"spaces":1,"cue":2,"keep":1,"vowels":1,"tall":1,"open":1,"soft":1,"palate":1,"lifted":1,"start":1,"yawn":1,"relaxed":1,"free":3,"analogy":1,"like":1,"hollow":1,"body":1,"guitar":1,"same":1,"string":1,"fuller":1,"because":1,"space":1,"why":1,"matters":1,"resonant":1,"carries":1,"better":1,"pleasant":1,"without":1,"forcing":1,"common":1,"misconception":1,"breathy":1,"forced":1,"more":1,"expressive":1,"correction":1,"supported":1,"healthiest":1,"most":1,"flexible":1,"expression":1,"comes":1,"from":1,"dynamics":1,"phrasing":1,"not":1,"strain":1,"practice":1,"sing":1,"feel":1,"buzz":1,"vibration":1,"move":1,"front":1,"face":1}'::jsonb),
('chunk_0c7b40cc41bc27a00b','file_c7904436411b2e478c','music.md','4.5 Blending & balance in ensemble','- **Definition:** **Blending** = matching your vowel, tone, and volume to others so voices sound unified. **Balance** = adjusting so no part is too loud or too soft relative to the whole.
- **How-to cue:** Listen more than you sing; match vowel shapes; avoid sticking out; a harmony part supports and sits under the melody.
- **Why it matters:** A choir should sound like one instrument, not many soloists.
- **Common misconception:** *"The best singer should be the loudest."* **Correction:** In ensemble, the goal is to blend — loudness that sticks out breaks the unified sound.
- **Practice cue:** If you can''t hear the person next to you, you''re singing too loud.','{"blending":2,"balance":2,"ensemble":2,"definition":1,"matching":1,"your":1,"vowel":2,"tone":1,"and":2,"volume":1,"others":1,"voices":1,"sound":3,"unified":2,"adjusting":1,"part":2,"too":3,"loud":2,"soft":1,"relative":1,"the":7,"whole":1,"how":1,"cue":2,"listen":1,"more":1,"than":1,"you":4,"sing":1,"match":1,"shapes":1,"avoid":1,"sticking":1,"out":2,"harmony":1,"supports":1,"sits":1,"under":1,"melody":1,"why":1,"matters":1,"choir":1,"should":2,"like":1,"one":1,"instrument":1,"not":1,"many":1,"soloists":1,"common":1,"misconception":1,"best":1,"singer":1,"loudest":1,"correction":1,"goal":1,"blend":1,"loudness":1,"that":1,"sticks":1,"breaks":1,"practice":1,"can":1,"hear":1,"person":1,"next":1,"singing":1}'::jsonb),
('chunk_729b7ac7ec5f3ab696','file_c7904436411b2e478c','music.md','4.6 Vocal health','- **Definition:** Habits that protect the voice from strain and injury.
- **How-to cue:** Warm up before singing; stay hydrated; avoid shouting/screaming; rest the voice when tired or sick; never push through pain.
- **Why it matters:** The voice is a lifelong instrument you cannot replace — protect it.
- **Common misconception:** *"Straining and pushing builds a stronger voice."* **Correction:** Pain or hoarseness is a warning sign; strength comes from good technique and gradual practice, not force.
- **Practice cue:** If your throat hurts or your voice is hoarse, stop and rest — do not push.

---','{"vocal":1,"health":1,"definition":1,"habits":1,"that":1,"protect":2,"the":3,"voice":5,"from":2,"strain":1,"and":4,"injury":1,"how":1,"cue":2,"warm":1,"before":1,"singing":1,"stay":1,"hydrated":1,"avoid":1,"shouting":1,"screaming":1,"rest":2,"when":1,"tired":1,"sick":1,"never":1,"push":2,"through":1,"pain":2,"why":1,"matters":1,"lifelong":1,"instrument":1,"you":1,"cannot":1,"replace":1,"common":1,"misconception":1,"straining":1,"pushing":1,"builds":1,"stronger":1,"correction":1,"hoarseness":1,"warning":1,"sign":1,"strength":1,"comes":1,"good":1,"technique":1,"gradual":1,"practice":2,"not":2,"force":1,"your":2,"throat":1,"hurts":1,"hoarse":1,"stop":1}'::jsonb),
('chunk_6a3cd8b1e9d0b7c931','file_c7904436411b2e478c','music.md','5. Sub-topic C — Music Literacy','Learning to read music is like learning to read words — the symbols tell you the pitch (how high/low) and the rhythm (how long) of each sound.','{"sub":1,"topic":1,"music":2,"literacy":1,"learning":2,"read":2,"like":1,"words":1,"the":3,"symbols":1,"tell":1,"you":1,"pitch":1,"how":2,"high":1,"low":1,"and":1,"rhythm":1,"long":1,"each":1,"sound":1}'::jsonb),
('chunk_55233d058b93ce1427','file_c7904436411b2e478c','music.md','5.1 The staff (stave)','- **Definition:** The set of **5 lines and 4 spaces** on which notes are written. Higher on the staff = higher pitch.
- **Example:** A note sitting on the bottom line is lower than a note on the top line.
- **Practice cue:** Point to two notes and say which sounds higher based on its position.','{"the":5,"staff":2,"stave":1,"definition":1,"set":1,"lines":1,"and":2,"spaces":1,"which":2,"notes":2,"are":1,"written":1,"higher":3,"pitch":1,"example":1,"note":2,"sitting":1,"bottom":1,"line":2,"lower":1,"than":1,"top":1,"practice":1,"cue":1,"point":1,"two":1,"say":1,"sounds":1,"based":1,"its":1,"position":1}'::jsonb),
('chunk_fe8aad8cda1940cf7b','file_c7904436411b2e478c','music.md','5.2 Treble clef','- **Definition:** The symbol at the start of the staff (also called the **G clef**) that fixes the note names; its curl circles the line for the note **G**.
- **Note names on the treble staff:**
  - **Lines** (bottom→top): **E – G – B – D – F** ("Every Good Boy Deserves Fun").
  - **Spaces** (bottom→top): **F – A – C – E** (spells "FACE").
- **Analogy:** The clef is like a "key" that tells you which letters the lines and spaces stand for.
- **Practice cue:** Name three notes on the staff using the line/space mnemonics.','{"treble":2,"clef":3,"definition":1,"the":12,"symbol":1,"start":1,"staff":3,"also":1,"called":1,"that":2,"fixes":1,"note":3,"names":2,"its":1,"curl":1,"circles":1,"line":2,"for":2,"lines":2,"bottom":2,"top":2,"every":1,"good":1,"boy":1,"deserves":1,"fun":1,"spaces":2,"spells":1,"face":1,"analogy":1,"like":1,"key":1,"tells":1,"you":1,"which":1,"letters":1,"and":1,"stand":1,"practice":1,"cue":1,"name":1,"three":1,"notes":1,"using":1,"space":1,"mnemonics":1}'::jsonb),
('chunk_68443cecb7e175e2be','file_c7904436411b2e478c','music.md','5.3 Note names & the musical alphabet','- **Definition:** Pitches are named with the letters **A B C D E F G**, then repeat. After G, it starts again at A.
- **Example:** Going up from C: C–D–E–F–G–A–B–C (an octave).
- **Misconception:** *"There are notes called H."* **Correction:** The English musical alphabet only uses **A–G**; it cycles.
- **Practice cue:** Say the alphabet forward and backward: A-B-C-D-E-F-G and G-F-E-D-C-B-A.','{"note":1,"names":1,"the":4,"musical":2,"alphabet":3,"definition":1,"pitches":1,"are":2,"named":1,"with":1,"letters":1,"then":1,"repeat":1,"after":1,"starts":1,"again":1,"example":1,"going":1,"from":1,"octave":1,"misconception":1,"there":1,"notes":1,"called":1,"correction":1,"english":1,"only":1,"uses":1,"cycles":1,"practice":1,"cue":1,"say":1,"forward":1,"and":2,"backward":1}'::jsonb),
('chunk_e72fd7d58ba2315aea','file_c7904436411b2e478c','music.md','5.4 Note & rest values','- **Definition:** Symbols showing how long a sound (note) or silence (rest) lasts, measured in **beats**.

| Note | Name (US / UK) | Beats in 4/4 | Matching rest |
|------|----------------|--------------|---------------|
| ○ (open, no stem) | Whole / Semibreve | **4 beats** | Whole rest |
| ♩ with open head | Half / Minim | **2 beats** | Half rest |
| ♩ (filled, stem) | Quarter / Crotchet | **1 beat** | Quarter rest |
| ♪ (filled, flag) | Eighth / Quaver | **½ beat** | Eighth rest |

- **Analogy (fractions):** A whole note is a whole pizza; two halves make a whole; four quarters make a whole; eight eighths make a whole.
- **Misconception:** *"A rest means stop playing/relax."* **Correction:** A rest is **counted silence** — you keep the beat internally and stay in time.
- **Practice cue:** Clap a quarter note (1 clap = 1 beat), then two eighths (2 claps in 1 beat: "1-and").','{"note":5,"rest":9,"values":1,"definition":1,"symbols":1,"showing":1,"how":1,"long":1,"sound":1,"silence":2,"lasts":1,"measured":1,"beats":4,"name":1,"matching":1,"open":2,"stem":2,"whole":7,"semibreve":1,"with":1,"head":1,"half":2,"minim":1,"filled":2,"quarter":3,"crotchet":1,"beat":5,"flag":1,"eighth":2,"quaver":1,"analogy":1,"fractions":1,"pizza":1,"two":2,"halves":1,"make":3,"four":1,"quarters":1,"eight":1,"eighths":2,"misconception":1,"means":1,"stop":1,"playing":1,"relax":1,"correction":1,"counted":1,"you":1,"keep":1,"the":1,"internally":1,"and":2,"stay":1,"time":1,"practice":1,"cue":1,"clap":2,"then":1,"claps":1}'::jsonb),
('chunk_1b4cf768fe9f1a0f47','file_c7904436411b2e478c','music.md','5.5 Time signatures','- **Definition:** The two stacked numbers after the clef. **Top number = beats per bar; bottom number = which note gets one beat** (4 = quarter note).
- **Examples:**
  - **4/4** ("common time") = 4 quarter-note beats per bar. Feels like: 1-2-3-4. Most pop and folk songs.
  - **3/4** = 3 quarter-note beats per bar. Feels like a waltz: 1-2-3, strong-weak-weak.
- **Misconception:** *"The bottom number is how many beats there are."* **Correction:** The **top** number is how many beats per bar; the bottom tells you *what kind* of note gets the beat.
- **Practice cue:** Count "1-2-3-4" for 4/4 and "1-2-3" for 3/4, stamping on beat 1.','{"time":2,"signatures":1,"definition":1,"the":6,"two":1,"stacked":1,"numbers":1,"after":1,"clef":1,"top":2,"number":4,"beats":5,"per":4,"bar":4,"bottom":3,"which":1,"note":5,"gets":2,"one":1,"beat":3,"quarter":3,"examples":1,"common":1,"feels":2,"like":2,"most":1,"pop":1,"and":2,"folk":1,"songs":1,"waltz":1,"strong":1,"weak":2,"misconception":1,"how":2,"many":2,"there":1,"are":1,"correction":1,"tells":1,"you":1,"what":1,"kind":1,"practice":1,"cue":1,"count":1,"for":2,"stamping":1}'::jsonb),
('chunk_30dfb07ceb1635831d','file_c7904436411b2e478c','music.md','5.6 Beat & rhythm','- **Definition:** The **beat** is the steady, regular pulse (like a heartbeat). **Rhythm** is the pattern of long and short sounds that plays over the beat.
- **Example:** Beat = a metronome ticking evenly; rhythm = the varied pattern of the words in "Twinkle, Twinkle."
- **Analogy:** The beat is the footsteps; the rhythm is the dance done over those steps.
- **Misconception:** *"Beat and rhythm are the same thing."* **Correction:** Beat is the constant pulse; rhythm is the changing pattern on top of it.
- **Practice cue:** Tap the steady beat with your foot while clapping the rhythm of a song''s words.','{"beat":8,"rhythm":7,"definition":1,"the":15,"steady":2,"regular":1,"pulse":2,"like":1,"heartbeat":1,"pattern":3,"long":1,"and":2,"short":1,"sounds":1,"that":1,"plays":1,"over":2,"example":1,"metronome":1,"ticking":1,"evenly":1,"varied":1,"words":2,"twinkle":2,"analogy":1,"footsteps":1,"dance":1,"done":1,"those":1,"steps":1,"misconception":1,"are":1,"same":1,"thing":1,"correction":1,"constant":1,"changing":1,"top":1,"practice":1,"cue":1,"tap":1,"with":1,"your":1,"foot":1,"while":1,"clapping":1,"song":1}'::jsonb),
('chunk_eeeb4294317d7cb295','file_c7904436411b2e478c','music.md','5.7 Tempo','- **Definition:** The **speed** of the beat, often given in Italian terms or in BPM (beats per minute).
- **Common terms:** *Largo* (very slow), *Adagio* (slow), *Andante* (walking pace), *Moderato* (moderate), *Allegro* (fast, lively), *Presto* (very fast). *Accelerando* = getting faster; *ritardando/rallentando* = getting slower.
- **Example:** A lullaby is *Adagio*; a celebration song is *Allegro*.
- **Misconception:** *"Faster music is always more exciting/better."* **Correction:** Tempo serves the mood — a slow tempo can be powerful and moving.
- **Practice cue:** Sing one phrase at *Andante*, then at *Allegro*, and describe how the feeling changes.','{"tempo":3,"definition":1,"the":4,"speed":1,"beat":1,"often":1,"given":1,"italian":1,"terms":2,"bpm":1,"beats":1,"per":1,"minute":1,"common":1,"largo":1,"very":2,"slow":3,"adagio":2,"andante":2,"walking":1,"pace":1,"moderato":1,"moderate":1,"allegro":3,"fast":2,"lively":1,"presto":1,"accelerando":1,"getting":2,"faster":2,"ritardando":1,"rallentando":1,"slower":1,"example":1,"lullaby":1,"celebration":1,"song":1,"misconception":1,"music":1,"always":1,"more":1,"exciting":1,"better":1,"correction":1,"serves":1,"mood":1,"can":1,"powerful":1,"and":2,"moving":1,"practice":1,"cue":1,"sing":1,"one":1,"phrase":1,"then":1,"describe":1,"how":1,"feeling":1,"changes":1}'::jsonb),
('chunk_889cf6bd3b9bfde4ea','file_c7904436411b2e478c','music.md','5.8 Dynamics','- **Definition:** How **loud or soft** the music is.

| Marking | Italian term | Meaning |
|---------|--------------|---------|
| **pp** | pianissimo | very soft |
| **p** | piano | soft |
| **mp** | mezzo-piano | medium soft |
| **mf** | mezzo-forte | medium loud |
| **f** | forte | loud |
| **ff** | fortissimo | very loud |
| **<** | crescendo | gradually getting louder |
| **>** | decrescendo / diminuendo | gradually getting softer |

- **Analogy:** Dynamics are like the volume knob and the light dimmer of a song — they add shadow and shine.
- **Misconception:** *"Singing louder = singing better."* **Correction:** Great singing uses a *range* of dynamics; soft, controlled singing is often harder and more expressive than loud singing.
- **Practice cue:** Sing one line with a crescendo (soft→loud), then a decrescendo (loud→soft).','{"dynamics":3,"definition":1,"how":1,"loud":7,"soft":7,"the":3,"music":1,"marking":1,"italian":1,"term":1,"meaning":1,"pianissimo":1,"very":2,"piano":2,"mezzo":2,"medium":2,"forte":2,"fortissimo":1,"crescendo":2,"gradually":2,"getting":2,"louder":2,"decrescendo":2,"diminuendo":1,"softer":1,"analogy":1,"are":1,"like":1,"volume":1,"knob":1,"and":3,"light":1,"dimmer":1,"song":1,"they":1,"add":1,"shadow":1,"shine":1,"misconception":1,"singing":5,"better":1,"correction":1,"great":1,"uses":1,"range":1,"controlled":1,"often":1,"harder":1,"more":1,"expressive":1,"than":1,"practice":1,"cue":1,"sing":1,"one":1,"line":1,"with":1,"then":1}'::jsonb);